### PR TITLE
Diego add back jest eslint prettier

### PR DESCRIPTION
**Pull request by DiegoSalas27**
# Description
Bringing back the configuration updates for jest, eslint, husky and prettier to development. I will be adding the unit and integration tests that have been merged in the past and that are present in this document: https://docs.google.com/spreadsheets/d/1t26Y9h3yRJAfvaWbveRzOz28plXWNgbe3A8Ceiqwyu4/edit#gid=19632796

## Related PRS:
N/A

## Main changes explained:
- Bringing back jest, linting, and prettier to the source code.

## How to test:
1. check into current branch
2. do `npm install`
3. if running on mac do `npm run prepare-macos-linux`
4. create a local test branch and perform any updates there
5. linting, prettier and jest should run when code is committed (jest should run if any test files are added in the staged area)

## Note:
Forgive for redoing this. Jae and I needed to merge development features into production solve a deployment issue that was breaking beta stage. Now that it's working, I am bringing back all changes and merged PRs from the past.

### CODE REVIEW

**Review by Abi-Liu — CHANGES_REQUESTED** [review]
Hey Diego, it seems there is an issue when running the `npm run test:staged` command when committing code. My test suite is failing to run and therefore never commits the code if I have a test file staged. I will attach a video for your reference.

https://github.com/OneCommunityGlobal/HGNRest/assets/59585815/27a61563-23d5-4915-aea6-71cfbd02cfdb

**Comment by DiegoSalas27** [comment]
> Hey Diego, it seems there is an issue when running the `npm run test:staged` command when committing code. My test suite is failing to run and therefore never commits the code if I have a test file staged. I will attach a video for your reference.
> 
> 
> 
> https://github.com/OneCommunityGlobal/HGNRest/assets/59585815/27a61563-23d5-4915-aea6-71cfbd02cfdb
> 
> 
> 
> 

Hey, Abi. Running those commands won't work since jest hasn't been configured in this PR. That's why you need to run the command in the execution steps I mentioned. The jest, eslint, prettier and husky configuration are in another PR.

**Comment by DiegoSalas27** [comment]
> Hey Diego, it seems there is an issue when running the `npm run test:staged` command when committing code. My test suite is failing to run and therefore never commits the code if I have a test file staged. I will attach a video for your reference.
> 
>  video1873549643.mp4

Hey @Abi-Liu, Thank you for bringing this up. Indeed, I tested it myself and the test files were not being tested when stated and being committed.

`.babelrc` ignores test related files when building the project for deployment (which makes sense to reduce the size of the bundled project):

image

This was keeping jest from testing the `spec` and `test` files when they were staged and being committed. As a result, I added `babel-jest` dependency which helps transforming js files with babel even when .babelrc ignores them:

image

Your tests should work now. Please let me know how it goes!

**Review by 20chen-7 — APPROVED** [review]
Screenshot 2024-04-12 at 2 38 23 PM
Functions work as expected

**Review by Abi-Liu — APPROVED** [review]
Hey Diego, the test suites now pass when committing!

Screenshot 2024-04-12 at 11 26 24 AM

**Review by Parth-tech — APPROVED** [review]
Hey Diego,
It works as expected.
PR 893

**Comment by mianmiantea2019** [comment]
Hey Diego,

It works as expected. However, I noticed something different from what other testers experienced in the terminal. Do you have any idea why? 

image
image

**Pull request merged**
