### PR TITLE
Nathalia new filter project by user name

### PR DESCRIPTION
**Pull request by nathcarnevalli**
# Description
image

## Related PRS (if any):
This backend PR is related to the #[2392](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2392) frontend PR.

## Main changes explained:
- Created the getProjectByPerson function in userProfileController.js
- Created the route to call the getProjectByPerson function

## How to test:
1. Check into current branch
2. Run `npm install`, `npm run build` and `npm run start` to run this PR locally
3. Go to the #[2392](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2392) frontend PR and follow the steps

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/69649453/76c3724e-b253-495a-83e5-beb713d17c61

## Note:
It's really important to run `npm run build`

### CODE REVIEW

**Review by HowieMiao — APPROVED** [review]
Tested PR with first name, last name, both, as well as non existent users to ensure no results found pop-up. Tested to make sure capitalization is not an issue either, no issues.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73614967/441c4571-16f6-4968-ac58-00830fe1a0f1

**Review by pavanswaroopl — DISMISSED** [review]
There's a minor issue, not sure whether it's an obvious behavior, but can you please have a look at the scenario below:

I am searching with my name which is "Pavan Swaroop Lebakula",
when I search for Pavan, it shows a project, which is good, and shows a successful fetch,
but when I search with "pavan s", it throws the error that nothing is found.

Screenshot 2024-06-28 at 2 35 53 PM
Screenshot 2024-06-28 at 2 36 45 PM
Screenshot 2024-06-28 at 2 36 36 PM

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and the functionality works fine. Left review on [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2392#pullrequestreview-2149089235)

**Review by sahithidhulipala9 — CHANGES_REQUESTED** [review]
For the names already listed, search results are displaying the corresponding projects. But for the person names that aren't listed in projects, i am not getting the error message.
PR 1006+ 2392

**Review by DiyaWadhwani — APPROVED** [review]
Hi Nathalia,

I have tested your changes and dropped a comment on your frontend PR.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2392#pullrequestreview-2149541624

Thank you.

**Review by jinxyou — APPROVED** [review]
I left a review at frontend, which can be found here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2392#pullrequestreview-2149931939

**Comment by vishavk1992** [comment]
your changes work great and i left the review on frontend PR 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2392#pullrequestreview-2154348464

**Review by vijay10pk — APPROVED** [review]
Changes works as expected for the all the scenarios. Refer to [Front-end PR Comment Link](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2392#pullrequestreview-2157901494)

**Comment by KaushikMreddy** [comment]
Hi, 
I've reviewed this PR in the frontend.

**Review by nikhilpittala16 — APPROVED** [review]
I left a review on the frontend PR, it can be found here: [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2392#pullrequestreview-2159480777]

**Review by HowieMiao — APPROVED** [review]
Approved on front end

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2392#pullrequestreview-2161112529

**Pull request merged**
