### PR TITLE
Ivy-pwd-error-BE

### PR DESCRIPTION
**Pull request by 20chen-7**
## Related PRS (if any):
This backend PR is related to the [#2549](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2549) frontend PR.

…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by vishnupriyaatheti — APPROVED** [review]
@20chen-7 I have verified the changes in local, and are working as expected.
Below are the cases I have considered:
**1) Invalid password:**
Expected : 404 status code with message body
Actual: Working as Expected

2)Empty password:
Expected: 400 status code with message body
Actual: Working as Expected.

3)Valid password:
Expected: 200 status code with token generation
Actual: Working as expected.
PR #1077
PR #1077 empty password check

**Review by SMitta11 — APPROVED** [review]
I reviewed changes using postman and it works as expected:

For Invalid password->404 not found 
Empty password-> 404 bad request
Valid password- > 200 OK
Screen Shot 2024-08-23 at 1 13 19 AM
Screen Shot 2024-08-23 at 1 13 49 AM
Screen Shot 2024-08-23 at 1 15 12 AM

**Review by Lemonnycodes — APPROVED** [review]
Hi ,

Checked the PR, it works as expected.

Screenshot 2024-08-24 001134

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.





Thank You

**Review by vedantg24 — APPROVED** [review]
Tested PR on Postman, and the changes are working as expected. Here are the results:

Empty password: 400 status code with correct message response 
Screenshot 2024-08-31 at 12 24 13 AM

Invalid password: 404 status code with correct message response 
Screenshot 2024-08-31 at 12 24 01 AM

Valid password:200 status code with token generation

**Review by yashwanth170 — APPROVED** [review]
Changes are working as expected.
invalid password
invalid request

**Review by ashayk9 — APPROVED** [review]
I have verified the changes locally, and they are working as expected. I tested the following scenarios: For an invalid password, I expected a 404 status code with a message body, and the functionality worked as expected. For an empty password, I anticipated a 400 status code with a message body, and this also worked as expected. Finally, for a valid password, I expected a 200 status code with token generation, and the feature behaved as intended.
Screenshot 2024-09-04 at 10 50 51 AM

Screenshot 2024-09-04 at 10 51 24 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
