### PR TITLE
Shivansh made Custom Infringement email for Core Team

### PR DESCRIPTION
**Pull request by shiva2096**
# Description

Screenshot 2023-08-24 at 6 47 49 PM
Screenshot 2023-08-24 at 6 48 17 PM

## Related PRS (if any):
None

## Main changes explained:
- Updated the function **getInfringementEmailBody** in the file **/HGNRest/src/helpers/userHelper.js**. Added extra argument **timeRemaining**, for a different behaviour when time is passed as an argument.
- Updated the function **assignBlueSquareForTimeNotMet** in the file **/HGNRest/src/helpers/userHelper.js**. Added condition for **Core Team** member. When the member is from core team, pass remaining time of current week to the getInfringementEmailBody function.

## How to test:
Before moving to testing, firstly you need to set up your own test email id to send the mail notification.
This is only for test purposes. Once tested you can revert these changes. These changes are not required on the main.

To send email using Gmail API using OAuth2 and nodemailer, kindly follow the below video and setup up a test mail id.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

Fill below variable values from the above setup in the .env file of the backend.
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = TRUE

Refer this document as well for testing gmail functionality:
https://docs.google.com/document/d/1HJJTDtWykjGb4IfiIFlHXDfp_IABvmwKxsMPqqF6rG8/edit

===========================================================================================
**If you can test this PR at 12:01 AM PST, skip step 7.**
**Else decide a time at which you want to test this PR, and follow step 7 as well** 
 
1. check into current backend branch
2. do `npm install` and `...` to run this PR locally
3. Log in as Admin User.
4. Create a **Core Team** role user with a valid/working email id using the User Management tab.
5. Note down this email used above.
6. Open the file **/HGNRest/src/utilities/emailSender.js**
- Search for the following code:
Screenshot 2023-08-24 at 5 53 00 PM

- Replace it with the following code (Use the email id of the core team user created above):
Screenshot 2023-08-24 at 5 53 13 PM

This will limit the emails to be sent to this user only, as your Gmail API will be active.

7. **Skip this step if you are testing at 12:01 AM PST**
- Open the file **/HGNRest/src/cronjobs/userProfileJobs.js**
- Search for the highlighted code.
Screenshot 2023-10-15 at 12 15 06 AM

- Suppose you want to test this at 3:50 PM PST on a Tuesday. 
- To run on Tuesday, you need to make the value if **SUNDAY = 2**
- Make the changes in 2 places as highlighted below.
Screenshot 2023-10-15 at 12 23 01 AM

So now the "Infringement Email" will be processed at this time (3:50 PM PST), instead of 12:01 AM PST.
To test at 10:32 AM PST, use the value "32 10 preceeding the asterisks"
To test at 8:43 PM PST, use the value "43 20 preceeding the asterisks"
Reach out to me if you need help with this step.

8. do `npm install` **again** and `...` to run this PR locally (**To be done before 12:01 am PST**)
9. Wait for the time to turn to 12:01 am (midnight) PST
10. Wait until you receive an Infingement mail on the above Core Team member email id.
It will have the Missed Hours that were committed this week.
proof of email

For non-core team members the email normally looks like this:
Screenshot 2023-08-24 at 11 27 47 PM

## Note:
Be patient when wait for the email, it takes about 20-30 mins. 
I would like to clarify that this pull request is primarily focused on ensuring that the modified email is correctly sent to the core team members, rather than assessing the speed at which the emails are delivered. I am not sure how the production server manages to send the email this quickly, but the time taken is out of scope for this PR.
Your understanding is greatly appreciated.

For a Core Team member, if they have committed 20 hrs per week, but were not able to complete those in the present week. The remaining hours will be added to the "**Additional Make-up Hours This Week**" field that you can check on their profile page. So for next week, they will have to work for 20 + the time Make-Up Hours field.

This PR is to notify such users (in case for Infringement assignment due to time not met for current week) that the remaining time has been added to the "**Additional Make-up Hours This Week**" field.

### CODE REVIEW

**Comment by astrjc0326** [comment]
Hi @shiva2096, I tried to run the code but couldn't generate the access token, so I generated one and used it to run the code.
Screen Shot 2023-09-29 at 9 34 58 PM

The email content for non-core members is as expected!
[Screen Shot 2023-09-29 at 11 41 08 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/98345990/7a9e4e0c-4629-418b-80b8-647a47fa9bab)

The email content for core member is as expected!
Screen Shot 2023-09-29 at 11 59 23 PM

It took 30 minutes to send the email to 50 people. So, by the time my email address shows up, the access token would have expired. 
I will try it again once I figure out how to solve the 'unauthorized_client' problem. Or if you have any thoughts, please share them with me.

Regarding the sending of emails, the content for both core members and non-core members works as intended!

**Review by Bhagyashree444 — COMMENTED** [review]
Great job! However, I haven't received the infringement email yet.

PR#485(4)

**Comment by shiva2096** [comment]
This step is missing from the video:
In the OAuth consent screen, add user whose google account you are confirming in the future steps.

Add Test User

**Comment by shiva2096** [comment]
> Great job! However, I haven't received the infringement email yet.
> 
> PR#485(4)

@Bhagyashree444 Thanks for testing this PR.

The backend service process all the users created on the development database. And thus it takes time.
Just keep the backend service running, it will surely send an email.

**Comment by shiva2096** [comment]
> Hi @shiva2096, I tried to run the code but couldn't generate the access token, so I generated one and used it to run the code. Screen Shot 2023-09-29 at 9 34 58 PM
> 
> The email content for non-core members is as expected! [Screen Shot 2023-09-29 at 11 41 08 PM](https://github.com/OneCommunityGlobal/HGNRest/assets/98345990/7a9e4e0c-4629-418b-80b8-647a47fa9bab)
> 
> The email content for core member is as expected! Screen Shot 2023-09-29 at 11 59 23 PM
> 
> It took 30 minutes to send the email to 50 people. So, by the time my email address shows up, the access token would have expired. I will try it again once I figure out how to solve the 'unauthorized_client' problem. Or if you have any thoughts, please share them with me.
> 
> Regarding the sending of emails, the content for both core members and non-core members works as intended!

@astrjc0326  Thanks for testing this PR.

I would like to clarify that this pull request is primarily focused on ensuring that the modified email is correctly sent to the core team members, rather than assessing the speed at which the emails are delivered. I am not sure how the production server manages to send the email this quickly, but the time taken is out of scope for this PR.
Your understanding is greatly appreciated.

**Review by malikjahanzaib — APPROVED** [review]
Hi @shiva2096, I have tested this PR as directed and it works. I put the cron job to run at 2:55 PM on Saturday and I received an infringement mail at 3:16 PM. Let me know if any further testing is needed. Great job!!!

Screenshots:

Screenshot 2023-10-21 152012

Screenshot 2023-10-21 150258

Screenshot 2023-10-21 150321

**Comment by shiva2096** [comment]
> Hi @shiva2096, I have tested this PR as directed and it works. I put the cron job to run at 2:55 PM on Saturday and I received an infringement mail at 3:16 PM. Let me know if any further testing is needed. Great job!!!
> 
> Screenshots:
> 
> Screenshot 2023-10-21 152012 Screenshot 2023-10-21 150258 Screenshot 2023-10-21 150321

Thanks @malikjahanzaib 
This is exactly what I wanted to be tested.

**Review by Bhagyashree444 — APPROVED** [review]
Excellent work! In userProfileJobs.js, I initially set the time to 4:30 PM but received the email at 5:36 PM. Your prompt update to the code, allowing me to receive the email at the user-set time, was greatly appreciated. This adjustment saved me from having to wait until Saturday at 12:01 AM. 
Screenshot (251)

**Review by astrjc0326 — APPROVED** [review]
Approve the change of change. Comment had left before.

**Comment by shiva2096** [comment]
@one-community 
Hello Jae,
We have 3 approvals on this PR, we can merge this branch now.

**Comment by one-community** [comment]
6 is the minimum I want to see... usually 8

**Comment by one-community** [comment]
Actually, this is low risk so I'm going to merge it

**Pull request merged**
