### PR TITLE
yihan add team code permission

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
The related frontend PR is [#1208](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1208)
This is 2nd PR of #480 which hasn't been merged to dev yet.

## Main changes explained:
- Update file createInitialPermissions.js for adding Edit Team Code permission.

## How to test:
1. check into current branch
2. do `npm run build` and `npm start` to run this PR locally
3. follow test steps of [#1208](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1208)

### CODE REVIEW

**Comment by DavidC0126** [comment]
I left the comment on FE PR#1208, great job!

**Review by Haoj1 — APPROVED** [review]
@AriaYu927 Commented in #1208. Good job!

**Review by GaryB93 — APPROVED** [review]
Tested with frontend PR#1208. Functionality approved.

**Review by winghojackyli — COMMENTED** [review]
Hi @AriaYu927 , I've tested the PR with #1208. Everything works great. Comments left here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1208#pullrequestreview-1608406385

**Review by Shiwani99 — APPROVED** [review]
Hi,
Good Job. Left comments for frontend PR#1208.

**Review by navneeeth — APPROVED** [review]
Hi! Tested your PR and it LGTM! Commented the full review on the[ frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1208#pullrequestreview-1629749568).

**Review by wantingxu7 — APPROVED** [review]
Hi,
Good work! comment in FE#1208

**Comment by Shubhu0** [comment]
Tested the PR, and everything looks good to me.

**Review by EdwinLauM — COMMENTED** [review]
Hi @AriaYu927! I left a more detailed review in your FE PR!

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Your frontend is now secure and functioning as expected. However, there's currently no authorization check in your backend to prevent my admin account from altering the team code arbitrarily. While my method of access might seem excessive, it highlights the fact that the backend currently permits admin accounts to modify the team code. If the intention is for only owners to have this capability, it may be advisable to either create a dedicated controller for this purpose or make adjustments to the existing one.

Furthermore, the team code I've set, "Bruh Y this happening," exceeds the required four-digit code format. Implementing a length validation mechanism to reject team codes that do not adhere to this four-digit standard could be beneficial.

To perform this check in postman, I converted the userprofile into JSON, deleted "dateChanged" within the json, and inputted my new team code "Bruh Y This Happening", and finally submitted it as a PUT request to `http://localhost:4500/api/userprofile/:myuserid`


Screenshot 2023-09-27 at 4 02 35 PM

**Review by KurtisIvey — APPROVED** [review]
Everything works now. I can't edit team codes using my admin account in postman.

pr494 no longer able to edit team code
Screenshot 2023-10-03 at 1 45 48 PM
Screenshot 2023-10-03 at 1 46 31 PM

**Pull request merged**
