### PR TITLE
Xiaow cleanup old timer and modify timer behavior for better UX

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
This PR cleans up the old timer related code and files, and modify timer behavior. Now if users stop timer before it runs out and log the passed time, the remaining time will be come the goal for the next timer, and if timer run out by itself and user log the time, the goal for next timer will be set back to the initial goal.

## Related PRS (if any):
This backend PR is related to the frontend [PR#1455](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1455#issue-1962550930).

## Main changes explained:
- Delete old timer related files
- Update new timer clientHandler file
- add one field called `initialGoal` in the timer model
…

## How to test:
1. check into current branch, check into frontend [PR#1455](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1455#issue-1962550930)
2. do `npm install` and `npm run dev` to run this PR locally
3. log as any user
4. go to dashboard
5. verify that 
  5.1 when logging time before timer runs out, the next goal is what is remaining from last timer
  5.2 when logging time after timer runs out, the next goal is what is set as the initial goal.
  5.3 try to break it.
  **5.4 (new) now if there are multiple tabs (on the same browser or different browsers), once timer runs out, the ringing effect should be consistent if user add more or log time on any one tab.**

## Screenshots or videos of changes:
how to set the initial goal (used to be Goal for today):
image

## Note:
The initial goal can only be set  by editing and saving goal at the bottom of the timer modal.

### CODE REVIEW

**Review by ChirayuRai — APPROVED** [review]
Commented on FE#1455. Great Job!

**Review by malikjahanzaib — DISMISSED** [review]
Hi @wang9hu, I have tested this PR locally and you can see my detailed [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1455#pullrequestreview-1700946130) on FE PR [#1455](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1455).

**Review by malikjahanzaib — APPROVED** [review]
Hi @wang9hu, Bug Fixed. Left detailed [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1455#issuecomment-1783655402) on FE PR [#1455](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1455). Great job!!!

**Comment by palakgosalia** [comment]
Hey, I have left a detailed review on PR 1455. Great work. Thank you

**Review by savio-henrique — COMMENTED** [review]
Hi @wang9hu , I've run the PR locally and left a detailed review is in [FE#1455](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1455). Great job :+1:!

**Comment by kavya151** [comment]
Hi @wang9hu I have tested the PR. Detailed review at #1455

**Review by navneeeth — APPROVED** [review]
Hello! Tested your changes and they LGTM! Commented a full review on the FE PR. Great implementation!

**Pull request merged**
