### PR TITLE
Abdel streamlined data input for new members

### PR DESCRIPTION
**Pull request by abdel-lall**
# Description

#### $\textcolor{red}{\textsf{(PRIORITY HIGH) Jae:}}$: Create a way for easy/nearly-automated data input for creating a new member 
- I’d like to be able to have a way for people to input their own information for initial setup in the software. Right now I set them up manually and it takes me a fair amount of time. It would be better to be able to send them a 1-time link that would have them set up the information for themselves. 
- Link needs to be 1-time so that people can’t just randomly create users
- Link should be generated by me just inputting their email somewhere like the top of the User Management page
- The parts that will need to be set up by me after they set themselves up are their Team and Projects/Tasks, so they shouldn’t have access to choose these. The rest though they should set up themselves. 
- I’d like to get an email each time a person sets themselves up, so I can easily check the details without logging into the software. If errors were made, I could also ask them to correct them by just forwarding the email with the corrections. 

## Related PRS:
This backend PR is related to the [#1073](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1073) frontend PR.

## Main changes explained:
- Updated routes.js and middleware.js.
- Added profileInitialSetupController.js, profileInitialSetupRouter.js and profileInitialSetupToken.js.

## How to test:
- check into the current branch.
- Set the environment variables (.env file) as follow:
- First you need to set up your own test email id to send the mail notification.

- To send email using Gmail API using OAuth2 and nodemailer, kindly follow the below video and setup up a test mail id.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

- Fill below variable values from the above setup in the .env file of the backend.
```
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = TRUE
```
- Fill below variable value with the email address you wish to use for receiving notifications
```
MANAGER_EMAIL=<add your own email>
```

- Get a free API key from https://opencagedata.com/pricing
- Fill below variable value with the API key
```
TIMEZONE_PREMIUM_KEY=<add API key here>
```
- npm run build
- npm start

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Backend works great and the email can be sent and received. The OpenCage Geocoding API works as well. Great work! Comment left on frontend #1073 pull request.

**Comment by one-community** [comment]
I am ridiculously excited about this new function. It is going to save me so much time while also improving accuracy!

**Comment by jacky776690g60** [comment]
(Commenting to confirm it works as intended)
See details about the testing from this <a href="https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1073#issuecomment-1659384724">comment</a>.

**Review by DavidC0126 — APPROVED** [review]
I tested the PR and it works as described. I leave the comment on [PR#1073](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1073).

**Review by sxiong5 — APPROVED** [review]
The PR works well. Approved the [HighestGoodNetworkApp#1073](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1073), nice work.

**Comment by one-community** [comment]
Getting close to ready for final review!! I'd like 3 more approvals on this and then branch conflicts fixed on the frontend. DM me on Slack once this is achieved

**Review by Indujaks — APPROVED** [review]
Verified your changes with both valid and invalid token. I was able to setup a new account through the link received.
Approved [PR #1073](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1073)  along with this!

**Review by n0vay — APPROVED** [review]
Works as Intended!
image

**Review by veronicacheng2 — APPROVED** [review]
Hi @abdel-lall, I have tested this PR and left review comments on #1073. 
Everything works perfectly.

**Review by navneeeth — APPROVED** [review]
LGTM! Thank you for the tutorial link to setup sending an email using Gmail API using OAuth2 and nodemailer. Great work with the implementation and the emails are sent as expected! Comment left on frontend PR #1073.

**Review by yunshan111 — APPROVED** [review]
Tested this PR, LGTM.

**Comment by beblicarl** [comment]
This functionality works as intended however there were a few errors in the backend console

issue #464

**Review by beblicarl — APPROVED** [review]

**Pull request merged**
