### PR TITLE
Yihan send review email

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
截屏2023-07-25 19 15 37

## Related PRS (if any):
To test this backend PR you need to checkout the [#1045](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1045) frontend PR.
This PR is based on [PR#443](https://github.com/OneCommunityGlobal/HGNRest/pull/443). I recommand to test #443 before review this one.

## Main changes explained:
- Update file taskController.js and taskRouter.js for adding send email function.

## How to test:
1. check into current branch
2. do `npm run build` and `npm start` to run this PR locally
3. follow the steps in the test instruction of [PR#1045](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1045).

### CODE REVIEW

**Comment by Lin1404** [comment]
Hi @AriaYu927 I tested your PR and leave comment on FE PR.

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. Left comments at frontend PR#1045.

**Review by StrawberryCalpico — APPROVED** [review]
I just tested your PR, Backend works great, Great Job
More details on [FR#1045](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1045#pullrequestreview-1678240015)

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hi @AriaYu927, tested this PR and left detailed review on FE PR [#1045](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1045/). 
[[FE Review Here](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1045/#pullrequestreview-1683892317)]

**Review by malikjahanzaib — APPROVED** [review]
Hi @AriaYu927, tested this PR again, works great. Detailed response on FE PR. 
Approving changes now.

**Pull request merged**
