### PR TITLE
Jordy add pop up editor controller unit tests

### PR DESCRIPTION
**Pull request by j-corp-25**
# Description

Unit tests for popupEditorController

## Related PRS (if any):
N/A

## Main changes explained:

- unit tests for `getAllPopupEditors`
- unit tests for `getPopupEditorById`
- unit tests for `createPopupEditor`
- unit tests for `updatePopupEditor`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run `npm run test popupeditor -- --verbose`

## Screenshots
Screenshot 2024-08-04 at 1 32 48 AM

## Note:

Check that all tests are passing
N/A

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
Hello @j-corp-25 
I have tested as mentioned above and all tests are passing.

Screenshot 2024-08-05 at 3 38 24 PM


Thank you.

**Review by SatyashanthiT — APPROVED** [review]
I reviewed this PR by checking out the current branch, installing dependencies, and running the tests locally. I verified that the unit tests for getAllPopupEditors, getPopupEditorById, createPopupEditor, and updatePopupEditor all pass successfully. The addition of these unit tests enhances test coverage and ensures the functionality of the popupEditorController. 

tested

**Review by DiyaWadhwani — COMMENTED** [review]
Hi,
All tests have passed. Attached a screenshot below.
Thank you for your work.

**Review by ishan-miglani — APPROVED** [review]
I have verified that all test cases are passing. Thanks!
Screenshot 2024-08-09 at 5 42 07 PM

**Review by AnkitLall — APPROVED** [review]
I have tested the feature, following the instructions in the PR, and it works as expected. Please refer the screenshots attached below.

Jordy add pop up editor controller unit tests #1055

**Review by ArshakBadalyan — APPROVED** [review]
Hi,
All tests have passed. Attached a screenshot as a result.
Thanks

Screenshot from 2024-08-11 21-00-48

**Review by adityasure9 — COMMENTED** [review]
The unit tests for popupEditorController have been implemented successfully, covering all key functions: getAllPopupEditors, getPopupEditorById, createPopupEditor, and updatePopupEditor. I tested the branch as instructed, and all tests passed without any issues. This PR significantly enhances the test coverage for the popup editor controller, ensuring its reliability.




Great work on adding these tests!

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (165)

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and its working as expected.

**Review by SMitta11 — APPROVED** [review]
I have tested this as per given instructions and all test cases passed.
Screenshot:

**Review by jinxyou — APPROVED** [review]
All test cases passed. Thank you!
Screenshot 2024-08-23 163401

**Review by AJAYINAVOLU — APPROVED** [review]
Tests are passing successfully.



Thank You

**Review by Saniya98 — APPROVED** [review]
Test cases passed as expected for me
image

**Review by ddshah878 — APPROVED** [review]
I have tested the PR, and all test cases have successfully passed.

image

**Review by panchalvatneu — APPROVED** [review]
All 12 tests passed, good work!

image

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture1055

**Review by ashmita123 — APPROVED** [review]
I've tested the feature. All unit tests passed successfully. Everything worked as expected.

Great work!

Screenshot 2024-09-20 at 2 39 11 PM

**Comment by mianmiantea2019** [comment]
All unit tests passed successfully.

image

**Comment by tharunaa-1** [comment]
all the test cases passed as expected.

image

**Comment by geetamatkar** [comment]
Hi @j-corp-25 ,
Tested this PR and all test cases have passed.

PR1055

**Review by ziyanw52 — APPROVED** [review]
All the test cases passed successfully.
1151728197038_ pic_hd

**Comment by pallavithorat** [comment]
I tested it as outlined above, and all tests have passed successfully.
PR#1055

**Comment by mianmiantea2019** [comment]
All the test cases passed successfully.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
