### PR TITLE
Parthj unit tests and integration test for time zone api controller.js

### PR DESCRIPTION
**Pull request by Parth-tech**
# Description
This PR contains both unit tests and integration tests for the `timeZoneAPIController.js`. 

## Related PRS (if any):
- This pull request is not related to any frontend pull request.
- This PR consists of similar unit tests as [PR 1027](https://github.com/OneCommunityGlobal/HGNRest/pull/1027) but in addition this PR covers the scenario when the `.env file` consists of both `TIMEZONE_COMMON_KEY` and `TIMEZONE_PREMIUM_KEY` API keys.

## Main changes explained:
- This unit tests which were part of [PR 1027](https://github.com/OneCommunityGlobal/HGNRest/pull/1027), were not correct since they did not consider the scenario when the `.env file` already consisted of both `TIMEZONE_COMMON_KEY` and `TIMEZONE_PREMIUM_KEY` API keys. Hence the unit tests have been refined. 
- The `timeZoneAPIController.js` too is modified to read the API keys within the `timeZoneAPIController function`.

## How to test:
1. check into current branch i.e. `git checkout parthj_unit_tests_and_integration_test_for_timeZoneAPIController.js`
2. do `npm install`
3. Go to [OpenCage Website](https://opencagedata.com/) and either login or sign up.
4. Create a GeoCoding API key. You do not need to pay anything as we can perform testing using the free trail's API key.
5. Open `.env file`
6. Set `TIMEZONE_PREMIUM_KEY=some_random_string`
7. Set `TIMEZONE_COMMON_KEY=Generated_API_Key_Of_Step_4`
8. `Save .env`
9. run the test i.e. `npm run test timeZoneAPI`

## Screenshots or videos of changes:
\
`Final Result after successful execution of tests:`

Screenshot 2024-08-02 at 2 59 13 PM

\
\
`Video Reference to generate API Key`

https://github.com/user-attachments/assets/e130939c-c81a-4c82-849c-9d709fbf5b3d

### CODE REVIEW

**Review by aaryaneil — DISMISSED** [review]
Tested the PR by following the instructions in the description and the test case for timeZoneAPI routes › getTimeZone - request parameter `location` based tests › 401 when `API key` is missing failed. I have attached a screenshot for your reference.
Screenshot 2024-08-03 at 10 44 17 AM

**Comment by Parth-tech** [comment]
> Tested the PR by following the instructions in the description and the test case for timeZoneAPI routes › getTimeZone - request parameter `location` based tests › 401 when `API key` is missing failed. I have attached a screenshot for your reference. Screenshot 2024-08-03 at 10 44 17 AM

Hi [Aaryaneil](https://github.com/aaryaneil),
Thank you identifying this bug. I will check it out.

**Review by Shadhrush5 — APPROVED** [review]
Hi, I have reviewed PR #1052. I executed the steps as mentioned and was able to run all the test cases with all of them passing. Thank you for the great work.

Screenshot 2024-08-05 at 12 29 40 PM

**Review by manikittu810 — APPROVED** [review]
Hello @Parth-tech 
All test cases passed as per mentioned above.
Screenshot 2024-08-05 at 4 04 17 PM

Thank you.

**Review by ishan-miglani — APPROVED** [review]
Hi, I have verified the test cases in this PR. All test cases pass after following the instructions. Thanks!
Screenshot 2024-08-09 at 5 37 45 PM

**Review by AnkitLall — APPROVED** [review]
I have tested the feature, following the instructions in the PR, and it works as expected. Please refer the screenshot attached below.

Parthj unit tests and integration test for time zone api controller js #1052

**Review by nikhilpittala16 — APPROVED** [review]
I have followed all the steps and tested the PR. All the test cases have passed.
Screenshot (167)

**Comment by SMitta11** [comment]
I tested this as per given instructions and all test cases passed:
PR 1052

**Review by SMitta11 — APPROVED** [review]
I tested this as per given instructions and all test cases passed:
PR 1052

**Review by adityasure9 — APPROVED** [review]
I have tested the PR by following the provided instructions. The unit tests and integration tests for the timeZoneAPIController.js work as expected. All test cases pass successfully after setting the TIMEZONE_PREMIUM_KEY and TIMEZONE_COMMON_KEY in the .env file. 

image

**Review by oliviahyw — APPROVED** [review]
I have tested this PR and all test cases were passed.
PR1052

**Review by AJAYINAVOLU — APPROVED** [review]
Tests are passing successfully.




Thank You

**Review by yashwanth170 — APPROVED** [review]
I've tested the feature according to the instructions in the PR, and it functions as expected. Please see the attached screenshot below for reference.
geolocation_api

**Review by Shreyav2000 — APPROVED** [review]
I have reviewed the PR for parthj_unit_tests_and_integration_test_for_timeZoneAPIController.js. All tests have passed successfully, and the implementation looks good. The test cases are comprehensive and cover various scenarios effectively.
Screenshot 2024-09-03 at 12 29 45 AM

**Review by Saniya98 — APPROVED** [review]
All test are passing successfully
image

**Review by SFA23SCM35V — APPROVED** [review]
Reviewed PR all the test cases passed approving 
PR #1052

**Review by neeharikakoniki — APPROVED** [review]
The unit and integration tests for the `timeZoneAPIController.js` passed successfully, including the scenario with both `TIMEZONE_COMMON_KEY` and `TIMEZONE_PREMIUM_KEY` API keys set in the `.env` file. 

image

**Comment by geetamatkar** [comment]
Hi @Parth-tech ,
I executed the steps as mentioned and all test cases are running as expected.

PR1052

**Review by Muzammil603 — APPROVED** [review]
image
I have tested this and it is working correctly

**Review by panchalvatneu — APPROVED** [review]
All 22 timeZoneAPI tests passed, good work!
image

**Comment by mianmiantea2019** [comment]
All tests passed, good work!

image

**Review by anirudhsk2107 — APPROVED** [review]
Hello @Parth-tech 

All test cases have passed 
Screen Shot 2024-09-19 at 3 04 51 PM

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
