### PR TITLE
Chengyan phase2 purchase reusable record backend

### PR DESCRIPTION
**Pull request by ChengyanOo**
# Description
This update introduces a backend enhancement for the **_purchase record addition/update for Reusable Items_** endpoint. It ensures seamless integration with the frontend's item management functionalities.

## Related PRS (if any):
While the frontend integration for this feature is still under development, you can utilize the in-progress frontend work for testing purposes. Check out [Chengyan phase2 reusables list UI #1956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956/) for the frontend changes. This will allow you to test the backend functionality in a more interactive manner, keeping in mind that the frontend is not yet finalized and subject to change.

## Main changes explained:
- Implemented the addReusable controller and SeedReusableItems helper, including checks for req.body ID and data types.

## How to test:
1. Switch to the current branch.
2. Execute `npm install`, `npm run build`, and `npm run start` to run this PR locally.
3. Test in conjunction with the frontend PR [Chengyan phase2 reusables list UI #1956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956/)
4. Review the code for potential code smells.

## Screenshots or videos of changes:
[Screenshot of Feature](https://github.com/OneCommunityGlobal/HGNRest/assets/69735000/836530b0-f067-49ff-9522-a4b74bee8950)
[Feature Walkthrough Video](https://www.loom.com/share/296df1740404450c9d8872a90f88f07f?sid=9c40806b-20aa-4033-a2be-a2d3bfc40a2e)

## Note: Sample Request Body Format
This example illustrates the expected format of the request body for submitting a purchase record:

```json
{
  "projectId": "65419e61105441587e2dec99",
  "itemTypeId": "65d517bd5ea5498275d7a732",
  "quantity": 88,
  "priority": "High",
  "brandPref": "3M",
  "requestorId": "6585fa42c53bf42bc52f237a"
}

### CODE REVIEW

**Review by ShengjieMao — APPROVED** [review]
Tested the backend with the frontend parts. Left a review there.

**Review by XiaohanMeng — APPROVED** [review]
Hi, I left my comment on frontend: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1979#pullrequestreview-1912212513

**Review by skaush21 — APPROVED** [review]
left a comment on frontend [PR 1979](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1979#pullrequestreview-1912569509)

**Comment by beblicarl** [comment]
I tested the frontend of this functionality and it works as intended

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
