### PR TITLE
Ramakrishna Teamcode Regex change and select All with No Team code option fix

### PR DESCRIPTION
**Pull request by Ramaruva**
## Related PRS (if any):
This Backend PR is related to [#2401](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2401) Frontend PR

…

## Main changes explained:
-updated the teamcode regex in necessary file to meet up new requirement to allow the any special characters anywhere in teamcode

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Please check frontend PR for further instructions

### CODE REVIEW

**Review by jinxyou — APPROVED** [review]
I left a review at 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2401#pullrequestreview-2149932861

**Review by HowieMiao — APPROVED** [review]
After testing PR, can ensure that team code Regex update now allows for all special characters. Disregarding status code 500 error when inputting, everything else seems to be in order with being able to select section with no team codes as well.

image

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and everything works fine. Left review on [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2401#pullrequestreview-2152296091)

**Review by sahithidhulipala9 — APPROVED** [review]
Left comment at Front End PR 2401.

**Review by vijay10pk — APPROVED** [review]

**Review by vishavk1992 — APPROVED** [review]
everything working perfectly except 500 error, i also left comment on frontend PR#2401

**Review by Trip2310 — APPROVED** [review]
Tested this backend PR with all special character, despite of 500 error able to select tem with no code. 
PR_1010

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works fine. Left review on frontend PR.
link can be found here: [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2401#pullrequestreview-2159535951
](url)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
