### PR TITLE
Jinchao fix visibility issues in Team Member Tasks

### PR DESCRIPTION
**Pull request by suigunfjc**
# Description
This PR solves the 7.c
image
The overall visibility logic in Team Member Tasks is same to leaderboard:
image
This PR will cover the visibility part and no-team user part. Another PR will be raised to solve the weeklyCommitTime logic.
## Main change
This PR aims to improve the taskController by following the best practice of separating the concerns of controllers and helpers. The controller functions should only handle req and res, while any supporting or business logic should be moved to helper functions. To achieve this, we have refactored the getTasksForTeamsByUser function in the controller by moving the related Mongoose code to a new function called getTasksForTeamsByUser in the taskHelper. Additionally, a new function called getTasksForSingleUser was created to handle cases where the user is not part of any team. This change has simplified the controller function and improved its readability and maintainability.
## How to test
Please test the visibility of Team Member Tasks for different classes of users by creating a team with all classes of users and logging in as each class. Make sure the visibility rules outlined in the specifications are followed. Additionally, test the three buttons to ensure that this PR does not break Kaixiang's latest update: [#800](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/800)

### CODE REVIEW

**Review by abdel-lall — APPROVED** [review]
Works as expected. Nice job!

PR353

**Comment by GKD890** [comment]
Tested from a volunteer account, can't see a invisible mentor in the same team. While the mentor can see members indeed. 

However, the button may break the app, tested from either mentor or volunteer account. A video link from mentor's view:

https://github.com/OneCommunityGlobal/HGNRest/assets/57503876/5b1e7b89-8ca8-4a71-b67e-71bad2728e01

an incomplete screenshot from console when that happened:

Backend_PR#353_button-crash

**Review by EdwinLauM — APPROVED** [review]
Hi @suigunfjc, I tested the changes and it works as intended. Tested on a volunteer account with an invisible admin and invisible mentor and both didn't show up. Good job!

PR #353

**Comment by papiasharmin** [comment]
Hello @suigunfjc,  I have tested PR from admin account and volunteer account with no team assigned. It's working as intended. one thing is when i change from admin to volunteer i can see all member task until i did a full refresh and vise-versa. I have console log the teamsData and singleUserData, they are fetch correctly though.
teamtask1
teamtask2
teamtask4
teamtask5

**Review by papiasharmin — APPROVED** [review]
the code looks good to me, great work.

**Review by 20chen-7 — APPROVED** [review]
I tested using the admin and manager accounts, and the visibility is intended.
Screenshot 2023-05-24 at 11 43 13 AM

**Review by yoyoweiii — APPROVED** [review]
I have tested in Admin, manager and volunteer accounts. It works as intended. Good work! @suigunfjc 
HGN APP - Personal - Microsoft​ Edge 5_25_2023 3_00_14 PM
HGN APP - Personal - Microsoft​ Edge 5_25_2023 3_00_54 PM
HGN APP - Personal - Microsoft​ Edge 5_25_2023 3_01_27 PM

**Pull request merged**
