### PR TITLE
Diego putting back unit and integration tests

### PR DESCRIPTION
**Pull request by DiegoSalas27**
# Description
Brings back unit and integration test files

## Related PRS (if any):
N/A

## Main changes explained:
N/A

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run the following command to run unit and integration tests: `npx jest --passWithNoTests --silent --noStackTrace --runInBand --forceExit`
4. 
## Note:

### CODE REVIEW

**Review by 20chen-7 — COMMENTED** [review]
after run `npx jest --passWithNoTests --silent --noStackTrace --runInBand --forceExit`, the test looks like:
Screenshot 2024-04-11 at 11 39 36 AM

**Review by linkhanthtel — COMMENTED** [review]
After running command, the test cases failed!

**Review by linkhanthtel — COMMENTED** [review]
I reviewed your PR and it shows one test failed!

**Comment by DiegoSalas27** [comment]
> I reviewed your PR and it shows one test failed!
> 
> 

Hey @linkhanthtel, there is no dashBoardController.spec.js file in this PR, please ensure you are working with the test files that are present in this PR. Let me know go it goes.

**Review by linkhanthtel — APPROVED** [review]
Hi Diego! I reviewed your PR and all tests passed!

**Comment by DiegoSalas27** [comment]
> Screenshot 2024-04-12 at 2 44 44 PM Screenshot 2024-04-12 at 2 44 53 PM Hi Diego, I have not finished `informationController`part, could you remove that from the branch?

Hey @20chen-7, please remove your `dist` folder and rerun the tests. Let me know how it goes.

**Review by 20chen-7 — APPROVED** [review]
Excellent work!
Screenshot 2024-04-12 at 10 00 34 PM

**Review by aaryaneil — APPROVED** [review]
Tested the code and all passed all the test cases.
Screenshot 2024-04-13 at 8 53 44 PM

**Review by Pandani07 — APPROVED** [review]
The tests passed. Refer photo 
Screenshot 2024-04-15 at 10 18 40 PM

**Comment by alla0810** [comment]
All test passed.  Great work!


image

**Comment by mianmiantea2019** [comment]
Tested the code and all passed all the test cases. Great work!

image

**Pull request merged**
