### PR TITLE
Olga_enforce_email_input_on_login

### PR DESCRIPTION
**Pull request by cvtqx**
# Description

(PRIORITY MEDIUM) Gary/Jae: (WIP Olga) Enforce email input when logging in so a user has to input their entire email address.
1.Start on the login page.
2.Enter any valid email address you’ve used in the past to login but enter only one character after the @ symbol in your email. I’m assuming this will work with any number of characters after the @ symbol.
3.Type in the correct password and you will be able to login.

## Main changes explained:
Removed regex from findOne query in loginController to enforce strict search

## How to test:
1. check into current branch
2. do `npm run build` and `npm start` to run this PR locally
3. check into development branch on the front end and run it
4. log in as any user
5.  verify that you are only able to log in when a complete email address is typed and are not able to log in otherwise

## Screenshots or videos of changes:

BEFORE:
https://www.loom.com/share/a2aafa6d99f44cf5abc8e33199951bbb

AFTER:
Loggin_in_AFTER

### CODE REVIEW

**Review by vinaykumarh — APPROVED** [review]
Reviewed the PR and the changes works as expected. Now the validation of user is based on complete email/username. Good work!

Before:

https://github.com/OneCommunityGlobal/HGNRest/assets/92617693/c582e218-32bd-411b-980c-3dd4593a1777

After:

https://github.com/OneCommunityGlobal/HGNRest/assets/92617693/d8fd8485-5056-436b-b92f-3cbca4f688fb

**Review by yaow62023 — APPROVED** [review]
I have tested your PR, no error related with this PR. The new user name check feature works great. 

https://github.com/OneCommunityGlobal/HGNRest/assets/137429365/6800dbd0-8545-4bf3-8096-29d667d3b18a

**Review by winghojackyli — APPROVED** [review]
Hi @cvtqx , I've tested the PR and it works as intended. 

https://github.com/OneCommunityGlobal/HGNRest/assets/108389005/f793ac1f-429c-407d-9d20-0b21395b224a

**Review by EdwinLauM — APPROVED** [review]
Hi @cvtqx! Code changes work as expected! Good job! :)

https://github.com/OneCommunityGlobal/HGNRest/assets/42288987/35cfa3e1-0455-45ba-8b6a-4234cd8f107c

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
