### PR TITLE
Jerry: is-email-exists route

### PR DESCRIPTION
**Pull request by jerryren527**
# Description
- This PR creates an unauthenticated route that provides non-sensitive data. This route checks if the provided email exists among all userProfiles in the database.
- The motivation of this PR is to use it in this task:

Screenshot 2023-09-28 at 11 40 24 AM

- I hope to have this PR merged into the development branch and then eventually into the main branch. Once this route is live in the beta app, I can make an axios request to this route in the beta backend server (i.e.,  make a GET request to `https://hgn-rest-beta.azurewebsites.net/api/is-email-exists/:email`)

- For the task shown in the above screenshot, I plan to make an axios GET request to `https://hgn-rest-beta.azurewebsites.net/api/is-email-exists/:email` for every attempt to create a new Admin or Owner account in the development environment. This route will respond with a 200 status code if the email provided exists in the beta database, or 404 status code if the email does not exist in the beta database.

## Related PRS (if any):
- N/A for now.

## Main changes explained:
- Created `src/controllers/isEmailExistsController.js,` and `src/routes/isEmailExistsRouter.js`
- Applied isEmailExistsRouter to app  in `src/startup/routes.js`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. In Postman, log into any account (POST `http://localhost:4500/api/login`)
4. Copy token from response, then make a request GET `http://localhost:4500/api/is-email-exists/:email`. You must add an ‘Authorization’ header and set the value to the token value you just copied. 
5. For a URL parameter, type in an email address that exists in the dev database. You should get a 200 status code response.
6. Now for the URL parameter, type in an email address that does not exist in the dev database. You should get a 404 status code response.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/55968519/b4bc5e50-fc9c-442c-9d18-b7deb1e8d7b5

## Note:
N/A

### CODE REVIEW

**Review by wantingxu7 — APPROVED** [review]
Hi @jerryren527 
the PR looks good to me, good work. You can find the testing video:

https://github.com/OneCommunityGlobal/HGNRest/assets/105323719/48d69139-92d6-4aa0-a57b-37ff5219cc1a

**Review by yangfan2001 — APPROVED** [review]
Hi! I have tested your new api in my local Postman. It works perfectly. Great Job!
image
image

**Review by tsunami776 — APPROVED** [review]
Hi @jerryren527, I tested the route locally using Postman and it works as described in the PR. Only users with emails stored in userProfiles will be prompted `Email, xxx@xxx.com, found.`


https://github.com/OneCommunityGlobal/HGNRest/assets/43768723/c98216a9-908a-4ed6-8c2a-ea5c3f84961b

**Review by malikjahanzaib — APPROVED** [review]
Hi @jerryren527 , I tested the feature locally with Postman and it works as intended. After logging in, 'is-email-exists' route returns 200 OK for an email in the system and 403 Forbidden for an email that does not exist. Great job!

Here is the test rec:

https://github.com/OneCommunityGlobal/HGNRest/assets/46221334/3ace8ff6-d7b9-43b6-bf77-5fd5c9cbe034

**Review by Iris-Song — APPROVED** [review]
Hi @jerryren527 , I tested the feature locally with Postman .It works as intended on exist email and nonexist email. 
Goodjob!
Screenshot 2023-10-06 at 15 39 38
Screenshot 2023-10-06 at 15 39 28

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR and it works as expected. I tested for both registered user and user who is not registered.

Screenshot 2023-10-06 at 10 01 04 PM

Screenshot 2023-10-06 at 10 01 22 PM

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works as intended.
Screenshot 2023-10-07 at 8 55 23 PM
Screenshot 2023-10-07 at 8 56 11 PM

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I tested your PR and works as intended. Great work!

https://github.com/OneCommunityGlobal/HGNRest/assets/92185695/6fd011ea-fc5c-4b3e-a248-cbc2ab1f77cc

**Review by BaileyM96 — APPROVED** [review]
Good afternoon @jerryren527 I went ahead and tested your changes on the back end and everything works fine, great work!

## Screenshots

Email Found
PR 560 is email exists route

Email NOT Found
PR 560 is email is NOT found

**Comment by BaileyM96** [comment]
@one-community This has 8+ approvals including mine.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
