### PR TITLE
Edwin - Fix logging authentication so partial match does not authenticate

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-06-19 at 3 46 39 AM

## Main changes explained:
Added "^" to the start of the string and "$" to the end of the string so that it has to match exactly to the email

## How to test:
1. check into current branch
2. do `npm run build` && `npm run start`
3. Check for partial email matching. Partial email matching should not authenticate a user.

## Video/Screenshots

https://github.com/OneCommunityGlobal/HGNRest/assets/42288987/829b6cb3-63e5-4b7a-b157-8093c78088d4

### CODE REVIEW

**Review by Chuehleo — APPROVED** [review]
Everthing work as intended, great job!

https://github.com/OneCommunityGlobal/HGNRest/assets/122568562/953edc8f-71ce-4644-aacf-f367a5d29237

**Review by KurtisIvey — APPROVED** [review]
functions as intended. Nice job 
pr412 works

**Review by eduhorta — APPROVED** [review]
Great job! 👍
The new regex won't accept the truncated domain.

image

**Comment by one-community** [comment]
Thank you all, moving this one to final review!

**Review by juneluo — APPROVED** [review]
It works as expected, well done.

**Pull request merged**
