### PR TITLE
Peizhou_multiple blueSquare delete issue

### PR DESCRIPTION
**Pull request by ZhangPeizhou**
# Description
image
https://www.loom.com/share/54d8b97ed84440f2bab51cc2de05b34d?sid=6a79915a-1b1c-4315-bdbc-6c5de28a867d

## Related PRS (if any):
This frontend PR is not related to any backend PR, please just check in to the development branch.

## Main changes explained:
- Explained why this issue happened. This issue is fixed by other pull requests as the router gets more completed.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to user profile
6. delete multiple blue squares, and refresh the page, see if those blue squares come back.

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/af252c69-2e79-450e-8d5d-c1dd7d4dc130

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Lexie5212 — APPROVED** [review]
I tested the PR, and the code changes worked as expected.

https://github.com/user-attachments/assets/2ecd6f90-4855-49bf-bc9a-91e94f34c319

**Review by manikittu810 — APPROVED** [review]
Hello @ZhangPeizhou 
PR working as mentioned.

Screenshot 2024-09-24 at 6 24 39 PM

Thanks.

**Review by nevatiarishabh — APPROVED** [review]
I have tested this PR. Everything is working as expected. The blue squares do not come back when they are deleted.

https://github.com/user-attachments/assets/ecf969e5-2b95-4b53-8bb8-7e034cea2143

**Review by anirudhsk2107 — APPROVED** [review]
The changes are working. The blue squares do not reappear 

Before:
Screen Shot 2024-09-25 at 6 01 16 PM

After:
Screen Shot 2024-09-25 at 6 01 39 PM

**Review by ashmita123 — APPROVED** [review]
Tested PR #1117 . It works as expected.

Before:
Screenshot 2024-09-25 at 9 02 23 PM

After: The blue squares does not come back.

Screenshot 2024-09-25 at 9 02 31 PM

**Review by neeharikakoniki — APPROVED** [review]
I tested this PR, and everything is functioning as expected. Once the blue squares are deleted, they do not reappear.

image

**Review by SFA23SCM35V — APPROVED** [review]
I checked out the current branch, ran `npm install` to set up the environment, and cleared the site data/cache. After logging in as an admin user, I navigated to the user profile, successfully deleted multiple blue squares, and verified that they did not return after refreshing the page. Everything is working as expected.



Screenshot (22)

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as mentioned.

https://github.com/user-attachments/assets/2ca2287e-ca87-48eb-9aef-ae641a85ff0e

**Review by ziyanw52 — APPROVED** [review]
This works.
When delete the blue squares, it will show the message that the blue squares are deleted successfully. And after refreshing the page, the blue squares are gone and not coming back.
171727423065_ pic_hd
181727423084_ pic_hd
161727423044_ pic_hd

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
