### PR TITLE
Diya blue squares changes

### PR DESCRIPTION
**Pull request by DiyaWadhwani**
# Description
Revoking the Edit Blue Squares permission ensures that the ‘Update’ button is not visible. Similarly, with the Delete Blue Squares and Assign Blue Squares permissions, the ‘Delete’ and ‘+’ buttons must not be visible to the user.
Update and Delete functionalities must update and delete the particular blue square.

## Related PRS (if any):
This backend PR is related to the backend PR #943.
To test this, you need to checkout PR #[2248](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2248) frontend PR

## Main changes explained:
- Commented out the check for the existing cache for a user so that the newly updated data in the database is fetched and displayed in realtime everytime the /userprofile API is called. 
- Added code to populate the infringements field when a user profile is being fetched.

## How to test:
1. check into current branch for the backend and the branch mentioned in the related frontend PR
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Log in as admin user
5. Other Links> Permissions Management>Volunteer>Assign/Edit/Delete Blue Squares
6. Log in as a volunteer and test all functionalities.

## Screenshots or videos of changes:
Screenshot 2024-07-03 at 9 58 40 AM

## Note:
Please ensure you test the assign/edit/delete individually as well to ensure that each of the permissions has its own buttons visible as well as its own functionality.

### CODE REVIEW

**Review by jinxyou — APPROVED** [review]
The permission control seems fine, and most of them are working properly. The one little issue I encountered was when I update/delete a blue square as a volunteer, I did receive two pop up window simultaneously, one being "successful", one being "failed", and it seems to happen all the time. Please see if you can fix it. Thank you. 
Screenshot 2024-07-13 161349
Screenshot 2024-07-13 161422
Screenshot 2024-07-13 161431
Screenshot 2024-07-13 161443
Screenshot 2024-07-13 161452

**Review by SMitta11 — APPROVED** [review]
I login as admin and gave permissions to volunteer to assign/edit/delete blue squares and then login as volunteer and tested that volunteer can perform these functionalities.
Screenshots:
Screen Shot 2024-08-22 at 5 05 33 PM
Screen Shot 2024-08-22 at 5 22 43 PM
Screen Shot 2024-08-22 at 5 23 23 PM

**Review by Parth-tech — APPROVED** [review]
Hey Diya,
When the volunteer account has the permissions, the account is able to edit, assign or delete accordingly. The PR works nicely. The only problem I encountered was that I had to logout and log back into the volunteer account in order to reflect the change in permissions.

`Image References:`

Screenshot 2024-08-29 at 5 37 24 PM

Screenshot 2024-08-29 at 5 35 41 PM
Screenshot 2024-08-29 at 5 36 36 PM

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected. I gave permission to the volunteer account to edit blue squares and tested that the volunteer is able access these functionalities.




Thank You

**Review by vedantg24 — APPROVED** [review]
Tested the PR, and the changes are working as expected. I gave an existing volunteer account the permissions required through an admin account. Logged back in as the volunteer, and the create, edit and update blue squares is working perfectly fine.

Screenshot 2024-08-31 at 1 16 53 PM
Screenshot 2024-08-31 at 1 17 36 PM
Screenshot 2024-08-31 at 1 17 56 PM

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are working as expected. Below are the screenshots for reference:
PR_Review_1016_1
PR_Review_1016_2
PR_Review_1016_3
PR_Review_1016_4

**Review by sri0606 — CHANGES_REQUESTED** [review]
Hey @DiyaWadhwani , I have reviewed your pull request. These are some issues I found:

* After giving an user the blue square permissions, I can see the "+" sign and was able to add a blue square.
* I get two popups saying it was both successful and a failure.
* But it is gone after refreshing the page and not being saved.
* When I click on the blue square, I get an empty "Save and Refresh" popup, but there is no save button. ("Save Changes" button is disabled).

Please refer to video below:

https://github.com/user-attachments/assets/54489c08-0ea8-4309-8917-5e64e71c69cf

Screenshot 2024-08-31 155612
Screenshot 2024-08-31 164832

**Comment by DiyaWadhwani** [comment]
> Hey @DiyaWadhwani , I have reviewed your pull request. These are some issues I found:
> 
> * After giving an user the blue square permissions, I can see the "+" sign and was able to add a blue square.
> * I get two popups saying it was both successful and a failure.
> * But it is gone after refreshing the page and not being saved.
> * When I click on the blue square, I get an empty "Save and Refresh" popup, but there is no save button. ("Save Changes" button is disabled).
> 
> Please refer to video below:
> 
>  PR.1016.mp4 
> Screenshot 2024-08-31 155612 Screenshot 2024-08-31 164832

Hi,
I checked this again and wasn't able to reproduce the issue you faced. Dropped a video below.

https://github.com/user-attachments/assets/4ebd38cc-28fc-42f4-8fb3-fc98890a7702

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
