### PR TITLE
Yongjian - Fix editing end date input for volunteering times tab

### PR DESCRIPTION
**Pull request by ypan710**
# Description
Screen Shot 2023-04-30 at 9 36 47 PM

## Mainly changes explained:
Added.a conditional check to ensure user is in cache before setting the end date in the record to that of user's data.

## How to test:
1. check into current branch
2. do `npm run build` and `npm start` to run this PR locally
3. check into frontend's development branch and do `npm run start:local`
4. login as admin role, under "Welcome, XXX" -> View Profile -> Volunteering Times tab, edit the End Date input and click on "Save Changes" button and verify there is no error alert.

## Screenshots
Screen Shot 2023-04-30 at 3 06 35 PM

Screen Shot 2023-04-30 at 3 06 47 PM

Screen Shot 2023-04-30 at 3 06 57 PM

Screen Shot 2023-04-30 at 3 07 09 PM

### CODE REVIEW

**Review by yoyoweiii — APPROVED** [review]
Hi Yongjian, I have tested these changes as a Admin as it required on the local env. The video attached show the updated end date comes without error. Good work! 


https://user-images.githubusercontent.com/60588210/235991217-85d09ab1-f5cd-41dc-8cb3-728ac9fdf908.mp4

**Comment by wang9hu** [comment]
There is no error when setting and saving 'End Date' from me. Good job! 
Screenshot 2023-05-04 175405
Screenshot 2023-05-04 175452

**Comment by EdwinLauM** [comment]
Works as intended! I was able to change the end date successfully without an error getting triggered. Great fix with just a conditional check!


https://user-images.githubusercontent.com/42288987/236363577-1c02f687-9a02-4b3d-98bd-2f2ee393c756.mov

**Review by EdwinLauM — APPROVED** [review]
Works as intended! I was able to change the end date successfully without an error getting triggered. Great fix with just a conditional check!

https://user-images.githubusercontent.com/42288987/236364267-7f2c8359-8845-42ea-a74c-41a275d3461e.mov

**Comment by papiasharmin** [comment]
The end date functionality working great.

https://user-images.githubusercontent.com/86232710/236515256-859b4514-f0f4-469e-a617-1e186cf6eacf.mp4

**Review by Sneha1b — APPROVED** [review]
LGTM!
Screen Shot 2023-05-04 at 1 40 06 PM
Screen Shot 2023-05-04 at 1 40 14 PM

**Comment by one-community** [comment]
Thank you all, moving to final review

**Review by abdel-lall — APPROVED** [review]
Works as expected. Good job!

PR338

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
