### PR TITLE
Jordy add notification controller unit tests

### PR DESCRIPTION
**Pull request by j-corp-25**
# Description

Unit tests for notificationController

## Related PRS (if any):
N/A

## Main changes explained:

- unit tests for `getUserNotifications`
- unit tests for `getUnreadUserNotifications`
- unit tests for `getSentNotifications`
- unit tests for `createUserNotification`
- unit tests for `deleteUserNotification`
- unit tests for `markNotificationAsRead`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run `npm run test notification`

**If  you want a detailed description you can run `npm run test notification -- --verbose`**

## Screenshots

Screenshot 2024-05-04 at 12 55 26 AM

## Note:

N/A

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
I reviewed your PR and all tests passed! Nice work!

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed. Good work.
Screenshot 2024-05-04 at 4 16 03 AM

**Review by MinSun0814 — APPROVED** [review]
image
Tested PR and tests passed.

**Review by Ramaruva — APPROVED** [review]
Hey I have run all test cases in my local env and all test cases are passed
image

**Review by nathcarnevalli — APPROVED** [review]
I reviewed your controller and I didn't find any problems or things to change. The tests are well implemented. Nice work! 

image

**Review by KaushikMreddy — COMMENTED** [review]
Hi, I've reviewed the code and the changes. All test cases have passed, code is clear and easy to follow. Great work!

image

**Review by gowthamdongari — APPROVED** [review]
All test cases working well in local environment
image

**Review by jayyy-s — APPROVED** [review]
Unit tests for notifications all pass. Test cases are consistent with and thoroughly cover all possible branches of the notification service and controller.
unit test pass
verbose passed

**Review by Abi-Liu — APPROVED** [review]
Hey Jordy, the tests look good!
Screenshot 2024-05-07 at 3 10 06 PM

**Review by Parth-tech — APPROVED** [review]
Hey Jordy,
Everything works correctly. Good Job!
Screenshot 2024-05-18 at 5 33 31 PM

**Review by Sandhya1236 — COMMENTED** [review]
All test cases passes. Good Job.


image

**Review by Sandhya1236 — APPROVED** [review]
https://github.com/OneCommunityGlobal/HGNRest/pull/925/files

image

**Review by Infinite-Turkey — APPROVED** [review]
image
All tests passed. Well done!

**Review by deepthikannan — APPROVED** [review]
image
I reviewed your PR and all the test cases passed well.

**Review by peter6866 — APPROVED** [review]
All tests passed as expected!
image

**Comment by ZhangPeizhou** [comment]
PR#925 Review
Pass all the tests

**Review by dikshitakejriwal — APPROVED** [review]
I reviewed your code and it looks good. All the test cases passed. 
Screenshot 2024-05-31 at 11 59 50 AM

**Review by Wenboooooo — COMMENTED** [review]
All tests have passed, it looks good to me.

**Review by Wenboooooo — APPROVED** [review]
All tests have passed, it looks good to me.

**Review by jinxyou — APPROVED** [review]
All test cases have passed. Great work!
Screenshot 2024-06-01 211541

**Review by Kavil-Jain-514 — APPROVED** [review]
All test cases passed!!


image
image


image
image

**Comment by akshit0211** [comment]
All test cases passed. Great work!

test notification
test notification -- --verbose

**Review by akshit0211 — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
