### PR TITLE
Nathan separate edit time entry permissions

### PR DESCRIPTION
**Pull request by nathanah**
# Description
This PR divides the `editTimeEntry` permission into several subpermissions controlling each part which can be edited (date, isTangible, time, and description).

## Related PRS (if any):
To test this backend PR you need to checkout the #[2221](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2221) frontend PR.

## Main changes explained:
- Added permissions to `PermissionsConst.js`
- Replaced `editTimeEntry` with `editTimeEntryTime`, `editTimeEntryDescription`, `editTimeEntryDate`, `editTimeEntryToggleTangible` (change tangibility for other users' time entries), and `toggleTangibleTime` (change tangibility for own time entries)

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links→ Permissions Management → Manage User Permissions
6. grant a volunteer account one of the listed permissions individually (`editTimeEntryTime`, `editTimeEntryDescription`, `editTimeEntryDate`, `editTimeEntryToggleTangible`, and `toggleTangibleTime`)
7. login to your volunteer account in an incognito window (so you can stay logged in with your owner account)
8. test the granted permission with volunteer
10. logout as volunteer
11. repeat steps 6-10 for each permission

## Notes
Check the Permissions Management spreadsheet or the descriptions in the Permissions Management Page for desired behaviors of permissions
https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit#gid=0

### CODE REVIEW

**Comment by mSharifHub** [comment]
Hello, I tested the code and I have not seen any issues or warning related to the functionality itself.
Screenshot 2024-05-04 at 3 24 40 PM

**Review by mSharifHub — COMMENTED** [review]
I would suggest a middleware approach to check for permissions to keep code more organized and easy to understand
I would suggest the following:
`const { hasPermission } = require('./permissions');

function requirePermission(permission) {
  return async function(req, res, next) {
    const hasPerm = await hasPermission(req.body.requestor, permission);
    if (!hasPerm) {
      return res.status(403).send({ error: 'You do not have the required permission' });
    }
    next();
  };
}

module.exports = {
  requirePermission
};`

besides this. the code functionality works as expected. I took a screen shot in the comments sections and have not noticed any issues.

**Review by nathcarnevalli — APPROVED** [review]
I tested every permission and all of them worked for me without any issues. Great job! However, I've found some problems with the frontend that I'll review on PR [#2221](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2221).

Screenshot 2024-05-10 092023

Screenshot 2024-05-10 093304

**Review by hbodgal — APPROVED** [review]
image

I was able to give permission and access it from volunteer account. I did not face any difficulties.

**Comment by KaushikMreddy** [comment]
I've left a detailed review in the front-end PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2221#pullrequestreview-2058698168

**Review by Wenboooooo — APPROVED** [review]
image

Looks good to me, all functions can be edited.

**Comment by cecilia-uu** [comment]
I have tested it and the #2221 frontend. It works well when I try to edit the time entries. But if I got it right, this change is to make this feature divided into different parts. I only add the 'edit Timelog description', but it seems that I can edit all the parts...
截屏2024-05-21 上午11 17 54
2-563e-455c-8fc0-c5df48853c38">

**Review by Sandhya1236 — APPROVED** [review]
I checked out the current branch, ran npm install and necessary commands to set up the PR locally, and cleared the site data/cache. As the owner user, I navigated to Dashboard → Other Links → Permissions Management → Manage User Permissions. I granted a volunteer account each of the listed permissions (editTimeEntryTime, editTimeEntryDescription, editTimeEntryDate, editTimeEntryToggleTangible, and toggleTangibleTime) individually. I logged into the volunteer account in an incognito window and tested each granted permission successfully. After logging out of the volunteer account, I repeated this process for each permission. All tests were successful, confirming that the permission management functionality works as intended.


image
image

**Review by Kavil-Jain-514 — APPROVED** [review]
Everything worked fine. The volunteer was able to edit the tangible time with permissions.
image

**Review by Parth-tech — APPROVED** [review]
Hey Nathan,
The codebase looks great and the required functionality works as intended. Great job! I have left a detailed review on the front-end repo, [review link.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2221#pullrequestreview-2091815844)

**Comment by peter6866** [comment]
Hi Nathan, I left a detailed review for the frontend PR.

**Review by ImzIssa — APPROVED** [review]
I reviewed your PR and everything looks great.

**User can edit the date**
Screenshot (418)

**User can edit the time log**
Screenshot (416)

**User can edit the description**
Screenshot (417)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
