### PR TITLE
Shengwei fix Sentry errors and update global error handling

### PR DESCRIPTION
**Pull request by ptrpengdev**
# Description
**Update backend error handling**.
- Include a new tag `tracking_id` which is searchable in the Sentry log
- Introduce a new global error handler to capture and log any unhandled error in the backend application

**Fix Sentry error**:
- sentry_emailSender_log

- sentry_profileIntialSetup

- sentry_userHelper_log

## Main changes explained:
- Update file src/controllers/profileInitialSetupController.js to eliminate `cannot set header after they sent to client` error
- Update file `src/routes/userProfileRouter.js` to fix the error introduced by unhandled null-value in sanitizer.
- Update the improper usage of logInfo() by applying JSON.stringify(obj) over the input.
- Create file `src/utilities/customError.js` to improve error handling practices
- Create file `src/utilities/globalErrorHandler.js` to include global error handling and capture any unhandled error in the backend application.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. To test for local and development environment logging, you need to configure NODE_ENV by adding **NODE_ENV=local** or **NODE_ENV=development** in the `.env` file. 
4. Verify missing value (firstName='' or lastName ='') is now handled in API POST http://localhost:4500/api/userProfile/ 
   - Verify error log is sent to console if NODE_ENV is set to `local`
   - Verify error log is sent to Sentry and searchable by `tracking_id`, `environment` or `transaction` tag if NODE_ENV is set to `development` 

     - image
     - image
     - image

- Sample Request Body:
```
{
    "password": "123Welcome!",
    "role": "Volunteer",
    "firstName": "Sample",
    "lastName": "Request",
    "jobTitle": "Software Engineer",
    "phoneNumber": "11111111111",
    "bio": "",
    "weeklycommittedHours": 10,
    "weeklySummaryOption": "Required",
    "personalLinks": [],
    "adminLinks": [],
    "teams": [],
    "projects": [
        {
            "isActive": true,
            "modifiedDatetime": "2024-03-28T18:50:00.516Z",
            "category": "Society",
            "_id": "6157b9a66dfe943665c9f83b",
            "projectName": "Orientation and Initial Setup"
        }
    ],
    "email": "sample_email@gmail.com",
    "privacySettings": {
        "blueSquares": true,
        "email": true,
        "phoneNumber": true
    },
    "collaborationPreference": "Zoom",
    "timeZone": "",
    "location": {
        "userProvided": "",
        "coords": {
            "lat": "",
            "lng": ""
        },
        "country": "",
        "city": ""
    },
    "allowsDuplicateName": false,
    "createdDate": "2024-04-22T11:59:03.866Z",
    "teamCode": "",
    "actualEmail": "",
    "actualPassword": ""
}
```

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by Ramaruva** [comment]
Hi when I am trying to test your changes  in postman I am getting invalid token can you please help me here how to get an valid token so that I can test the changes
image

**Review by alla0810 — CHANGES_REQUESTED** [review]
Hi, [ptrpengdev](https://github.com/ptrpengdev).
I have similar problem to [Ramaruva](https://github.com/Ramaruva)'s.

I ran this branch after adding `NODE_ENV=development` in the `.env` file.
I could see the Sentry message sending from my computer from the Sentry Server.
I've tried to send the POST message you recommended from Insomnia, but the message my Insomnia received from the branch is `error: Unauthorized request`.  

image

I also tried to access `http://localhost:4500/api/userProfile`, the server seems to have no route configured with this address.

image

**Comment by ptrpengdev** [comment]
> Hi when I am trying to test your changes in postman I am getting invalid token can you please help me here how to get an valid token so that I can test the changes image

Hi @Ramaruva 

You will **need a valid JWT token attached** to the request header. You could obtain the JWT token by : 
- Login into the application via UI. Inspect any network request and extra the token from the request's header.

**OR**

- Use Postman to call the /login endpoint with your credentials. The endpoint should return the JWT token in the response payload.

image

**Comment by alla0810** [comment]
> > Hi when I am trying to test your changes in postman I am getting invalid token can you please help me here how to get an valid token so that I can test the changes image
> 
> Hi @Ramaruva
> 
> You will **need a valid JWT token attached** to the request header. You could obtain the JWT token by :
> 
> * Login into the application via UI. Inspect any network request and extra the token from the request's header.
> 
> **OR**
> 
> * Use Postman to call the /login endpoint with your credentials. The endpoint should return the JWT token in the response payload.
> 
> image

Do we have test this PR like this hard?
I've tried to get the token from the network side, and used this token to send POST message to the server, but still failing with error message: "Invalid token".

image

image

**Comment by Ramaruva** [comment]
> > > Hi when I am trying to test your changes in postman I am getting invalid token can you please help me here how to get an valid token so that I can test the changes image
> > 
> > 
> > Hi @Ramaruva
> > You will **need a valid JWT token attached** to the request header. You could obtain the JWT token by :
> > 
> > * Login into the application via UI. Inspect any network request and extra the token from the request's header.
> > 
> > **OR**
> > 
> > * Use Postman to call the /login endpoint with your credentials. The endpoint should return the JWT token in the response payload.
> > 
> > image
> 
> I've tried to get the token from the network side, and used this token to send POST message to the server, but still failing with error message: "Invalid token".
> 
> image
> 
> image

Yes for me also I was getting same issue

**Comment by Ramaruva** [comment]
> > Hi when I am trying to test your changes in postman I am getting invalid token can you please help me here how to get an valid token so that I can test the changes image
> 
> Hi @Ramaruva
> 
> You will **need a valid JWT token attached** to the request header. You could obtain the JWT token by :
> 
> * Login into the application via UI. Inspect any network request and extra the token from the request's header.
> 
> **OR**
> 
> * Use Postman to call the /login endpoint with your credentials. The endpoint should return the JWT token in the response payload.
> 
> image

Hi,
I have tried using latest token also still getting same issue 
image

**Review by Ramaruva — APPROVED** [review]
After  adding proper tokens in postman and that too in header I was able to test the changes and I was able to see both logs in local and development 
Thanks 

image

image

**Review by Parth-tech — APPROVED** [review]
Hey Shengwei,
Everything seems to be correct, great job. 

Reference: 
Development_Slack-Lname notification
Development-Sentry-LName
Local-FName Log
Local-LName Log
Sentry Log LName

**Review by alla0810 — APPROVED** [review]
I should have input the token in the header field.
After setting the `Authorization` field in the header of the API packet after disabling the bearer authentication, I could also get the correct result.
Both `local` and `development` environments work good.
`development` environment can filter the issues based on `tracking_id` and `transaction`.
Nicely done!!

**Comment by KaushikMreddy** [comment]
Hi, 

1. Verified the changes on Node_Env = local, Errors are seen in Postman response and in console in Vscode.

image
image

2. Verified the changes on Node_Env = development

Error is sent to Sentry, Error is shown as expected.

image
image

3. Filtering using the transaction id is working as expected as well
image


Great work!

**Review by nathcarnevalli — APPROVED** [review]
Worked as expected :)

Screenshot 2024-05-14 120223
Screenshot 2024-05-14 120236

**Review by Infinite-Turkey — APPROVED** [review]
image
Works as expected!

**Review by peter6866 — APPROVED** [review]
Changes work as expected. A tracking ID is available for searching the error.
image

**Comment by akshit0211** [comment]
It is working as expected with both local and development fields. Great work!

postman error

Sentry error

**Review by akshit0211 — APPROVED** [review]

**Review by DiyaWadhwani — APPROVED** [review]
Hi,
I have tested out everything as per your instructions.
Setting the NODE_ENV=local displays errors in both postman and my VSC terminal


Changing NODE_ENV=development gives me the error in Sentry and can be filtered using the tracking_id parameter.


Great work. Thankyou

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
