### PR TITLE
Updated way to handle duplicate names.

### PR DESCRIPTION
**Pull request by LeeSingChanYau**
This is a PR for Other Links → User Management → Create New User ([PR 476] needs finishing, a “duplicate name created” popup happens after it is created, which is good. Need the rest of the below still though)
Make “user with duplicate name” popup require a person to click to confirm that they want to create a person with a duplicate name
Make “user with duplicate name” so it is not case sensitive. Currently a user without any caps is not considered a duplicate of the name that includes capitalization of first names.
The above PR also seems to have broken the auto-refresh for adding a new person… I should see that new person as soon as they are added and now I don’t anymore
How to test:
- With a dev account go to Other Links → User Management → Create New User.
- Create a user with with a name that has been used before (first name + last name).
- Create it with an email that hasn’t been used before and also with one that has been used before.
- A new popup should appear asking to confirm if you want to create the user with a duplicate name.
- Check if it behaves the right way.
- Check if the newly created user shows up.

### CODE REVIEW

**Review by RJBornToWin — CHANGES_REQUESTED** [review]
I found this issue:
Front end:
Issue 1. Go to user management -> filter user (RJ T1) -> Create duplicate (RJ T1) -> Shows popup -> Select Confirm -> issue is though filtered user list updates with newly added user, the search field gets cleared. For this the search key shouldn't be updated.

Screen Shot 2023-01-18 at 9 11 27 PM
Issue 2.  Go to user management -> filter user (RJ T1) -> Create duplicate (RJ T1) -> Shows popup -> Select Cancel -> Entire form closes. Instead the user should be allowed to change the username.

Screen Shot 2023-01-18 at 9 11 53 PM

Backend:
Issue 1: The code change has been handled only for postUserProfile. This is for new user creation. What happens when a user name is updated ? Was this usecase clarified ? I am able to save duplicate username through profile name change. If this is out of scope for you, please confirm with Jae.

**Comment by LeeSingChanYau** [comment]
Yeah, I think Issue 3 should be adressed but other functions in the backend other that postUserProfile are not related to this PR. Issue 2 I see that but I will confirm with Jae if that is what we want.

**Review by RafaelCastilhoCastro — COMMENTED** [review]
Hi @LeeSingChanYau,
I tested the PR together with frontend PR #657 and all works as intended.

1. When creating a new user using an existing email, the same red alert pops and the modal stays open awaiting to be corrected.
2. When creating a new user with the same name but different email, a confirmation modal pops up.

**Review by PrabhjotSembhi — CHANGES_REQUESTED** [review]
I suggest we should also check the Phone number. currently, we accepting the same number for different accounts. 

Please check if phone number already exists

**Comment by one-community** [comment]
Good catch Prabhjot! We're allowing the same phone number because fake data is sometimes used for all the testing, and the odds of the same number actually being entered by accident for two people is so low. Some orgs may not care about the number too, and will add ALL fake info... so we don't want that to create problems for orgs like us that use real info.

**Comment by AnishPandita** [comment]
Hey @LeeSingChanYau , Tested your PR with the necessary backend branch and everything seems to work fine. Overall code looks neat too.

https://user-images.githubusercontent.com/111321945/215164277-089b5d6a-3f5d-444d-8f06-e4f59555d911.mov

**Comment by one-community** [comment]
Alan, have all 3 of RJs requests been integrated here? I'll merge this if they have.

**Comment by LeeSingChanYau** [comment]
@one-community Yes, I think so.

**Comment by one-community** [comment]
Ok, thank you. I've requested she look at it again so I can merge it.

**Comment by one-community** [comment]
She said still bugs in the associated frontend... please fix those so we can merge them together.

**Comment by RJBornToWin** [comment]
Hello @one-community and @LeeSingChanYau , I see there are open comments in the front end PR : https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/657. 
I shall re review this once Alan can address all the comments in both the PRs and tag me.

**Comment by Filipe-Oliv** [comment]
Hi @LeeSingChanYau 

The red notice appears when creating a new user with an existing email address.


A confirmation window appears when establishing a new user with the same name but a different email address.


Both users appear in the search results.


Checking the previous comments I noticed the same issue as @PrabhjotSembhi where it was possible to add the same phone numbers in different accounts. Let me know if this is outside the scope of your PR.

Otherwise, it's working as intended.

**Comment by one-community** [comment]
Duplicate phone number should be allowed.

**Review by Filipe-Oliv — APPROVED** [review]
@LeeSingChanYau after I saw some other people on the team running this PR I found it in one of your comments with Rafael and saw that for this PR there is a branch to BE. I tested it again and it is working as intended. My appoligies.

**Comment by PrabhjotSembhi** [comment]
@LeeSingChanYau what's the status on this? 
When I can review it.

**Comment by agujjar2206** [comment]
I have tested this PR and it works as expected. I created a new user with a name that has been used before and a new popup appeared asking to confirm if I want to create the user with a duplicate name. I also created a user with an email that hasn't been used before and one that has been used before. The pop-up behaved correctly.

**Review by agujjar2206 — APPROVED** [review]
Code changes look OK and follow the best standards.

**Comment by suigunfjc** [comment]
Hi @LeeSingChanYau, I tested this PR with #657 at the front end, and everything looks good to me. The popup shows properly when I input a duplicate name. Well done!
Screenshot 2023-02-18 152833

**Review by tingedudu8 — APPROVED** [review]
Hi @LeeSingChanYau, I tested your PR and all features works well. Thanks!
PR272

**Comment by kamtoeddy** [comment]
Hi @LeeSingChanYau,

Tested the feature and everything works as expected
Screenshot (504)
Screenshot (506)

**Review by kamtoeddy — APPROVED** [review]

**Comment by harlleybastos** [comment]
Hi @LeeSingChanYau, I just tested it here and it seems to be working, great job!

https://user-images.githubusercontent.com/37200778/221208252-2e44fe76-5386-4620-8b21-26117c27fa3b.mp4

**Review by rauleffting — APPROVED** [review]
Hi @LeeSingChanYau. Your PR was tested and everything is working quite well, as you can see below:

https://user-images.githubusercontent.com/29555732/221361951-8a8d482c-20e3-4b70-b441-8585ebe031e2.mp4

Approved! Thank you very much!

**Comment by dkamghem** [comment]
> 

It seems to work as intended. Once an email has been used already it does not let you create the new user. If you have duplicate username but different password, it does create the user but just give you a pop message saying it is a duplicate one.
Screen Shot 2023-02-27 at 4 46 29 PM (2)
Screen Shot 2023-02-27 at 5 44 36 PM (2)
Screen Shot 2023-02-27 at 5 47 10 PM (2)

**Comment by dkamghem** [comment]
I might have done it accidentally. Please check to see if it is open now.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by one-community** [comment]
It is still closed. Please google hot to fix this problem.

**Comment by dkamghem** [comment]
What about now?
It is listed on my side as open please let me know if it is the case for you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by one-community** [comment]
Here's what I see: 
image

**Comment by one-community** [comment]
And 
image

**Comment by dkamghem** [comment]
What about now? It should be good.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by one-community** [comment]
Same. If you see something different then the two images I dropped, drop images of the same areas showing what you see.

**Comment by dkamghem** [comment]
[X]
[X]
[X]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dkamghem** [comment]
I’m not sure why on your side it is saying that. It seems we are not talking about the same PR. Let me check that one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
