### PR TITLE
Hoang fix viewing other dashboard

### PR DESCRIPTION
**Pull request by kylepham**
# Description
Screenshot 2024-05-16 at 4 02 56 PM

## Related PRS (if any):
This backend PR is related to the https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2257 frontend PR.
…

## Main changes explained:
- Update websocket contract to receive and parse JSON message
- Refactor `handleMessage` function

## How to test:
1. check into current branch
2. do `npm install` and `npm run dev` to run this PR locally
3. verify that every checkpoint in the frontend PR works as expected

## Screenshots or videos of changes:
None.

## Note:
None.

### CODE REVIEW

**Review by jinxyou — APPROVED** [review]
I left a review at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2257#pullrequestreview-2121042297

**Review by suaniii — APPROVED** [review]
I have tested the changes, and they work as expected. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2257#pullrequestreview-2124323597

**Review by shradac — APPROVED** [review]
Left a comment on frontend PR. Good job!

**Review by DiyaWadhwani — APPROVED** [review]
Hi Hoang,
Tested out your changes and left a comment on your related frontend PR. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2257#pullrequestreview-2145028544
Great job. Thank you

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected. left a PR review on [front-end](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2257#pullrequestreview-2170475949).

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by one-community** [comment]
Whoops, can't merge...need conflicts fixed on frontend

**Pull request merged**
