### PR TITLE
Sherly correct stars redo

### PR DESCRIPTION
**Pull request by freecode23**
# Description
1. Make it so changing a person’s required hours doesn’t create incorrect stars for past weeks
Screenshot 2023-08-01 at 8 58 45 PM

2. Add history icon to the user's profile page and a modal that shows the history if there is one.  
image

# How to Test
## 0. Prerequisites:  
npm version 6.14.^

#### Back end
1. Checkout to current branch for back end
2. Run `npm i`
4. Run `npm run build`
5. Run `node src/utilities/addNewField.js`
This will make sure that all users will have their schema updated
6. Run` npm start`

#### Front end
1. Checkout to this branch for front end (PR #1080) : [sherly-correct-stars-past-weeks-front](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1080)
2. Run `npm i`
3. Run `npm run start:local`
4. Log in as Owner
5. Make the user you want to test have already committed hours in the past week that is 20% more than the required hours: 
	Example:
	0Sherly Volunteer: has committed 60.07/40 on week before last. 

### Test 1: Check if history of promised hours icon is working
1. Go to dashboard —> click on your user to test—> Volunteering Times Tab
2. Find weeklyCommittedHours —> click on the history icon
3. If the user has never made any changes to weekly committed hours, it will just say so 
Example: 0Sherly Volunteer
6. Change the committed time of this user. Say reduce by 20 hours
7. Click history icon again. It should show a new one 
8. If you update again, it should not change. Because changing committed hours within a day should not affect anyhing
We don’t want to keep all these unnecessary data in database
9. Keep note of the history of this user:
40 hours 
20 hours

**Video description for test 1: (Turn sound on)**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/087c5a6b-3957-4159-981c-017947317a72

### Test 2: Check that stars are awarded correctly in weekly summaries report
1. Go to Dashboard —> Go to report —> weekly summaries report
2. Check that your user past history committed hours, mine was 40 has not changed and stars has not changed
3. Check that if you add a new tangible hour to this user,  the star still works correctly

**Video description for test 2: (Turn sound on)**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/e0156b80-c2a6-4b94-9ff0-6abf2a9076fd

### Test 3: Check that in weekly summaries report the commitment dates are assigned correctly
1. Have a user with 2 or more promised hours in the past.
This is ideally tested using unit testing for more rigorous testing. But please help test with whatever scenario you guys have in mind. 
2. Go to dashboard —> click on your user to test—> Volunteering Times Tab:
3. Click on the history icon and take note of the dates:
My example:
Promised hours 5- starting date August 1
Promised hours 7 - starting date July 27th
Promised hours 12 - starting date June 4th

4. Below is an illustration of the timeline to check:
Screenshot 2023-08-01 at 9 00 19 PM

5. Make sure the weekly committed hours follows the history correctly both on webpage and pdf (See video for details).

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/bb2c70ce-05fa-486a-9302-18b6b8f6b6e5

### CODE REVIEW

**Comment by one-community** [comment]
Shouldn't there be a frontend PR with this, not just a link to your branch?

**Comment by one-community** [comment]
I see it now, please link this in the description: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1080 And this one in the description there too, please.

**Review by winghojackyli — APPROVED** [review]
Hi @freecode23 , I've tested this PR along with https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1080. 
They work great together and I left comment there.

**Comment by beblicarl** [comment]
Tested the frontend and everything works as intended. Good work!

**Review by beblicarl — APPROVED** [review]

**Review by DavidC0126 — APPROVED** [review]
Hi @freecode23 , I've tested this PR with [PR1#1080](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1080). They both work as intended. I leave the comment on FE PR.

**Review by veronicacheng2 — APPROVED** [review]
Hi @freecode23 , I have tested this PR together with https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1080. 
Everything works perfectly and I leave the comments on FE PR.

**Review by Abiddy — APPROVED** [review]
Tested along with the frontend PR for this work. Works great!

**Comment by n0vay** [comment]
Getting this error while trying to setup backend.
image

**Review by ThapeloMasasa — APPROVED** [review]
The code in the backend is well written and I left more details about reviewing the functionality in the front end PR

**Review by eduardocodes — APPROVED** [review]
Hi @freecode23 

I tested this PR along frontend PR and everything worked as intended. Great job!

**Comment by one-community** [comment]
Sorry, I missed this backend and merged the frontend. The app is broken in some pretty important ways, so please resolve the merge conflicts on this ASAP so I can merge it too.

**Pull request merged**
