### PR TITLE
Jiyuan added scheduled-on date to scheduled blue square reason

### PR DESCRIPTION
**Pull request by Jiyuanxia**
# Description
Screenshot 2023-11-29 153713
Screenshot 2023-11-29 153739

## Related PRS (if any):
This frontend PR is related to the [#1641](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1641) frontend PR.

## Main changes explained:
- Update file UserProfile.js for adding the `createdDate`

## How to test:
1. check into current branch
2. `npm install`
3. `npm run build`
4. `npm start`
5. follow the instruction of the frontend PR

### CODE REVIEW

**Review by this-journey — APPROVED** [review]
Everything works great, see my review on PR 1641.

**Comment by DragonSlayer2401** [comment]
I tested this PR with the related frontend PR please go there to see my full review.

**Comment by yuhuimin1996** [comment]
I've tested this BE pr along with the FE pr #1641. Please see my comments there, thanks.

**Review by pshereen — APPROVED** [review]
I tested the PR as a admin user.

It works as per the requirement. 

Created date appears before the blue square description.


https://github.com/OneCommunityGlobal/HGNRest/assets/7041610/6802c5d7-43d5-4c67-9a4b-0f39fc77cfe1

**Review by Renanluizssx — APPROVED** [review]
it is working very well, you can see my review on PR #1641: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1641

**Review by X1aoZhang99 — COMMENTED** [review]
Hi, check my approval on PR [1641](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1641). Congrats!

**Review by X1aoZhang99 — APPROVED** [review]

**Review by Sophie-lei — APPROVED** [review]
I've tested this BE PR along with the FE PR#1641. Please see my comments there, thanks.

**Comment by Vishala09** [comment]
I have left my comment in the corresponding FE PR. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1641#pullrequestreview-1830875438

**Review by Sophie-lei — APPROVED** [review]
everything looks good , see my review in #1641 FE

**Review by peterson337 — CHANGES_REQUESTED** [review]
I have tested pull request #1641, and unfortunately, it is not functioning as expected. Please refer to my change request comment on the corresponding pull request for further details:[https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1641](640)

**Review by peterson337 — APPROVED** [review]

**Review by peterson337 — APPROVED** [review]
I tested this PR along with the corresponding frontend PR, and it worked. Please review the test results on the frontend PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1641

**Review by KevHnh — APPROVED** [review]
Everything works as expected. I tested this backend with its respective frontend.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1641

**Comment by xmyoot** [comment]
Tested the backend, and it complied successfully, however I ran into some issues on the front end please reference: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1641#issuecomment-1913459307

**Review by Pandani07 — APPROVED** [review]
This PR works as intended, great functionality. I have added a video of the testing on the related frontend's PR, #1641

**Pull request merged**
