### PR TITLE
Parthj unit test time off request controller

### PR DESCRIPTION
**Pull request by Parth-tech**
## Description
This PR contains unit tests for `timeOffRequest Controller`

## Related PRS (if any):
None. 

## Main changes explained:
- Adds unit test code for `timeOffRequest Controller`
- Adds requirement files (with `.md` extension) highlighting the different test cases

## How to test:
1. check into current branch by `git checkout parthj_unit_test_timeOffRequestController`
2. do `npm install` 
3. execute test by `npm run test timeOffRequestController`

## Screenshots or videos of changes:

The result should look as follows:

Screenshot 2024-06-28 at 5 15 18 PM

### CODE REVIEW

**Review by sahithidhulipala9 — COMMENTED** [review]
Hey Parth,
I am getting no test cases found error.
Screenshot 2024-06-28 225450

**Comment by Parth-tech** [comment]
> Hey Parth, I am getting no test cases found error. Screenshot 2024-06-28 225450

Hey Sahithi,
Did you checkout in the branch and execute the test command?

**Review by jinxyou — APPROVED** [review]
All tets cases have passed. Great work! 
Screenshot 2024-06-29 182427

**Review by pavanswaroopl — APPROVED** [review]
Hello,

Excellent work, tests the functionality well and the 
Screenshot 2024-06-29 at 9 19 49 PM
test case successfully passed.

**Review by HowieMiao — APPROVED** [review]
All tests passed
image

**Review by Logeshwari-Renu — APPROVED** [review]
All the test cases have been passed.

**Review by Rishitha1309 — APPROVED** [review]
All test cases passed successfully.
PR1007

**Review by Trip2310 — APPROVED** [review]
Tested this PR, all tests passed
PR_1007

**Review by vishavk1992 — APPROVED** [review]
All test cases passed successfully. 

PR-1007
Great Work!!

**Review by MinSun0814 — APPROVED** [review]
image

**Review by nikhilpittala16 — APPROVED** [review]
All test cases have passed. Great work!
Screenshot (28)

**Review by linkhanthtel — APPROVED** [review]
All test cases passed as expected!

Screenshot 2024-07-06 at 11 40 32 PM

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and it works as expected.
Screenshot 2024-07-06 154405

**Review by Shadhrush5 — APPROVED** [review]
Hi, I tested the PR 1007 with the following steps.
Checked out the branch parthj_unit_test_timeOffRequestController
Ran npm install
Ran  npm run test timeOffRequestController

Screenshot 2024-07-10 at 10 38 11 AM

The test cases seem to be working fine. Great work.

**Review by sahithidhulipala9 — APPROVED** [review]
All test cases passed!
PR 1007

**Review by nyelmela — APPROVED** [review]
I have tested this PR and all test cases have passed.

image

**Review by gowthamdongari — APPROVED** [review]
All test cases works as expected!
image

**Review by vijay10pk — APPROVED** [review]
All the test cases passed.

Screenshot 2024-07-11 at 8 30 54 PM

**Comment by ZhangPeizhou** [comment]
All tests passed. Nice work!

**Review by DiyaWadhwani — APPROVED** [review]
Hi Parth,
All tests have passed. I have attached a screenshot below. Great work.
Thank you

Screenshot 2024-07-14 at 8 07 51 AM

**Review by ishan-miglani — APPROVED** [review]
I have tested these changes and all the test cases pass. Great work!
Screenshot 2024-07-18 at 8 34 48 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
