### PR TITLE
Yihan send review email

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
截屏2023-07-25 19 15 37

## Related PRS (if any):
To test this backend PR you need to checkout the [#1045](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1045) frontend PR.
This PR is based on [PR#443](https://github.com/OneCommunityGlobal/HGNRest/pull/443). I recommand to test #443 before review this one.

## Main changes explained:
- Update file taskController.js and taskRouter.js for adding send email function.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. follow the steps in the test instruction of [PR#1045](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1045).

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
The PR works great and I left comment on FE PR#1045.

**Review by xaanders — APPROVED** [review]
I have tested FrontEnd PR. Works good!

**Review by 20chen-7 — APPROVED** [review]
The code looks good

**Comment by zuhang2000** [comment]
I have tested front end PR 1045. Left my comment there, thank you!

**Review by yunshan111 — APPROVED** [review]
Looks good to me, I tested the frontend.

**Pull request closed without merging**
