### PR TITLE
Jerry - user management permissions

### PR DESCRIPTION
**Pull request by jerryren527**
# Description
The main motivation of this PR is to run this branch with FE PR #[1312](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1312). This PR addresses 403 errors that arise when interacting with the app as shown in FE PR #1312.

## Related PRS (if any):
Frontend: #[1312](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1312)

## Main changes explained:
- Requests to `api/userprofiles/` endpoints will check for the `seeUserManagementTab` and `seeUserManagement` front permissions. 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally

### CODE REVIEW

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I have left my comments at frontend PR#1312

**Review by wantingxu7 — APPROVED** [review]
The pr works as intended with FE 1312, comment there. Good work!

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I tested it and viedoe is at FE.

**Review by navneeeth — APPROVED** [review]
Hello! Tested the PR and it works as intended. Good implementation! Commented a full review on the frontend PR.

**Review by Bhagyashree444 — APPROVED** [review]
Works as expected. I have left my comments on frontend PR#1312

**Review by malikjahanzaib — APPROVED** [review]
Hi @jerryren527, I have tested this PR and everything seems to work as described in the PR description. Left detailed review on the FE. Great Work!

**Review by StrawberryCalpico — APPROVED** [review]
Hi I tested your PR, details on [FE#1312](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1312#pullrequestreview-1677648642)

**Review by shubhankarval — CHANGES_REQUESTED** [review]
Hey @jerryren527, left a comment on [#1312](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1312)

**Comment by palakgosalia** [comment]
Hey, I left detailed review in PR 1312

**Review by shubhankarval — APPROVED** [review]
Hey @jerryren527, left a comment on FE PR [#1312](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1312).

**Review by Alforoan — COMMENTED** [review]
I left my comment on fe #1312

**Review by skaush21 — COMMENTED** [review]
not sure if its a backend issue, but when line 17 of PermissionsManagement.jsx is set to true in frontend. the submit button does not work. left a comment on frontend PR #1312
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1312

**Comment by jerryren527** [comment]
Thank you all. I’m closing this PR as another developer has already addressed the changes it aimed to make. Please see refer to this [google sheet](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit?usp=sharing).

**Pull request closed without merging**
