### PR TITLE
Roberto-Fixes assign badge delay

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
When assigning badges to users specifically on the badgemagement, there was either a delayed response which would take minutes to update the user profile or it wouldn't update at all.
 
Screenshot 2023-09-30 at 8 55 35 PM

## Related PRS (if any):
To test this backend PR you need to checkout the #[1390](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1390) frontend PR.
…

## Main changes explained:
- Adds if statement to badgeController.js to check if cache has user's information, if it does then clear that cache so when you visit the user's profile the updates will show immediately.
…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build`, and `npm start` to run this PR locally
3. Follow FE instructions

## Note:
Please make sure to run `npm run build`, if not the code will not be compiled and changes will not be shown.

### CODE REVIEW

**Review by StrawberryCalpico — APPROVED** [review]
Hi, I test this pr and it works as intended. Great Work!


https://github.com/OneCommunityGlobal/HGNRest/assets/114443664/ed03a901-6d76-48f9-bc37-e21e2b1b5180

**Review by navneeeth — APPROVED** [review]
Hey @robertoooc! Tested your changes and they LGTM! Commented a full review on the frontend PR.

**Review by malikjahanzaib — APPROVED** [review]
Hi @robertoooc, I tested your changes, and all the fixes in this PR work as intended. Detailed review left on FE PR #1390. Great work!

**Review by tsunami776 — APPROVED** [review]
Test video and comment left in FE PR. Nice work! I worked on a similar issue related to delay update and I also found it was related to cache.

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I left my comment on FE.

**Review by Shubhu0 — APPROVED** [review]
Hi @robertoooc, I tested your changes, and all the fixes in this PR are working as intended. Detailed review on Frontend PR #1390.

**Review by JeffLi117 — APPROVED** [review]
Review left on FE PR #1390.

**Comment by RheaWu1212** [comment]
Hi, I left my comment on FE#1390.

**Review by Cloid — APPROVED** [review]
Hi there, I ledge a comment on [FE#1390](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1390)

**Review by ChirayuRai — COMMENTED** [review]
Hello, I left my comment on FE#1390.

**Review by shubhankarval — APPROVED** [review]
Backend looks good, left a change request on FE [#1390](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1390).

**Comment by Lin1404** [comment]
Hi, I test this pr and it works as intended. I left my comment on FE#1390.

**Review by Lin1404 — APPROVED** [review]

**Comment by palakgosalia** [comment]
Hey, I have left a detailed review on PR 1390. Thank you

**Review by KurtisIvey — APPROVED** [review]
Clean code once again. Cache is handled exactly as desired. No console errors detected during testing either.

Screenshot 2023-11-10 at 12 02 18 PM


Badges updated after 1 refresh as mentioned in the testing instructions. I refreshed from the user's profile page in order to see if the changes took place. Also logged out and under a different user with the new badge still persisting. Fantastic job!
Screenshot 2023-11-10 at 11 17 04 AM
Screenshot 2023-11-10 at 11 16 23 AM

**Pull request merged**
