### PR TITLE
resolve conflicts

### PR DESCRIPTION
**Pull request by EvianTan**
This PR is trying to resolve current merge conflict on [PR](https://github.com/OneCommunityGlobal/HGNRest/pull/204)

I followed the second answers from [here](https://stackoverflow.com/questions/59110548/github-resolve-conflicts-button-disabled).
1. git pull main/development
2. checkout into main
3. git rebase development
4. create a new branch getting changes from main, since main is protected cannot be directly pushed
5. push changes in this new branch and create a PR

If you feel I'm doing it the wrong way or you have the hint to resolve the above conflicts, feel free to tell me.

### CODE REVIEW

**Review by Programmingrelated1999 — APPROVED** [review]
I have try to rebase the development with the changes from this branch. Then I create a new branch and was able to create PR without any conflicts.

**Comment by Programmingrelated1999** [comment]
Hi Yiyun, 

For this PR we are only testing if there are any merge conflicts by trying to create a new branch and check if there are merging conflicts, right? 
I have tried rebasing the development with this branch and created a new branch. And I was able to try to create pr without any merge conflicts.

**Comment by EvianTan** [comment]
> Hi Yiyun, 
> 
> 
> 
> For this PR we are only testing if there are any merge conflicts by trying to create a new branch and check if there are merging conflicts, right? 
> 
> I have tried rebasing the development with this branch and created a new branch. And I was able to try to create pr without any merge conflicts. 

Great testing! Please also check the basic functionality like start/pause/stop and log time. Thank you so much!

**Comment by Programmingrelated1999** [comment]
I have check the timer functions, they work great!

**Pull request merged**
