### PR TITLE
Anirudh - Fetch end date field from dashboardhelper

### PR DESCRIPTION
**Pull request by Pandani07**
# Description
Add to Leaderboard a way to see how many days until a person’s last day. A scheduled last day can be set in 3 places:

1. User Management>Set Final Day
2. Profile>Basic>Set Final Day Information
3. Profile>Volunteer Times tab>End Date

## Related PRS (if any):
This backend PR is related to the frontend PR [#2220](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2220)
…

## Main changes explained:
After this Date has been set, you can see the count of the remaining days on the leaderboard, under the days left column.
I have also fixed `Unsafe arithmetic operation on optional chaining` errors in `dashboardhelper.js`

## How to test:

1. check into current branch
2. do npm install and npm run build && npm run start to run this PR locally
3. Follow the instructions on the frontend PR

### CODE REVIEW

**Review by Sandhya1236 — APPROVED** [review]
I have tested the changes successfully by checking out the current branch, running npm install, and npm run start:local to set up the PR locally. After clearing site data and cache, I logged in as an OWNER user and navigated to the dashboard to view the profile. I set a final day at the bottom of the profile page and observed a red countdown indicator on the leaderboard. If the indicator did not appear immediately, a page reload resolved the issue. Only Owners and Admins can set the final dates. All functionalities worked as expected, and the feature appears stable. The PR is ready for merging.

image

**Review by peter6866 — APPROVED** [review]
Changes work as expected. I left a detailed review for the frontend PR.

**Review by KaushikMreddy — APPROVED** [review]
Hi, 

I've left a review on the frontend PR and approved the changes.

**Comment by akshit0211** [comment]
I left a comment on the front-end PR. It is working as expected. [Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2220#pullrequestreview-2114371147)

**Review by akshit0211 — APPROVED** [review]

**Review by Kavil-Jain-514 — APPROVED** [review]
I have reviewed the PR and the red countdown indicator is displayed on the leaderboard.

image

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Pull request merged**
