### PR TITLE
Johny fix bug on create folder for tasks with subtasks

### PR DESCRIPTION
**Pull request by johny4437**
#Description
Fixe bug ( PRIORITY MEDIUM) - 1
Creating sub-tasks in a WBS doesn’t create a new folder and makes the tasks uneditable
Logged in as Admin → Other Links → Projects → AAA USE THIS PROJECT → Click WBS Icon → Choose “Jae's WBS - USE THIS” → Choose task not in folder → Edit → Add Task → Should create folder out of parent and including new task.
## Mainly changes explained:
1 - Was added a new field  called  `childrenQtd`  in the task Schema  `./src/models/task.js` , this field is responsible to count the number of childrens (subtasks)  of a task.
2 - Was created a new function in the ` ./src/controllers/taskController.js` called `updateChildrenQtd` responsible to update the `childrenQtd` when to delete a subtask of a given task.
3 - Then was added a route in the file `./src/routes/taskRouter.js`.

Captura de Tela (102)
Captura de Tela (103)
Captura de Tela (101)

## How to test:
check into current branch
do `npm run build` then
do `npm install` and `...` to run this PR locally

## Note:
The mean functionality is in the front-end please verify the PR related to the frontend and run both.
OBS: "When was creating  subtask for a task  the folder icon was showing up, but when delete all subtasks the folder icon did not goes away".

### CODE REVIEW

**Comment by rauleffting** [comment]
I did a branch (gh pr checkout 268) and the PR didn't build (npm run build):

Screen Shot 2023-01-04 at 11 45 44

I think the error is here:

Screen Shot 2023-01-04 at 11 48 38

Thank you!

**Comment by johny4437** [comment]
Hi @rauleffting , thank you for wait so long, I fixed the `userHelper.js` file, now I think you can run the app properly. Than you!

**Review by rauleffting — APPROVED** [review]
Thank you very much, Johny! It worked perfectly. I'm going to approve.

Screen Shot 2023-01-07 at 13 07 21

PS: I also tested the frontend, but @EvianTan is reviewing it so it's better that you solve it together.

**Comment by EvianTan** [comment]
Hi @johny4437 ,

I have very basic but also important questions here:
1. Does this PR relates to frontend PR 613? show I run them both to test the whole functionalities?
2. With or without this backend PR, is there any difference I can check from the user side?

**Comment by johny4437** [comment]
Hi @EvianTan, thank you for asking!
1 - Yes this PR is related to the frontend PR 631.
2 - Yes, now when you delete all subtasks from a mother task the folder icon goes away, this was a change that you requested in the frontend PR 631.

**Comment by Filipe-Oliv** [comment]
Hi @johny4437 .

Following up on this, wainting for the new FE.

**Pull request closed without merging**
