### PR TITLE
Lucas create blue square reason scheduler

### PR DESCRIPTION
**Pull request by Lucas-E**
# Description
Backend part of the reason scheduling feature

## Related PRS (if any):
This backend PR is related to frontend's [#1081](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1081) PR
…

## How to test:
Check the videos on the frontend PR

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Hi @Lucas-E , I've tested both frontend and backend PRs and they works great together. Test videos can be found here. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1081#pullrequestreview-1562144613

**Review by TheDescendant39 — COMMENTED** [review]
@Lucas-E When I opened your code changes in VSCode, it is suggesting me quite a few formatting changes because of the ESLint extension. Could you please look into these formatting changes? Most of them are related to "String should be in single quotes".
Screen Shot 2023-08-04 at 3 36 17 PM

**Review by Abiddy — APPROVED** [review]
Tested this in the frontend and it looks good to me!

**Review by ThapeloMasasa — APPROVED** [review]
The code is well written with comments and I left a more detailed review in the frontend...

**Review by scoopstroop92 — COMMENTED** [review]
Tested both the front end and back end PR . Great job.  Left a review in the front end PR

**Review by yunshan111 — APPROVED** [review]
Tested backend and frontend, LGTM!

**Review by navneeeth — APPROVED** [review]
LGTM! Tested both the parts of the PR and commented on the [ frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1081). Cool implementation!

**Review by veronicacheng2 — APPROVED** [review]
Hi @Lucas-E, I have tested the PR together with Frontend. The details are left on #1082.

**Comment by zuhang2000** [comment]
Good job! I have left my comment on PR 1082.

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Comment by AuroraLovesWhales** [comment]
Hi @Lucas-E. I have reviewed this PR along with the frontend. Everything is working as expected. Great job!

**Review by AuroraLovesWhales — APPROVED** [review]

**Pull request merged**
