### PR TITLE
Jiayu Sort projects by most recent edited inventories and members

### PR DESCRIPTION
**Pull request by peter6866**
# Description
image

This is only for sorting the **members** since inventory is not in use.

## Related PRS (if any):
To test this backend PR you need to checkout [frontend PR2443](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2443).

## Main changes explained:
- Update `projectController.js` to include `membersModifiedDatetime` field when fetching the projects, and set the `membersModifiedDatetime` field to the current time when assigning/removing members from project.
- Update `userProfileController` to include the logic to check which projects have changed when the user profile is updated, and update the `membersModifiedDatetime` field for the projects changed.
- Update `src/models/project.js` to update the project model to include `membersModifiedDatetime` field.
- Update `userProfileRouter.js` to include the project model in the userprofile controller
- Update `routes.js` to include project model in the userProfile router.

## How to test:
1. check into current branch
2. do `npm install` and `npm run build && npm run start` to run this PR locally
3. Please follow the test steps in the frontend PR to test. 

## Screenshots or videos of changes:
https://www.loom.com/share/f90a2754cee444f8ae711a0a0f09c749?sid=3a343985-0bc6-480a-9942-b18bda25ec1e

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected. left a review on [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2443#pullrequestreview-2184533599](front-end)

**Review by vishavk1992 — COMMENTED** [review]
I have tested this PR with frontend PR2443 and also left comment on frontend PR with video reference.

**Review by Chetan0606 — APPROVED** [review]
I have reviewed the PR and it's associated front end PR and added my review screenshots over there. Thanks!

**Review by SrikanthChowdary495 — COMMENTED** [review]
I have tested this PR with frontend PR. I have left comment on frontend PR.

**Review by kabraambika — APPROVED** [review]
I have reviewed this PR and it's associated front end PR and added my comments related to frontend over there.

**Comment by beblicarl** [comment]
I have reviewed this PR and it's associated frontend PR and added my comments related to the frontend over there.

**Review by beblicarl — APPROVED** [review]

**Review by ishan-miglani — APPROVED** [review]
I have reviewed the PR and it's associated front end PR and added my review screenshots over there. Thanks!

**Review by jinxyou — APPROVED** [review]
I left a review at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2443#pullrequestreview-2190183896

**Review by cvtqx — APPROVED** [review]
Reviewed this PR and it works as described. Left comments in FE.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
