### PR TITLE
Huijie fix add lost hours editing deleting

### PR DESCRIPTION
**Pull request by metaphor987**
# Description

## Related PRS (if any):
This backend PR is related to the frontend PR 2710.

## Main changes explained:
The error when adding, editing, or deleting lost hours is caused by a Mongoose validation error for users with an empty `jobTitle` field. Setting the `validateModifiedOnly` option to true when saving updates to the user profile can ensure that only modified fields are validated.

## How to test:
1. check into current branch
2. do `npm install`, `run run build` and `npm start` to run this PR locally
3. Clear site data/cache
4. log as admin or owner user (admin user do not have permission for adding lost hours)
5. go to Reports -> Reports -> Add Lost Time, or Show Person Lost Time, verify that the following errors do not occur:
6. owners do not get a 500 error when adding a person's lost time:
    error image before the PR
    
7. Do not get an error when updating a person's lost time
    error image before the PR
    
8. Do not get an error when deleting a person's lost time
    error image before the PR:
    
9. owners do not get an error when adding a lost time for team or project: 
    error image before the PR:
    
Thank you!

### CODE REVIEW

**Review by Ankuriboh — APPROVED** [review]
Easy fix that only validates modified fields. Can confirm that new data is stored in database.

**Review by javid679 — APPROVED** [review]
Logged in as DevAdmin, can confirm data is stored in the database, below is the video for reference: 


https://github.com/user-attachments/assets/2043b7a9-17f6-483e-9da4-a71649f242b2

**Comment by sheetalmangate** [comment]
As per user story code changes look good.

**Review by hqzhu0913 — APPROVED** [review]
Both people and team edit time work as expected.
Screenshot 2024-10-22 at 11 58 07 AM
Screenshot 2024-10-22 at 11 58 48 AM
Screenshot 2024-10-22 at 11 52 05 AM
Screenshot 2024-10-22 at 11 52 30 AM

**Review by samarth9201 — APPROVED** [review]
Verified the changes. Works as expected. Tried Adding updating and deleting functionality. 

@hqzhu0913 I faced similar problem, clearing the site cache worked for me.

Screenshot (116)
Screenshot (117)
Screenshot (118)

**Review by hqzhu0913 — APPROVED** [review]
Hi,
I figure out why I can't see the Add time lost button. And everything works as explained.
Screenshot 2024-10-28 at 10 34 40 PM
Screenshot 2024-10-28 at 10 34 57 PM
Screenshot 2024-10-28 at 10 35 20 PM

**Comment by nathanah** [comment]
If some users don't have `jobTitle`s, would it make more sense to modify the mongoose schema to include that? Or should those users be updated?

**Comment by one-community** [comment]
Thank you all, merging!  Requested Nathan's comment be raised as a new bug

**Pull request merged**
