### PR TITLE
Peterson_Fix_the_500_error_in_editing_last_week

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This PR has been created to fix the bug: ReferenceError: value is not defined.

## Related PRS (if any):
This  backend  PR is associated with the following frontend PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023

## Main changes explained:
The userProfileRouter file has been modified to fix the bug: ReferenceError: value is not defined.

## How to test:
1. check into current branch.
2. do `npm install`, `npm run build`  and `npm start` to run this PR locally.
3. Please adhere to the instructions outlined in the frontend PR.

## Screenshots or videos of changes:
a

## Note:
None

### CODE REVIEW

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed the frontend PR related to this. Both are working correctly.

**Review by hetvi11110 — APPROVED** [review]
I tested both frontend and backend PR. Both are working as mentioned. For reference, please check the comment on frontend PR.

**Review by Abi-Liu — APPROVED** [review]
Changes work as expected! Please refer to my review on the frontend PR for a more detailed summary: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023

Note: The error seems to have occured due to the error in the frontend rather than the backend. changing `value` to `req` doesn't change anything as its just an arbitrary variable name.

**Comment by SanketKaware** [comment]
The changes look good. Here is my frontend review of your PR -

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#issuecomment-1998710197

**Review by SanketKaware — APPROVED** [review]

**Review by SRamen1999 — COMMENTED** [review]
I reviewed the frontend PR related to this. Both are working correctly.

**Comment by rajnada** [comment]
Hi,

I have reviewed both frontend and backend PR and both working fine!
[https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#issuecomment-2001170506](url)

**Review by iven-yao — APPROVED** [review]
tested this pr with [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023), and both works correctly.

**Review by ImzIssa — APPROVED** [review]
Hey, I've tested this PR with the frontend and everything is working fine. Nice work!

My frontend PR review for reference:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#pullrequestreview-1941474737

**Comment by 20chen-7** [comment]
Left review at the frontend.

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and it works properly. I left a comment on the frontend.

**Comment by anandsesha** [comment]
Hi, I have followed the instructions outlined in the frontend PR and tested the functionality and it is working fine. The errors listed are not observed.
Link to my review: [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#issuecomment-2016652038](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#issuecomment-2016652038)

**Review by Sarthak32 — COMMENTED** [review]
I tested your PR . Please check my review on frontend https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#pullrequestreview-1956485868

**Review by sameersdeshpande — COMMENTED** [review]
Please refer to my review on the frontend PR for a more detailed summary: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023

**Review by kylepham — APPROVED** [review]
I left a review on frontend [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#pullrequestreview-1964624316). Good work.

**Comment by rajnada** [comment]
Hii,

Here is my frontend review. Functionality worked as mentioned. [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#issuecomment-2028118731](url)

**Comment by MQChen211** [comment]
Hi, I've tested this PR with the frontend and it works as expected. [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#issuecomment-2035366644](url)

**Review by aaryaneil — APPROVED** [review]
Tested your PR and everything works as expected. Left review on (frontend.)[https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2023#pullrequestreview-2013188946]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
