### PR TITLE
Diego enforcing eslint and prettier on staged files

### PR DESCRIPTION
**Pull request by DiegoSalas27**
image

# Description
Adds eslint and prettier to format the code style and enforce finding programming errors and fixing errors programatically on staged files before code is committed. While we cannot control how each developer sets up their development environment, we can enforce running prettier and eslint on staged files so only the files that are about to be committed will be inspected and formatted without having to manually perform any action. 

## Related PRS:
N/A

## Main changes explained:
- Functionality binds to git hooks with husky (pre-commit) to run eslint and prettier on staged files
- Lints staged files (not the entire codebase)
- Lints and applies code style formatting sequentially before code is committed
- Formats code style with prettier even when eslint doesn't find any linting errors or warnings.

## How to test:
1. find "Preferences: Open User Setting (JSON)" options by entering `cmd + shift + p` in vs code
Screen Shot 2024-03-20 at 11.07.34 AM
2. comment all of the properties and values if the JSON file (this will disable prettier from formatting code when a file is saved):
Screen Shot 2024-03-20 at 11.09.13 AM
3. check into current branch
4. do `npm install`
5. checkout into a new branch of your own to test this functionality (since we will create a new commit to test this). eg. `git checkout -b yourname/test_eslint_prettier`
6. if running on Mac or Linux run: npm run prepare (this will make husky files executable)
7. update any file: eg. `server.js`:
Screen Shot 2024-03-20 at 11.14.06 AM
8. try breaking any of the `.prettierrc` defined rules
9. save the changes, add them to the staging area (git add filename), commit the changes.
10. lint-staged and prettier should run and stop the execution if there are any programming errors that eslint cannot fixed (for instance a variable that is not initialized like in the previous image); otherwise, the files should be formatted with prettier (based on the `.prettierrc` file) and fixed with eslint if any rules broken were fixed by eslint.
11. try changing another file. eg. config.js
Screen Shot
12. add only one of the files to the staging area, commit the changes. If the commit succeeds, only the staged file will be linted and formatted. The rest of the files that are not in the staging area will remain untouched.

### Running
https://github.com/OneCommunityGlobal/HGNRest/assets/26840798/f364762d-cf56-41e2-b881-98eb2347b54c

## Note:
This change integrates eslint and prettier in a way that no conflicts will arise between them. Rules defined in .prettierrc will override eslint code style formatting rules (which is recommended). Eslint will only be used to catch programming errors that can lead to bugs in production.

### CODE REVIEW

**Review by 20chen-7 — APPROVED** [review]
Work as expected. This can check format and some syntax issues, preventing related issues.
Screenshot 2024-03-21 at 11 23 06 AM
Screenshot 2024-03-21 at 11 24 40 AM
Screenshot 2024-03-21 at 11 24 57 AM

**Comment by DiegoSalas27** [comment]
> Work as expected. This can check format and some syntax issues, preventing related issues.
> 
> Screenshot 2024-03-21 at 11 23 06 AM
> 
> Screenshot 2024-03-21 at 11 24 40 AM
> 
> Screenshot 2024-03-21 at 11 24 57 AM
> 
> 

Awesome. Thank you for helping me testing it.

**Review by Abi-Liu — APPROVED** [review]
Works as expected! On commit, the files automatically get reformatted and linted as the code is committed!

**Review by luisarevalo21 — APPROVED** [review]
Hello @DiegoSalas27 ,

I tested your PR and works as intended. 
Great work! 
Upon commenitng out my settings, then checking into a new branch. I then edited `server.js` I then attmpted to commit and was denied the commit because eslint couldn't fix it. 
I then removed it and added a space which passed and formatted the code. 
Great work!

Screenshot 2024-03-21 at 9 10 26 PM
Screenshot 2024-03-21 at 9 15 03 PM

**Review by Pandani07 — COMMENTED** [review]
Tested this PR and everything works as intended! I edited server.js and a space formatting issue was automatically fixed, but my commit was denied for the incorrect variable declaration. 
Screenshot 2024-03-22 at 8 35 36 PM
Screenshot 2024-03-22 at 8 34 56 PM
Screenshot 2024-03-22 at 8 34 45 PM

**Review by SMitta11 — COMMENTED** [review]
I followed the given steps and everything worked as expected:
1. Commented all properties in JSON file
2. Checked to current branch and did npm install
3. checked to my new branch
4. added let name; in server.js file and put some extra spaces
5. committed these changes and it gave error as expected
6. Then changed another file config.js and added let some; and some space there and it also behaved in same way
7. Then uncommented the properties and in config.js and server.js, only gave spaces and removed unused variables, and then committed changes and it ran successfully changing the spaces using prettier.
Please find below screenshots:

**Pull request merged**
