### PR TITLE
Mohammad - Middle name search on the Project team members search bar(Backend)

### PR DESCRIPTION
**Pull request by mohabbasd**
Add middle name searching to the project member search bar:
Fixes # (bug list priority medium)
Modify getUserBySingleName and getUserByFullName in userProfileController.js located in HGNRest. To allow for middle name querying.
Modify findUserProfiles in projectMembers.js in HighestGoodNetworkApp to extract and send the middle name to the backend.
Note: Users are stored with a firstName field and lastName field. The middle name should be concatenated to the end of the first name. The below table shows an example of how a user with a middle name is stored.

## Related PRS (if any):
To test this backend PR you need to checkout the #[2022](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2022) frontend PR.

## How to test:
check into current branch and check into frontend branch separately
do npm run build and npm start to run this PR locally

### CODE REVIEW

**Review by meetpadhiar4 — COMMENTED** [review]
Hi reviewed the front end PR related to this. Have suggested few changes in that PR.

**Comment by SanketKaware** [comment]
I have reviewed both frontend and backend PR. Change looks good.

Here is my frontend PR review - 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2022#pullrequestreview-1955657155

**Review by Sarthak32 — APPROVED** [review]
Hi, this works good ! I have also wrote review on frontend PR :https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2022#pullrequestreview-1966835814

**Review by ImzIssa — APPROVED** [review]
Hello, I've reviewed this PR and everything looks okay.

Here is my Review of the frontend PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2022#pullrequestreview-1955612071

**Review by iven-yao — APPROVED** [review]
I just reviewed this pull request with its [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2022#pullrequestreview-1967870909), it works as expected.

**Review by SRamen1999 — APPROVED** [review]
I just reviewed this pull request with its frontend https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2022, it works as expected.

**Review by Tiantian-C — APPROVED** [review]
I have reviewed the PR. It works well!
Screenshot 2024-04-03 at 10 54 05 PM

**Review by aaryaneil — APPROVED** [review]
Changes work as expected, left a review on the [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2022#pullrequestreview-1984703183)

**Review by p-suram — APPROVED** [review]
Changes looks good. I have tested using Admin account. Please find Frontend review [here](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2022#pullrequestreview-1984845121)

**Pull request merged**
