### PR TITLE
Sav refactor userHelper.js

### PR DESCRIPTION
**Pull request by Lunaliar**
# Description
This is a basic refactoring of the userHelper file. This file contains the weekly badge functions and a few other things. I've updated some unused variables, undefined values, and a bunch of hard-to-read loops. To test this PR you can run a test user through the badge functions at the bottom of the file.

## Related PRS (if any):
This is related to all badge bugs but doesn't address any directly.
…

## How to test:
1. check into the current branch.
2. do `npm install` and `...` to run this PR locally.
3. Inside userHelper.js on line 1379 add a filter to select your test user (recommend using firstName).
4. shift awardNewBadges function call on line 16 of the userProfileJobs down to line 17 outside of the Sunday conditional.
5. Change the cronjob syntax to a good frequency for testing on line 8 of userProfileJobs (recommend using '*/2 * * * * ').
6. Add a few console logs to check that the awardNewBadges is running properly.
7. run 'npm run build' and then 'npm start'.
8. observe results and keep an eye out for errors generated.

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Hello @Lunaliar , I've tested your PR and it works great. 

First, I set the cron job to be done every 2 minutes. Console logs are added at every run of the cron job. I also log the test user profile at every run to check the status of. (e.g. changes in badge)

I can add badge from the frontend and get the status update from console log. 
Besides, I can add tangible hour to over 40 hours a week to make the cron job help me to add a new badge. 

### Adding badge (badge number: 0)


### Next cron job run after adding batch (badge number: 1)


I can also delete badge from frontend and the the cron job can catch that update.

**Review by veronicacheng2 — APPROVED** [review]
Hi @Lunaliar, I follow the suggested frequency '*/2 * * * * ' and added a console log for printing badgeCollection to ensure that awardNewBadges was running. Below is the screen capture of the backend after I assigned new badges on the frontend:

image

**Review by ThapeloMasasa — APPROVED** [review]
The awardBadge function runs as expected

Screenshot 2023-08-11 at 8 32 49 PM

**Comment by AuroraLovesWhales** [comment]
Hi @Lunaliar. I have tested this PR and the functionality works as intended for the awardNewBadges function. Great job!

I manually added the 90 Hours in a Week badge to my user at the frontend and was able to see the badge being logged at the backend. 
image

**Review by AuroraLovesWhales — APPROVED** [review]

**Comment by one-community** [comment]
Great job everyone, will merge this as soon as the merge conflicts are resolved!

**Pull request merged**
