### PR TITLE
Aishwarya_Purchase-Tool-Request-Form-Backend

### PR DESCRIPTION
**Pull request by Aishwaryak01**
Aish_Purchase-Tool-Request-Form-(Backend)

Description
This pull request adds the backend logic for the Purchase Request: Tool form in the BM Dashboard (Phase 2).

Related PRS (if any):
This PR must be checked out to test #1752 frontend PR

Main changes explained:
Add BM Dashboard collections to the dev database: buildingTool
Add Mongoose schema file buildingTool
Add POST route to either create a new document in buildingTool collection (if the tool is being ordered to the project for the first time), or update purchase record sub-document in an existing document (if the material has been ordered previously for the project). In either case, the purchaseRecord sub-document will have default values added to date, requestedBy, and status fields, in addition to the submitted form data.

How to test:
git checkout Aish_Purchase-Tool-Request-Form-(Backend)
npm install
npm run dev
check the related frontend PR for further instructions

Optional: connect to the dev db via Mongo Compass, open the buildingTool collection, and observe that documents and sub-documents are being updated correctly.

Notes
Please remember to either Approve or Request Changes. Do not just leave a comment.
Please leave a review for both the front and backend branches after you have finished testing!

### CODE REVIEW

**Review by Alforoan — APPROVED** [review]
I left a comment on the fe #1752.

**Review by abdel-lall — APPROVED** [review]
LGTM.

**Review by tdkent — DISMISSED** [review]
Please fix the merge conflicts. Also, Olga added new Tool router and controller files in her Tool Details branch. Can you merge your code into those files?

**Review by tdkent — APPROVED** [review]

**Review by Renanluizssx — APPROVED** [review]
Hi @Aishwaryak01, see my review please:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1752

**Review by KevHnh — APPROVED** [review]
I tested this backend with the corresponding frontend pr and everything works as expected. I was able to submit a tool purchase request successfully. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1752#pullrequestreview-1860625921

**Comment by xmyoot** [comment]
See comment on front end pr: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1752#issuecomment-1925508767

**Review by Pandani07 — APPROVED** [review]
The functionality in this PR work as intended. I have left a review on the frontend PR

**Review by ilyaflaks — APPROVED** [review]
More detailed review on PR1752. I reviewed this code and found that it works perfectly. Good work!

**Review by SaiDeepak-NEU — APPROVED** [review]
Hello Aishwarya,

Tested the purchase request :tools form submission and the submission worked pretty smooth. Status code 201 was being displayed in the network tab on successful submission as expected. 
Screenshot (72)
Please review the frontend PR for additional pictures and comments.

**Review by mohabbasd — APPROVED** [review]
Hello, tested this PR using the front end branch 1752 and this PR works as expected.

**Review by SRamen1999 — APPROVED** [review]
I tested this backend with the corresponding frontend pr and everything works as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1752#pullrequestreview-1860625921

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by 20chen-7** [comment]
left review in the frontend

**Pull request merged**
