### PR TITLE
Shengwei Enhancement: badge assignment and modification will not remove earned date

### PR DESCRIPTION
**Pull request by ptrpengdev**
# Description
image

## Related PRS (if any):
This frontend PR is related to the #1830 fronted PR.
To test this backend PR you need to checkout the frontend branch #[1830](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1830) frontend PR.
…

## Main changes explained:
- Update code in manual/user badge assignment and automatic weekly badge assignment to accommodate new changes - keep earned date when badge count decreases.
- Update badge collection data model

## How to test:
1. check into the current branch and frontend branch #[1830](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1830)
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ task→…
6. verify function “A” (feel free to include screenshot here)

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Pandani07 — APPROVED** [review]
Reviewed this PR and the frontend PR, works as intended!

**Review by TareqMia — APPROVED** [review]
Hello, I reviewed the related front-end PR. Everything worked as expected 👍

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and it works as instructed.

**Review by peterson337 — APPROVED** [review]
Hi ptrpengdev, The frontend pull request worked as expected. Good job! Please see my comment on the frontend pull request for more details: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1830

**Review by XiaohanMeng — APPROVED** [review]
Hello, I reviewed the corresponding front-end PR, and everything functioned as expected 👍. The video is included in the front-end review for further details.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1830

**Comment by Jingyii800** [comment]
Hi, I have reviewed this full-stack feature. Please find more details in this comment. [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1830#pullrequestreview-1881770143]

**Review by brandta-1 — APPROVED** [review]
# Review
Verified with frontend PR #1830

# Videos
See [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1830#pullrequestreview-1887043928)

**Review by 666saofeng — APPROVED** [review]
It worked as intended on my side. Please refer to the video for details


https://github.com/OneCommunityGlobal/HGNRest/assets/62363348/91025117-6653-4370-a955-43b2f474da12

**Pull request merged**
