### PR TITLE
Jerry - streak fix auto dropoff

### PR DESCRIPTION
**Pull request by jerryren527**
# Description
This PR aims to solve this bug:
Screenshot 2023-12-22 at 1 07 03 PM

## Related PRS (if any):
None.

## Main changes explained:
- Ensured that `changeBadgeCount()` does not get passed undefined value by changing `badgeCollection[i].badge.count - 1` to `badgeCollection[i].count - 1`
- When checking ‘X Hours for X Week Streak’ badges that are greater than 1 week long, ensured that the badges are checked in descending order by `week` and `totalHrs` values. This ensures that the auto dropoff logic works correctly. E.g., 30 Hours for 2 Weeks Streak badge is replaced by a 30 Hours for 3 Weeks Streak badge, when previously the 30 Hours for 2 Weeks Streak badge would not be removed and the user will keep that badge in addition to the newly awarded 30 Hours for 3 Weeks Streak badge.
- Added logic to correctly award the same type of streak badge to the user that they already possess. 
- Added logic to correctly avoid awarding streak badges to a user when “in between streak badges” and building upon an ongoing streak. E.g., a user that logs four consecutive weeks of 30 hours is awarded with the “30 Hours for 4 Weeks Streak” badge. The next streak badge to earn is “30 Hours for 6 Weeks Streak” badge. Therefore, when the user logs their fifth consecutive week of 30 hours, the logic detects that the user is building upon an ongoing streak and will not award the user with another “30 Hours for 4 Weeks Streak” badge. 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. For testing purposes, install jest by running this command `npm i jest`. You may uninstall jest after you finish testing.
4. Inside package.json, change a line under “scripts”. Change “test”: “test” to “test”: “jest”
5. Run the test file by running this command: `npm test userHelper.test.js`
6. These unit tests take a relatively long time to run (around 10-15 seconds on my computer for bigger tests). If any test fails due to timing out, ajust the second argument provided to the `test()` calls. E.g., 10000 equals 10 seconds until timeout. Increase that number accordingly.
7. `ctrl` + `c` to force stop the jest execution.
8. Note: you may uninstall jest after testing this PR if you want.

After understanding the bug, you may try to come up with alternative test cases that may not have been considered yet. You can create your own test case by copying the structure of any existing test case in userHelper.test.js. Please keep in mind the X Hours For X Weeks badges that exist in the database when thinking of alternative test cases. A spreadsheet containing every badge can be found [here](https://docs.google.com/spreadsheets/d/1zq7BY7k8EB6_4sO8Lo5M8A2bOhwNBPQmUFmtT66cauI/edit?usp=sharing). By coming up with new test cases, we can ensure that the code changes are correct and robust.

### How to run test file:

https://github.com/OneCommunityGlobal/HGNRest/assets/55968519/0806df82-6583-403d-a4d5-a48eda5dc517

## Screenshots or videos of changes:

How to use Visual Studio Code debugger to debug badge component:

https://youtu.be/GYR6GSAVC_k

### CODE REVIEW

**Review by 666saofeng — CHANGES_REQUESTED** [review]
All tests have passed. However, it seems that streak badges cannot automatically drop off on my side.
image
image
image

**Review by Renanluizssx — COMMENTED** [review]
Hi @jerryren527, i tested your unit tests, but it gaves me some error, i increased the timeout in tests but it didn't work yet:

https://github.com/OneCommunityGlobal/HGNRest/assets/91035340/93e04dde-8081-4e55-a7cd-a0bc269b1fa0

**Review by brandta-1 — APPROVED** [review]
# Review
All tests finished on my machine:

# Video

https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/ddcd7d8f-a75c-4fd3-8da7-e005f5274b9b

**Comment by jerryren527** [comment]
Thank you for your comment, @666saofeng. The reason why the streak badges are not automatically dropping off on your side is that the unit tests create a new document in the userProfile collection. The creation of this new document represents the creation of a new user. In these unit tests, the `lastWeekTangibleHrs` and `savedTangibleHrs` properties are modified. Then the `checkXHrsForXWeeks()` function is executed which modifies the `badgeCollection` property. The `badgeCollection`’s value is then compared against its expected value using jest’s assertion methods. After the tests are completed, the document is deleted. Therefore, the unit tests are not related to any existing users in the database, so you should not be able to see any of those changes on your end.

For a better understanding of how I manually tested the code changes, watch my video tutorial where I show how I tested my code changes by making manual changes to a user in the userProfile collection in MongoDB Compass and manually inspecting the value of badgeCollection. Watch from 5:56 (https://youtu.be/GYR6GSAVC_k?si=b6XnbEnH8so23v3M&t=358)

**Pull request closed without merging**
