### PR TITLE
Chengyan phase2 reusables list

### PR DESCRIPTION
**Pull request by ChengyanOo**
# Description
This backend update complements the frontend PR [Chengyan phase2 reusables list UI #1956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956/), introducing a REST endpoint for get and delete reusable items as part of the Phase Two development of the HGN app.

## Related PRS (if any):
[Chengyan phase2 reusables list UI #1956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956/)

## Main changes explained:
- Implemented a new controller functions in `bmReusableController.js` to facilitate the REST endpoint for get and delete reusables.

## How to test:
1. Switch to the current branch.
2. Execute `npm install`, `npm run build`, and `npm run start` to run this PR locally.
3. Test in conjunction with the frontend PR [Chengyan phase2 reusables list UI #1956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956/)
4. Review the code for potential code smells.

## Screenshots or videos of changes:
This week

Detailed walk through: 
https://www.loom.com/share/f2a55f5d317f4e979627765edf1fa9a6?sid=2c390651-9dad-4c52-b12d-2a4b12c9dc97

### CODE REVIEW

**Review by TareqMia — APPROVED** [review]
Hi @ChengyanOo, I have reviewed the code for this PR and everything looks good and is functioning 👍 I have also left some comments on the related front-end [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956#pullrequestreview-1887043710).

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed this PR and the frontend PR related to this and everything seems to be working properly.

**Review by ShengjieMao — APPROVED** [review]
Reviewed the pull, left review in frontend

**Review by XiaohanMeng — APPROVED** [review]
Hi, I've provided my feedback on the Frontend project. Everything on backednd is working well.

**Review by brandta-1 — APPROVED** [review]
# Review
Routes correctly pulled reusable ```buildingInventoryItems``` and also correctly pulled custom items made for testing.

# Video

See [front end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956#pullrequestreview-1899581182)

**Review by sucheta90 — APPROVED** [review]
Please refer to the [comment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956#pullrequestreview-1926064573)

**Pull request merged**
