### PR TITLE
XiaoW_Refactor time entry handlers and fix bugs

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
This PR mostly cooperate with frontend PR[#1818](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1818#issue-2078128477). 

## Related PRS (if any):
To test this backend PR you need to checkout the [#1818](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1818#issue-2078128477) frontend PR.
…

## Main changes explained:
- Modify getTimeEntriesForUsersList for time entries of TeamMemberTasks
- Refactor putUserProfile logic to make it check for existing fields when updating
- Refactor getLeaderboard logic
- Refactor taskHelper logic
- Fix timeentry modal bug
…

## How to test:
1. check into current branch and [#1818](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1818#issue-2078128477) frontend PR
2. do `npm install` and `npm run dev` to start this PR locally
3. check more instruction on the frontend

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Shiwani99 — APPROVED** [review]
Great work. Added comments to frontend PR.

**Review by robertoooc — APPROVED** [review]
Hey @wang9hu, along with the frontend I also took a close look at this backend. 

Overall everything works well with this backend, it's changes definitely helped with getting rid of that undefined.toString error originating from the taskHelper file. 

The only area of concern that I have a bit is the taskHelper function, I compared this pr and the dev site and the time from this pr took a bit longer to process in the getTasksForTeams function, specifically for admin/owner user's because they get that huge list. 

left was this branch, right was dev site:
Screenshot 2024-01-12 at 8 33 05 PM

However, this still beats the long pipeline of aggregation queries that we used to have so great job with everything.

**Review by sucheta90 — APPROVED** [review]
The functions work as intended. Left comment on the Frontend PR.

**Comment by mianmiantea2019** [comment]
The functions work as intended. Added comments to FE PR [1818] (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1818)

**Pull request merged**
