### PR TITLE
Iven add teams team code colors filters on dashboard backend

### PR DESCRIPTION
**Pull request by iven-yao**
## Related PRS (if any):
To test this backend PR you need to checkout the [#2224](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2224) frontend PR.

## Main changes explained:
- Update `taskHelper.js` to include teamNames, teamCode and WeeklySummaryOption in team members data for filter feature

## How to test:
1. check into current branch
2. do `npm install`
3. do `npm run build`
4. do `npm start`
5. following the instruction in frontend PR

### CODE REVIEW

**Review by aaryaneil — COMMENTED** [review]
Tested the PR and left a review on the [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2224#pullrequestreview-2039303783)

**Comment by MinSun0814** [comment]
Tested and left review at PR2224.

**Comment by beblicarl** [comment]
i left a review on the frontend for this functionality

**Review by beblicarl — APPROVED** [review]

**Review by nathcarnevalli — COMMENTED** [review]
Reviewed on the PR [#2224](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2224#pullrequestreview-2051057297)

**Review by MinSun0814 — APPROVED** [review]
Reviewed frontend and left a comment

**Review by gowthamdongari — APPROVED** [review]
Works as expected check frontend PR #[2224](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2224) for detailed review

**Comment by ZhangPeizhou** [comment]
Reviewed frontend and left a comment

**Review by peter6866 — APPROVED** [review]
Reviewed the frontend PR and it works great with backend.

**Review by Sandhya1236 — APPROVED** [review]
I checked out the current branch, ran npm install and npm run start:local to set up the PR locally, and cleared the site data/cache. I logged in as an admin/owner/mentor/manager user and navigated to the dashboard → Tasks. I verified that the three multi-select filters for Team Names, Team Codes, and Color (WeeklySummaryOptions) functioned correctly. Additionally, I confirmed that this new feature worked as expected in dark mode. All tests were successful, confirming the proper functionality of the filters and their compatibility with dark mode.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/9d342140-966b-4443-b843-8f04bd33101a

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
