### PR TITLE
Xiao fix x hours in one week badges

### PR DESCRIPTION
**Pull request by X1aoZhang99**
# Description
Screenshot 2024-03-19 at 14 46 15

## Related PRS (if any):
N/A

## Main changes explained:
- Split the existing XHoursForXWeeks function into two separate entities
- Create a function to allocate badges for X hours in 1 week.

## How to test:
1. Check into the current branch
2. Comment out the test code in the `userProfileJobs.js` under `HGNREST/src/cronjobs/` so that it can run every minute, not every Sunday night. 
Screenshot 2024-03-19 at 14 53 56
3. Also, change the query in the `awardNewBadges` function in `userHelper.js` under `HGNREST/src/helpers/` from all active users to whatever user you own so that the test will not affect all users. 
Screenshot 2024-03-19 at 15 11 50
4. Then go to MongoDB Compass and search for the user you entered in the previous step in the `userProfile` table. Modify the `lastWeekTangibleHrs` to a number between 40 and 50 hours. 
5. do `npm install` `npm run build` and `npm start` to run this PR locally
6. After 1 minute, check that 50 hours for 1 week is not assigned. (you can do this by checking the database or by frontend)
7. Then edit the `lastWeekTangibleHrs` to a number between 50 - 60 hours, then check if 50 hours for 1 week are assigned but 60 hours for 1 week is not. 

### First video
https://github.com/OneCommunityGlobal/HGNRest/assets/113070229/aa7e1a8c-e5b4-48cf-b35c-4487ba012f15

### Second video
https://github.com/OneCommunityGlobal/HGNRest/assets/113070229/d731cfd2-cb5c-4cdf-885d-c6653f763f76

### CODE REVIEW

**Review by psharma1984 — COMMENTED** [review]
hi @X1aoZhang99 Getting this error while running npm start after i make changes 
a
b
c
d

**Review by 666saofeng — APPROVED** [review]
I tested with admin, volunteer, and manager accounts. All worked as intended.
image
image
image

**Review by Renanluizssx — APPROVED** [review]
Hi @XiaohanMeng, i reviewed your PR and it's working as you said, please access my review below:

https://github.com/OneCommunityGlobal/HGNRest/assets/91035340/3f352de1-8ea3-4e08-ad62-f3b8df1df94a

**Comment by X1aoZhang99** [comment]
> hi @X1aoZhang99 Getting this error while running npm start after i make changes a b c d

Hi @psharma1984 ,

I think the problem is that you need to comment out the `'*****'` in the `userProfileJobs.js` since you commented on both lines. This will result in your error. 

Please DM me if you still have errors.

**Review by hetvi11110 — APPROVED** [review]
I have checked PR as mentioned here. And it is working as expected.

https://github.com/OneCommunityGlobal/HGNRest/assets/13557067/a98537dc-4068-40cb-97c7-e499789e4496

**Comment by j-corp-25** [comment]
Hi Xiao, 

Im following your directions as written but I tested volunteer user and admin and no badge changes at all.

The hours are updated on the database but the badge is not showing. Is there a specific front end branch you're using? 

I'm asking this because after I update on `MongoDB Compass`  it persist in redux state but badge doesnt show. 

I have attached screenshots below

- Made the file changes as instructed
FileChanges


- Database changes persist in redux but no badge
Redux

- No badge added to collection
noBadge

**Review by XiaohanMeng — APPROVED** [review]
Hi Xiao, your feature worked as intended. The new 50 hours badge was assigned to the user. 

https://github.com/OneCommunityGlobal/HGNRest/assets/113215317/eeb267a3-f709-4d81-959b-fb5b2e45cdf8

**Comment by X1aoZhang99** [comment]
> Hi Xiao,
> 
> Im following your directions as written but I tested volunteer user and admin and no badge changes at all.
> 
> The hours are updated on the database but the badge is not showing. Is there a specific front end branch you're using?
> 
> I'm asking this because after I update on `MongoDB Compass` it persist in redux state but badge doesnt show.
> 
> I have attached screenshots below
> 
> * Made the file changes as instructed
>   FileChanges
> * Database changes persist in redux but no badge
>   Redux
> * No badge added to collection
>   noBadge

Hi @j-corp-25 , 

Can you please attach a video so I can look into this issue, or can you DM me on Slack?

**Review by skaush21 — APPROVED** [review]
Hi @X1aoZhang99, feature works as expected.
* checked into branch
* modified code as mentioned in steps
* modified lastweektangiblehrs in mongodb compass(values used: 40,45,50) 
* npm install, npm run build, and npm start ran locally
* after a minute first checked 40 hours, badge was assigned 
* checked 45 hours, count increased for 40 hours
* lastly checked 50 hours, badge was assigned
* Frontend is displaying the badges

**Review by j-corp-25 — APPROVED** [review]
Hi @X1aoZhang99 ,

I followed the instructions very carefully, and its working as expected.

I tested Volunteer,core and Admin.  Badges are showing after following steps for each account.

I tested with the 40-range then waited for the 40 badge, then 50-range and waited for 50 badge.

Screenshots are below
- Volunteer 
 
PR_802___

- Admin 

PR_##802
- Coreteam

PR_802____

**Review by aaryaneil — APPROVED** [review]
The changes work as expected, good work.
Screenshot 2024-04-06 at 10 23 33 PM
Screenshot 2024-04-06 at 10 28 05 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
