### PR TITLE
Jatin make columns editable by owner

### PR DESCRIPTION
**Pull request by JatinAgrawal94**
# Description
Screenshot 2024-07-19 at 7 15 15 PM

## Related PRS (if any):
To test this backend PR you need to checkout the #[2620](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2620) frontend PR.

## Main changes explained:
- Created api endpoint to update user information from user management page.

## How to test:
1. check into current branch
2. do `npm install` and `npm run build` to run this PR locally
3. Follow steps mentioned in frontend PR further.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/588efe23-0f5f-47aa-b86b-67f97c37059c

### CODE REVIEW

**Review by AJAYINAVOLU — APPROVED** [review]
Reviewed on the Frontend Repository [Link](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2620#pullrequestreview-2261519321).  

Thank You

**Review by Jingyii800 — DISMISSED** [review]
Please see my comment on the front end branch.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2620#pullrequestreview-2270674939

**Review by SMitta11 — APPROVED** [review]
Approved PR and comments on frontend PR.
[frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2620#pullrequestreview-2274157406)

**Review by sri0606 — DISMISSED** [review]
Please checkout the [comment I made on frontend PR.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2620#pullrequestreview-2284358482)

**Review by Saniya98 — APPROVED** [review]
Reviewed on the frontend PR2620 
[](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2620#pullrequestreview-2304348983)
image

**Review by neeharikakoniki — APPROVED** [review]
The updates to make the columns editable by the Owner on the User Management page improve the usability and efficiency for managing user data directly. I tested the feature as described, verifying that edits were saved correctly across both the Profile and Reports pages
image

**Pull request merged**
