### PR TITLE
Leo Add ability to create a team from the Add Team option of User Management

### PR DESCRIPTION
**Pull request by Chuehleo**
# Description
Screenshot 2023-07-12 001931

## Related PRS (if any):
To test this backend PR you need to checkout the #997 frontend PR.
…

## Main changes explained:
- Update the postTeam function in teamcontroller.js to avoid user creating duplicate teams.
…

## How to test:
1. check into current branch in backend and frontend
2. do 'npm run build' and 'npm start' to run this PR locally
3. rest, follow frontend PR

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by sxiong5 — APPROVED** [review]
Tested with [PR#997](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/997), and it worked as expected! Great job!

**Review by DavidC0126 — APPROVED** [review]
Tested with frontend [PR#997](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/997) and it worked as intended.

**Review by scoopstroop92 — COMMENTED** [review]
Hello @Chuehleo there is some issue with the branch name as it has special characters. How to switch to this branch Leo-Add-ability-to-create-a-team-from-the-“Add-Team”-option-of-User-Management?

**Comment by mounica-dingari-by** [comment]
Hi @Chuehleo , I've tested this feature along with PR#997 and it works perfectly, as intended. But, I'd like to suggest that, please close the modal window once the 'confirm' button is pressed. 

Screenshot from 2023-07-20 21-07-16

**Comment by ramyaram2092** [comment]
> Hi @Chuehleo , I've tested this feature along with PR#997 and it works perfectly, as intended. But, I'd like to suggest that, please close the modal window once the 'confirm' button is pressed.
> 
> Screenshot from 2023-07-20 21-07-16

Hello @mounica-dingari-by  could you mention the branch name you used to test this PR?

**Comment by mounica-dingari-by** [comment]
> > Hi @Chuehleo , I've tested this feature along with PR#997 and it works perfectly, as intended. But, I'd like to suggest that, please close the modal window once the 'confirm' button is pressed.
> > Screenshot from 2023-07-20 21-07-16
> 
> Hello @mounica-dingari-by could you mention the branch name you used to test this PR?

Hi @ramyaram2092 , for testing the backend, switch to this 'Leo-Add-ability-to-create-a-team-from-the-“Add-Team”-option-of-User-Management' branch and for frontend it's 'Leo_add_create_team_ability_to_add_team_popup'.

**Comment by ramyaram2092** [comment]
> Leo-Add-ability-to-create-a-team-from-the-“Add-Team”-option-of-User-Management

I couldnt find this branch name @mounica-dingari-by 

image

**Comment by mounica-dingari-by** [comment]
> > Leo-Add-ability-to-create-a-team-from-the-“Add-Team”-option-of-User-Management
> 
> I couldnt find this branch name @mounica-dingari-by
> 
> image

@ramyaram2092 , please do git fetch first , so that you'll see all the latest branches and then you can switch to this "Leo-Add-ability-to-create-a-team-from-the-“Add-Team”-option-of-User-Management" branch

**Comment by Shreyj14** [comment]
Hi @Chuehleo 

The PR works as intended, and I was able to create the team. I can see that certain changes have been implemented which were part of the suggestions from the comments above. The changes I noticed which look good are -
1) When confirm is clicked without picking a team it displays the message "Hey, you need to pick a team first"
2) If a team exists it throws a message alerting that the team already exists.

As mentioned earlier, it would be nice if you close the add team window once the team is assigned as it will be much clear for the user to know that the team was assigned.

https://github.com/OneCommunityGlobal/HGNRest/assets/118795427/8e5c287e-b650-4b9d-a1ec-d28d7e4296f7

**Review by Shreyj14 — APPROVED** [review]

**Comment by iTvX** [comment]
Tested on the back end again, and everything is fine. As I mentioned early, an error message like "This team isn't found, you need to create a team first." may be better.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/24f45cde-0600-4b49-80c0-cf17d8457349

**Review by scoopstroop92 — APPROVED** [review]
It was an issue with vscode terminal. I was able to pull the branch successfully outside the ide 
Thank you for your inputs @mounica-dingari-by 
@Chuehleo  the functionality works well. Uploaded the testing video in front end PR 997
Approving the PR on the same note

**Review by shiva2096 — APPROVED** [review]
Hi @Chuehleo 

Great work ! The functionality is working as expected.


https://github.com/OneCommunityGlobal/HGNRest/assets/26687177/beea196d-1154-4ad1-9b3d-0ecd417db853

**Review by igorrochadasilva — COMMENTED** [review]
Hi @Chuehleo !

I tested the PR with #997 and it works as intended, and I was able to create the team.

Great work! 😃
Obs: When  I tried to create a already existing team, It didn't created, but I received the message: "Team added successfully", I don't know if it would be good receive a message: "The team is already created" ?


453_01_try-register-already-exist-team

**Review by vemanamadhu — APPROVED** [review]
Good job. Left comments on [#997 ](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/997#)

**Review by mahamakhan — APPROVED** [review]
Left comments on frontend. Works perfectly fine.

**Review by Indujaks — APPROVED** [review]
Tested Changes, works as expected!
Screenshot 2023-07-27 at 4 57 12 PM

**Review by yaow62023 — APPROVED** [review]
I have tested your PR, all the comment at PR# 997. Great Work!

**Review by zuhang2000 — APPROVED** [review]
Tested with PR 997. Left comment there. And it worked as expected! Great job!
My comment on 997: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/997#pullrequestreview-1553141507

**Review by mahamakhan — APPROVED** [review]
Tested the functionality and was able to create a team and add it successfully. 

image
Screenshot 2023-07-29 200615
Screenshot 2023-07-29 200519
Screenshot 2023-07-29 200714

**Review by ThapeloMasasa — APPROVED** [review]
The functionality works as intended both for the backend and the frontend. and the code is well written 
Screenshot 2023-07-31 at 9 45 44 PM

Screenshot 2023-07-31 at 9 46 04 PM

**Review by winghojackyli — APPROVED** [review]
Hello @Chuehleo , this backend PR was tested along with the frontend #997 PR and they work great together. It has been approved and comment left here. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/997#pullrequestreview-1562190692

**Review by Abiddy — APPROVED** [review]
Works well

[Screencast from 08-12-2023 08:52:17 PM.webm](https://github.com/OneCommunityGlobal/HGNRest/assets/77697776/f457ef2e-2f2f-4020-bb94-9c4f385f39f8)

**Comment by veronicacheng2** [comment]
Hi @Chuehleo, I tried testing this PR with #997, but the 'Create New Team' input and button do not show up. Please let me know if I did anything wrong during the testing. Thank you.

image

**Review by veronicacheng2 — APPROVED** [review]
Hi @Chuehleo, I have tested the PR with the frontend. Everything works as intended. Comments left on #997.

**Review by winghojackyli — APPROVED** [review]
Hi @Chuehleo , I've tested this PR with the updated frontend PR and they work well together. 
Approval with comments left here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/997#pullrequestreview-1585734071

**Comment by Shubhu0** [comment]
PR working as intended. Good job!

**Comment by Shiwani99** [comment]
Hi,
Great work. Added my comments to front end PR#453.

**Comment by wantingxu7** [comment]
Good work! works as intended. Comment in FE #997

**Comment by RheaWu1212** [comment]
Tested with FE #997, comments there.

**Review by JeffLi117 — APPROVED** [review]
Review left on FE PR # 997.

**Review by yi-lin-1234 — APPROVED** [review]
Hi, I tested this PR with #997,  and it works as intended. Great work!

https://github.com/OneCommunityGlobal/HGNRest/assets/92185695/d754e910-37b6-4d59-9d56-6e1fc9eecf3e

**Review by StrawberryCalpico — APPROVED** [review]
Hi I tested this PR, details in [#997](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/997#pullrequestreview-1672444731)

**Review by malikjahanzaib — APPROVED** [review]
Hi @Chuehleo, I tested this PR and it works as intended. Left detailed review on [FE PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/997).

**Comment by kavya151** [comment]
Hi @Chuehleo tested this with #997 and worked as intended. Details in #997

**Review by navneeeth — CHANGES_REQUESTED** [review]
Hello, @Chuehleo! I tested this functionality and have commented the full review on the FE PR while addressing an issue. Good implementation!

**Review by navneeeth — APPROVED** [review]
Approving after the recent fix on the FE. Great job!

**Pull request merged**
