### PR TITLE
Diego add conventional commits with husky

### PR DESCRIPTION
**Pull request by DiegoSalas27**
image

# Description
Adds a bash script to enforce conventional commits. Conventional commits are a recommended way to write commit messages which will be later use to for creating commit history that is readable and that can self document the source code using Changelogs. This can be further automated with through a custom action in github workflows.

## Related PRS:
N/A

## Main changes explained:
- Adds a bash script file in .husky to bind to the commit-msg git hook to enforce commit messages complying with conventional commits specification.

## How to test:
1. check into current branch
2. do `npm install`
3. if you are working on Mac or Linux, run the following command: `npm run prepare` (this will make .husky files executable)
4. create a new branch of you own for testing this PR
5. perform any changes in file and add a commit message that doesn't comply with the conventional commits specification (it should fail to commit your staged files)
6. write a commit message that does comply with conventional commits specification (it should pass)
7. watch the attached video to understand how properly follow these directions.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/26840798/52bd7afc-7d07-4f51-889b-26517b74ad68

## Note:
This is approach to write our commit messages should be enforced in order to better document our code and have a better commit history which can be easily tracked. In addition, automated documenting tools like changelogs will leverage this conventional commits to further document the code in a MarkDown file.

### CODE REVIEW

**Review by Abi-Liu — APPROVED** [review]
Hey Diego, I really like the changes you are trying to make. I tested the precommit message and it works as intended, only allowing me to make a commit according to the standards.

https://github.com/OneCommunityGlobal/HGNRest/assets/59585815/5dcc7f72-a500-4f35-90c2-e818a263b3f8
Screenshot 2024-03-21 at 4 18 35 PM

**Review by navyasrim — APPROVED** [review]
Hi,
As mentioned the changes are working as expected and the screen shots are attached.For this I created branch "nav-test-conv-messgepr" and added file and commited for testing..Can deleted this branch once approved or merged.
PR-804-1
PR-804-2

**Review by luisarevalo21 — APPROVED** [review]
@DiegoSalas27 
Hello, 

I tested your branch, and was able to succefully replicate the new changes. 
Attempting to add a plain commit message displays an error. 
However, once I added a correct message I was able to commit the message. 
Great work! 
I've attached a screen shot and video. 

Screenshot 2024-03-21 at 8 46 16 PM


https://github.com/OneCommunityGlobal/HGNRest/assets/22454953/6abfb8d5-39c1-4363-8e5d-11f618b54b61

**Review by swathyjayaseelan — APPROVED** [review]
Great effort to make sure we have a structured format for commit messages. Works as expected.
Screenshot 2024-03-22 at 11 34 44 AM

**Review by Pandani07 — COMMENTED** [review]
Tested this PR and works as intended. My commit was denied when I gave a random message, but was allowed when I followed the convention.

Screenshot 2024-03-22 at 9 20 19 PM

**Review by SMitta11 — COMMENTED** [review]
I followed the steps and created a new branch to test those changes.
Done changes in project.js file and then added a git commit message without following instructions and got a message that "your commit message is invalid".
And then again added a commit message that  comply with conventional commits specification and it worked as expected.
Screenshots:
Screen Shot 2024-08-30 at 10 38 15 PM
Screen Shot 2024-08-30 at 10 39 34 PM

**Pull request merged**
