### PR TITLE
yihan create submit for review button

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
This backend PR is related to the [#1013](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1013) frontend PR.

## Main changes explained:
- Update file task.js for adding reviewStatus property to task object.

## How to test:
1. check into current branch on both frontend and backend.
2. do `npm install` and `npm run build` to run this PR locally
3. follow the description of [PR#1013](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1013)

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/915fceb5-8325-4cd8-941a-6711d705a33d

## Note:
It may take some time for button to update.

### CODE REVIEW

**Review by joyceiphone — APPROVED** [review]

**Review by mahamakhan — COMMENTED** [review]
left a review on the frontend

**Review by winghojackyli — APPROVED** [review]
The PR works great with front end PR #1013 and I left comments there.

**Review by Lin1404 — APPROVED** [review]

**Comment by Lin1404** [comment]
Hi @AriaYu927, I've tested this PR with FE PR and it worked perfect, good job!

**Review by zuhang2000 — APPROVED** [review]
This PR works perfect with the related front end PR #1013. I left comments there. Good job!

**Review by yunshan111 — APPROVED** [review]
LGTM! Tested both frontend and backend.

**Review by veronicacheng2 — APPROVED** [review]
Hi @AriaYu927, I have tested this PR together with #1013. Comments left on #1013 and everything works as intended.

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
