### PR TITLE
Jingyi-User Profile: Rehireable / Notrehireable Check Box

### PR DESCRIPTION
**Pull request by Jingyii800**
# Description
When logging as Owner/Admin, going to one user's user profile, besides the user's time log icon, there is a checkbox to change the rehireable status of this user.
Also, when viewing people by Reports>Reports>People>Choose person>,  the rehireable/Not rehireable checkbox is on the right.
image
image

## Related PRS (if any):
This backend PR is related to the [#2032](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2032#issue-2175168478) fronend PR.

## Main changes explained:
- Add server function to change the status of rehireable/Not rehireable

## How to test:
1. check into current branch
2. do `npm install` and `npm run build` and `npm start` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Leaderboard→ select one user→ User profile
6. verify there's a check box besides the "clock" icon to change rehireable status. When clicking on it, a popup window will ask you to confirm the change.
7. Refresh the page to make sure this change is saved.
8. go to Reports>Reports>People>Choose person>, see there is a checkbox under the "title". When clicking on it, a info window will pop up and show the result.
9. Refresh the page to make sure this change is saved.
10. Log in as a Volunteer Role; make sure you cannot see this checkbox on the User Profile Page.

### CODE REVIEW

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed the frontend PR related to this and it work as intended.

**Review by 20chen-7 — COMMENTED** [review]
not sure what happened, but when I run npm start from the frontend, here is what I got
Screenshot 2024-03-14 at 2 28 57 PM

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and left a review on the Frontend PR.

**Review by yvonnep165 — APPROVED** [review]
Hi, I tested this PR and left a review on the Frontend PR 2032.

**Review by aaryaneil — COMMENTED** [review]
Left a review on the [frontend.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2032#pullrequestreview-1984710112)

**Pull request merged**
