### PR TITLE
Leo_fix_issue_update_with_updating_existing_password

### PR DESCRIPTION
**Pull request by Chuehleo**
# Description
Screenshot 2023-10-13 151833

## Related PRS (if any):
To test this backend PR you need to checkout the #1414 frontend PR.
…

## Main changes explained:
- modify the logic in UpdatePassword and ValidatePassword function
…

## How to test:
1. check into current branch in backend and frontend
2. do 'npm run build' and 'npm start' to run this PR locally
3. rest, follow frontend PR

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by StrawberryCalpico — DISMISSED** [review]
Hi I tested your PR, details on [FE#1414](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1414#pullrequestreview-1677620158)

**Review by JeffLi117 — APPROVED** [review]
Comments left on FE #1414.

**Comment by Cloid** [comment]
Tested PR and left comments on FE#1414

**Review by Cloid — CHANGES_REQUESTED** [review]
Tested PR and left comments on FE#1414

**Review by malikjahanzaib — COMMENTED** [review]
Hi @Chuehleo, I have tested this PR and left detailed review on FE #1414.

**Comment by yangfan2001** [comment]
Hi I have read your code and tested your PR, details on FE#1414.

**Review by yangfan2001 — COMMENTED** [review]
Hi I have read your code and tested your PR, details on FE#1414.

**Comment by shubhankarval** [comment]
Hey, tested your PR and left a comment on FE#1414.

**Comment by RheaWu1212** [comment]
Hi I tested your PR and left a comment on FE#1414.

**Review by TuanDinh140194 — APPROVED** [review]
Hi! I have test your PR, and everything works great! First, I have logged in to my owner account and changed my password. After change my password, I have logged in again with my new password and it work correctly. Next, I have reset the password of my volunteer account from the owner account and try to logged in with my volunteer account. The password works as expected. Finally, in the volunteer account, I have check the update password for different account and it is not appear as describe. Great work ! 

https://github.com/OneCommunityGlobal/HGNRest/assets/81892917/cb716d0d-af21-4f88-be88-a278543daf76

**Review by ChirayuRai — COMMENTED** [review]
Hello! I looked at your code and tested the changes as well. Those comments are on FE#1414.

**Comment by AriaYu927** [comment]
I've tested this PR and left a comment with more details in [#1414](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1414#issuecomment-1780924657).

**Review by shubhankarval — APPROVED** [review]
Hey @Chuehleo , left a comment on FE PR [#1414](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1414).

**Comment by beblicarl** [comment]
I have reviewed the frontend and the functionality works as intended

**Review by beblicarl — APPROVED** [review]

**Review by Cloid — APPROVED** [review]
Tested and left a comment on FE PR 1414.

**Pull request merged**
