### PR TITLE
Parthj unit and integration test forgotpwdcontroller.js

### PR DESCRIPTION
**Pull request by Parth-tech**
# Description
PR adds unit test for forgotPwdcontroller.js, integration test for forgotPwdRouter.js and a readme highlighting the test cases covered in both.

## Related PRS (if any):
None

## Main changes explained:
- Added unit test file named: forgotPwdcontroller.spec.js
- Added integration test file named: forgotPwdRouter.test.js

## How to test:
1. check into current branch
2. do `npm install` 
3. do `npm run test forgotPwd`
4. All test cases should pass

## Screenshots or videos of changes:
Output looks like this:
Screenshot 2024-05-25 at 6 29 43 PM

### CODE REVIEW

**Review by MinSun0814 — APPROVED** [review]
image

**Review by peter6866 — APPROVED** [review]
All tests passed successfully. 
image

**Review by cecilia-uu — APPROVED** [review]
All tests passed successfully.
截屏2024-05-27 上午11 05 50

**Review by Kavil-Jain-514 — APPROVED** [review]
The code looks good, and all the test cases have been passed.
image

**Comment by Infinite-Turkey** [comment]
image

**Review by Infinite-Turkey — APPROVED** [review]
image
All tests passed. It looks good to me!

**Review by Sandhya1236 — CHANGES_REQUESTED** [review]
The test cases are failing. The test failures in the code are due to timeouts and invalid header values in the API requests. The timeout errors indicate that asynchronous callbacks aren't completing within the specified 5000 ms limit. This can be resolved by increasing the Jest timeout using jest.setTimeout(10000) and ensuring that all asynchronous operations are correctly awaited and callbacks are invoked. The invalid header value errors occur because the Authorization header is being set to undefined. To fix this, ensure that the Authorization header is properly assigned with a valid token in the tests. Here are the screenshots below for reference.

image
image

**Comment by Parth-tech** [comment]
> The test cases are failing. The test failures in the code are due to timeouts and invalid header values in the API requests. The timeout errors indicate that asynchronous callbacks aren't completing within the specified 5000 ms limit. This can be resolved by increasing the Jest timeout using jest.setTimeout(10000) and ensuring that all asynchronous operations are correctly awaited and callbacks are invoked. The invalid header value errors occur because the Authorization header is being set to undefined. To fix this, ensure that the Authorization header is properly assigned with a valid token in the tests. Here are the screenshots below for reference.
> 
> image image

**Comment by Parth-tech** [comment]
> # Description
> PR adds unit test for forgotPwdcontroller.js, integration test for forgotPwdRouter.js and a readme highlighting the test cases covered in both.
> 
> ## Related PRS (if any):
> None
> 
> ## Main changes explained:
> * Added unit test file named: forgotPwdcontroller.spec.js
> * Added integration test file named: forgotPwdRouter.test.js
> 
> ## How to test:
> 1. check into current branch
> 2. do `npm install`
> 3. do `npm run test forgotPwd`
> 4. All test cases should pass
> 
> ## Screenshots or videos of changes:
> Output looks like this: Screenshot 2024-05-25 at 6 29 43 PM



> The test cases are failing. The test failures in the code are due to timeouts and invalid header values in the API requests. The timeout errors indicate that asynchronous callbacks aren't completing within the specified 5000 ms limit. This can be resolved by increasing the Jest timeout using jest.setTimeout(10000) and ensuring that all asynchronous operations are correctly awaited and callbacks are invoked. The invalid header value errors occur because the Authorization header is being set to undefined. To fix this, ensure that the Authorization header is properly assigned with a valid token in the tests. Here are the screenshots below for reference.
> 
> image image

Hi Sandhya,
Thank you for reviewing the PR. Can you help me reproduce the errors? It worked at my end so I was wondering did you attach any options to the test command while testing or anything else?

**Comment by KaushikMreddy** [comment]
Hi Parth, 
All your test cases have passed
image

**Review by Wenboooooo — APPROVED** [review]
All tests have passed. It looks good to me.

**Review by dikshitakejriwal — APPROVED** [review]
The code looks good. All the test cases passed. 
Screenshot 2024-05-31 at 4 54 06 PM

**Review by j-corp-25 — COMMENTED** [review]
hi @Parth-tech 

Just want to point out that some tests did not pass 

error

**Review by deepthikannan — APPROVED** [review]
image
All test cases passed !

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-06-01 at 6 42 32 PM

**Review by jinxyou — APPROVED** [review]
I run the test on my local setup. All the test cases have passed. Nice work!
Screenshot 2024-06-01 205327

**Comment by Sandhya1236** [comment]
Hi @Parth-tech ,

Thank you for your reply. I apologize profusely for the confusion earlier. I followed your suggestion to reproduce the errors again and realized I might have forgotten to run npm install the last time.

This time, I made sure to run npm install before executing the tests with npm run test forgotPwd. The tests executed perfectly without any errors.

I appreciate your patience and understanding. Please let me know if there's anything else you need.

Best regards,
Sandhya

**Review by Sandhya1236 — APPROVED** [review]
The test cases are failing. The test failures in the code are due to timeouts and invalid header values in the API requests. The timeout errors indicate that asynchronous callbacks aren't completing within the specified 5000 ms limit. This can be resolved by increasing the Jest timeout using jest.setTimeout(10000) and ensuring that all asynchronous operations are correctly awaited and callbacks are invoked. The invalid header value errors occur because the Authorization header is being set to undefined. To fix this, ensure that the Authorization header is properly assigned with a valid token in the tests. Here are the screenshots below for reference.

image
image

**Comment by Parth-tech** [comment]
> Hi @Parth-tech ,
> 
> Thank you for your reply. I apologize profusely for the confusion earlier. I followed your suggestion to reproduce the errors again and realized I might have forgotten to run npm install the last time.
> 
> This time, I made sure to run npm install before executing the tests with npm run test forgotPwd. The tests executed perfectly without any errors.
> 
> I appreciate your patience and understanding. Please let me know if there's anything else you need.
> 
> Best regards, Sandhya

No problem.
Thanks for your efforts!

**Comment by Parth-tech** [comment]
> hi @Parth-tech
> 
> Just want to point out that some tests did not pass
> 
> error

Hey @j-corp-25,
I will take a look into it. Meanwhile can you help with the steps to reproduce this? Did you add any flag while executing the test command or anything else? 
Thanks in advance.

**Review by CloudyZ524 — APPROVED** [review]
Hi Parthj,
All unit test in your pull request has been passed! Great job!

Screenshot 2024-06-07 at 12 52 03

**Review by Ramaruva — APPROVED** [review]
Hi, tested the given test cases and all test cases are passed.
image

**Review by suaniii — APPROVED** [review]
Hi, the code looks good, and all the test cases have been passed.
image

**Review by shradac — APPROVED** [review]
All tests passed. The tests cover all specified scenarios. Good Work!

**Comment by Trip2310** [comment]
Hi Parth, I am not able to run test, showing no test
forgotPwd_err

**Comment by sahithidhulipala9** [comment]
All test cases passed!
PR962

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by Trip2310 — APPROVED** [review]
Hi Parth, tests are passed successfully
PR#962

**Review by DiyaWadhwani — APPROVED** [review]
Hi Parth, 
All your test cases have passed. Thank you for the clear instructions. Great work.

**Review by nikhilpittala16 — APPROVED** [review]
All test cases passed successfully.
Screenshot (34)

**Review by nyelmela — APPROVED** [review]
I have tested this PR and all test cases have passed.
image

**Review by Rishitha1309 — APPROVED** [review]
All test cases passed.!

**Review by Vigneshwar-Muriki — APPROVED** [review]
Performed unit testing as mentioned and all test cases passed successfully.
Screenshot 2024-07-12 170611

**Comment by ZhangPeizhou** [comment]
All tests passed. Well done!
PR#962

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
