### PR TITLE
Jacob - Optimize member search

### PR DESCRIPTION
**Pull request by DragonSlayer2401**
image

## Related PRS (if any):
This backend PR is related to the [#1934](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1934) frontend PR.
…

## Main changes explained:
- Optimize member filtering
- Add full name searching
- Clear search results when none are found
…

## How to test:
1. check into current branch
2. check into the related frontend branch
3. do npm install
4. do npm run build
5. do npm start

## Screenshots or videos of changes:
Before:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/9a5b653e-48b0-431f-9b10-c40109898234

After:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/68051a17-978a-4125-b9be-3a308150fc6a

### CODE REVIEW

**Review by TareqMia — APPROVED** [review]
Hello, I have left my comments on the related front-end [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1934#pullrequestreview-1874262635). Great job on implementing this 👍

**Comment by galgalinidhi** [comment]
I have left a comment here - https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1934

**Review by SaiDeepak-NEU — APPROVED** [review]
Hi Jacob,
I tested the filter project members feature on the frontend and everything worked very smoothly, please check the frontend PR for screenshots.

**Review by Jingyii800 — APPROVED** [review]
Hi, I have tested this feature with frontend PR, and it works very well. Please see more details on https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1934#pullrequestreview-1883999071.

**Comment by beblicarl** [comment]
I tested and left a comment on the frontend of this functionality and it works as intended

**Review by beblicarl — APPROVED** [review]

**Pull request merged**
