### PR TITLE
Imran_See_User_Management_Tab_Full_Functionality

### PR DESCRIPTION
**Pull request by ImzIssa**
# Description
Create "See User Management Tab (Full Functionality)" permission.
Make the "Other Links" -> "User Management" option appear/accessible with full functionality of User Management page (user is able to create, delete, and update users) for users who have the "See User Management Tab (Full Functionality)" permission.

## Related PRS (if any):
To test this backend PR you need to checkout the [#2478](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2478) frontend PR.
…

## Main changes explained:
- added new Permission 'userManagementFullFunctionality'

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Follow steps on the Frontend PR to test

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by SMitta11 — APPROVED** [review]
Added comment at front end PR, it works as expected.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2478#pullrequestreview-2244165859

**Review by Lemonnycodes — APPROVED** [review]
Tested the PR, it works as expected.
Detailed review added to the Front End PR

**Review by vishnupriyaatheti — CHANGES_REQUESTED** [review]
Tested this PR and kept my comments in frontend PR.

**Review by AJAYINAVOLU — APPROVED** [review]
Tested the PR and it works as expected.
I have added the review to the Front End repo.

**Review by sri0606 — APPROVED** [review]
I have reviewed the changes and[ left a review on frontend PR.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2478#pullrequestreview-2281407924)

**Review by Shreyav2000 — CHANGES_REQUESTED** [review]
I have followed the steps as instructed and tested the functionality, but it is not working as expected. For more details, please refer to the comment and video attached in the link provided below. Could you please check the issue with the backend?
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2478#pullrequestreview-2285212457

**Review by ashayk9 — CHANGES_REQUESTED** [review]
made comment on the frontend pr with the issue found

**Review by crystallow1168 — APPROVED** [review]
Tested PR with frontend [PR #2478](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2478#pullrequestreview-2304075044) and changes are working as expected

**Review by neeharikakoniki — CHANGES_REQUESTED** [review]
Reviewed  at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2478#pullrequestreview-2304325338

**Review by Muzammil603 — COMMENTED** [review]
I have tested this and this functionality is not working front end PR #2478.

**Pull request closed without merging**
