### PR TITLE
Carl-fix-suggestion-icon-modal

### PR DESCRIPTION
**Pull request by beblicarl**
# Description
The "Suggestion Icon Modal" stopped over a week ago. Initially, when the Suggestion Icon is clicked a modal appears on the screen allowing suggestions to be made.

## Related PRS (if any):
This backend PR is related to the [#1292](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1292) frontend PR.
To test this backend PR you need to checkout the [#1292](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1292)  frontend PR.
…

## Main changes explained:
- Added error handling to the functions for effective debugging
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to dashboard→ Suggestion Icon…
5. verify function “A” (feel free to include screenshot here)

### CODE REVIEW

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I have added my comments for front end PR#1292.

**Review by iTvX — APPROVED** [review]
I have tested your pr, and left comments on the front end.

**Review by navneeeth — APPROVED** [review]
Hi! Tested your changes and commented a review on the [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1292#pullrequestreview-1629833596). Good work!

**Review by robertoooc — APPROVED** [review]
Works well tested it along with PR 1292.

**Review by Haoj1 — APPROVED** [review]
@beblicarl Good job! Comments are left in #1292

**Review by zuhang2000 — COMMENTED** [review]
Good job! I leave on front-end PR 1292 there.

**Review by ChristianHrs — APPROVED** [review]
Hi @beblicarl ,

I've reviewed the changes and it works fine on my end. 
Comments on front-end post

**Review by AriaYu927 — COMMENTED** [review]
Works great! I left a comment under #1292

**Review by tsunami776 — COMMENTED** [review]
Comment left in FE PR#1292. Nice work!

**Review by wantingxu7 — APPROVED** [review]
Good work! Left comment in FE PR

**Review by DavidC0126 — APPROVED** [review]
Left comment on FE PR. LGTM.

**Review by eduhorta — APPROVED** [review]
Great Work! Left comment FE PR aswell. 👍

**Comment by one-community** [comment]
Wonderful, thank you. Merging!!

**Review by Bhagyashree444 — COMMENTED** [review]
Good Work. Reviewed and commented on frontend PR - #1292 as well.

**Pull request merged**
