### PR TITLE
Vishala Consumables API

### PR DESCRIPTION
**Pull request by Vishala09**
# Description
This PR is about the Consumables List View from Phase 2 with Sorting based on project name and item name , Filtering based on selected values of project and consumable and Modal implementation for viewing update and purchase history.
Implements # (WBS) 8.1.2

## Related PRS (if any):
To test this backend PR you need to checkout the [#1758](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1758) frontend PR.

## Main changes explained:
- Created a fetch api for consumables

## How to test:
1. check into current branch
2. do `npm run build` and `npm run start` to run this PR locally
3. Test api : http://localhost:4500/api/bm/consumables

### CODE REVIEW

**Review by abdel-lall — APPROVED** [review]
LGTM.
Screenshot 2023-12-29 233941

**Review by Alforoan — APPROVED** [review]
I left my comment on the fe pr #1758

**Review by scoopstroop92 — COMMENTED** [review]
Left a feedback on the front end PR

**Review by tdkent — CHANGES_REQUESTED** [review]
Only issues are the conflicts on routes.js

**Review by scoopstroop92 — APPROVED** [review]
The functionality works as expected. Good Job Vishala !

**Review by tdkent — APPROVED** [review]

**Pull request merged**
