### PR TITLE
Wbs4.2.1/forgot password changes

### PR DESCRIPTION
**Pull request by getnithesh**

### CODE REVIEW

**Comment by daoquangvy** [comment]
I wonder if you can update this PR since I got a lot of errors when I tried to run this Back-End branch with our current Front-End development branch.
image

**Comment by getnithesh** [comment]
> I wonder if you can update this PR since I got a lot of errors when I tried to run this Back-End branch with our current Front-End development branch.
> image

Hi @daoquangvy  - the above error is in utils/objects.cs and which is not changed as part of this PR. As the scope of this PR is only user management can you check with latest development branches of both hgnrest and react app and if the error persist ask Jae to raise a bug so that we can include that in work item, please?

**Comment by daoquangvy** [comment]
Hi @getnithesh,

I have tried to run the latest development branch of both HGNRest and the React app, there is no error or anything that happen.
When I tried to run the HGNRest (back-end) using this branch, I have the same bug happens again,

**Comment by getnithesh** [comment]
> Hi @getnithesh,
> 
> I have tried to run the latest development branch of both HGNRest and the React app, there is no error or anything that happen.
> When I tried to run the HGNRest (back-end) using this branch, I have the same bug happens again,

Hi @daoquangvy  I did a merge with development branch and pushed the changes, all working good at my end, could you try again one more time , please, if the issue persist can we have a scrennshare session to discuss over google meet ? 

sharing the screenshot of the app 
image

**Review by daoquangvy — APPROVED** [review]
Everything is working normally without any bugs or issues. 

So I will approve this.

**Pull request merged**
