### PR TITLE
test: tests for getAllBadges

### PR DESCRIPTION
**Pull request by Abi-Liu**
# Description
Unit and Integration tests for the getAllBadges method and routes

## Related PRS (if any):
N/A

## Main changes explained:
- Added unit tests for positive and negative cases in the getAllBadges method
- Created integration tests for the getAllBadges routes.
…

## How to test:
1. check into current branch
2. do `npm install` 
3. run `npm run test badge`
4. verify all tests pass

## Screenshots or videos of changes:
Screenshot 2024-04-04 at 4 07 45 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by j-corp-25 — COMMENTED** [review]
Hi @Abi-Liu ,

I have followed the instructions as noted in your PR but I am not getting the expected results.

Only 1 test passes on my end and the rest fails. 
this is what is on my terminal after I ran your instructions 

`actionItem routes › badgeRoutes › should return 401 if authorization header is not present`

Instance Exited before being ready and without throwing an error!

 `actionItem routes › badgeRoutes › should return 401 if authorization header is not present`

 Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

 `actionItem routes › badgeRoutes › Should return 404 if the route does not exist`

    Instance Exited before being ready and without throwing an error!

`actionItem routes › badgeRoutes › Should return 404 if the route does not exist`

  MongooseError: Operation `badges.deleteMany()` buffering timed out after 10000ms

 `actionItem routes › badgeRoutes › Should return 404 if the route does not exist`

Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

`actionItem routes › badgeRoutes › Should return 404 if the route does not exist`

TypeError: Invalid value "undefined" for header "Authorization"TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"

 `actionItem routes › Post badge route › Should return 403 if user does not have permissions`

    Instance Exited before being ready and without throwing an error!

`actionItem routes › Post badge route › Should return 403 if user does not have permissions`

    MongooseError: Operation `badges.deleteMany()` buffering timed out after 10000ms

`actionItem routes › Post badge route › Should return 403 if user does not have permissions`

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

`actionItem routes › Post badge route › Should return 403 if user does not have permissions`

    TypeError: Invalid value "undefined" for header "Authorization"TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"

`actionItem routes › Post badge route › Should return 201 if the badge is successfully created`

    Instance Exited before being ready and without throwing an error!

 `actionItem routes › Post badge route › Should return 201 if the badge is successfully created`

    MongooseError: Operation `badges.deleteMany()` buffering timed out after 10000ms

`actionItem routes › Post badge route › Should return 201 if the badge is successfully created`

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

`actionItem routes › Post badge route › Should return 201 if the badge is successfully created`

    TypeError: Invalid value "undefined" for header "Authorization"TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"

`actionItem routes › Post badge route › Should return 400 if another badge with the same name exists`

    Instance Exited before being ready and without throwing an error!

`actionItem routes › Post badge route › Should return 400 if another badge with the same name exists`

    MongooseError: Operation `badges.deleteMany()` buffering timed out after 10000ms

`actionItem routes › Post badge route › Should return 400 if another badge with the same name exists`

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

`actionItem routes › Post badge route › Should return 400 if another badge with the same name exists`

    TypeError: Invalid value "undefined" for header "Authorization"TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Authorization"`

I have attached the video below with the failed command, I ran it twice just in case

I have attached a video below following the instructions:

https://github.com/OneCommunityGlobal/HGNRest/assets/95154804/90b5753d-bbe0-4582-984a-b8142fdac8de

**Comment by Abi-Liu** [comment]
Hey @j-corp-25. That's interesting. I can't replicate those errors no matter what I've tried. I'm also not using the `deleteMany` query anywhere in the tests or the controllers so I'm not sure why that error is even popping up.

Do you mind taking a video of the `badgeRouter.test.js` file so I can see the code you have?

**Comment by j-corp-25** [comment]
hey @Abi-Liu 

I tried it again just to see, I also pulled the latest changes to see if maybe something was not picked up, but I still dont see the expected result.



I'm free on slack as well if you want to discuss about this PR


Here is a snapshot:

ErrorPR_836

Here is the video of the `badgeRouter.test.js` file as requested.


https://github.com/OneCommunityGlobal/HGNRest/assets/95154804/919babb2-198d-496a-8c5a-5d7616b9acb4

**Comment by DiegoSalas27** [comment]
Hey @Abi-Liu,

You test are thorough and I was able to execute them successfully, there is only one question I want to ask. Please find it inside of the file changes, I added a comment there.

**Review by aaryaneil — COMMENTED** [review]
All the test cases were passed, in the first go there were failures but I couldn't recreate it.
Screenshot 2024-04-06 at 10 46 25 AM

**Review by p-suram — APPROVED** [review]
I am able to successfully run test cases and they all passed on first go.
image

**Review by jennZhang93 — APPROVED** [review]
All tests passed. Codes look good as it covered many scenarios. Good work! 
Screenshot 2024-04-06 at 8 25 29 PM

**Pull request merged**
