### PR TITLE
Abi badge delete badge tests

### PR DESCRIPTION
**Pull request by Abi-Liu**
# Description
Unit and integration tests for the delete badge controller method and route.

## Related PRS (if any):
N/A

## Main changes explained:
- Testing the positive and negative cases for the `deleteBadge` method in the badgeController
- integration tests for the delete badge route

## How to test:
1. check into current branch
2. do `npm install`
3. run `npm run test badge`
4. verify all tests pass

## Screenshots or videos of changes:
Screenshot 2024-04-10 at 10 40 20 AM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Parth-tech — APPROVED** [review]
Hey Abi,
All the test cases did pass, great job. You have covered 403, 400, 200 and 500 cases very well. If I do come up with any edge case I will post them here for you to include them. Thanks. 
DeleteBadge Test Cases

**Review by jennZhang93 — APPROVED** [review]
I've tested with the given test and it all passed on the first run. The codes also covers major situations. Good work!

Screenshot 2024-04-10 at 8 20 54 PM

**Review by j-corp-25 — COMMENTED** [review]
Hey @Abi-Liu , im still running into issues running these tests. 

I'm encountering issues with running the test suite on Windows, particularly with the routes tests, while the controller tests are passing successfully. Here’s a summary:

- **Environment**: The issue occurs on Windows; no problems on Mac.

- **Issue**: All tests in the routes suite fail despite attempts to troubleshoot.

- **Troubleshooting Done**:
  - Ran tests with `--verbose` for more details, but didn't uncover any clues.
  - Deleted `node_modules` and `package-lock.json`, but the issue persists.
  
- **Next Steps**: I'm on the lookout for insights from anyone with experience running these tests on Windows. 

PR869


 #### Errors from the routes test similar to what was encountered in PR #836:

PR869TestRoute1

PR869TestRoute2

PR869TestRoute3

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all test cases passed.
Screenshot 2024-04-20 at 12 47 06 PM

**Review by gowthamdongari — APPROVED** [review]
All test cases passed!
image

**Comment by mSharifHub** [comment]
I run all the test, went over the files. I am new to the organization. however, the code is working how suppose to. I have not found nothing to be of concern.

**Review by Ramaruva — APPROVED** [review]
I have run the test cases in my local env and all test cases are passed
image

**Review by KaushikMreddy — COMMENTED** [review]
Hi @Abi-Liu 
I've reviewed your changes. All test cases have passed. Its amazing that you've covered all the error codes in your cases. Good work!

image

image

### Error faced and Fixed
I faced an error while running npm install in my windows laptop. 
image

Line 19 in package.json :    `"prepare": "husky install && chmod ug+x .husky/* && chmod ug+x .git/hooks/*"`, 

This line will not run in Windows, if anyone is running this in windows, please replace this line with this code below:

  `"prepare": "husky install && if %OS% == Windows_NT (echo Running on Windows) else (echo Running on Unix) && ./.husky/*"`
  
 Good work overall!

**Review by Wenboooooo — APPROVED** [review]
Hi! It looks good to me. All cases have passed.

**Review by Infinite-Turkey — APPROVED** [review]
All the tests went through. Thank you for your work!
image

**Review by MinSun0814 — APPROVED** [review]
image

**Comment by ZhangPeizhou** [comment]
Passed all tests
PR#896

**Review by dikshitakejriwal — APPROVED** [review]
All the test cases passed. Great work! All the cases were covered according to me. Will let you know if I come across any other edge case. 
Screenshot 2024-05-29 at 6 47 58 AM

**Review by peter6866 — APPROVED** [review]
Great work. All tests passed as expected. 
image

**Comment by ZhangPeizhou** [comment]
PR#869
All tests passed

**Review by deepthikannan — APPROVED** [review]
image
All test cases passed, looks good to me !

**Review by Kavil-Jain-514 — APPROVED** [review]
All Test cases have passed !!
image

**Comment by akshit0211** [comment]
All the test cases passed. The code covers all the major areas. Good job!

npm run test badge
npm run test badge -- --verbose

**Review by akshit0211 — APPROVED** [review]

**Comment by Abi-Liu** [comment]
Moved to https://github.com/OneCommunityGlobal/HGNRest/pull/984

**Pull request closed without merging**
