### PR TITLE
Demi_fix_duplicate_id_error

### PR DESCRIPTION
**Pull request by this-journey**
# Description
Fixes Phase 2 WBS Bugs line item 3 “Material List” 
Material items and purchase record were not having a unique ID created causing an error in the console.

## Related PRS (if any):
[PR 1813
](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1813)
## Main changes explained:
- Delete code that prevented a unique ID from being made in both purchase records and update records
- Deleted existing records in MongoDB to prevent an error from occurring since the existing records lacked an ID
- Created new records with unique ID's attached

## How to test:

1. git pull
2. check into current branch
3. npm install
4. npm run build && npm start to run this PR locally
5. Clear site data/cache in local storage
6. log in as any user
7. go to http://localhost:3000/bmdashboard/login to confirm your login credentials
8. go to http://localhost:3000/bmdashboard/materials
9. select "View" under "Purchases"
10. Verify that you do not receive a console error for duplicate keys
11. select "View" under "Updates"
12. Verify that you do not receive a console error for duplicate keys

## Screenshots or videos of changes:
Screenshot 2024-01-04 at 1 17 33 PM (2)

## Note:
Use dev branch to test front end functionality.

### CODE REVIEW

**Comment by bajajtushar094** [comment]
Hi @this-journey, I am getting this error when checked out in your branch. Is there anything which I am missing?
Screenshot 2024-01-07 at 14 55 24

**Comment by Cavein254** [comment]
Hi @this-journey, the page display is blank on the `http://localhost:3000/bmdashboard/materials`  when implementing both pr's #686  and #[1813](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1813)
Screenshot from 2024-01-12 13-50-26

**Review by abdel-lall — APPROVED** [review]
LGTM.

**Comment by this-journey** [comment]
@Cavein254 and @bajajtushar094 I was not able to duplicate the error screen you received.  Please make sure that before you switch to this branch you've done "git pull" from the dev branch and then after you switch to this branch you go into the dev tools and under application delete the "persist root" out of local storage.  This step is critical any time you switch into a new branch.  Try it and let me know if it still isn't working.  Thank you!

**Pull request merged**
