### PR TITLE
Xiao F fix caps name bug and inconsistencies with the change name feature

### PR DESCRIPTION
**Pull request by tsunami776**
# Description

CleanShot 2023-09-29 at 15 54 01

## Related PRS (if any):
N/A

## Main changes explained:
- Update file `src/controllers/userProfileController.js` for checking cache if no results from the database

## How to test:
1. Check into current BE branch
2. Make sure do `npm run build` and `npm start` to start the BE
3. Make sure check out FE commit by `git checkout 428bf64be5244d1b18dfb3917196187ea20fe1f5` or any other commits that work on dev branch because user profile is not working on latest commit
4. Start the FE by `npm run start:local `
5. Log in as admin user
6. Go to dashboard→ Other Links→ User Management→ Create a user with all-caps name
7. Go to dashboard→ Other Links→ User Management→ Find the user created→ Go to its profile page → Change to a lower case first or last name or any other name→ Go back to User Management page to check if name changed → Check the user's profile if name changed
8. Find any existing user in User Management and do step 5 to check if name change works properly

## Screenshots or videos of changes:
Before:

https://github.com/OneCommunityGlobal/HGNRest/assets/43768723/9eeea01e-fa1f-487e-bccc-7876aa0067ae

After(create a new user with all-caps then change its name):

https://github.com/OneCommunityGlobal/HGNRest/assets/43768723/dcda284c-8417-47ce-bbaa-2bd598cf130a

After(change existing user name without delay):

https://github.com/OneCommunityGlobal/HGNRest/assets/43768723/e0e753f4-2fbb-46aa-b337-5574e23b4112

### CODE REVIEW

**Review by JeffLi117 — APPROVED** [review]
Changes work as intended. In either the scenario of 1) creating a user with all capitalized letters in the name or 2) an already created user with all capitalized letters, I am able to edit their name (first or last) and see the change take effect.

Creating new user (JEFFTESTCAPS LITESTCAPS):
image
image

Editing said user to have a last name that is not all capitalized letters (Li): 
image

Finding the resulting user after changes have been saved:
image

Finding an already created user (ALREADY CAPITALIZED):
image

Changing said user's last name to be not all capitalized letters (Capitalized):
image

Confirming changes when searching for user after changes are saved:
image

Great job!

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works as intended. There's no error when I did these instructions.

https://github.com/OneCommunityGlobal/HGNRest/assets/49748716/b52bcb5a-591f-475f-a18b-38c5d1503946

**Review by yangfan2001 — APPROVED** [review]
Hi I've read and tested your PR. It worked as described. Great Job!

Create a user with all-caps name
image
all-caps name displayed correctly
image
Change the name to lower case
image
The name displayed correctly in user management page
image
The name displayed correctly in user profile page
image

**Review by Haoj1 — APPROVED** [review]
@tsunami776 Good job! I have tested your pr and it works as intended when I was try to create a full cap user and it could be displayed correctly in the user management. And it displays correctly after change

https://github.com/OneCommunityGlobal/HGNRest/assets/99279909/c9d7f0ab-3f99-4a5d-9731-9e3a3280115f

**Review by wantingxu7 — APPROVED** [review]
Hi, I've tested the pr. The function LGTM. I first change the last then change the first name, the changes can be reflected in the interface.

https://github.com/OneCommunityGlobal/HGNRest/assets/105323719/b730d027-9cb7-4e69-adeb-a04fba2b6d9a

**Review by Bhagyashree444 — APPROVED** [review]
Great work!  Name Changes are correctly updated on usermanagement list and user profile page as well for both existing user and for the newly created user.

Screenshot (162)

Screenshot (163)

**Comment by RheaWu1212** [comment]
Name changed correctly from cap to lowercase, great work!

https://github.com/OneCommunityGlobal/HGNRest/assets/109626741/70558048-0fb0-4836-baff-0a5ddacb3b42

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great!

[screencast-hgnapplication_react_beta.surge.sh-2023.10.06-17_42_54.webm](https://github.com/OneCommunityGlobal/HGNRest/assets/68056104/6956afa6-8165-4d8b-901f-5ba88eb67eee)

**Review by beblicarl — APPROVED** [review]

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR and it works as expected. I tested by creating a new user with all caps and tried to check if the name change from user profile is reflected in user management, and I also checked for existing user as well and the name change was consistent in both user profile and user management page without any delay.

https://github.com/OneCommunityGlobal/HGNRest/assets/78906820/ef126c3b-4c0b-416e-a40a-c1c9613c02f9

**Review by malikjahanzaib — APPROVED** [review]
Hi @tsunami776 , the bugs mentioned in this PR seem to have been fixed. Below is my test recording. Great work!

Test Rec:


https://github.com/OneCommunityGlobal/HGNRest/assets/46221334/5d7d6cb3-c368-473e-bfee-6225ad7b0a3b

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I tested your PR and works as intended. Great work!

https://github.com/OneCommunityGlobal/HGNRest/assets/92185695/eb8f047c-cb51-43a7-8a5d-881ddf75491d

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
