### PR TITLE
Abdel deadline follow up tracking solution

### PR DESCRIPTION
**Pull request by abdel-lall**
# Description
1.	#### $\textcolor{red}{\textsf{(PRIORITY HIGH) Jae:}}$  Create way for me to track people I’ve followed up with about deadlines 

-  On the Tasks tab, I’d like a little box I can click on and off. I’m thinking the best location is to the right of the time numbers below. This is because it is related to those numbers and I want it super easy to scroll the whole tasks list and see who needs a followup or not.
- It should be visible and usable by every class but Volunteers. Any class checking the box will change its appearance for all others that can see it. This is so everyone knows if a person has been followed up with yet.
- It should have mouseover text that says, “This box is used to track follow ups. Clicking it means you’ve checked in with a person that they are on track to meet their deadline.”
- I’d like the box to be Red outline with light pink filler when a person is at 50% of their task deadline, again at 75% of their task deadline, and again when they are at 90% of their task deadline. This is to make it clear that it needs to be checked/the person needs to be followed up with. Once checked, the box should change back to normal but with a check in it. 
- I’d like the box to reset/auto-clear the check within the box when a person reaches 75% and 90%, so the box is ready/needs to be checked again. This is so I can track when I’ve followed up with people and also know when/if my managers are following up with people.
- I’d like an “i” icon for information that explains all of the information above.
- I’d also like mouseover text that will be different for the box at each level 
      **A -**. 0-50%: Check this box once you’ve checked in for the first time with this team member to make sure they are clear on their task.
      **B -**. 0-50%: Check this box once you’ve checked in for the first time with this team member to make sure they are clear on their task.
      **C -**. Your team member’s task should be at least 75% complete! Check this box once you’ve confirmed they are on track to meet their deadline. Request additional time be added to their task if it is needed.
      **D -**. Your team member’s task should be almost complete! Check this box once you’ve confirmed they are on track to meet their deadline. Request additional time be added to their task if it is needed.
image

## Related PRS :

- To test this backend PR you need to checkout the **935** frontend PR.

## Main changes explained:

- Update taskController file Add setFollowUp.
- Update taskRoutes file Add new route for setFollowUp.
- Update task model file Add followedUp

## How to test:

- check into current branch
- do `npm run build`
- do `npm start`
- checkout the **935** frontend PR.

### CODE REVIEW

**Review by cvtqx — APPROVED** [review]
Works as described. Great job! left review in FE PR.

**Comment by rachnapandya** [comment]
Works as intended.

**Review by mahamakhan — APPROVED** [review]
Left a review on the frontend

**Review by xaanders — APPROVED** [review]
Left a review on frontend PR 935. Approved.

**Review by ramyaram2092 — APPROVED** [review]
Checked the front end PR . The back end for deadline follow up  works as intended

**Review by DavidC0126 — APPROVED** [review]
Checked the front end [PR#935](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935), and they work as described. I left review in FE PR.

**Comment by iTvX** [comment]
Works as described. The lag issue is still there but the function is good as described.



neCommunityGlobal/HGNRest/assets/467

91134/ca2b82ec-c707-4b6b-a33b-a383f0393933)

**Comment by zuhang2000** [comment]
Please check my comment on front-end PR #935. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935#pullrequestreview-1553532112

**Review by ThapeloMasasa — COMMENTED** [review]
Works as expected, left a more detailed review on the frontend PR

**Review by ThapeloMasasa — APPROVED** [review]

**Review by winghojackyli — APPROVED** [review]
Everything works as intended. Comment left under the frontend pull request. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935#pullrequestreview-1564063675

**Review by veronicacheng2 — APPROVED** [review]
Hi @abdel-lall, I have tested it together with #935. Comments left there.

**Comment by Shubhu0** [comment]
Checked the PR, works as intended.

**Review by Shiwani99 — DISMISSED** [review]
Hi,
Left comments at frontend PR#935.

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hi @abdel-lall, Left detailed [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935#pullrequestreview-1702717599) on [FE PR 935](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935).

**Review by Shuhua-L — DISMISSED** [review]
Hi @abdel-lall, I ran into issues while loading tasks. More details can be found in the [FE PR review.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935#pullrequestreview-1738030143)

**Review by Changhao3220K — COMMENTED** [review]
left review in the FE

**Comment by palakgosalia** [comment]
Hey, left review in FE PR

**Review by Alforoan — COMMENTED** [review]
I left a comment on fe #935.

**Comment by Haoxiang310** [comment]
I've left my PR review in FE PR #935 and here is the link: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935

**Review by pshereen — DISMISSED** [review]
After switching to the branch, "Abdel_deadline_follow_up_tracking_solution", tasks are not loading both in the admin dashboard and volunteer dashboard.

image


But the tasks are loading in the dashboard if I switch to development branch.

image

**Review by Sophie-lei — CHANGES_REQUESTED** [review]
Add the comment in PR#935, please check for details.

**Comment by galgalinidhi** [comment]
I left a comment on PR#935

**Review by Renanluizssx — COMMENTED** [review]
see my review @abdel-lall please:https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935

**Review by SRamen1999 — DISMISSED** [review]
Left comments at frontend PR#935.

**Review by SaiDeepak-NEU — COMMENTED** [review]
Hello adbel, 

I tested the PR with instructions given in the frontend but the tasks page was loading properly for me. 
Please take a look at the PR 935 for additional details and picture.

**Review by XiaohanMeng — COMMENTED** [review]
Hi, I've left a comment on the FE project for your attention. Please take a moment to review it there.

**Review by brandta-1 — COMMENTED** [review]
# Review
Following up on [front end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935#pullrequestreview-1887057751). The dashboard does not return tasks that are correctly assigned to users in MongoDB. The ```getTasksForTeamsByUser``` controller in ```src/controllers/taskController.js``` caught the following error:

```
MongoError: PlanExecutor error during aggregation :: caused by :: document constructed by $facet is 105092090 bytes, which exceeds the limit of 104857600 bytes
    at MessageStream.messageHandler (C:\Users\umbrahammer2\Documents\HGN\HGNRest\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection.js:299:20)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (C:\Users\umbrahammer2\Documents\HGN\HGNRest\node_modules\mongoose\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (C:\Users\umbrahammer2\Documents\HGN\HGNRest\node_modules\mongoose\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.ondata (internal/streams/readable.js:731:22)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  ok: 0,
  code: 4031700,
  codeName: 'Location4031700',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 17, high_: 1708218542 },
    signature: { hash: [Binary], keyId: [Long] }
  },
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 17, high_: 1708218542 }
}
```

**Comment by skaush21** [comment]
left a comment on frontend [PR 935](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935)

**Review by MALAV1308 — DISMISSED** [review]
Hello , I have tested your PR and task doesn't appear after assigning and I found some mongo error in the console. Please look into it and solve it before merging. Thank you.

**Review by hetvi11110 — CHANGES_REQUESTED** [review]
I tested both frontend and backend PR. please check the comment on frontend PR.

**Review by kylepham — APPROVED** [review]
Backend changes look good and work well. I left some [reviews](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935#pullrequestreview-1980957866) on the frontend PR.

**Comment by MQChen211** [comment]
Hi, I tested this backend with PR#935 and it works as expected.
[https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/935#issuecomment-2048309890](url)

**Pull request merged**
