### PR TITLE
Fix email subject spelling error

### PR DESCRIPTION
**Pull request by aChrisChen**
Update mis-spelling subject in email template.

### CODE REVIEW

**Comment by EvianTan** [comment]
I'm not sure the scope of this PR. I do find many misspelling "Infringment" both in HGNRest and HGNApp , do we want to change all of them in this PR?

**Comment by one-community** [comment]
**PR for: Just realized there is a spelling error in the subject line of the automated blue square emails we send out. Infringment should be Infringement.**

Let's get this small change done and then please add/log a separate bug for changing all the misspellings because missing one in the code could break something pretty important and I don't want to risk that this week when I'm traveling. Testing these is also difficult to do.

**Comment by aChrisChen** [comment]
there are lots of misspelling of the “Infringment” as the variable name in the current code base. I would suggest we create a separate task to refractor all of them instead of changing all the strings in this PR.

**Comment by EvianTan** [comment]
> I also noticed that there are lots of misspelling of the “Infringment” as the variable name in the current code base. I would suggest we create a separate task to refractor all of them instead of changing all the strings in this PR to make sure we are not breaking any of functions.

Sounds cool. Please add a separate bug in the list as refactoring

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
