### PR TITLE
Anny create quick setup function and modal for new team members

### PR DESCRIPTION
**Pull request by astrjc0326**
# Description
image

## Related PRS (if any):
To test this backend PR you need to checkout the [#1673 frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1673).

## Main changes explained:
1. Created title schema
2. Created controller for interacting with database
3. Created route from title

## How to test:
1. check into current branch
4. do `npm install` and `...` to run this PR locally

### CODE REVIEW

**Comment by DragonSlayer2401** [comment]
I tested the related frontend PR [#1673](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1673) please go there for a full review.

**Review by Alforoan — APPROVED** [review]
I left a review on the front end pr.

**Comment by astrjc0326** [comment]
The backend code is updates and now ready to be reviewed again.

**Review by this-journey — CHANGES_REQUESTED** [review]
Please see my full review on pr #1673.

**Review by Alforoan — APPROVED** [review]
I left a comment on fe pr 1673.

**Pull request closed without merging**
