### PR TITLE
Ramakrishna Updating the teamcode validation with numbers

### PR DESCRIPTION
**Pull request by Ramaruva**
- Modified the regex to accept alphanumeric characters and adjusted the length constraints.
- Updated the validation message to reflect the new requirements.

# Description
image

## Related PRS (if any):
To test this backend PR you need to checkout the [#2330](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2330)  frontend PR.
…

## Main changes explained:
Upadated the regex validation for teamcode in team and userprofile mongodb…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. And Follow the instructions in frontend PR

### CODE REVIEW

**Comment by Parth-tech** [comment]
Hey Ram,
I did not get the expected results. I have left a comment on the front end repo. Hope you can help with a video highlighting the steps to follow for reviewing the PR, [frontend-review.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2330#issuecomment-2155618668)

**Review by jinxyou — COMMENTED** [review]
I didn't get the expected test result. So please check it at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2330#pullrequestreview-2105961824

**Comment by akshit0211** [comment]
It works as expected. I left a comment on the front-end PR. [Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2330#pullrequestreview-2105995491)

**Review by akshit0211 — APPROVED** [review]

**Review by TXMO-dev — APPROVED** [review]
Well written and self explanatory, great job on this PR!

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and it works as expected. I have left a comment on the front-end PR [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2330#pullrequestreview-2108559149](url)

**Review by Jingyii800 — APPROVED** [review]
It worked well.  Please refer to my comments for frontend branch. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2330#pullrequestreview-2111934700

**Comment by KaushikMreddy** [comment]
The changes made are working well. I've left a review on the frontend.

**Review by KaushikMreddy — APPROVED** [review]
The changes made are working well. I've left a review on the frontend.

**Review by Parth-tech — APPROVED** [review]
Hi Ram,
Everything looks great and works well too. I have tested the team code with alphabets, special characters and numbers as well as the team code's expected length is supposed to be between 5 to 7 chars. All cases passed. Great Job!

Weekly Summary Page Cases:
Weekly 5 valid
Weekly 7 valid
Weekly extra Chars


Profile page cases:
Profile 5 valid
Profile 6 valid
Profile 7 Valid
Profile extra chars
Profile invalid

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
