### PR TITLE
Abi map locations test suite

### PR DESCRIPTION
**Pull request by Abi-Liu**
# Description
Unit and integration tests for the map locations routes and controller

## Related PRS (if any):
N/A
…

## Main changes explained:
- Unit tests for map locations controller
- Integration tests for map locations router
…

## How to test:
1. check into current branch
2. do `npm install` 
3. run `npm run test mapLocations`
4. Verify all tests pass

## Screenshots or videos of changes:
Screenshot 2024-07-20 at 12 42 58 AM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by jinxyou — APPROVED** [review]
All test cases have passed. Great work!
Screenshot 2024-07-20 194004

**Comment by cecilia-uu** [comment]
截屏2024-07-21 下午3 10 54
Great job!

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-07-21 at 7 24 02 AM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (155)

**Review by Annezhang673 — APPROVED** [review]
All tests passed and worked as expected. No bugs present. 
PR1037

**Comment by mianmiantea2019** [comment]
All tests passed and worked as expected. 

image

**Review by SatyashanthiT — APPROVED** [review]
Reviewed this PR and have tested all the test cases and observed working perfect
image

**Review by DiyaWadhwani — APPROVED** [review]
Hi Abi,
All tests have passed. Attached a screenshot below.
Thank you
Screenshot 2024-08-08 at 4 36 14 AM

**Comment by one-community** [comment]
Thank you all, I'll merge this as soon as conflicts are resolved

**Pull request merged**
