### PR TITLE
Navneeth Make adding a Project save the category selected

### PR DESCRIPTION
**Pull request by navneeeth**
# Description
bug I am working on

## Related PRs (if any):
This backend PR is related to the [#1226 frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1226).

## Main changes explained:
Fixed the issue caused in ```projectController.js``` by updating the parameter name (req.body.category) that was read incorrectly from the request body when adding a project.

## How to test:
1. check into current branch
2. do `npm run build` and `npm start` to run this PR locally
3. Follow the steps in the frontend PR

## Screenshots or videos of changes:

See frontend PR

### CODE REVIEW

**Review by vinaykumarh — DISMISSED** [review]
Reviewed the PR #490 and the result is as expected.
I am able to see the category of the project as set during creation of new project.

Before Changes: 
https://github.com/OneCommunityGlobal/HGNRest/assets/92617693/043da9ff-9f87-4e9a-9363-0deff1d34a15

After Changes:
https://github.com/OneCommunityGlobal/HGNRest/assets/92617693/a9cc2c73-c601-4ac1-a823-99a7a84fa852

Good work!

**Review by ss23046 — APPROVED** [review]
Hi @navneeeth ,
Tested your PR, great job!

https://github.com/OneCommunityGlobal/HGNRest/assets/99052235/36c9ae26-f23a-4dfc-9fe7-c569b05b3b55

**Review by Haoj1 — DISMISSED** [review]
@navneeeth Good job! Category has been successfully saved after creating. 

before change

https://github.com/OneCommunityGlobal/HGNRest/assets/99279909/3f619987-9ecb-44f2-a366-0441bd0b846d

after

https://github.com/OneCommunityGlobal/HGNRest/assets/99279909/3ae88438-778d-48f2-8c45-83bfddbd7ffd

**Review by GaryB93 — DISMISSED** [review]
When creating a new project the category is saved. However, if you change the category to something else and then try changing it back to the original category you will notice that you can't. See video below.

https://github.com/OneCommunityGlobal/HGNRest/assets/108501006/e549fdbe-53e1-44a8-99b3-5c59b2cfa976

**Comment by navneeeth** [comment]
> When creating a new project the category is saved. However, if you change the category to something else and then try changing it back to the original category you will notice that you can't. See video below.
> 
>  Screen.Recording.2023-08-30.at.8.58.18.PM.mov

Hey @GaryB93! Thank you for catching this bug. I request you to re-review the PR now that I have worked on a fix. Since this bug fix was related to the frontend, I have created a new PR for the frontend and updated its link here in the description. So, please test it with the related frontend branch. Many thanks!

**Review by AuroraLovesWhales — APPROVED** [review]

**Review by robertoooc — APPROVED** [review]
Hi @navneeeth, I tested your branch along with the FE branch as well and found no issues. Left comments on FE.

**Review by EdwinLauM — COMMENTED** [review]
Hey @navneeeth! I have tested your changes, however, whenever I create a new project the category doesn't save after the refresh. Changing the categories of the project does work though. I have checked out both the frontend and backend branches

https://github.com/OneCommunityGlobal/HGNRest/assets/42288987/cfb23cbd-f73d-47ea-99a9-c69ddabbcf8c

**Review by veronicacheng2 — APPROVED** [review]
Hi @navneeeth, I have tested together with the FE. Everything works perfectly. Details left on FE.

**Review by winghojackyli — APPROVED** [review]
Hi @navneeeth , I've tested this PR along with the frontend PR #1226. Comments left here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1226#pullrequestreview-1608409182

**Review by GaryB93 — APPROVED** [review]
Tested with frontend PR#1226. When adding a new project the category is now saved and when changing a preexisting project's category you are able to select from the entire menu. Great work!

**Comment by one-community** [comment]
> Hey @navneeeth! I have tested your changes, however, whenever I create a new project the category doesn't save after the refresh. Changing the categories of the project does work though. I have checked out both the frontend and backend branches

Please fix this as part of this PR

**Comment by DavidC0126** [comment]
I tested the PR with FE PR and I left the comment on FE PR. Good job!

**Review by vikrambadhan — APPROVED** [review]
Hi, 
Great work! I tested your PR and it works as intended.

https://github.com/OneCommunityGlobal/HGNRest/assets/85417946/9fd64e55-38cc-4183-a3df-91c3240ad3b4

**Review by tsunami776 — APPROVED** [review]
I tested the PR and it works as intended. Now the new project's category can be changed to another category and then changed back. 

https://github.com/OneCommunityGlobal/HGNRest/assets/43768723/ac14cf35-98ba-4f8f-bb30-65e250a2ebb4

**Comment by Shubhu0** [comment]
Tested this PR, works as intended.

**Review by ChristianHrs — CHANGES_REQUESTED** [review]
Hi @navneeeth ,

I checked the changes and left a comment on the frontend post.

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great job. Left comments at frontend PR#1226.

**Review by ChristianHrs — APPROVED** [review]

**Comment by one-community** [comment]
Thank you everyone, moved to final review!

**Comment by wantingxu7** [comment]
Hi,
tested with FE and comment there

**Comment by Shubhu0** [comment]
Tested PR, and works as intended. Good job!

**Review by EdwinLauM — APPROVED** [review]
Hi @navneeeth, works as expected! Left a more detailed review in the FE PR

**Pull request merged**
