### PR TITLE
Jatin improve report loading time

### PR DESCRIPTION
**Pull request by JatinAgrawal94**
# Description
Screenshot 2024-09-25 at 11 02 20 PM

## Related PRS (if any):
This backend PR is related to the [#2780](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2780) frontend PR.
…

## Main changes explained:
- Updated src/controllers/timeEntryController.js A for updating query.
- Update file src/models/timeentry.js

## How to test:
1. check into current branch
2. do `npm install` and `npm run build` and `npm start` to run this PR locally
3. Go to frontend Repo for further steps.

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/c1454060-8f0e-41df-a8ae-041d133bc1e3

### CODE REVIEW

**Review by shivansh-nathani — APPROVED** [review]
Tested it and things look good, suggested a few cosmetic changes on the FE PR.

**Review by lucy-xfl — APPROVED** [review]
image
Everything works well.

**Comment by javid679** [comment]
logged in as devadmin and tested the PR, everything is looking good. Great Job!

Screenshot (35)

**Review by aaryaneil — APPROVED** [review]
Tested the PR and left a review on the [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2780#pullrequestreview-2364876025)

**Review by hqzhu0913 — COMMENTED** [review]
I review the backend PR and frontend PR. I just have a question that it seems all the data processing is in the front end. May this the reason be the reason it's slow when loading the charts? Would the query to mongoose database use some aggregate functions and provide simpler data to the frontend.

**Review by hqzhu0913 — APPROVED** [review]
Great job! Loading time improves a lot. Thank you. 
Screenshot 2024-10-31 at 2 17 30 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Review by NazaninHashemian — COMMENTED** [review]
Changes in timeEntryController.js:

The updates to the query logic are reasonable and align with expected functionality.
Changes in timeentry.js:

The modifications to the model are appropriate and do not introduce any noticeable regressions.
Testing Instructions:

The provided testing instructions (checking out the branch, installing dependencies, building, and running the server) are clear.
Ensuring functionality on the frontend is specified, which completes the testing process.
Overall Impression:
The updates seem well-executed, and I found no issues in the provided instructions or implementation details. Good job!

**Pull request merged**
