### PR TITLE
Xiaow task system improvement

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
This PR aims to cooperate with frontend to overhaul the task system logic and improve UI. Major changes include but not limited to: overhaul Task component and task controller display logic, improve logic of task import, addition, move, delete and edit,  improve task reducer logic, and make code more organized.

## Related PRS (if any):
To test this backend PR you need to checkout the [#1032](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1032#issue-1816682914) frontend PR.

## Main changes explained:
- Optimize the logic of importTask, postTask, deleteTask controllers 
- Make postTask controller to modify current wbs's modifiedDatetime
- Remove updatedChildrenQty and its corresponding router,  merge its logic in deleteTask controller since those two requests are always sent at the same time in the frontend.
- Rewrite moveTask logic and make child tasks move with their mother
- Add one getWBSId controller and its corresponding router for sending wbs info to frontend for checking if new task is added to database since the page load.
…

## How to test:
1. check into current branch and frontend PR [#1032](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1032#issue-1816682914)
2. do `npm install` `npm run build` and `npm start` to run this PR locally
3. check frontend PR for further instruction

### CODE REVIEW

**Review by joyceiphone — APPROVED** [review]
Tested task assignment related functionality. Everything looks good.

**Review by DavidC0126 — APPROVED** [review]
Tested this PR with frontend [PR#1032](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1032#pullrequestreview-1546367799), and all works as intended.

**Comment by Shreyj14** [comment]
Tested the Frontend PR#1032, worked as intended.

**Review by Shreyj14 — APPROVED** [review]

**Review by shiva2096 — APPROVED** [review]
HI @wang9hu 

I have tested this PR along with the frontend PR. The changes are working as expected.

**Review by Lin1404 — APPROVED** [review]

**Comment by Lin1404** [comment]
Hi @wang9hu 

I have tested the PR with the frontend PR #1032, PR looks great and works perfectly.

**Review by zuhang2000 — APPROVED** [review]
I have tested this PR with the related frontend PR. Working as expected! Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1032#pullrequestreview-1562427155

**Review by ThapeloMasasa — APPROVED** [review]
The code is well written and the functionality works as intended... left more details on frontend PR.. Great Job!!!

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @wang9hu. I have tested your PR and everything is working perfectly as intended. Great work! I left my comment in the frontend PR.

**Pull request merged**
