### PR TITLE
Aaron remove blue square and send email to new users (or short week) who did not complete their hours

### PR DESCRIPTION
**Pull request by AaronPersaud**
# Description
image

- the PR implements all the highlighted functionality (the red was discussed with Jae and it's no longer necessary)

## Related PRS (if any):
N/A

## Main changes explained:
- added new Cronjob that runs at 2AM on Sunday that calls new `removeBlueSquareAndSendEmail` function
- `removeBlueSquareAndSendEmail` finds all users that have started after current date and after the previous Tuesday (short week), and if they have a blue square it is removed and they receive an email notifying them about this
- DOES NOT remove the blue square and email the user if they meet the above criteria AND completed their hours (fringe case)

### Gmail API
Before testing, you need to set up your own test email id to send the mail notification.
This is only for test purposes. Once tested you can revert these changes..

To send an email using the Gmail API with OAuth2 and nodemailer, follow the video below and set it up.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

Fill in the these variable values from the above setup in the .env file of the backend.
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = true

NOTE: if you get a 403 error (<b>"Access blocked: emailapi has not completed the Google verification process"</b>) when you reach the part around 6 minutes, go to [console.cloud.google.com](http://console.cloud.google.com/) -> OAuth Consent Screen and then add your email to "Test users". It's not mentioned in the YouTube video but I saw it in one of the comments.

image

credit to [PR964](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/964), thank you @Aishwaryak01 

You also have to edit the following in the code.

1. Edit my cronjob so that it runs at a specific time for you. The first option in the Cronjob is minutes, so for example if you want the job to run at 12:45, edit it to '45 * * * * *' (`removeBlueSquareJob.js` at line 7).

image

2. Edit the first parameter in the `emailSender` in the `removeBlueSquareAndSendEmail` function to the email you used for the Gmail API setup, so all the sent emails will be sent there instead of to all the found users.

image

After testing, you can undo these changes.

=============================================================================

Before testing the changes, you have to create a few user accounts. You can either do this locally, or on the live dev branch (https://hgnapplication_react_dev.surge.sh). 

1. Login as owner, go to Other Links → User Management → Create New User
2. Create 3 accounts, name them whatever you like.
3. Go to each of their profiles (Volunteering Times tab) and edit their start dates to the following:
  i. Last Monday (for this week it's August 14)
  ii. Last Tuesday (for this week it's August 15)
  iii any day after the current date
4. Give each user a blue square, use whatever description you want.

(The first account is outside of the range of a "short week", the second account is the "short week" case, and the third account is the regular case).

<b> User was deleted, currently making new User please ignore this for now </b>
I also have a user called Aaron BlueSquare2, that will help you test the fringe case. Just be sure this user has at least 1 blue square before running the cronjob. (This user's start date is last Wednesday and they've completed their weekly hours).

=============================================================================

1. check into current branch
2. make sure you've done the above steps (editing the cronjob/emailSender and creating the new users).
3. do `npm run build` and `npm start` to run this PR locally
4. wait until the cronjob runs
5. check the email you set up with the Gmail API and verify the following:
  - you did not receive an email for (i) or Aaron BlueSquare2
  - you received emails for users (ii) and (iii) from above
  - NOTE: you might receive a bunch of other emails, since there will be other test accounts that have been created after last Tuesday whose hours are not completed, which means they also meet the criteria for the email

6. Go back to the dev branch (local or https://hgnapplication_react_dev.surge.sh) and make sure the blue squares are removed for (ii) and (iii) but not removed for (i) and Aaron BlueSquare2

## Note:
Please DM me or comment here with questions so I can clear up any ambiguity, I understand there are a lot of steps to test this PR.

### CODE REVIEW

**Comment by one-community** [comment]
Oh man, I am so excited about this one... it is going to save me a TON of time...

**Review by Shiwani99 — COMMENTED** [review]
Hi,
I tried testing your PR. I did set up everything up everything as per your instruction, but despite setting the time and date in the cron jobs file, I'm still not getting mail for removal blue squares for short week. I first assigned a blue square as you mentioned for short week that is I assigned the test user start date as 24th September 2023 and assigned a blue square for 23rd September 2023. I set up the time in the cron jobs for the current date and the time given below so that a mail will be automatically sent to remove the blue square for the user whose start date is later. The first requirement was mentioned to auto remove the blue square and send a mail, but I'm not getting any mail despite setting the time and date in cron jobs file. I'm attaching screenshots. Please let me know if I'm doing something wrong. I have set up environment variables too.

Screenshot 2023-09-23 at 3 09 02 PM

Screenshot 2023-09-23 at 3 09 56 PM

Screenshot 2023-09-23 at 3 10 53 PM

**Comment by Cloid** [comment]
Hi there.

I tested the first edge case by creating a new account but I can't access the User Management page from the dropdown menu. Tried it via Owner/Account/DevAdmin acct:
image
image
image

I also can't update the start time manually via the volunteer user's profile page as Admin:
image


The dropdown option does appear when I use the latest dev backend branch. Alongside, with the ability to change the start date time Maybe update this branch to have the latest dev changes and it'll probably fix this issue. I followed the Local React setup guide and added the extra vars to the .env file. Let me know if I did something wrong though.

**Review by Cloid — CHANGES_REQUESTED** [review]
See above comment

**Review by malikjahanzaib — APPROVED** [review]
Hi @AaronPersaud, I have tested this PR locally and it seems to work perfectly for the users I created. As for the fringe case that had to be tested using "Aaron BlueSquare2" I couldn't find such user. Rest I am attaching the screenshots below showing initial creation of users and assignment of blue squares for 3 users 'Jahanzaib Cron1', '...Cron2' and '...Cron3'. 
After running the Cron Job, blue squares were removed for the users:
 Cron2 which started on Tuesday last week
 Cron3 who's start date is in the future

 As for the Cron1 which started Monday last week, the blue square persisted.

I couldn't test for the user "Aaron BlueSquare2", which was supposed to be a fringe case, as it didn't exist at the time of my testing. 
Based on the correct working for other users I created, and receiving a confirmation via Email, I am approving this PR for now. If you want me to test again for any fringe case you can re-request the review and I'll be happy to do the testing again.

Great job, I suppose this is going to be of great help for the Admins!!! 
 
 Screenshots:
 
Users Created+Blue Squares Assigned:

Screenshot 2023-10-20 223337


 
Screenshot 2023-10-20 223408

Screenshot 2023-10-20 222126

After running the Cron Job:

Received Blue Square removal emails for users '...Cron2' and '...Cron3' (and a bunch of other users too that met the criteria), but not for the user '...Cron1':

Screenshot 2023-10-20 224038

Verifying in the Dev Database:

Screenshot 2023-10-20 224129

Screenshot 2023-10-20 224142

Screenshot 2023-10-20 224155

**Review by savio-henrique — APPROVED** [review]
Hi @AaronPersaud , nice job on this PR! 

I've tested everything locally as requested, using Gmail API, and it seems to be working for the users I created. I've tested it 2 times, on the first one I inputted the start dates wrongly (this one emailed me for the 3 accounts), and on the other time I tested with the correct start dates.

Searching on my email for the "Aaron BlueSquare2" account, no emails matched the user. I searched in the dev site, the user doesn't exist, so it didn't have any Blue Squares to remove and I wasn't able to test the fringe case. :/

---

# Testing

I've attached below the screenshots from the creation of the 3 accounts and the Blue Squares, before and after the Cron Job.

Those were the correct starting dates: 
* Sávio itest - **09/10** 
* Sávio iitest - **10/10**
* Sávio iiitest - **23/10**

After running the Cron Job, the Blue Squares from the 'Sávio iitest' and 'Sávio iiitest' accounts were removed and the email regarding their removal was received as shown in the screenshots below.

## Screenshots

Code from the Cron Job and emailSender:

bluesquarecode
emailsender

Creation and assignment of the Blue Squares:

itest-before
iitest-before
iiitest-before

---

After the Cron Job was executed, the emails that I've received and the filtering looking for 'Aaron BlueSquare2':

emails
iitest-mail
iiitest-mail
aaronbluesquare

---

The accounts after the Cron Job ran:

itest-after
iitest-after
iiitest-after

---

# Final Thoughts

After testing it for the accounts that I've created, it seems to be working perfectly without any issues, so, for now, I'm approving this PR, if anything changes I could test it again if requested.

(Sorry if my english was bad :/, I would appreciate feedback on this review if it's not a problem :smile:)

Again, congrats on this PR, nice work :+1: !

**Comment by RheaWu1212** [comment]
Hi I'm testing your PR, however I ran into error, please take a look at the pic and let me know if anything I did wrong, thanks!

Screen Shot 2023-10-21 at 21 23 46

**Review by ChirayuRai — COMMENTED** [review]
I tested this on my machine, making sure to follow the video and the instructions listed. However, it seems the cron job doesn't run (I verified this by having the function also print something out when it does run). Any ideas as to why? 

Screenshot 2023-10-21 at 7 37 19 PM

**Comment by AaronPersaud** [comment]
Commenting here to address any issues anyone is facing:

I believe my account for testing the fringe case was deleted, so I'm going to be making a new account for users to test and I will update the steps to test accordingly.

@Shiwani99, I do not believe the Cronjob ran for you. Please note that the cronjob is coded to run on PST, so if you're not on Pacific time, the numbers you set were 3 hours too early. That's why in the PR instructions I suggested it run by the specific minute, since that allows us to ignore time differences.  

@Cloid, please try making a new admin/owner account and see if that fixes your access to User Management. Another workaround I can think of is to use https://hgnapplication_react_dev.surge.sh to create the new users instead of localhost. Only the backend is required to be run locally to test the new Cronjob.

@savio-henrique, thank you for reviewing this PR! You explained everything thoroughly and clearly, and you showed the results at every stage in the workflow of this PR. Well done!

@RheaWu1212, can you expand your terminal for HGNRest? I'm not seeing the output error.

@ChirayuRai, the only thing that comes to mind is you didn't build after editing the Cronjob. Did you run `npm run build` after editing and saving the file with the Cronjob?

**Comment by John-Flavian** [comment]
Everything seems fine to me.

**Review by lacnoskillz — COMMENTED** [review]
Hi @AaronPersaud 
I followed your steps pulled your code ran build but nothing seems to happen
Not sure if im missing something
image

**Comment by AaronPersaud** [comment]
Hi @lacnoskillz, thank you for reviewing the PR!

There's a chance the Cronjob did not run, can you please add some console statements in the Cronjob and then redo the testing to make sure it's running?

**Comment by emunkh404** [comment]
Hi, I PR reviewed today. the Cronjob did not run, there was couple warnings in userHelps.js
image
image
image

**Comment by AaronPersaud** [comment]
Hi @emunkh404, thank you for reviewing the PR.

Can you drop some `console.log` statements in the cronjob file to see if where it stops working and let me know? 

Thank you.

**Comment by Changhao3220K** [comment]
On local environment, I tried to edit the removeBlueSquareAndSendEmail function but it seems that function has been removed from the dev repo. seems like everything about email has been moved to the emailSender.js and its only using the environment variables for verifications.
Tested to create multiple new users and I think they functions normal, but when it comes to different users who share the same email address e.g. for Oauth testing to get email notifications, the page will pop error. I think this err should be better written for users to understand the real issue.
Screenshot 2023-11-15 at 11 57 19 PM
Screenshot 2023-11-15 at 11 59 32 PM

Screenshot 2023-11-15 at 11 40 39 PM
Screenshot 2023-11-15 at 11 41 07 PM
Screenshot 2023-11-15 at 11 43 54 PM
Screenshot 2023-11-15 at 11 49 59 PM

**Comment by AaronPersaud** [comment]
Hi @Changhao3220K, thank you for testing the PR. 

The function `removeBlueSquareAndSendEmail` was created in this PR, and will not be found in the development branch. 

As for your comment about OAuth, I'm not sure if I'm understanding it correctly. Are you saying you're getting an unclear error when multiple users have the same email? I believe users are currently not allowed to make new accounts using existing emails, so that shouldn't be related to this PR. If you're talking about using OAuth to create a new HGN account, I'm not aware of that functionality existing and you can only sign up using an email/password combination. Either way, this PR makes no changes to creating user accounts (creating user accounts is only for testing the different cases), so all those issues are out of the scope of this PR, and you might need to log a new issue the bugs doc. Please let me know if you need more clarification and if I'm misunderstanding anything. Thank you.

**Comment by Changhao3220K** [comment]
> Hi @Changhao3220K, thank you for testing the PR.
> 
> The function `removeBlueSquareAndSendEmail` was created in this PR, and will not be found in the development branch.
> 
> As for your comment about OAuth, I'm not sure if I'm understanding it correctly. Are you saying you're getting an unclear error when multiple users have the same email? I believe users are currently not allowed to make new accounts using existing emails, so that shouldn't be related to this PR. If you're talking about using OAuth to create a new HGN account, I'm not aware of that functionality existing and you can only sign up using an email/password combination. Either way, this PR makes no changes to creating user accounts (creating user accounts is only for testing the different cases), so all those issues are out of the scope of this PR, and you might need to log a new issue the bugs doc. Please let me know if you need more clarification and if I'm misunderstanding anything. Thank you.

Hi @AaronPersaud Thank you very much for reply my review and your patience!
Sorry about my misunderstanding for the code part, This is my first PR review and I am still learning how to do it properly.
One question I do need some clarification is that if I want to add a new function removeBlueSquareAndSendEmail to my local repo, I think I need more details after the first if statement &&. I will also attach a screenshot below, please let me know if I did it correctly. Thank you!
Screenshot 2023-11-16 at 10 12 40 AM

**Comment by ptrpengdev** [comment]
Code conflicts need to be resolved.
image

**Comment by Changhao3220K** [comment]
> Hi @Changhao3220K, thank you for testing the PR.
> 
> The function `removeBlueSquareAndSendEmail` was created in this PR, and will not be found in the development branch.
> 
> As for your comment about OAuth, I'm not sure if I'm understanding it correctly. Are you saying you're getting an unclear error when multiple users have the same email? I believe users are currently not allowed to make new accounts using existing emails, so that shouldn't be related to this PR. If you're talking about using OAuth to create a new HGN account, I'm not aware of that functionality existing and you can only sign up using an email/password combination. Either way, this PR makes no changes to creating user accounts (creating user accounts is only for testing the different cases), so all those issues are out of the scope of this PR, and you might need to log a new issue the bugs doc. Please let me know if you need more clarification and if I'm misunderstanding anything. Thank you.

Hi @AaronPersaud 
I modified the cornjob but did not receive any notification yet, the frontend codebase seems changed this morning so I am not sure if the user I created get updated in the codebase yet.
Screenshot 2023-11-17 at 9 50 26 AM
Screenshot 2023-11-17 at 12 42 50 PM
Screenshot 2023-11-17 at 12 38 46 PM
Screenshot 2023-11-17 at 12 39 31 PM

**Review by ptrpengdev — CHANGES_REQUESTED** [review]
**Environment Setup:**
- Frontend branch: development (latest)
- Backend branch: aaron_new_user_blue_square_send_special_email

**Issues:**
The PR's code is not up to date with the code from the development branch. Users are unable to redirect to the user management page to modify user information, preventing testing.

**Steps to Reproduce:**

- Checkout the backend branch aaron_new_user_blue_square_send_special_email and frontend branch development.
- Log in as Owner/Admin.
- Click on Other Links.
- Click on the User Management button (this should redirect the user to the dashboard page).

I have attached the video for additional clarification. 
0:00 - 0:33 envrioment checkup
0:47 step to reproduce
1:48 shows failed API calls

https://github.com/OneCommunityGlobal/HGNRest/assets/69882989/58461adf-378a-4f56-9f88-5f3c74c55348

**Comment by AaronPersaud** [comment]
@Changhao3220K, you can add some `console.log` statements or use breakpoints in VS Code in the cronjob file to ensure that the cronjob is running `removeBlueSquareJob.js` . Also, make sure you run `npm run build` after editing the file.


@ptrpengdev, thank you for reviewing. I am getting that same error, so you can just create the accounts using the dev site (https://hgnapplication_react_dev.surge.sh/).
 
image

**Review by KavyaAlla — CHANGES_REQUESTED** [review]
Hi @AaronPersaud ,
I have tested this PR locally with the given instructions on 18th Nov saturday
I have created 3 users:
Kavya TNB1 - Start date: 19th Nov Sunday
Kavya TNB2 - Start date: 13th Nov Monday
Kavya TNB3 - Start date: 14th Nov Tuesday
Screenshot 2023-11-18 at 3 24 13 PM

According to the PR, I have to get emails for TNB1, TNB3 but I got emails for all three users.

Screenshot 2023-11-18 at 3 16 31 PM
Screenshot 2023-11-18 at 3 16 44 PM
Screenshot 2023-11-18 at 3 16 56 PM

**Comment by AaronPersaud** [comment]
Hi @kavya151, thank you for reviewing the PR!

My wording may not have been clear in the instructions. When I said last Monday/Tuesday, I meant the Monday/Tuesday before the previous Sunday. This is because the Cronjob will run on Sundays, so we have to set the start date values to days before the current week's Sunday to mock the cronjob on any day other than Sunday.

Since you ran it on Nov. 18 (Saturday), the correct values would be:
Last Monday: Nov. 6
Last Tuesday: Nov. 7
Any day after: Nov. 19 or later (correct value)

Since today is Nov. 19, and it's a new week, the correct values are:
Last Monday: Nov. 13 (correct value)
Last Tuesday: Nov. 14 (correct value)
Any day after Nov. 20 (you need to change this one now)

If you re-test the cronjob with the above values, you should get the expected behaviour. Sorry for any confusion! Please let me know if you need any more clarification.

**Review by ilyaflaks — APPROVED** [review]
@AaronPersaud I reviewed this PR with the following user accounts: 
PR479-remove-blue-square
I gave them all blue squares for fictitious reasons. After the suggested code changes and scheduling an email to be sent out this morning I got the following e-mails (as well as a few others, apologies to those who did not want their blue squares removed):
PR479-remove-blue-square-2
PR479-remove-blue-square-3
No email was addressed to the user Ilya FALX who allegedly started last Monday. I believe that was the intention with this line of code: 
PR479-remove-blue-square-4

Looks like everything is working as described! Good job! 

EDIT: I also noticed some conflicts between the front end and this branch. Because of it, the buttons and links on FE don't work, so I had to create these accounts from the "development" branch of the backend. This must be due to the recent merged changes to the front end on the "development" branch. I don't think this will lead to any problems when your code is merged.

**Pull request closed without merging**
