### PR TITLE
Nathan individual permissions fix

### PR DESCRIPTION
**Pull request by nathanah**
# Description
Permission checks on the back end were not including individual user permissions for some reason, so this added that.

## Related PRS (if any):
None

## Main changes explained:
- Modified hasPermission() params from requestor.role to all of requestor to include requestor.requestorId.
- Updated hasPermission() calls to account for new params
- Removed hasIndividualPermission() calls and removed export

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. login as admin user
4. go to dashboard→ Other Links→ Permission Management→Manage User Permissions
5. Give individual permissions to a different account and Submit at the bottom (I will explain testing for Edit Task)
6. Confirm that changes using new permission stay after a refresh.
a. For Edit Task, click on a task on the dashboard. 
b. Click edit and edit any information
c. Save changes.
d. Refresh
e. Confirm changes stayed

### CODE REVIEW

**Review by LucileTech — APPROVED** [review]
It's working as expected with an owner account Screenshot 2023-09-28 at 17 10 05
Screenshot 2023-09-28 at 17 11 59
Screenshot 2023-09-28 at 17 13 36
Screenshot 2023-09-28 at 17 14 19

Not an admin one which as a front-end bug fixed in this new PR:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1349

**Comment by Jiyuanxia** [comment]
Hi @nathanah , I have reviewed your pull request and tested it. It works as you intended. Well done!

Give my another account edit task permission
Screenshot 2023-09-28 233431

Able to see edit button
Screenshot 2023-09-28 233554

Task after editing
Screenshot 2023-09-28 233619

Just a little issue might not relate to this PR. My volunteer account do not have any permissions but still able to see "Other links" and "Permissions Management"
Screenshot 2023-09-28 233937

Permissions management page. On this page I can assign someone a permission, the message saying I did that successfully but actually I did not. I double checked this account's permissions but as I mentioned, this account do not have any. I think there may be an issue with status display and permission checking.
Screenshot 2023-09-28 233944

Screenshot 2023-09-28 234021

**Review by navneeeth — APPROVED** [review]
Hello, @nathanah! Tested your changes and they work as expected. Good implementation!

Logged in as an Owner account and navigated to `Dashboard-> Other Links-> Permissions Management-> Manage User Permissions`. 

Here, I added the `Edit Task` permission for a Volunteer account and hit Submit:
edit task permission granted

Then, I logged in as the above Volunteer and confirmed that the Edit Task permission works as intended by editing information on a task listed in the Dashboard (also confirming that the 'Edit' button is displayed in the task). The update happens successfully and does not change on refresh.

Testing video:

https://github.com/OneCommunityGlobal/HGNRest/assets/44264834/2cd29573-67d4-48b1-9a34-2797d3fe7e9b

**Review by eduhorta — COMMENTED** [review]
Hey @nathanah!

I did try to check for the individual permissions being added and the change was not reflected on the user.

Here is a video of my testing:

https://github.com/OneCommunityGlobal/HGNRest/assets/105796041/a3a79c9e-6267-433c-a375-b2f845af5240

I did add every permission, log out and log back, hard refresh/empty cache

image
image

Am I missing something?

**Review by Shiwani99 — APPROVED** [review]
Hi,
I tested your PR. It works as expected.


https://github.com/OneCommunityGlobal/HGNRest/assets/78906820/35b6286d-ea89-4674-bf07-4df15311ad60

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this and it works as intended.

https://github.com/OneCommunityGlobal/HGNRest/assets/49748716/026ff95d-2428-4b58-b631-22050b810cac

**Review by EdwinLauM — APPROVED** [review]
Hey @nathanah, I have tested your PR and it works as expected!

https://github.com/OneCommunityGlobal/HGNRest/assets/42288987/92c1b753-0cfe-43e6-ad00-9fadaba9b57b

**Review by Haoj1 — COMMENTED** [review]
@nathanah I have try to give my volunteer account permission to add and create task, but I am unable to see the other link in volunteer account. Do you know how to fix it?

https://github.com/OneCommunityGlobal/HGNRest/assets/99279909/b0962ace-f1c9-4ea5-9c62-e810e2dc804c

**Review by wantingxu7 — APPROVED** [review]
Hi, I've tested by first logging in as owner to give a volunteer permission and it works as intended following the instructions. Good work!

https://github.com/OneCommunityGlobal/HGNRest/assets/105323719/d2354ca9-5894-4599-9dcd-66f347f3d347

**Review by Bhagyashree444 — APPROVED** [review]
Well done!
FE - development branch , BE - current branch
This feature works as expected for the owner's account. However, for admin accounts, when navigating to "Other Links" and selecting "Permission Management," I observed that there was no option to "Manage User Permissions." Nevertheless, I was able to edit existing tasks, and the changes were successfully reflected upon refreshing the page.

Screenshot (169)

Screenshot (171)

Screenshot (173)

**Comment by Shreyj14** [comment]
Hi @nathanah The code is working as intended.

https://github.com/OneCommunityGlobal/HGNRest/assets/118795427/2167e217-c5fa-4b46-850e-247e1054da18

**Review by StrawberryCalpico — APPROVED** [review]
Hi! I just checked your PR, it worked perfectly! This was done in [#1387](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1387#pullrequestreview-1663975568),Great job

**Review by malikjahanzaib — APPROVED** [review]
Hi @nathanah, I have reviewed and approved the changes. Everything works as intended. I was able to assign edit permissions using an owner account and the changes persisted. Also, the volunteer that was given the permission was able to edit the task and the changes persisted after the refresh. Great work!

Test rec:


https://github.com/OneCommunityGlobal/HGNRest/assets/46221334/0ce1df89-6c5f-4019-b7a2-6c9eaf12feca

**Comment by RheaWu1212** [comment]
Hi I have tested your PR and it works as expected!


https://github.com/OneCommunityGlobal/HGNRest/assets/109626741/cc7ca327-9a8f-4066-a044-18ec3ff9fd68

**Review by Cloid — COMMENTED** [review]
Hi there.

I've tested this and gave feedback in [fe #1387](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1387#pullrequestreview-1691317266).

EDIT: Whoops thought this was more connected to FE # 1387. Didn't realize it was its own functionality.

**Pull request merged**
