### PR TITLE
Shereen_Bulk Reusables Update

### PR DESCRIPTION
**Pull request by pshereen**
Added Routing and Controller Function for Bulk Reusables Update

# Description
Router and controller for Update Reusable - Bulk
Implements # (WBS) 10.2.6

## Related PRS (if any):
This backend PR is related to the (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2389) frontend PR.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Follow the testing steps in the related frontend PR

### CODE REVIEW

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and the functionality works fine. Left review on [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2389#pullrequestreview-2143060275)

**Review by nyelmela — APPROVED** [review]
I have tested this successfully
image

**Comment by sahithidhulipala9** [comment]
Reviewed and left comment at Front End PR!

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by jinxyou — APPROVED** [review]
I left a review at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2389#pullrequestreview-2149933701

**Review by pavanswaroopl — CHANGES_REQUESTED** [review]
I have given a comment with my observations on frotend PR, please have a look.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2389#pullrequestreview-2149935277

**Review by HowieMiao — CHANGES_REQUESTED** [review]
Test PR, increment functions and input no longer accepts 'e', seems to be running into problems with POST after submitting. On back-end branch and this front-end 2389 PR branch

image

**Review by HowieMiao — APPROVED** [review]
Client sided back end problems with npm, previous change requests can be ignored. PR is functional

image

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR functionality everything work and left comment on frontend PR.

**Comment by Vigneshwar-Muriki** [comment]
Reviewed and left comment at Frontend PR

**Comment by pshereen** [comment]
> Test PR, increment functions and input no longer accepts 'e', seems to be running into problems with POST after submitting. On back-end branch and this front-end 2389 PR branch
> 
> image

Addressed

**Comment by pshereen** [comment]
> Test PR, increment functions and input no longer accepts 'e', seems to be running into problems with POST after submitting. On back-end branch and this front-end 2389 PR branch
> 
> image

Addressed

**Comment by pshereen** [comment]
> I have given a comment with my observations on frotend PR, please have a look. [OneCommunityGlobal/HighestGoodNetworkApp#2389 (review)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2389#pullrequestreview-2149935277)

Addressed

**Pull request merged**
