### PR TITLE
Edwin - Added 3rd toggle to bio announcement

### PR DESCRIPTION
**Pull request by EdwinLauM**
### Description
- Added a third state for the “Bio Posted/Requested” selection to the Weekly Summary Report Page. It now includes "Posted, "Default", "Requested"
- A toggle switch that can change the status of bio announcement has been modified to toggle between three states instead of 2. 

### Mainly changes explained:
Changed the `bioPosted`property from boolean to string to allow for three different states.  

### How to test:
**Please test with the front end [PR 866](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/866)**
checkout this branch
for the server:
npm run build
npm start
for the front end:
npm run start:local
run the front end and test

### CODE REVIEW

**Review by stevenpaalz — APPROVED** [review]
Confirmed that this and associated front end PR is working as intended.

As admin:
Screenshot 2023-06-02 at 10 47 23 AM

As volunteer:
Screenshot 2023-06-02 at 10 52 36 AM

**Review by NidaZaki — APPROVED** [review]
Changes look good! Approved the FE PR as well!

**Review by nathanah — APPROVED** [review]

**Review by cvtqx — APPROVED** [review]
Works as intended! 

1. Changed the toggle to posted from Admin account in FE:

AdminToggleToPosted

2. The toggle status remains the same in the report:

AdminToggleReflected

3. The toggle status is the same when checked in a volunteer account:

VolunteerToggleRemains

**Review by eduhorta — APPROVED** [review]
Working as intended!
Left a review on the FE PR #866.
Nice job! 👍

**Review by bienzguoa — APPROVED** [review]
Working as intended!
Left a review on the FE PR #866.
Good job! 👍

**Pull request merged**
