### PR TITLE
Raul add owner section to the top

### PR DESCRIPTION
**Pull request by rauleffting**
# Description
(DASHBOARD COMPONENT - PRIORITY LOW) 

> (PRIORITY LOW) Jae: Add to top of app a section that the “Owner” class (only) can edit to post a message to all users of the app like, “Happy Holidays”. (WIP - Raul)
> When not showing a custom message, it should show our horizontal logo. Give me the dimensions I’m allowed and I’ll have our graphics guy create one just for this.
> I’d like the UI for posting the message to have the ability for me to set an expiration date so it’ll automatically return to the logo on that date

## Mainly changes explained:
An owner message section was added to the Header. So now, owner accounts can post messages by image or text on the header for all the volunteers.

## How to test:
1. this PR is related to frontend [PR #698](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/698). You have to use both to test this feature.
2. git checkout raul_add_owner_section_to_the_top
3. npm run build
4. npm run start
5. log in as **OWNER**
6. A pen should be displayed for you:
header

7. click and try to create and delete messages. For image messages, try using this one - which the resolution is made for this resource:
image

8. The pen should only be displayed for owner accounts. The message has to be displayed for everyone.
9. This resource is made only for computers (width higher than 1400px).

### CODE REVIEW

**Review by Lucas-E — APPROVED** [review]
Hey Raul, i also reviewed this PR and it works very well. Great job!
Captura de tela de 2023-03-07 23-03-03

**Review by NyahJ — APPROVED** [review]
Hi @rauleffting,

Great job! The feature appears in front-end is awesome and works as expected, and codes here for backend changes are pretty good, thank you!! 

截屏2023-03-08 下午7 02 56

**Review by crystalsong2021 — APPROVED** [review]
Nice work!

**Comment by PrabhjotSembhi** [comment]
Hey, @rauleffting I can see that message on top but I was not able to log in as Owner. I am not seeing that option
image

I have tried everything multiple times but still cant seeing option to switch role as Owner

**Comment by one-community** [comment]
Thank you everyone, moving this to final review.

**Pull request merged**
