### PR TITLE
Jordy add owner message controller unit tests

### PR DESCRIPTION
**Pull request by j-corp-25**
# Description

Unit tests for ownerMessageController

## Related PRS (if any):
N/A

## Main changes explained:

- unit tests for `getOwnerMessage`
- unit tests for `updateOwnerMessage`
- unit tests for `deleteOwnerMessage`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run `npm run test owner`

**If  you want a detailed description you can run `npm run test owner -- --verbose`**

## Screenshots

ownerMessageControllerComplete

## Note:

N/A

### CODE REVIEW

**Review by Ramaruva — APPROVED** [review]
test cases are working fine 
image
 but when I am trying to run npm run owner as stated I am getting error 
image
 it is only working when I am running this command npm run test owner -- --verbose so can you please this

**Review by Infinite-Turkey — APPROVED** [review]
image
npm run ower failed while npm run test owner -- --verbose worked.

**Review by MinSun0814 — APPROVED** [review]
image
All tests passed.

**Review by cecilia-uu — APPROVED** [review]
It works well with 'npm run test owner -- --verbose', but has error with 'npm run owner'.
截屏2024-05-25 上午11 53 41

**Review by Sandhya1236 — APPROVED** [review]
I checked out the current branch and ran npm install followed by attempting to run npm run owner, which failed. Subsequently, I executed npm run test owner -- --verbose for a detailed description, and this command executed successfully. All tests passed as expected, confirming that the changes introduced in the PR are functioning correctly despite the initial command failure.
image

**Comment by deepthikannan** [comment]
image

All the test cases passed.

**Review by deepthikannan — APPROVED** [review]
image
All test cases passed

**Comment by j-corp-25** [comment]
> image
> 
> npm run ower failed while npm run test owner -- --verbose worked.

This is fixed now,thank you for letting me know

**Review by Parth-tech — APPROVED** [review]
Hey Jordy,
Good job done. Everything look good.
Screenshot 2024-05-25 at 12 04 35 AM

**Comment by KaushikMreddy** [comment]
Hi, 
All your test cases have passed
image

**Review by jennZhang93 — APPROVED** [review]
All tests passed. Good work!
Screenshot 2024-05-25 at 9 10 07 PM

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-05-25 at 8 51 44 PM

**Review by peter6866 — APPROVED** [review]
All tests passed as expected.
image

**Review by Kavil-Jain-514 — APPROVED** [review]
The code looks good, and all the test cases have passed.
Good work.
image

**Comment by ZhangPeizhou** [comment]
Passed all tests
PR#959

**Review by Wenboooooo — APPROVED** [review]
All 9 tests have passed. Given the test contents, different response statuses have been tested(404, 200, 403, 201...) It looks good to me.

**Review by jinxyou — APPROVED** [review]
All test cases have passed. Nice work!
Screenshot 2024-06-01 210230
Screenshot 2024-06-01 210310

**Comment by akshit0211** [comment]
Hi, all the tests passed. Good work!

All tests passed

**Review by CloudyZ524 — APPROVED** [review]
Hi Jordy, 
All unit test cases in this pull request passed! 
Screenshot 2024-06-06 at 12 15 17

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Comment by sahithidhulipala9** [comment]
All test cases passed!
PR 959

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (71)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
