### PR TITLE
Yongjian - Update message for inactive user account after login

### PR DESCRIPTION
**Pull request by ypan710**
# Description
Screen Shot 2023-07-07 at 11 55 04 AM

## Main changes explained:
Display the message "Sorry, this account is no longer active. If you feel this is in error, please contact your Manager and/or Administrator." if the user exists in the database but his or her profile is not active.

## How to test:
1. check into current branch from the backend
2. do `npm run build` and `npm start` from the backend
3. check into development branch from the frontend
4. do `npm run start:local` to run the frontend
5. log in as admin user
6. go to dashboard→ User Management -> search for a non-admin role of under your account -> change "Active" status to "Inactive" by clicking on the green dot
7. log out of your admin account
8. attempt to login with the non-admin role with status already set to "Inactive" from step 6
9. verify that the message "Sorry, this account is no longer active. If you feel this is in error, please contact your Manager and/or Administrator." is displayed after clicking on submit button after entering credentials

## Screenshots
Screen Shot 2023-07-07 at 11 49 27 AM

Screen Shot 2023-07-07 at 11 47 18 AM

Screen Shot 2023-07-07 at 11 47 25 AM

### CODE REVIEW

**Review by HectorAgudelo — APPROVED** [review]
The changes to the code perform as expected. nice!
PR#438

2-PR#438

**Review by AaronPersaud — APPROVED** [review]
Everything looks good! 

<b> Changed user to inactive </b>

438_inactive_user

<b>Inactive message</b>

438_inactive_message

- user gets inactive user message instead of invalid email/password

I have approved the PR.

**Comment by luisarevalo21** [comment]
Hello [ypan710](https://github.com/ypan710), 
I have reviewed your code and works as intended great job! 

However, I did receive one error when attempting to login as both an admin and a volunteer. See screenshot.

### Error Received
- I get "Cannot set headers after are sent to the client" on the the backend server. 


Screenshot 2023-07-07 at 8 06 53 PM

Screenshot 2023-07-07 at 8 07 05 PM

Screenshot 2023-07-07 at 8 07 24 PM
Screenshot 2023-07-07 at 8 09 10 PM
Screenshot 2023-07-07 at 8 09 29 PM
Screenshot 2023-07-07 at 8 09 36 PM

**Review by siddharthmohite — APPROVED** [review]
This works as expected. Displays the message if user is inactive.
Screenshot 2023-07-07 at 11 05 17 PM
Screenshot 2023-07-07 at 11 03 11 PM

**Review by igorrochadasilva — APPROVED** [review]
Hello @ypan710 !
Great work = D

The Pr's works as intended.


Inactive user on dashboard user manager
inactive-user

If I try to access with the user, I receive the message.
message-error

The code looks well 🚀

**Comment by beblicarl** [comment]
This functionality works as intended. However, we have some errors in the backend console log.

### SCREENSHOT

issue #438

### ERROR MESSAGE

error-438

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
> This functionality works as intended. However, we have some errors in the backend console log.

Please request a change rather than approve something like this.

**Review by tdkent — CHANGES_REQUESTED** [review]
Local testing of this branch confirms

- the updated error message is displayed to a user attempting to login with an "inactive" account.
- the error message is displayed regardless of the value entered in the **Password** input (unless no value is entered, in which case a validation error is displayed).
- an error with code 403 is returned from the backend and logged to the frontend console.

438-frontend-error-display

**Errors**
The following error is logged to the backend console each time a login request for an inactive user is sent: `Cannot set headers after they are sent to the client`

- the error does not occur when invoking the "Invalid password" error for an active user in the same `if/else` block.

438-backend-error

Testing Video:

https://github.com/OneCommunityGlobal/HGNRest/assets/98129080/c922d673-252d-416f-9131-4db3074c1608

**Review by tdkent — APPROVED** [review]
Confirmed that the `Cannot set headers after they are sent to the client` error has been fixed. Nice job!

**Review by bienzguoa — APPROVED** [review]
It works perfect! The code is clear and helps understand.
Screenshot 2023-07-15 at 2 58 57 AM
Screenshot 2023-07-15 at 2 59 19 AM

**Review by iTvX — APPROVED** [review]
I have reviewed your code and test it, it looks good.


https://github.com/OneCommunityGlobal/HGNRest/assets/46791134/b430ea06-c2c6-4ae0-930d-2c1fee4f1922

**Review by scoopstroop92 — APPROVED** [review]
Hello @ypan710 the functionality works as expected. 

https://github.com/OneCommunityGlobal/HGNRest/assets/89441435/220a4f0e-9db0-4696-9af8-f1d906bb2fc1

No errors on the console as well .
Approving the PR on the same note

**Comment by one-community** [comment]
Thank you all, this one is low risk, merged! Thanks for all your excellent reviews!

**Pull request merged**
