### PR TITLE
Papia creates suggestion icon

### PR DESCRIPTION
**Pull request by papiasharmin**
# Description
(PRIORITY HIGH) Jae: Add “Suggestions” Icon to Dashboard icons section
It should function just like the Report App Bug icon (see below) but have the option to be submitted anonymously. 
Should have a dropdown that includes these options:
Suggestion Category: 
To identify and remedy poor client and/or user service experiences
To identify bright spots and enhance positive service experiences
To make fundamental changes to our programs and/or operations
To inform the development of new programs/projects
To identify where we are less inclusive or equitable across demographic groups
To strengthen relationships with the people we serve
To understand people's needs and how we can help them achieve their goals
Other
Would you like a followup/reply regarding this feedback? 
Should include an edit button for an Owner to add to the above “Suggestion Category:” dropdown
Should include an edit button for an Owner to add an additional information collection field if needed

## Related PRS (if any):
To test this backend PR you need to checkout the #998 frontend PR.

## Main changes explained:
created a json data file for suggestion modal data, added get and post function for  adding value to suggestion data file and fetching the data from frontend, added create suggestion mail body function and send suggestion email function

## How to test:
1. check into current branch in backend and frontend
2. follow  this link https://docs.google.com/document/d/1j92U7Vr14gQLehr1e_gkMdqWcOA37WGxNLv9yTa96CY/edit and Aishwarya Kalkundrikar's comment on how to send email
3. do 'npm run build' and 'npm start' to run this PR locally
4. rest, follow frontend PR

## Note:
I will suggest go to dashboardController.js-> sendMakeSuggestion function -> emailSender -> change the email address from oneCommunity to your gmail. So that you can easily verify that email successfully send.

### CODE REVIEW

**Comment by beblicarl** [comment]
I followed the steps and this helps in setting up the email. It works as intended

**Review by beblicarl — APPROVED** [review]

**Comment by luisarevalo21** [comment]
Hello @papiasharmin,

Do you mind providing so more details on how to test this PR?
As I attempted to run your application but was unsuccessful in setting up the email portion. 
I tested your frontend portion which worked great, I was able to create a suggestion and add more options as well.

However, when running the backend I got a bit confused as the documentation was a bit complex and had a lot of boiler point and was unsure which steps were needed. Any feedback would be great. 

The main issue I have is what exactly do I need to setup on the backend. I saw your note on changing the email to my email in the emailSender function inside of dashboardController, however, I didn't get an email. So, I'm aware I am missing some steps. 

Thanks

**Comment by papiasharmin** [comment]
> Hello @papiasharmin,
> 
> Do you mind providing so more details on how to test this PR? As I attempted to run your application but was unsuccessful in setting up the email portion. I tested your frontend portion which worked great, I was able to create a suggestion and add more options as well.
> 
> However, when running the backend I got a bit confused as the documentation was a bit complex and had a lot of boiler point and was unsure which steps were needed. Any feedback would be great.
> 
> The main issue I have is what exactly do I need to setup on the backend. I saw your note on changing the email to my email in the emailSender function inside of dashboardController, however, I didn't get an email. So, I'm aware I am missing some steps.
> 
> Thanks

Hello @luisarevalo21, Ikonw the documentation is not clear, that is way I said to follow the comment In the documentation, by Ashwarya kalkundrika at the right, where she has given the guidance briefly, just watch the youtube video, of how to send test email using Oauth 2 carefully. Get the values for the evironmental variables, and add them in the .env file. I hope you will be able to do that, if you are still confuse, please let me know.

**Review by xaanders — APPROVED** [review]
Working well. Approved as well as PR 998 Frontend

**Review by scoopstroop92 — APPROVED** [review]
Tested both the front end (PR #998) and  the back end.  Functionality works as expected. Nice work 

https://github.com/OneCommunityGlobal/HGNRest/assets/89441435/4f4ff29d-f334-453d-a748-a76666df0571

**Comment by luisarevalo21** [comment]
> > Hello @papiasharmin,
> > Do you mind providing so more details on how to test this PR? As I attempted to run your application but was unsuccessful in setting up the email portion. I tested your frontend portion which worked great, I was able to create a suggestion and add more options as well.
> > However, when running the backend I got a bit confused as the documentation was a bit complex and had a lot of boiler point and was unsure which steps were needed. Any feedback would be great.
> > The main issue I have is what exactly do I need to setup on the backend. I saw your note on changing the email to my email in the emailSender function inside of dashboardController, however, I didn't get an email. So, I'm aware I am missing some steps.
> > Thanks
> 
> Hello @luisarevalo21, Ikonw the documentation is not clear, that is way I said to follow the comment In the documentation, by Ashwarya kalkundrika at the right, where she has given the guidance briefly, just watch the youtube video, of how to send test email using Oauth 2 carefully. Get the values for the evironmental variables, and add them in the .env file. I hope you will be able to do that, if you are still confuse, please let me know.

Hello @papiasharmin I successfully got the values for the .env file, however, after getting them I was still unsuccessful in making the backend work as intended.

I was able to follow the steps in the google doc on Implement a Feature Related to Emailsender 

So i can see the effect. i modified the userprofile jobs file like so. 
Screenshot 2023-07-14 at 10 40 12 PM


However, for emailsender file i was confused on what i needed to modify 
on the dashboardcontroller i adjusted the sendMakesuggestion like it shows in your note 
Screenshot 2023-07-14 at 10 41 43 PM


Any feedback?

**Review by iTvX — APPROVED** [review]
I followed all the steps and tested from the front end and backend, and all is good now.

**Review by cvtqx — APPROVED** [review]
Tested the FE and BE of this PR and it works as described. I received the email with a new suggestion. Great job!

Email sent

**Review by winghojackyli — APPROVED** [review]
This PR works great with the frontend PR #998 which I approved. New suggestion email was successfully configured and sent.

**Review by DavidC0126 — APPROVED** [review]
I tested the FE and BE of this PR and it works as intended. I received the email with a new suggestion. 

https://github.com/OneCommunityGlobal/HGNRest/assets/74082492/40e02c1a-2954-46ca-9f96-f007f68e646d

Screenshot 2023-08-03 at 6 14 54 PM

**Comment by veronicacheng2** [comment]
Hi @papiasharmin, I tried clicking the suggestion icon but there was nothing popped up. Please advise if I have missed anything. Thank you!

image

**Pull request merged**
