### PR TITLE
Ajay- fix person name search on Project Page

### PR DESCRIPTION
**Pull request by AJAYINAVOLU**
# Description
This PR adds a backend endpoint that provides autocomplete suggestions for person names when entered. It returns the first name, last name, and ID from the database.
Fixes # (bug list priority medium 47)

## Related PRS (if any):
To test this backend PR you need to checkout the #[2676](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2676) frontend PR.
…

## Main changes explained:
- Update userProfileController.js to add the logic for handling autocomplete functionality, retrieving first name, last name, and ID from the database.
- Update userProfileRouter.js to define the route for the new autocomplete endpoint, linking it to the controller. 
…

## How to test:
1. Check into the current branch
2. Do `npm install` , `npm run build` and `npm start` to run this PR locally
3. Open Postman to access to the endpoint
4. First create a POST request to `http://localhost:4500/api/login` using the owner credentials in the body to get the token.
5.  token
6. Copy the token and create a new GET request `http://localhost:4500/api/userProfile/autocomplete/name` replacing the name with the text you want to search along with the token in the authorization
7. get_request
8. The request will return the user's suggested First Name, Last Name, and ID.

### CODE REVIEW

**Review by ArtemisNyx3 — CHANGES_REQUESTED** [review]

**Review by crystallow1168 — APPROVED** [review]
Hi @AJAYINAVOLU,

Your changes is working as expected 👍🏻

image
✅ Results limited to 10, when searching using "chr"

**Review by manikittu810 — APPROVED** [review]
Hello @AJAYINAVOLU 
Everything is working as expected.
Screenshot 2024-09-18 at 8 01 46 PM
Thank you.

**Review by ArtemisNyx3 — APPROVED** [review]
image
Clean readable code. Good job 👍🏽

**Review by Lexie5212 — APPROVED** [review]
I tested the PR. The request is working as expected!
Screenshot 2024-09-19 at 21 39 06

**Review by RishithaMamidala — APPROVED** [review]
@AJAYINAVOLU 
Backend endpoint that provides autocomplete suggestions for person names when entered. It correctly returns the first name, last name, and ID from the database.
PR 1101

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected. left a review on [front-end](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2676#pullrequestreview-2332374027)

**Review by neeharikakoniki — CHANGES_REQUESTED** [review]
Reviewed at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2676#pullrequestreview-2334870690

**Pull request merged**
