### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by ramyaram2092**
Taking a look at the recent reviews. Kindly do not review the PR unless you see a different kind of bug to report

# Description
- A “Limit See-All” option for teams 

-  Other Links ->Teams

- When this option is turned on for a team member,  the team member  shouldn't  be able to see  other members of the team in their dashboard 

- The member however should be able to see team members of other teams  they are part of 

## Related PRS (if any):
This backend PR is related to the [1905](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905) frontend PR.
To test this backend PR you need to checkout the [1905](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905) frontend PR.

## Main changes explained:

- Added  a "visible" attribute to Member Object in Teams document and set it to true by default.
- Added a new route to updating the team member visibility. 
- Add  a  function  called  "updateTeamVisibility "in teams Controller   to process the newly selected visibility of the team member

## How to test:
1. check into current branch
2. run node src/utilities/addMembersToTeams.js so that "visible" attribute gets added to all existing team members
_(This is expected to take time. This step is not needed if you are testing a new team with new team members)_
4. run `npm install ` followed by `npm run build start`  and  `npm start ` to run this PR locally
5.  Now follow the steps mentioned in the front end PR

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/89441435/887ed506-2ce6-443d-beb4-645abc471335

## Note:
- Kindly mention any  bugs , errors you see in the console. 
- Try breaking the functionality , any suggestion is helpful

### CODE REVIEW

**Review by SaiDeepak-NEU — COMMENTED** [review]
Checked into both the frontend and backend branches required to test this feature.

Everything worked fine except one issue which I noticed regarding the status of the toggle which I mentioned in the frontend PR 1905. please take a look

**Review by Sophie-lei — COMMENTED** [review]
Hey, I tested this PR and left a comment in PR#1905. Please view for details.

**Review by KevHnh — COMMENTED** [review]
Hi Ramya, I reviewed the correlated  frontend PR and it works as expected except for one issue. The toggle gets triggered upon opening the modal. See my comments in the Frontend PR for more information. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905

**Review by Pandani07 — CHANGES_REQUESTED** [review]
Hello, I've reviewed this and left comments on the frontend's PR. Everything works except the toggle being off when I haven't set it.

**Review by Renanluizssx — COMMENTED** [review]
See my review @ramyaram2092 in PR#1905: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905#pullrequestreview-1860724050

**Comment by galgalinidhi** [comment]
Hi @ramyaram2092, see my comments for https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905.

**Review by 666saofeng — COMMENTED** [review]
See my review on front end PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905

**Comment by TareqMia** [comment]
Hello, I have left a comment on associated PR#1905. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905

**Review by SRamen1999 — COMMENTED** [review]
I Checked into both the frontend and backend branches required to test this feature.
Everything worked fine except for one bug which I mentioned in the frontend PR 1905. please take a look.

[https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905#pullrequestreview-1871202481](url)

**Comment by Weiyao-Li** [comment]
I have tried multiple times and waited for over 20 minutes. Still cannot receive "Done" from it.

image

**Review by brandta-1 — CHANGES_REQUESTED** [review]
# Review
See [1905 review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905#pullrequestreview-1899169850)

**Review by XiaohanMeng — COMMENTED** [review]
Hi, I left my comment on FE project:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905#pullrequestreview-1904919359

**Review by hetvi11110 — CHANGES_REQUESTED** [review]
I tried to test this PR as mentioned here, but I am also facing the same deprecated error, and all the team members got removed from the database. Here's the screenshot for reference.

https://github.com/OneCommunityGlobal/HGNRest/assets/13557067/42814e11-d1b4-45a6-8ec1-3ec8468c47ad

Screenshot 2024-03-15 170015
PR 731

**Comment by ramyaram2092** [comment]
@hetvi11110  Could you elaborate on the deprecated error ? If you are referring to the console message ,  adding the visibile attribute does take time ! its expected to take time. 
Also I am not clear as to where and why team members are getting deleted ? if you try to open a team where there is no team members added its expected to be empty

**Comment by hetvi11110** [comment]
> @hetvi11110 Could you elaborate on the deprecated error ? If you are referring to the console message , adding the visibile attribute does take time ! its expected to take time. Also I am not clear as to where and why team members are getting deleted ? if you try to open a team where there is no team members added its expected to be empty

Hello @ramyaram2092 , I encountered a deprecated error while running the addMembersToTeams.js file. The specific error message is: DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead. Additionally, before executing this file, I verified that members were indeed added. I've attached a reference video for clarity. I waited for the process to complete for around 15-20 minutes. I thought it might be stuck in a never-ending loop.

https://github.com/OneCommunityGlobal/HGNRest/assets/13557067/76e1b79f-9e3b-4c9c-a3c7-9d7146724ee4

**Comment by ramyaram2092** [comment]
@hetvi11110   I see that you are checking in the UI while the db is getting updated . Could you confirm if you are seeing the same behavior in the UI  after the db update process.

**Comment by SanketKaware** [comment]
I have reviewed both frontend and backend PRs and requested some changes. Please take a look -
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905#pullrequestreview-1940849161

**Review by hetvi11110 — APPROVED** [review]
Hello @ramyaram2092 , I've checked the backend code, and it's working fine on my system. Thank you for your guidance.

**Comment by anandsesha** [comment]
Hi Ramya, 
- Checked out the current branch
- Skipped running the node src/utilities/addMembersToTeams.js script due to extended runtime (over 30 mins).
- Started the server locally for both backend and frontend.

Encountered an error in the browser console, preventing the login functionality from appearing. 
PR 731

Backend build displayed an error, as below:
Screenshot (623)

Please confirm if my testing procedure is correct.

**Comment by Gayathr-2012** [comment]
Hello,

I tested the current branch and added two teams along with their members. In team_a, I toggled it off. However, when I opened the team members section, the toggle switched off and then on automatically. After visiting the profile of a user from team_a, I was able to see members from team B.

image
image
image

**Review by sameersdeshpande — COMMENTED** [review]
See my review on front end PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1905

**Pull request merged**
