### PR TITLE
Wanting UPDATED make 5 letter codes editable only by admin&owner

### PR DESCRIPTION
**Pull request by wantingxu7**
# Description
截屏2023-11-03 上午11 16 18

## Related PRS (if any):
FE #1485

## Main changes explained:
update userProfileController.js
…

## How to test:
1. check into current branch and FE #1485
2. do `npm run build` and `npm start` to run this PR locally

## Screenshots or videos of changes:
see FE #1485

## Note:
see FE #1485

### CODE REVIEW

**Review by lichanghaogit — APPROVED** [review]
Comment left in the FE

**Comment by ptrpengdev** [comment]
Tested. The code worked as expected. Commented on [FE PR 1485](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485)

**Review by AriaYu927 — APPROVED** [review]
Tested this PR, left a comment on frontend PR.

**Review by Shuhua-L — APPROVED** [review]
I have reviewed and left a comment on the FE [PR 1485](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485#pullrequestreview-1785326303)

**Review by Alforoan — APPROVED** [review]
I left a comment on fe pr #1485.

**Pull request merged**
