### PR TITLE
Add new field "Start Date" to Create New User modal

### PR DESCRIPTION
**Pull request by AaronPersaud**
# Description
See [PR1126](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1126)

## Related PRS (if any):
To test this backend PR you need to checkout [PR1126](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1126) in the frontend.

## Main changes explained:
- createdDate field is now set from value in front-end 
- createdDate is defaulted to the next day
- added new field `isFirstTimelog` to the userProfile model to determine the user's first timelog (boolean set to true)

## How to test:
1. check into current branch and front branch with the same name
2. do `npm run build` and `npm start` to run this PR locally
3. follow steps in the front-end

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Hi @AaronPersaud , I've tested this PR with the frontend PR #1126. Approval with comment left here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1126#pullrequestreview-1579326995

**Review by navneeeth — APPROVED** [review]
Hey @AaronPersaud!  The PR works as expected and I have approved & commented on its [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1126). Good implementation!

**Review by yunshan111 — APPROVED** [review]
The PR works as expected, I attached the testing record on your frontend PR.

**Comment by DavidC0126** [comment]
Hi, I left the review on frontend PR, nice work!

**Review by jerryren527 — APPROVED** [review]
Hello! [I left a review on FE PR 1126](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1126#pullrequestreview-1581470837). Great job!

**Review by yaow62023 — APPROVED** [review]
I have test your PR at frontend PR#1126, all the new features work as intended.

**Review by yurisokolovicz — APPROVED** [review]
Dear @AaronPersaud 

This pull request was reviewed by me on the front end, and the comments are available there.

**Comment by beblicarl** [comment]
I have reviewed the frontend of this PR and everything works great

**Review by beblicarl — APPROVED** [review]

**Review by Haoj1 — APPROVED** [review]
@AaronPersaud I commented in #1126, good job!

**Pull request merged**
