### PR TITLE
Jordy add force pwd controller unit tests

### PR DESCRIPTION
**Pull request by j-corp-25**
# Description

Unit tests for `forcePwdcontroller`

## Related PRS (if any):
N/A

## Main changes explained:

- unit tests for `forcePwd`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run `npm run test forcePwd `

**If  you want a detailed description you can run `npm run test forcePwd -- --verbose `**

**Check if all 4 test cases are passing**

## Screenshots

Screenshot 2024-05-04 at 7 41 25 PM

## Note:

N/A

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
All 4 test cases passed! Nice work!

**Review by Ramaruva — APPROVED** [review]
Hi I have reviewed the changes in my local env and all test cases are passed 
image

**Review by nathcarnevalli — APPROVED** [review]
I analyzed forcePwdController.js and its test cases. The test code is very well implemented and consistent with the controller. I ran the tests and they all passed. Great job :)

Screenshot 2024-05-08 183538

**Review by KaushikMreddy — COMMENTED** [review]
Hi, I've tested and reviewed the code added. All test cases have passed. Code is simple to follow and run. Good work!

image

**Review by gowthamdongari — APPROVED** [review]
All test cases working fine
image

**Review by jayyy-s — APPROVED** [review]
All test cases passed. Reviewing the code, the test cases are consistent with the implementation of forcePwdController.js so looks good to me.
test cases passed

**Review by MinSun0814 — APPROVED** [review]
image

**Review by Parth-tech — APPROVED** [review]
Hi Jordy,
Good job all test cases passed.
4 Tests Passed

**Review by Abi-Liu — APPROVED** [review]
Looks good! Good job testing the nested promise chaining.

Screenshot 2024-05-17 at 7 46 14 PM

**Review by Wenboooooo — APPROVED** [review]
image
Looks good to me, all cases have passed

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-05-18 at 5 48 15 PM

**Review by Sandhya1236 — APPROVED** [review]
I reviewed forcePwdController.js and its test cases. The test code is well-implemented and consistent with the controller. I ran the tests, and they all passed. Excellent work!

image

**Review by Infinite-Turkey — APPROVED** [review]
All 4 tests went through and time was lower than estimated.
{7C08FDB4-1A62-45b0-A7DE-BE7856E75EE1}

**Review by deepthikannan — APPROVED** [review]
image
All tests passed.

**Review by peter6866 — APPROVED** [review]
All tests passed as expected.
image

**Review by dikshitakejriwal — APPROVED** [review]
Hi, I reviewed all the test cases and they pass successfully. Good Work!
Screenshot 2024-05-31 at 12 08 21 PM

**Review by jinxyou — APPROVED** [review]
All test cases have passed! Good work.
Screenshot 2024-06-01 211302

**Review by Kavil-Jain-514 — APPROVED** [review]
All test cases have passed!

image

image

**Comment by akshit0211** [comment]
All test cases passed as expected. Good work!

All test cases passed

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR  and all the test cases have passed.
Screenshot (87)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
