### PR TITLE
Eduardo Add `.nvmrc` file. Node v14.

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
In this pull request, we're introducing a valuable addition to our project - the `.nvmrc` file. This file is designed to streamline the process of managing Node.js versions, ensuring that collaborators and contributors use the appropriate version when working on the project. 

## Related PRS :
[Front-end PR.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1536)

## Main changes explained:
Do you use `nvm`? 
Then you can run `nvm install` or `nvm i` in the project folder to install and use the most appropriate version of Node.

Added .nvmrc file: 
This file specifies the required Node.js version for the project. 

## How to test:

1. check into current branch
2. do `nvm i` and `npm i` to run this PR locally
3. run `npm run dev`
4. log as any user
5. verify if the app is working properly
***

## Alternative testing

1. Access the [branch URL](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/tree/Eduardo_add_.nvmrc_file).
2. Click on Code -> Create Codespace

image

3. Wait for the virtual environment to load

image

4. Run the command

image

## Video of change:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/e29644e9-3548-4a35-837e-d3f722cf894d

## Note:
If you already have the appropriate version of Node installed in your environment, running the command will perform the checkout.

### CODE REVIEW

**Review by tdkent — APPROVED** [review]
Followed instructions, running `nvm i` set the node version to v14.21.3. App runs correctly.

**Review by KurtisIvey — APPROVED** [review]
Thought my computer was going to undergo a catastrophic error there for a bit while nvm i was running lol. Have tested it and found it to perform exactly as intended. Really did simplify the process for mac users.


What I did:
   Delete my old version of node that I used with HGN (v14.17.6)
   confirm deletion with nvm ls
   Then run nvm i (takes a bit of time to install, so don't panic)
   Afterwards, confirm installation via "nvm ls". You should see the node version installed
   
   
Screenshot 2023-11-17 at 10 20 29 AM

**Review by sahilpatel18 — APPROVED** [review]
After testing, I found that everything works exactly as intended. Great work!

**Comment by palakgosalia** [comment]
Hey, I tested your PR and I was able to change the theme to dark mode. I also tested out different tabs like User Management and Teams and everything works as expected. Good work


https://github.com/OneCommunityGlobal/HGNRest/assets/104417272/a3baf5e0-3d13-409c-a230-370916775cd1

**Comment by palakgosalia** [comment]
Hey, Left a comment in the FE PR. Thank you

**Review by AaronPersaud — APPROVED** [review]
Hi Eduardo, I've tested and it works perfectly!

<b>Running `nvm i` and switching the versions</b>

image

<b>Running `npm i` to install node packages</b>

image

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
