### PR TITLE
Imran_Fix_Total_Team_Report_team_code_fields

### PR DESCRIPTION
**Pull request by ImzIssa**
# Description
Screenshot (505)

## Related PRS (if any):
To test this backend PR you need to checkout the frontend development branch.

## Main changes explained:
- Update getAllTeams function in teamController.js to include the most-used team code
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user

## Screens
Screenshot (509)
hots or videos of changes:

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (178)

**Review by jinxyou — APPROVED** [review]
I tested the function and it seems working fine. Great work!
Screenshot 2024-08-23 154917

**Review by SMitta11 — APPROVED** [review]
I tested this PR as mentioned in description. I works fine but I see one inactive team, please find below screenshot and check if that is expected behavior. If yes then this PR works as expected.

**Review by vishnupriyaatheti — APPROVED** [review]
@ImzIssa changes are working expected.
BE PR 1075

**Review by vedantg24 — APPROVED** [review]
Tested the PR as per the description mentioned and everything works as expected.

Screenshot 2024-09-06

**Review by Shreyav2000 — CHANGES_REQUESTED** [review]
Hi,

I noticed that the `isActive` field is included in the output, but it’s not being used to filter out inactive users before the aggregation. Since the requirement is to calculate the most-used team code based on active users, you should add a $match stage to ensure only active users are included in the aggregation.
Screenshot 2024-09-07 at 4 05 24 AM

For example, you can add:
```
{
  $match: {
    "members.isActive": true  // Filter to include only active users
  }
}
```
This will make sure the team code is calculated based on active members only. Please review and update accordingly. I have recieved the following output after testing:

Screenshot 2024-09-07 at 4 00 43 AM

**Comment by saurabhshetty29** [comment]
PR looks good; everything is functioning as expected.
Screenshot 2024-09-10 at 10 38 04 PM

**Comment by geetamatkar** [comment]
I tested this PR and it is working as expected. 
PR1075

**Review by ashayk9 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot 2024-09-14 at 12 22 26 PM

**Review by Muzammil603 — APPROVED** [review]
image
I have tested this and this works fine.

**Review by crystallow1168 — APPROVED** [review]
Hi @ImzIssa,

I have tested the PR and changes are working as expected 👍🏻

image

**Review by anirudhsk2107 — APPROVED** [review]
The changes are working as expected
Screen Shot 2024-09-21 at 1 40 23 AM

**Review by nevatiarishabh — APPROVED** [review]
I have reviewed the PR, and everything seems to be working as expected.

Screenshot 2024-09-21 at 4 44 20 PM

**Review by SFA23SCM35V — APPROVED** [review]
I checked out the current branch, ran `npm install` to set up the environment, and cleared the site data/cache. After logging in as an admin user, I verified that the team code field under terms correctly displays active teams. The functionality is working as expected.

**Review by mrinalini-raghavendran19 — CHANGES_REQUESTED** [review]
Hello!

Changes look mostly good to me, but I still see inactive users being loaded on the screen - check the recording below for reference. 

Suggestions to correct this - 

In the `teamController.js` file - between the `$group` and `$unwind` operations, you can add a `$match` phase that filters based on the active users; by selecting those user profile fields where `isActive` is set to `true`

Do take a look once!

https://github.com/user-attachments/assets/b014a1a6-baf0-4c19-b321-2c3a646d2a38

**Review by neeharikakoniki — APPROVED** [review]
I tested it locally, following the instructions provided, and confirmed that the function retrieves and displays the additional information accurately.
 
 
image

**Comment by pallavithorat** [comment]
I tested the function, and it appears to be working as expected. Well done!
PR #1075

**Review by javid679 — APPROVED** [review]
Hey I tested this PR it is working fine: 

image

**Comment by sheetalmangate** [comment]
How to verify whether Team Codes Displayed on the UI Are Correct or not?

From the code changes, I could not find how the most used Team Code is fetched.

**Pull request closed without merging**
