### PR TITLE
Parthj unit tests task controller

### PR DESCRIPTION
**Pull request by Parth-tech**
# Description
This PR covers the unit tests for the taskController.js

## Related PRS (if any):
None

## Main changes explained:
- Requirement files have been added which describes the test scenarios
- Added a new file `taskController.spec.js` that contains all the code.

## How to test:
1. check into current branch
2. do `npm install`
3. do `npm run test taskController` 
4. All test cases must pass

## Note:
Successfully execution results may look as follows:
Screenshot 2024-09-11 at 1 03 01 PM

### CODE REVIEW

**Review by SFA23SCM35V — CHANGES_REQUESTED** [review]
FAIL  src/controllers/badgeController.spec.js
PR #1096

**Review by neeharikakoniki — APPROVED** [review]
The PR looks solid and covers the necessary unit tests for taskController.js. A few tweaks regarding edge case handling and test structure could enhance the maintainability of the tests.
ss1
ss2

**Review by neeharikakoniki — CHANGES_REQUESTED** [review]
The code need changes 
ss2
ss1

**Comment by ArtemisNyx3** [comment]
**Branch: parthj_unit_tests_taskController**
image
**taskController** tests passed.

I noticed that running `npm run test` throws some errors and has failed test cases. I don't know if this falls within the scope of this PR. Could you help clarify?
image

**Comment by Parth-tech** [comment]
> FAIL src/controllers/badgeController.spec.js PR #1096

Hi [neeharikakoniki](https://github.com/neeharikakoniki),
The other error are unrelated to this PR. I made a mistake while writing the instructions to check this PR. 
Could you try again using `npm run test taskController` and check for errors?
Thanks!

**Review by ArtemisNyx3 — APPROVED** [review]
taskController tests passed, approving PR
image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (193)

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases were passed.
Screenshot 2024-09-12 at 5 34 26 PM

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture1096

**Comment by geetamatkar** [comment]
Hi @Parth-tech ,
I tested this PR and it is working as expected.

PR1096

**Review by swaroop-2007 — APPROVED** [review]
Hey @Parth-tech, everything works as expected. Great job!
Screenshot 2024-09-13 115236

**Review by ashayk9 — APPROVED** [review]
I have tested the P. All the test cases have passed.
Screenshot 2024-09-13 at 12 29 13 PM

**Review by Saniya98 — APPROVED** [review]
All test cases are passing
image

**Review by linkhanthtel — APPROVED** [review]
All test cases passed as expected! Nice work!

PR#1096

**Comment by sud306** [comment]
I am getting "No tests found, exiting with code 0" when executing "npm run test taskController".
PFA the screenshot.
5 PR1096_1

**Review by panchalvatneu — APPROVED** [review]
all 58 taskController tests passed image

**Review by Muzammil603 — APPROVED** [review]
image
I have tested and all test cases are passed

**Comment by mianmiantea2019** [comment]
I have tested and all test cases are passed

image

**Review by ddshah878 — APPROVED** [review]
All the test cases have passed. Good job!

image

**Review by RishithaMamidala — APPROVED** [review]
@Parth-tech 
Tested the PR and it passes all the testcases.
PR 1096

**Review by crystallow1168 — APPROVED** [review]
Hi @Parth-tech,

Tested the PR and all the tests passed! 👍🏻

image

**Review by chu-ziyu — APPROVED** [review]
I have tested this PR and all the tests passed as expected!
Screenshot 2024-09-18 at 6 08 58 PM

**Review by manikittu810 — APPROVED** [review]
Hello @Parth-tech 

Everything is working as expected.

Screenshot 2024-09-18 at 8 06 49 PM

Thank you.

**Review by anirudhsk2107 — APPROVED** [review]
Approving PR. The tests passed.

Screen Shot 2024-09-19 at 2 14 34 PM

**Review by Lexie5212 — APPROVED** [review]
I have tested the PR, and all tests pass.
Screenshot 2024-09-19 at 16 03 19

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Review by nevatiarishabh — APPROVED** [review]
PR covers the unit tests for the taskController.js. I have tested the PR and all test cases have passed as expected. 

Screenshot 2024-09-20 at 12 00 12 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
