### PR TITLE
huijie - fix timelog and profile page times don't match

### PR DESCRIPTION
**Pull request by metaphor987**
# Description
  description
Profile page: The incorrect logged time on the profile page is due to several small bugs in `timeEntryController.js`. These bugs cause incorrect updates to the `userProfile.hoursByCategory` field in the database during the creation, modification, and deletion of time entries. 

Timelog page: The query for retrieving time entries for the timelog page does not include those related to archived projects.

The bug fix in this PR and performing the one-time recalculation should make the times on two pages the same.

## Related PRS (if any):
To test this backend PR you need to checkout the frontend PR [2383](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2383).

## Main changes explained:
The code changes in this PR include two parts:
1. fix the bugs in `timeEntryController.js` to ensure correct updates in the future
2. implement APIs for backing up existing data and recalculating the `userProfile.hoursByCategory` and `userProfile.totalIntangibleHrs`. They are one-time recalculation.
  - The backup methods create new fields in the `userProfile` collection as copies of the existing data. After this PR is merged and shows no errors, I will submit another PR to remove the backup fields. The recalculation is based on the related time entries and projects of a user.

Please feel free to share any better ways to recalculate or test the code changes. If you find any potential issues with the current method, please feel free to comment. Your help is greatly appreciated.

## How to get prepared for testing:
1. check into current branch
2. do `npm install`, `npm run build` and `npm start` to run this PR locally
3. Clear site data/cache
4. log in as any user type
5. find the logged hours in timelog page: timelog → search by date range → ensure full time range (for example, modify the “from” year to 0000) → search → find “Tangible Effort” and “Intangible Effort”  
  

6. find the logged hours in profile page: view profile → volunteering times  
  

7. instructions for viewing and editing data in MongoDB: https://docs.google.com/document/d/1wI4vCaELQN-qogAqybqdxIMJ3Ah1SZpOyALeS2M2bBM/edit?pli=1 
If a user has the backup field, you could find it like this: 

8. steps for using Postman to send request:
- choose POST method and enter the url
- enter the authorization key. Instructions to get the key(in README.md): 
- send the request

## How to test the functionalities
1. back up for tangible hours: 
    1. send the post request to url: `http://localhost:4500/api/TimeEntry/backupAllUsers/HoursByCategory` on Postman. It takes about 30s.
    2. Result: A success message should be displayed. For users that don’t have a `backupHoursByCategory` field in `userProfiles` collection before, the field will be created as a copy of `hoursByCategory`. Others will not have changes.
2. back up for intangible hours: 
    1. send the post request to url: `http://localhost:4500/api/TimeEntry/backupAllUsers/totalIntangibleHrs` on Postman. It takes about 30s.
    2. Result: For users that don’t have a `backupTotalIntangibleHrs` field in `userProfiles` collection before, the field will be created as a copy of `totalIntangibleHrs`. Others will not have changes.
3. recalculate tangible hours: 
    1. send the post request to url: `http://localhost:4500/api/TimeEntry/recalculateHoursAllUsers/tangible` on Postman. It takes about 1-3 mins.
    2. Result: After sending this request, The total tangible hours on the profile page should be correct. The tangible hours on the profile page and timelog page should be the same.
4. recalculate intangible hours:
    1. send the post request to url:  `http://localhost:4500/api/TimeEntry/recalculateHoursAllUsers/intangible` on Postman. It takes about 1-3 mins.
    2. Result: After sending this request, the total intangible hours on profile page should be correct. The intangible hours on profile page and timelog page should be the same.
5. Test the bug fix: Verify that when a user creates, modifies, or deletes a time entry, the total logged hours (both tangible and intangible) on the profile page change as expected.

## Note:
The dev site and the local branches are connected to the same database. Thus, if you send requests to recalculate the logged time in the database, others may modified time entries after that and make the hours incorrect again(since bug still exists on dev branch). Considering this, I suggest that check the recalculation result right after sending the request. Thank you for reviewing this PR :) !

### CODE REVIEW

**Review by angelalalacheng — APPROVED** [review]
Hi metaphor987,
I first set the frontend branch as `huijie_fix_times_on_timelog_and_profile_page_dont_match` and backend branch as `Huijie_Fix_Timelog_and_ProfilePage_Times_not_match`. Then, I check all the numbers. The timelog, profile page times and mongodb data are consistent.
Screenshot 2024-07-11 at 4 21 42 PM
Screenshot 2024-07-11 at 4 22 15 PM
Screenshot 2024-07-11 at 4 36 31 PM

**Review by SrikanthChowdary495 — APPROVED** [review]
I have test this 2383 PR with help of Front end. It working good.

**Review by kabraambika — CHANGES_REQUESTED** [review]
I logged two 15-minute entries using the timer to verify the calculation for tangible time logs.

The correct number is displayed on the dashboard, but **I'm uncertain about the "View Profile > Volunteering times" section**. When navigating to "View Profile > Volunteering times," the total tangible hours for this week shows 0.50, which matches the dashboard. However, the overall total tangible hours still shows 0.25, and the total tangible food hours also remain at 0.25. Please refer to the images below:
image
image

**Review by Chetan0606 — APPROVED** [review]
Everything looks good and provided my observation in the associated frontend PR.

**Comment by varunreddy03** [comment]
@metaphor987 
I have tested this PR 1004, with the help of the Frontend PR 2383.
I have set the frontend branch as "huijie_fix_times_on_timelog_and_profile_page_dont_match" and 
backend branch as "Huijie_Fix_Timelog_and_ProfilePage_Times_not_match."

Case 1: I have checked with 1.27hrs of Intangible and 0.75hrs of tangible time in the dev App from a volunteer profile. and checked the data in profile and MongoDB all the values are consistent.
PR 2383+1004_0
PR 2383+1004_1
PR 2383+1004_2

Case 2: Then in this case I have logged an additional tangible time that is a total tangible time of 0.82hrs and Intangible time of 1.27hrs, even in this case I have checked all the values in dashboard, Profile and MongoDB all these values are consistent.
PR 2383+1004_3
PR 2383+1004_4
PR 2383+1004_5

**Review by varunreddy03 — APPROVED** [review]
@metaphor987 
I have tested this PR 1004, with the help of the Frontend PR 2383.
I have set the frontend branch as "huijie_fix_times_on_timelog_and_profile_page_dont_match" and 
backend branch as "Huijie_Fix_Timelog_and_ProfilePage_Times_not_match."

Case 1: I have checked with 1.27hrs of Intangible and 0.75hrs of tangible time in the dev App from a volunteer profile. and checked the data in profile and MongoDB all the values are consistent.


PR 2383+1004_0
PR 2383+1004_1
PR 2383+1004_2


Case 2: Then in this case I have logged an additional tangible time that is a total tangible time of 0.82hrs and Intangible time of 1.27hrs, even in this case I have checked all the values in dashboard, Profile and MongoDB all these values are consistent.


PR 2383+1004_3
PR 2383+1004_4
PR 2383+1004_5

**Comment by metaphor987** [comment]
Hi @[kabraambika](https://github.com/kabraambika),
Thank you for reviewing my PR. I wasn’t able to reproduce the error on my end. I added two 15-minute time entries for a Food project, and the profile page correctly displayed 0.5 for the total tangible hours. I’ve recorded a quick 2-minute video showing my testing process:

https://github.com/user-attachments/assets/cef4c204-fac8-45c5-bb01-d6ab4a13ee23


Could you please check to see if there might be any differences between our testing methods or results? Thanks!

**Review by adityasure9 — COMMENTED** [review]
I've provided a detailed explanation on the frontend PR related.

**Review by kabraambika — APPROVED** [review]
I am unable to recreate the previous scenario and created a new user profile to verify and it's working as intended hence approving this PR.

**Pull request merged**
