### PR TITLE
Shengwei_HotFix: Page render issue in Timelog

### PR DESCRIPTION
**Pull request by ptrpengdev**
# Description
Hotfix blank page in the main site.

image

Hotfix for time entry render issue
- Add project/task name and category information in getTimeEntriesForSpecifiedPeriod
- Update time entry data model to include new virtuals

## Related PRS (if any):
Related to fronted [PR2159](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2159)

## Main changes explained:
- Update timeEntryController.js and timeentry.js to include additional information for getTimeEntriesForSpecifiedPeriod API

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard -> timelog
6. log a time entry under a specific project
7. remove the user from the project 
8. reload the timelog page

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by alla0810** [comment]
Hi, [ptrpengdev](https://github.com/ptrpengdev).
I just found out this PR is linked with https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2159, which is marked as 'do not review'.

I just want to let you know that this PR seem to succeed in keeping time log after the associated project is removed, but what I found out is, I could never delete the project.
At first, I've tried to remove the user from the project assignment, and it looked like I could successfully remove a user from a project.  But when I came back to the user profile, the project was still there, and the user was still assigned to the project that I just removed.

I moved to the project link to remove the project itself to see if the user is still assigned to the obsolete project, and what I saw was, I couldn't really remove the project itself!  When I came back from another page to the project page, the project was still there ALIVE, which means we can never delete any project, and any user once assigned one project should always stay as a member of the project FOREVER!!

Please see the video below.

https://drive.google.com/file/d/1dNpB3xyeQGRev1qy_gQIUcnDFaqiBbPB/view

image

image

image

image

image

image

[PR898.pptx](https://github.com/OneCommunityGlobal/HGNRest/files/15027111/PR898.pptx)

**Comment by ptrpengdev** [comment]
> Hi, [ptrpengdev](https://github.com/ptrpengdev). I just found out this PR is linked with [OneCommunityGlobal/HighestGoodNetworkApp#2159](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2159), which is marked as 'do not review'.
> 
> I just want to let you know that this PR seem to succeed in keeping time log after the associated project is removed, but what I found out is, I could never delete the project. At first, I've tried to remove the user from the project assignment, and it looked like I could successfully remove a user from a project. But when I came back to the user profile, the project was still there, and the user was still assigned to the project that I just removed.
> 
> I moved to the project link to remove the project itself to see if the user is still assigned to the obsolete project, and what I saw was, I couldn't really remove the project itself! When I came back from another page to the project page, the project was still there ALIVE, which means we can never delete any project, and any user once assigned one project should always stay as a member of the project FOREVER!!
> 
> Please see the video below.
> 
> https://drive.google.com/file/d/1dNpB3xyeQGRev1qy_gQIUcnDFaqiBbPB/view
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> [PR898.pptx](https://github.com/OneCommunityGlobal/HGNRest/files/15027111/PR898.pptx)

Hi @alla0810 ,

Thank you for reviewing this hotfix. This fix tends to be a temporary solution for the frontend blank page issue caused by missing project names. There are existing issues with the Project/Task deletion which is currently handled by Xiao W. This hoftix is currently blocked by Xiao's PR. Hence, a 'DO NOT REVIEW' label added to the frontend PR. I just updated this backend PR with the 'DO NOT REVIEW' label. Thank you for testing.

**Review by cgomezhub — APPROVED** [review]
left comment in frontend PR # 2159 https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2159#pullrequestreview-2033896801

**Comment by mSharifHub** [comment]
When following the instructions above, I was attempting to find a task but could not add. I then clicked on user Profile and got the error  "Can not read properties of undefined ( reading  'reduce')


Screenshot 2024-05-01 at 11 47 37 AM

**Review by mSharifHub — COMMENTED** [review]
I have not seen any issues with the code that has been changed. Yet, the issue I reported in the conversation is not related to this file.

**Comment by KaushikMreddy** [comment]
Hi, is this PR to be reviewed or not reviewed?

**Pull request closed without merging**
