### PR TITLE
Lawrence - Hide sensitive data

### PR DESCRIPTION
**Pull request by lchua2314**
# Description
Task desc

## Main changes explained:
- Hide hardcoded login credentials using the .env file.

## How to test:
1. add the content from the Note section into your .env file
2. check into current branch
3. do `npm install` and `npm start` to run this PR locally
4. log out if you haven't already
5. login as any user
6. check the backend console for any errors

## Note:
Add the following to your .env file:
```
TIME_ARCHIVE_FIRST_NAME=TimeArchiveAccount
TIME_ARCHIVE_LAST_NAME=TimeArchiveAccount
TIME_ARCHIVE_EMAIL=TimeArchiveAccount@yopmail.com
```

### CODE REVIEW

**Review by luisarevalo21 — APPROVED** [review]
Hello @lchua2314,

I tested your PR and works as intended great work!
The application runs as normal when signing in and I've added the variables into my .env file. 
I also didn't see any errors on the backend nor any relevant

https://github.com/OneCommunityGlobal/HGNRest/assets/22454953/50291937-1802-4fd2-bb50-ae7ca685e446

Screenshot 2023-07-18 at 9 06 16 PM
Screenshot 2023-07-18 at 9 06 30 PM
 errors on the front end.

**Review by DavidC0126 — APPROVED** [review]
Hi @lchua2314, I have tested your PR and everything works correctly and has no error on the backend when running.  Nice job!
PR#449_hideCredential

https://github.com/OneCommunityGlobal/HGNRest/assets/74082492/55858558-89a2-451d-a82b-d471bc4f86d0

**Review by joyceiphone — APPROVED** [review]

**Comment by mounica-dingari-by** [comment]
I've tested your PR for backend and it looks fine. I don't see any errors in the backend. 
Screenshot from 2023-07-19 16-48-04

**Review by AaronPersaud — APPROVED** [review]
Hi, I've tested and it works great!

image

- no console errors when logging in 

Great job!

**Review by xaanders — APPROVED** [review]
Hi. I've tested both frontend and backend PRs. All works good. 
The backend terminal stays clean whichever user I login to.(admin, owner, volunteer, manager)

**Comment by Shreyj14** [comment]
Hi, I've tested this branch and it works as intended. There was no error message in the backend console when I logged in to the application. Great work!
Screenshot 2023-07-20 at 3 47 42 PM

https://github.com/OneCommunityGlobal/HGNRest/assets/118795427/376a3062-e6b5-4e79-a1f9-02e9e080a750

**Review by scoopstroop92 — APPROVED** [review]
No errors in the backend . Approving the PR on the same account
image

Could you explain the  significance of the TimeArchiveAccount ? Trying to understand the use case

**Review by scoopstroop92 — APPROVED** [review]
No errors in the backend . Approving the PR on the same note 
image

**Review by igorrochadasilva — APPROVED** [review]
Hi @lchua2314 !

I've tested your PR and it works as intended. 
There was no error message in the backend console when I logged in to the application.
Great work! 😃

449_01_terminal-no-errors

**Review by shiva2096 — APPROVED** [review]
Hi @lchua2314 

I have tested the PR locally and found no errors in the terminal when logged into the application.

Screenshot 2023-07-21 at 8 17 54 PM

**Pull request merged**
