### PR TITLE
Jiayu Fix bug manual add lost volunteer time

### PR DESCRIPTION
**Pull request by peter6866**
# Description
image

## Related PRS (if any):
This backend PR is related to [FE# 2319](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2319).

## Main changes explained:
- Updated `timeEntryController.js` to allow adding/editing/deleting non-user time entries for projects and teams.

## How to test:
1. check into current branch
2. do `npm install` and `npm run build && npm run start` to run this PR locally
3. Clear site data/cache
4. log as **owner** user
5. go to dashboard→ Reports→ Reports→ Add Lost time
6. verify owner can successfully add lost time for Project, Person, and Team.
7. verify owner can successfully edit and delete lost time for Project, Person, and Team.

### Before Changes
image
image

### After Changes
https://www.loom.com/share/df6c6c8043ad405088c3766672dec080?sid=e4b769b9-4c1a-4245-9f1e-735f2f9c4342

### CODE REVIEW

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and it works as expected. I have left a comment on frontend [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2319#pullrequestreview-2110866693)

**Review by TXMO-dev — APPROVED** [review]
Great job on this everything works fine

**Comment by akshit0211** [comment]
Everything is working fine. I have left a comment on the front-end PR. [Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2319#pullrequestreview-2114458996)

**Review by akshit0211 — APPROVED** [review]

**Review by Kavil-Jain-514 — APPROVED** [review]
The functionality works and I have reviewed the PR for the front-end PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2319#pullrequestreview-2117526988

**Review by tianyangL11 — APPROVED** [review]
I have tested the PR and it works as expected. I have left a comment on frontend

**Review by DiyaWadhwani — APPROVED** [review]
Hi Jiayu,
This functionality works as expected. Dropped a video implementation on the related front end PR 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2319#pullrequestreview-2140627378
Thank you

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Great work.

https://github.com/OneCommunityGlobal/HGNRest/assets/47699187/5048c45e-6032-4da4-8038-8d7e2fb611f9

**Review by pavanswaroopl — CHANGES_REQUESTED** [review]
Hello,

Great work, but I have observed while adding lost time for team, steps to reproduce:

Add lost time -> select team -> and type a new team name -> it will ask for create new team with the name you have given, while it doesn't make sense to add lost time for a team that has not been created, I'm not sure that option might be at a wrong place, correct me if I'm wrong.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/5ae52f3b-7804-4883-95fc-8c9f4bea631c


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/09e7cc84-4f6c-46eb-ab04-b847a731bfd7


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/eb523a98-a8ac-4533-8f01-993dc6207709

Screenshot 2024-06-29 at 5 03 03 PM

**Review by pavanswaroopl — APPROVED** [review]
Found an issue that might not be related to this PR, hence approving it.

Please report this to concerned team, Thanks @peter6866

**Review by vishavk1992 — APPROVED** [review]
this PR working as intended and i left comment on frontend PR. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2319#pullrequestreview-2159362467

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
