### PR TITLE
Haoji create a cronjob for app to get profile images from website

### PR DESCRIPTION
**Pull request by Haoj1**
# Description
image

## Related PRS (if any):
To test this backend PR you need to checkout the [#1470](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1470) frontend PR.
…

## Main changes explained:
- Update package.json for Web Scraping tools
- Update src/controllers/userProfileController.js for allowing url as a valid img source
- Create a function updateProfilesPic in src/controllers/userProfileController.js for fetching the pictures from the sites
- Update src/models/userProfile.js to allow temporarily store the possible pictures
…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm run start` to run this PR locally
3. log as owner user

4. Feel free to change the cronjob period in src/cronjobs/userProfileJobs.js, the following change allows cronjob to run every minute 
image

5.  If you do not want to modify others' profiles during testing, you can add a search keyword in src/helpers/userHelper.js like the following. That could make sure cronjob only works on your own created users.
image

6. See how to test in frontend
7. do `git restore .` to undo the changes

## Note:
See frontend

### CODE REVIEW

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hi @Haoj1, check my [FE review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1470#pullrequestreview-1711793383).

**Review by shubhankarval — CHANGES_REQUESTED** [review]
Hey @Haoj1, just left a comment on FE PR [#1470](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1470).

**Comment by Haoj1** [comment]
> Hi @Haoj1, check my [FE review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1470#pullrequestreview-1711793383).

Hi @malikjahanzaib, could you help me review the new PR with the same functions? https://github.com/OneCommunityGlobal/HGNRest/pull/608 I have fixed this error and enabled email sender for alerting user to update their profile img

**Comment by Haoj1** [comment]
> Hey @Haoj1, just left a comment on FE PR [#1470](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1470).

Hi @shubhankarval, would you mind helping me review the new PR with the same function?https://github.com/OneCommunityGlobal/HGNRest/pull/591#pullrequestreview-1713832290. I have fixed the typo and enabled email sender for alerting user to update their profile img

**Pull request closed without merging**
