### PR TITLE
Iven - Allow accounts with permission make suggest on tasks and see the notification after approval

### PR DESCRIPTION
**Pull request by iven-yao**
## Related PRS (if any):
To test this backend PR you need to checkout the [#2200](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2200) frontend PR.

## Main changes explained:
- Update `taskHelper.js`, fix the logic in building taskNotifications list in each user's data, also fix a potential NaN error in timeEntry to pass the lint

## How to test:
1. check into current branch
2. do `npm install` 
3. do `npm run build`
4. do `npm start`
5. following the instruction in frontend PR

### CODE REVIEW

**Comment by Ramaruva** [comment]
Hi I have added my comments regarding this pr in frontend pr

**Review by Ramaruva — APPROVED** [review]
Hi I have verified again with the steps you suggested and it working well and one more thing can you clarify here did you make any particular changes for dark mode in this code changes  because some of the modal (while some modal in edit are not in dark mode ) and so I am accepting the changeset

https://github.com/OneCommunityGlobal/HGNRest/assets/64008831/ad8f8920-89f9-43e6-a25a-d5588fec0b50

**Review by Ramaruva — APPROVED** [review]
Added comments in frontend and working as expected

**Review by nathcarnevalli — APPROVED** [review]
The functionalities are working as expected, no issues were found. I reviewed on the [frontend ](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2200#pullrequestreview-2055250841)too.

https://github.com/OneCommunityGlobal/HGNRest/assets/69649453/3a98bb2f-ceb8-409b-ab75-44edf11032fb

**Review by peter6866 — APPROVED** [review]
Changes work as expected. I left a comment in your frontend PR.

**Pull request merged**
