### PR TITLE
Jinchao fix active/inactive button in user management and user profile page

### PR DESCRIPTION
**Pull request by suigunfjc**
# Description
Fix bug:
(PRIORITY MEDIUM) Jae: Fix ability to make people inactive from their Profile Page (WIP Jinchao)
a.	Admin login → Profile Page → Click green dot at top to make inactive. Then go to Other Links → User Management → Find the person → You’ll see they are still showing green dot like they are active… The don’t show up anymore on the Leaderboard but they show up active here and eventually show back up on the leaderboard. They should be made inactive everywhere and STAY INACTIVE

## Mainly changes explained:
Extend `userProfileController.changeUserStatus` :
Update the `allusers` cache after changing user's status.

## How to test:

1. Admin login -> User Management
2. Click the green/grey dot to inactive/active a user and see the immediate change on both the user management page and the user profile page.
Screenshot 2023-03-08 214309
3. Go to a user's profile page and click the green/grey dot to active and inactive the user and see the immediate change on both the user management page and user profile page.
Screenshot 2023-03-08 214356
4. Log in to that user's account to check the account status.

### CODE REVIEW

**Comment by nicollext** [comment]
Hey @suigunfjc! After testing the changes I faced some problems. 

1.When changing the the user status at the UserManagement page: the status is updated at the user's profile, but if the user is set to INACTIVE he is not able to do the login anymore. 

https://user-images.githubusercontent.com/101591708/224396423-a7c8fbbb-6884-4d73-b9f8-9e38e5c6cbc2.MP4


https://user-images.githubusercontent.com/101591708/224396469-c324719b-2c5e-431a-85be-18ef2a88ae22.MP4

2. When changing the user status at the user profile page: the status is not updated at the UserManagement page. 


https://user-images.githubusercontent.com/101591708/224396884-b2e93cdd-5f12-465b-b8af-57dd7f3b4084.MP4

**Comment by vitorsaa2k** [comment]
> Hey @suigunfjc! After testing the changes I faced some problems.
> 
> 1.When changing the the user status at the UserManagement page: the status is updated at the user's profile, but if the user is set to INACTIVE he is not able to do the login anymore.
> 
> 2. When changing the user status at the user profile page: the status is not updated at the UserManagement page.

@nicollext Both are expected behavior. Correct me if i'm wrong @suigunfjc 

1. Exactly the user should not be able to log in if he is marked as inactive.
2. This is a bug and will be fixed with PR [#699(FE)](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/699)

**Comment by vitorsaa2k** [comment]
Working as expected, I did the change from PR#699(FE) so the UserManagemente page will update after making changes on the UserProfile page.

https://user-images.githubusercontent.com/17365161/224403845-da612190-7001-4a37-9454-bfb8e895d4b5.mp4

**Review by Lucas-E — COMMENTED** [review]
Hey, just tested your PR and everything works fine. I deactivated my volunteer user, then activated it again, and everything worked very well. Great job!
Captura de tela de 2023-03-11 02-13-05
Captura de tela de 2023-03-11 02-13-01
Captura de tela de 2023-03-11 02-12-57
Captura de tela de 2023-03-11 02-12-53
Captura de tela de 2023-03-11 02-12-49

**Comment by NyahJ** [comment]
Hi @suigunfjc,

All the test results worked as expected, the activate and deactivate functions on both of the "User management page" and "User profile" can update all the status in the system. Great job, thanks!

截屏2023-03-11 下午9 43 34
ey, just tested your PR and everything works fine. I deactivated my volunteer user, then activated it again, and everything worked very well. Great job!

截屏2023-03-11 下午9 44 01

**Review by kangjay88 — APPROVED** [review]
Hi @suigunfjc, I have tested this PR and it works as intended when following the steps.
https://user-images.githubusercontent.com/108297706/224528403-c1e971f7-50a5-423a-9335-32001b7936d7.mp4
I did have a weird glitch when I tried deactivating a user, and then refreshing the page to see if the changes would stick: not sure if anyone else sees that glitch when testing, here is my example below: 

https://user-images.githubusercontent.com/108297706/224528520-9be94e1e-ef3b-4da8-be66-6d35361261b8.mp4

**Comment by one-community** [comment]
Moved to final review, thank you all.

**Review by rauleffting — APPROVED** [review]
Hi @suigunfjc. Your PR worked as intended.

https://user-images.githubusercontent.com/29555732/224754407-99977a48-43f8-4a4b-826d-b08d6aa31fdb.mp4

The code is perfect as well. Thank you!

**Comment by one-community** [comment]
Merged and this is still a bug on the Dev and Main. Might be because your way to test it is different than what I described in the bug. You way of testing it always worked. This from the PROFILE PAGE is what is a problem: Admin login → Profile Page → Click green dot at top to make inactive. Then go to Other Links → User Management → Find the person → You’ll see they are still showing green dot like they are active…

**Comment by suigunfjc** [comment]
> 

Hi @one-community , I think this problem is related to the 'usermanagemement page not updating' bug I fixed in PR#699. Could you open the reports page and go back to the usermanagement page to see if the status has been updated? If it is updated, then this bug can be fixed after we merge PR#699.

**Comment by one-community** [comment]
Ok, yes, that worked. 699 is also approved, so I've merged it. Thank you.

**Pull request merged**
