### PR TITLE
Jianjun - add bio status to weekly report

### PR DESCRIPTION
**Pull request by juneluo**
### Description
Add a “Bio Posted/Requested” selection to the Weekly Summary Report page
A toggle switch that can change the status of bio announcement has been added to this page for every user.

### Mainly changes explained:
add the `bioPosted` to the report props aggregated from the userprofile.

### How to test:
**Please test with the front end[ PR823](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/823).**
checkout this branch
for the server:
npm run build
npm start
for the front end:
npm run start:local
run the front end and test

### CODE REVIEW

**Comment by AriaYu927** [comment]
Have tested this PR and comment under[ PR#823](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/823#issuecomment-1546736902)

**Review by GKD890 — APPROVED** [review]
Hi Juneluo, the code looks good to me. I tried to reproduce @AriaYu927 's problem, but seems it works on my computer. Here's the [link](https://www.dropbox.com/s/nhju2sgnvk3k8ex/Backend_PR%23352_record.mov?dl=0) of the video.

**Review by AriaYu927 — APPROVED** [review]

**Review by abdel-lall — APPROVED** [review]
LGTM.

**Review by drewlong314 — APPROVED** [review]
I have tested the PR along with [PR #823](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/823). The code looks good and it works as expected.

**Review by yoyoweiii — APPROVED** [review]
Work as intended. Good work! @juneluo  I tested this branch along with https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/823

https://github.com/OneCommunityGlobal/HGNRest/assets/60588210/b11f0141-6018-477c-906b-9064087399c8

**Review by EdwinLauM — APPROVED** [review]
Works as intended along with [PR #823](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/823). Good job!

**Comment by one-community** [comment]
Thank you everyone for your reviews! 

I accidentally merged this before moving to final review. Don't believe the label, it's been reverted. Will revert my revert once this is approved by the leadership team and then it will be merged again: https://github.com/OneCommunityGlobal/HGNRest/pull/354

**Pull request merged**
