### PR TITLE
Ilya consumables add page

### PR DESCRIPTION
**Pull request by ilyaflaks**
# Description
consumables-add

Adds functionality for the user to navigate to /consumables/add, enter the required information (consumable name, description, measurement units, size) and create a new consumable type in the system. 

The front end validates the input to have a name that is at least 4 characters long and a description that is at least 10 characters long. The back end checks if a consumable under the same name already exists.

## Related PRS (if any):
This backend PR is related to the [#1926](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1926) front end PR.
To test this backend PR you need to checkout the **ilya_consumables_add_page** branch on the front end 
…

## Main changes explained:
- /consumables GET route added to fetch existing consumable types
- /consumables POST route added to create a new consumable type
- fetchConsumableTypes and addConsumableType functions added to bmInventoryTypeController.js to find and create using the consumableType model
- consumableType model edited to include an optional "size" parameter, "units" is now required

## How to test:
1. check into current branch
2. do `npm install` and `npm run build && npm start` to run this PR locally
3. checkout **ilya_consumables_add_page** on the front end, do `npm install` and `npm run start:local` to run on the front end 
4. log in as any user
5. go to [http://localhost:3000/bmdashboard](http://localhost:3000/bmdashboard) and log in again
6. go to [http://localhost:3000/bmdashboard/consumables/add](http://localhost:3000/bmdashboard/consumables/add), enter some dummy data, press "Add Consumable" when the button is enabled
8. A success message should appear if everything is acceptable or a warning message if not (such as a duplicate value)
consumables-fe
9. In MongoDB compass open hgnData_dev.buildingInventoryTypes collection. Press "Find", scroll all the way to the bottom or search by name and verify that the entered information is saved in the database
compass

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HGNRest/assets/105448137/a3890930-fc88-4915-93fa-c385ce635ef2

## Note:
Examples of construction consumables can include nails, screws, batteries, lumber, etc.

### CODE REVIEW

**Review by Pandani07 — APPROVED** [review]
Reviewed and tested this PR along with the frontend, left a video there. The feature works as intended!

**Review by ShengjieMao — APPROVED** [review]
Function worked perfectly. Great work. Left a review on frontend pr.

**Review by SaiDeepak-NEU — DISMISSED** [review]
Everything worked smoothly and as expected but one small bug was noticed. The input fields were accepting empty values by entering spaces. You can look into this and make a correction. Please look at the attached ss.
Screenshot (86)

**Review by 666saofeng — APPROVED** [review]
Hi I tested with admin account and it worked as intended.

image

https://github.com/OneCommunityGlobal/HGNRest/assets/62363348/cc767a76-10d4-4d17-8fc1-626fa03a42a8

**Review by peterson337 — APPROVED** [review]
Hi ilyaflaks, The frontend pull request worked as expected. Good job! Please see my comment on the frontend pull request for more details: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1926#pullrequestreview-1883297663

**Review by Jingyii800 — APPROVED** [review]
Hi, I have tested this backend with the frontend. Great work! Please check more details in this comment. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1926#pullrequestreview-1883908043

**Review by brandta-1 — APPROVED** [review]
# Review
Tested and working correctly per [front end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1926#pullrequestreview-1887074832).

**Review by XiaohanMeng — APPROVED** [review]
Hi, I left my comment on FE project, everything worked as intended. Well Done!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1926

**Comment by 20chen-7** [comment]
left review at the frontend, good job!

**Comment by ilyaflaks** [comment]
@one-community can you please merge this PR into "development"? All of the changes requested have been addressed and I resolved the merge conflicts. Thanks

**Pull request merged**
