### PR TITLE
Luis edit warning description backend

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description
This the backend which allows owners to edit warning descriptions. 
Owners should be allowed to edit warning descriptions and only owners

## Related PRS (if any):
To test this backend PR you need to checkout the frontend PR #2077

## Main changes explained:
- i added a new controller function `editWarningDescription.js` which handles logic to updating and setting the new value on the backend. 
- It returns a message confirming the description was edited successfully 

## How to test:
1. check into current branch
2. do `npm install` and `npm run build && npm run start` to run this PR locally
3. Follow the instructions of the Frontend PR

### CODE REVIEW

**Review by Abi-Liu — APPROVED** [review]
Looks good! For a more in depth review please see my frontend review [here](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2077)

**Review by meetpadhiar4 — DISMISSED** [review]
Have requested changes on the frontend PR

**Review by Pandani07 — APPROVED** [review]
Works well, left a review on the frontend

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and left a review on the frontend.

**Review by aaryaneil — APPROVED** [review]
Works well. Reviewed on the [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2077#pullrequestreview-1984592871)

**Review by SRamen1999 — COMMENTED** [review]
I tested your PR and left a review on the frontend. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2077#pullrequestreview-1995164842

**Review by Parth-tech — COMMENTED** [review]
Hey Luis, 
Great job done, it works as intended. Also, I have asked for a small change on front-end repo. Please check it out. 
[Front end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2077#pullrequestreview-2005449710)

**Review by Tiantian-C — COMMENTED** [review]
Please refer the frontend.

**Review by cgomezhub — CHANGES_REQUESTED** [review]
Submitted a request for a change to the frontend (#207)

**Review by nathcarnevalli — COMMENTED** [review]
I left a review on [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2077#pullrequestreview-2061559740).

**Review by nathcarnevalli — COMMENTED** [review]
I left a review on [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2077#pullrequestreview-2077631422).

**Review by cvtqx — COMMENTED** [review]
The backend works and warning can be created, edited and deleted successfully.  Faced one minor issue in the FE though. Left review in the FE PR.

**Pull request merged**
