### PR TITLE
Kaixiang fix edit and delete role

### PR DESCRIPTION
**Pull request by KaixiangGU**
This is PR is related to FE PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/651

### CODE REVIEW

**Review by LeeSingChanYau — APPROVED** [review]
Added new property. Looks good! Please read the comments I left in the front-end.

**Review by rauleffting — APPROVED** [review]
Hi @KaixiangGU! I've tested your PR. Everything worked quite well with Owner account. As you can see below:

https://user-images.githubusercontent.com/29555732/215130298-95e0aa56-f244-45a5-9233-334cab68b3a9.mov

I have nothing to question about the code, so I'm going to approve it. Thank you very much!

**Comment by RafaelCastilhoCastro** [comment]
Hi @KaixiangGU 
I performed new tests with a new Owner account and still got the same results of my last review on PR#651.

**Comment by RafaelCastilhoCastro** [comment]
Hi Guys,
I made new tests and I got no more issues, as I reported on PR#651.
Thanks.

**Review by rauleffting — APPROVED** [review]
Perfect. I tested it again, it's working perfectly. And all the code changes that I requested were done. Thank you very much!

**Pull request merged**
