### PR TITLE
yihan create way to see 6 months & yearly anniversaries

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
To test this backend PR you need to checkout the [#1603](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603) frontend PR.

## Main changes explained:
- Update file dashBoardController.js and dashboardRouter.js for including a function of posting trophy data.
- Update file dashboardhelper.js, reporthelper.js and userProfile.js for adding trophy icon property

## How to test:
1. check into current branch on both FE and BE
2. do `npm install` and `...` to run this PR locally
3. follow the test steps of [#1603](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603).

### CODE REVIEW

**Comment by ptrpengdev** [comment]
Tested with the FE [PR1603](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603). The feature works as expected.

**Review by pika-chu11 — COMMENTED** [review]
Hi @AriaYu927 , I have tested ur PRs and left a comment in the FrontEnd [#1603](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603). Great Job!

**Review by ilyaflaks — APPROVED** [review]
Everything works just as described! Good work! More detailed comment in PR#1603 on the front end

**Review by Alforoan — COMMENTED** [review]
I left a comment on fe pr.

**Comment by mianmiantea2019** [comment]
Tested with the PR1603. The feature works as expected.

**Comment by GKD890** [comment]
I used changing system time method at first, then I created a user that has a startDate 1 year ago (I recommend to use latter one as it's less likely to cause other error in you browser).
**Result** : I can verify the `1y` trophy icon in Weekly Summaries page shown as below
Screenshot 2024-04-11 at 15 43 34

However, I met such log information related to database. For comparing, I switched to `development`  branch and it never appears. It seems related to the document size in aggregation stage. Not sure if it's just me. So, if other reviewers can confirm would be great.

Screenshot 2023-12-30 at 15 56 45

**Comment by Haoxiang310** [comment]
Tested with the frontend PR#1603. It works fine.

**Comment by DragonSlayer2401** [comment]
I tested this PR with the related frontend please go there to see my full review.

**Comment by yuhuimin1996** [comment]
Tested with FE pr#1603. Please see my comments there.

**Review by Renanluizssx — COMMENTED** [review]
it is nice

**Review by Renanluizssx — APPROVED** [review]
it is working very well @AriaYu927, you can see my review on PR#1603: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603

**Review by Sophie-lei — APPROVED** [review]
Everything works as expected! I left comments in the 1603 frontend PR.

**Review by 666saofeng — COMMENTED** [review]
I left comments under PR1603https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603#pullrequestreview-1834189005

**Review by KevHnh — COMMENTED** [review]
Left comments on FR [PR#1603](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603) 

Provided screenshot of error message from the backend that only occurs when loading into the dashboard (specifically fetching data for leaderboard)

**Comment by galgalinidhi** [comment]
Hi @AriaYu927, I get the following error on the Backend Console-

**Comment by Sophie-lei** [comment]
I left comments in the PR#1603 frontend PR. and leave the problem comment there.

**Review by yvonnep165 — CHANGES_REQUESTED** [review]
Hi @AriaYu927 ,

I tried to test the pr but got the same error as mentioned by one of the previous reviewers at the backend. It seems like there's a MongoDB error related to the size limit of documents constructed during aggregation operations. 
Screenshot 2024-01-27 at 4 02 59 PM

**Review by Pandani07 — COMMENTED** [review]
I have left a comment on your frontend PR as well, 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603#pullrequestreview-1852425642

I get the following error in the backend console when I run this

Screenshot 2024-01-30 at 4 45 29 PM
Screenshot 2024-01-30 at 4 45 33 PM

**Review by peterson337 — CHANGES_REQUESTED** [review]
I encountered an error when attempting to run the backend.

a

**Review by SRamen1999 — CHANGES_REQUESTED** [review]
I tried to test the pr but got the same error as mentioned by one of the previous reviewers at the backend. 

Screen Shot 2024-02-08 at 6 31 50 PM

**Review by XiaohanMeng — COMMENTED** [review]
I have the same issue on my backend terminal as mentioned by the reviewer above.

#1603_bug

**Review by mohabbasd — CHANGES_REQUESTED** [review]
Hello, I tested this PR and it requires changes unfortunately it was not working as intended.

**Review by brandta-1 — CHANGES_REQUESTED** [review]
# Review
I have also received the same MongoDB error that others have cited. Upon login, the leaderboard is unable to load. The following video shows the error in the frontend. I will reference this in my [frontend review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603#pullrequestreview-1887063134).

# Video

https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/bf323d34-af6a-4cc9-a859-495709a0b956

**Pull request closed without merging**
