### PR TITLE
Roberto fix assigning duplicate badges

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
Whenever trying to manually assign badges to a user and duplicate badges are involved there aren't any clear updates being made. There was no logic to handle duplicate badges which would not allow badges to be updated anymore.

## Related PRS (if any):
Use latest frontend

## Main changes explained:
- Shortened fillEarnedDateToMatchCount function to handle all logic itself not needing a second helper function, also added edge case of user trying to lower badges count
- Added logic to assignBadge function to handle instances of duplicate badges and merge them to one with updated variables.

## How to test:
1. check into current branch
2. go to `src/controllers/userProfileController.js`, comment out lines `579 - 583`. *This step is important to clear backend cache, clearing cache through browser won't help when making changes to mongo compass and wanting to see changes immediately*
3. do `npm install` and `npm run build && npm start` to run this PR locally
4. log as admin user
5. go to any user profile and make sure they have at least 2 different badges assigned to them
6. create duplicate badges, here's a quick way to do this: 

https://github.com/OneCommunityGlobal/HGNRest/assets/117053202/905fe9e0-e944-4179-b893-6de73f75956e

8. Verify that either assigning a new badge or even incrementing count of any badge results in duplicate badges being merged.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/117053202/1b91d657-117e-416d-a9e2-eda76d262cda

## Note:
*Make sure to follow step 2, if you make changes to the database through mongo compass, you won't see immediate changes in frontend due to the backend cache still not being renewed*

### CODE REVIEW

**Review by jerryren527 — APPROVED** [review]
Hi, @robertoooc ,

This is a great solution for the issue of having duplicate badges and no real logic to handle this case! Your solution is elegant and works correctly according to my testing. Your code for the `fillEarnedDateToMatchCount()` function works well too. In my testing demonstration, I had two duplicate badges with multiple different earned dates. And after the two duplicate badges merge into one badge, all the earned dates are present and sorted in order. Great job!


https://github.com/OneCommunityGlobal/HGNRest/assets/55968519/adf286af-880c-4f37-8566-ddda1ff61ede

**Review by ilyaflaks — APPROVED** [review]
I reviewed the functionality and the code changes and everything works well!
Reproduced the issue by editing badge UUID in Compass:
PR666-dev-branch-dupl-result-03
Assigned a new badge of a different kind on the front end: 
PR666-roberto-branch-assign-4
The duplicates are now grouped together: 
PR666-roberto-branch-grouped-05
I then reproduced the problem again and tested if changing the badge count groups the badges:
PR666-roberto-remove-dup-byincr-06
The duplicate badges are grouped together! 
PR666-roberto-remove-dup-byincr-07
Very good, clean code! fillEarnedDateToMatchCount is now much more robust and the overall logic of combining "earnedDate" is now easier to follow

**Review by ChengyanOo — APPROVED** [review]
Hi @robertoooc,

Excellent work on implementing the new feature! I've thoroughly reviewed your code and can confirm that the changes are functioning as intended. Keep up the good work!


https://github.com/OneCommunityGlobal/HGNRest/assets/69735000/11487f43-adcd-43a3-a7dc-efa65446cb10

**Review by pshereen — APPROVED** [review]
Tested the PR.
The implemented feature is working as per the requirement.
Added two new badges to a user.
Screenshot 2024-01-24 190934

Incremented count of one of the badges from 1 to 3. And the duplicate badges are grouped together.

Screenshot 2024-01-24 191331

image

The edge case of user trying to lower badges count is also handled.

image

**Review by Renanluizssx — APPROVED** [review]
Hi @robertoooc, i reviewed your application and it's correct, nice.

https://github.com/OneCommunityGlobal/HGNRest/assets/91035340/0799cb37-5e89-42b5-8bb0-1389e76987dc

**Comment by xmyoot** [comment]
Hi Roberto, I reviewed your badge feature on the front end and it looks great! working properly please reference video: 

https://github.com/OneCommunityGlobal/HGNRest/assets/15240538/3a1d7c74-d98e-4172-86b5-564b71a5fd84

**Review by Pandani07 — APPROVED** [review]
Reviewed your PR and works as intended! Great
The duplicates are grouped together and after that, all the earned dates are retained and organized in sequential order
Screenshot 2024-01-30 at 3 23 54 PM
Screenshot 2024-01-30 at 3 21 38 PM

**Review by XiaohanMeng — APPROVED** [review]
Hi @robertoooc, 

I've tested the PR you submitted, and I'm pleased to report that it runs smoothly and the code is efficient. My testing procedure involved the following steps: I used an admin account to change the badge of a volunteer account; then, in MongoDB Compass, I modified the badge to be the same as another; upon refreshing, all identical badges were successfully merged. Additionally, I observed that adding a badge also results in the merging of identical badges. Well done on implementing this feature.

https://github.com/OneCommunityGlobal/HGNRest/assets/113215317/8c8eaf66-afa6-45b1-98dd-d81273fa2275

**Review by brandta-1 — APPROVED** [review]
# Review
I've reviewed the code in ```src/controllers/badgeController.js``` and tested through the front end as well as MongoDB Compass. The changes are functioning correctly.


# Videos:

## Splitting duplicate badge dates through MongoDB:

https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/e166c3de-faf2-4f8f-a5c8-f50466273810

## Creating duplicate badge dates through MongoDB:

https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/9ec8312a-258d-43ac-9bf4-8fd30de1bba4

## Creating duplicate badge as front-end admin:

https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/89280adc-41da-4836-b6fa-b96bc49b7a45

**Comment by huangweihou** [comment]
Hey Roberto, The duplicated badges add up correctly and please reference the below screenshots:
Screen Shot 2024-02-17 at 2 26 21 PM
Screen Shot 2024-02-17 at 2 27 03 PM
Screen Shot 2024-02-17 at 2 27 22 PM

**Review by huangweihou — APPROVED** [review]
Hi Roberto, The duplicate badges updated correctly and please use the screenshots as reference:
Screen Shot 2024-02-17 at 2 26 21 PM
Screen Shot 2024-02-17 at 2 27 03 PM
Screen Shot 2024-02-17 at 2 27 22 PM

**Review by peterson337 — APPROVED** [review]
HI Roberto, I tested your application, and everything worked as expected. Good job!

a

**Review by Coops023 — APPROVED** [review]
Hi Roberto, i reviewed this PR and everything works as it should, great job on this one!

PR#666

**Review by psharma1984 — APPROVED** [review]
Reviewed the PR, it works efficiently. I used an admin account to change the badge of another account; then, in MongoDB Compass, upon refreshing, found that all identical badges were successfully merged and saw the increase of the badge count as i added new badge. Screenshots for reference below
Screenshot 2024-02-22 120914
Screenshot 2024-02-22 125600
Screenshot 2024-02-22 125228
Screenshot 2024-02-22 125416

**Review by PratimaSingh02 — COMMENTED** [review]
https://github.com/OneCommunityGlobal/HGNRest/assets/48998232/46c4862e-7e76-483c-b56a-3cc1d5e9abcc

I reviewed the functionality and it works well.
When adding new badges the duplicate badge created via Compass gets merged.
However assigning a new same type of badge from the frontend again, might give a wrong count (as shown in the video). It shows one extra badge when adding the same badge, after changing directly in database.

**Comment by robertoooc** [comment]
@PratimaSingh02, nice catch! Seems like some new FE changes may have caused this problem. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1999
This new pr ^^ helps fix this issue.

**Review by DiegoSalas27 — COMMENTED** [review]
Hi Roberto. Nice work. Your code seems clean and well written. I have some questions regarding the behavior (since there could be other alternative flows in the bagde assigning process). I have attached a video with related questions about how the webpage should behave in different scenarions. Overall, I really like the simplicity of your code, it was very easy to follow along.


https://github.com/OneCommunityGlobal/HGNRest/assets/26840798/ffdc68ad-1c95-4e53-8820-5d4675775f1a

**Review by PratimaSingh02 — APPROVED** [review]
The merge functionality seems to be working great except the wrong count that shows up when adding the same type of badges. Approving the change as new [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1999) has been created for the same.

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by ChengyanOo — APPROVED** [review]
Great work, I went through your code and didn't found any code smells. Check out the last comment I left for the video

**Comment by robertoooc** [comment]
@DiegoSalas27, to clarify any doubts mentioned in your video: 
We're currently using the mongodb GUI to force duplicate badges, the cause for this is because there have been some occasions where we've seen duplicate badges pop up in a user's profile and it's not fully clear how they're being generated, so for testing purposes I am having people use the GUI to force duplicates and check the new logic fixes the bug. A duplicate badge in this case is the array of badgesCollection having instances where there are more than one object with the same badgeId as another, so basically at some point the logic was flawed and would push a new instance of a badge to the array rather than updating the contents of the object. Our previous logic for this route would also break when you tried to update the badgeCollection array if it contained duplicates because it didn't know how to handle it. 
Another thing you may have mentioned in your video was about the counts, the logic is supposed to merge the counts by adding them and all other variables of the badge if there are duplicates.

**Comment by DiegoSalas27** [comment]
> @DiegoSalas27, to clarify any doubts mentioned in your video: 
> 
> We're currently using the mongodb GUI to force duplicate badges, the cause for this is because there have been some occasions where we've seen duplicate badges pop up in a user's profile and it's not fully clear how they're being generated, so for testing purposes I am having people use the GUI to force duplicates and check the new logic fixes the bug. A duplicate badge in this case is the array of badgesCollection having instances where there are more than one object with the same badgeId as another, so basically at some point the logic was flawed and would push a new instance of a badge to the array rather than updating the contents of the object. Our previous logic for this route would also break when you tried to update the badgeCollection array if it contained duplicates because it didn't know how to handle it. 
> 
> Another thing you may have mentioned in your video was about the counts, the logic is supposed to merge the counts by adding them and all other variables of the badge if there are duplicates.

Got it. Thank you for clarifying that.

**Review by 666saofeng — APPROVED** [review]
Hi Roberto, it worked as intended. Great job!

https://github.com/OneCommunityGlobal/HGNRest/assets/62363348/ba1bfb4f-8f4b-40d2-8fa4-fe3b66db2743

**Review by cvtqx — APPROVED** [review]
Works as described - duplicate badges are grouped together.

1. User with assigned badges:


2. Added a duplicate badge to this user and the badges are grouped:



3. The issue dates of duplicates are displayed correctly:


4.Incremented count, duplicate badges are grouped together and the count is correct:



Great job!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
