### PR TITLE
yihan create editable four-letter team code option

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
To test this backend PR you need to checkout the [#1162](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1162) frontend PR.

## Main changes explained:
- Update file userProfile.js and userProfileController.js for adding teamCode property to userProfile object.
- Update file reporthelper.js for adding teamCode property to weekly summaries report object.

## How to test:
1. check into current branch
2. do `npm run build` and `npm start` to run this PR locally
3. follow test steps in front end PR #XXX

### CODE REVIEW

**Review by tsunami776 — APPROVED** [review]
Tested with FE PR #1162. After commenting out lines 116~126 of /src/components/WeeklySummariesReport/WeeklySummariesReport.jsx, BE initializes and saves Team code as described in the PR.

PR Review #480_1

**Review by Haoj1 — APPROVED** [review]
Nice work @AriaYu927! Backend works on my end and no bugs. The test videos are in FE#1162. The loading time when first entering the weekly summary pages is a little bit longer? Perhaps spliting records into pages could be an option?

**Review by winghojackyli — APPROVED** [review]
Hi @AriaYu927 , I've tested this PR with the frontend PR #1162. Comments left here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1162#pullrequestreview-1597073104

**Review by robertoooc — APPROVED** [review]
Hi @AriaYu927, I tested your branch along with [frontend branch 1162](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1162#pullrequestreview-1601566984l). This backend branch didn't provide any issues and worked well.

**Comment by Shubhu0** [comment]
Tested the PR, works well with no noticeable errors.

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I have left comments at frontend PR#1162.

**Pull request merged**
