### PR TITLE
Shadhrush - Fixing "Send Emails" visibility for Volunteers with 'Other Links' access and adding a new Send Emails Permission

### PR DESCRIPTION
**Pull request by Shadhrush5**
# Description
image
image
Controller method includes role and permission checks before sending emails in the backend.

## Related PRS (if any):
To test this backend PR you need to checkout the #2572 frontend PR.
…

## Main changes explained:
-Added checks to the controller method before sending out emails.
…

## How to test:
check into current branch
do npm install and ... to run this PR locally
Clear site data/cache
Please follow the remaining steps in frontend PR

### CODE REVIEW

**Review by Parth-tech — APPROVED** [review]
Hi Shadrush,

The PR works well. Great job done. 
Left a review on the front end repo. [Frontend review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2572#pullrequestreview-2252920654)

**Review by skaush21 — APPROVED** [review]
Reviewed Implemented code. Code checks out, this will work for its intended case. Great work! Left a comment in frontend as well [PR #2572](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2572/files)

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected. left a review on the [front-end](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2572#pullrequestreview-2255697587)

**Review by SMitta11 — APPROVED** [review]
The front end PR works fine.Left a comment at frontend PR.

**Review by nathanah — APPROVED** [review]

**Review by sri0606 — APPROVED** [review]
Hi @Shadhrush5 ,

Everything worked as expected. I have left a comment on the[ frontend PR too](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2572#pullrequestreview-2273388044).

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
