### PR TITLE
Improve cache behavior when creating/deleting/updating user data

### PR DESCRIPTION
**Pull request by stevenwang213**
This PR focuses on backend cache improvement.
This PR modifies the cache based on different user management operations e.g. creating, deleting, and updating user profile, rather than removing the whole user cache. 
By doing this, we can save the loading time of the app and eliminate the need to access the database whenever we just make a slight change to one user profile.

### CODE REVIEW

**Comment by migfernandes01** [comment]
While testing this, I couldn't add and update a user. I did `git pull` to make sure I was using the most recent changes. Delete works though and it looks good!
Here are the errors:
error creating user
error updating user

**Review by stevenwang213 — COMMENTED** [review]
I tried "add" and "update" again, but I didn't get any error at local. Did you get any error messages in the terminal?

**Comment by migfernandes01** [comment]
I ran `npm run serve` this time and it worked all well!

**Review by migfernandes01 — APPROVED** [review]
Passed all tests

**Pull request merged**
