### PR TITLE
Abi wbs tests

### PR DESCRIPTION
**Pull request by Abi-Liu**
# Description
Full unit and integration test suite for WBS controller and routes.

## Related PRS (if any):
N/A

## Main changes explained:
- Unit testing controller methods
- Integration testing routes
- 
## How to test:
1. check into current branch
2. do `npm install` 
3. Run `npm run test wbs`
4. verify all tests pass

## Screenshots or videos of changes:
Screenshot 2024-05-07 at 3 10 06 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Ramaruva — APPROVED** [review]
Hey I have run the given test cases in my local env and all test cases are passed
image

**Review by linkhanthtel — APPROVED** [review]
All tests passed as expected! Nice work!

**Review by MinSun0814 — APPROVED** [review]
image
All tests passed as intended. Nice work!

**Review by j-corp-25 — APPROVED** [review]
Hi @Abi-Liu ,

The tests are working now. I switched to my macbook and all tests are passing. Im glad It was something with my windows setup. I'll make sure to run the test on my macbook and not windows going forward for better accuracy. Awesome work on these tests!

Screenshot 2024-05-09 at 11 55 35 PM

**Review by gowthamdongari — APPROVED** [review]
All test cases working fine in local 
image

**Review by DiegoSalas27 — APPROVED** [review]

**Comment by DiegoSalas27** [comment]
Excelent PR and through Unit and Integration tests. Please follow Abi's PRs for your own unit and integration tests. This is what a perfect unit and integration tests looks like.

**Pull request merged**
