### PR TITLE
Attempting to Fix Weekly Summary Server Error

### PR DESCRIPTION
**Pull request by chrisweilacker**
Attempting to Fix Weekly Summary Server Error via a change in locale to en.

### CODE REVIEW

**Review by MalathiMe — COMMENTED** [review]
Chris, 

Are these fix available in dev env(https://hgnapplication_react_dev.surge.sh/dashboard)?

**Comment by chrisweilacker** [comment]
Well this fix needs to be merged which requires a review first, it will then be applied to both dev and beta I think.

**Comment by chrisweilacker** [comment]
Not needed.

**Review by MalathiMe — COMMENTED** [review]
Looks good from my end

**Pull request closed without merging**
