### PR TITLE
Shihao - Improve Summary Loading Performance

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Screenshot 2023-08-24 at 17 51 20

## Related PRS (if any):
This backend PR is related to the [#1172](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1172) frontend PR.

## Main changes explained:
- Update query

## How to test:
Follow the instructions in [#1172](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1172) to test

### CODE REVIEW

**Review by DavidC0126 — APPROVED** [review]
I left my comment on FE PR.

**Review by vinaykumarh — APPROVED** [review]
Detailed review commented on FE PR #1172.

**Review by veronicacheng2 — APPROVED** [review]
Hi @sxiong5, tested together with [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1172). Comments left on the frontend.

**Comment by beblicarl** [comment]
I have tested both the frontend and backend of this functionality and both works well

**Review by beblicarl — APPROVED** [review]

**Review by Haoj1 — APPROVED** [review]
@sxiong5 Good job! Commented review in #1172

**Comment by Shreyj14** [comment]
Hi @sxiong5  Tested this PR with frontend #1172. Great Work.

**Review by scoopstroop92 — APPROVED** [review]
Works as expected. Good job

**Comment by zuhang2000** [comment]
I tested this PR with front-end PR #1172. Good job!

**Review by zuhang2000 — APPROVED** [review]
I tested this PR with front-end PR #1172. Good job!

**Review by ss23046 — APPROVED** [review]
Hi @sxiong5 , I reviewed the PR, good job, it's much quicker now

https://github.com/OneCommunityGlobal/HGNRest/assets/99052235/416438be-d68e-46af-82d1-1f92737feaeb

**Review by yaow62023 — APPROVED** [review]
Tested this PR at pr#1172.

**Review by winghojackyli — APPROVED** [review]
Hi @sxiong5 , I've tested this PR with the frontend PR #1172. Comments left here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1172#pullrequestreview-1597073940

**Pull request merged**
