### PR TITLE
Luis unit test inventory controller get all inv in project

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description
Unit Test for getAllInvInProjectWBS, postInvInProjectWBS, getAllInvInProject

## Related PRS (if any):
N/A
…

## Main changes explained:
- Unit tests for getAllInvInProjectWBS, postInvInProjectWBS, getAllInvInProject
- Integration tests for map locations router
…

## How to test:
1. check into current branch
2. do `npm install` 
3. run `npm run test inventoryController`
4. Verify all tests pass

## Screenshots or videos of changes:
Screenshot 2024-07-22 at 9 44 06 PM

## Note:
Please note I submitted a previous PR with a few test, but I re-did them to relearn and improved it as well.
Here is the previous PR 921
https://github.com/OneCommunityGlobal/HGNRest/pull/921

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (142)

**Review by ishan-miglani — CHANGES_REQUESTED** [review]
Hi, 8 out of 11 test cases are being skipped here. Please address this. Thanks!
Screenshot 2024-07-23 at 11 50 06 PM

**Comment by luisarevalo21** [comment]
> Hi, 8 out of 11 test cases are being skipped here. Please address this. Thanks! Screenshot 2024-07-23 at 11 50 06 PM

@ishan-miglani resolved! Forgot I left a '.only'

**Comment by luisarevalo21** [comment]
> I have tested the PR and all the test cases have passed. Screenshot (142)

@nikhilpittala16 Hello, please re-test it and ensure all passes pass. There should 11 passed in total.

**Review by ishan-miglani — APPROVED** [review]
Verified that all 11 test cases are passing. Thanks!
Screenshot 2024-07-25 at 10 09 19 PM

**Review by Annezhang673 — APPROVED** [review]
All 11 tests cases passed. 
PR1044

**Review by Chetan0606 — APPROVED** [review]
Followed the description and verified accordingly. Here's my observation.

image

**Review by SrikanthChowdary495 — APPROVED** [review]
I have tested this PR. All the test cases passed successfully. 
7tests

**Review by Shadhrush5 — APPROVED** [review]
Hi, I reviewed the PR #1044. The tests execute as expected. Thank you for the great work.

Screenshot 2024-07-26 at 11 58 02 AM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and now all the test cases have passed. sorry for the confusion.
Screenshot (154)

**Review by Parth-tech — APPROVED** [review]
Hey Luis,
All test cases passed. Good job.
Screenshot 2024-07-26 at 10 05 15 PM

**Review by jinxyou — APPROVED** [review]
All test cases passed. Great work!
image

**Review by vamshik2024 — APPROVED** [review]
I have reviewed the PR and all 11 test cases passed

image

**Review by kabraambika — APPROVED** [review]
I have reviewed this PR and all test cases are passing for inventoryController.spec.js as shown below:

image

**Comment by mianmiantea2019** [comment]
I have reviewed the PR and all 11 test cases passed

image

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Review by gowthamdongari — APPROVED** [review]
All test cases working well
image

**Review by Pranay-ai — APPROVED** [review]
Hey i have tested the PR and the test cases work right
image

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-08-03 at 8 27 11 AM

**Review by ReinaT5678 — APPROVED** [review]
All the tests passed!

Screenshot 2024-08-03 at 2 34 52 PM

**Review by SatyashanthiT — APPROVED** [review]
Tested this PR and have found all the necessary changes working correctly.

image

**Review by DiyaWadhwani — APPROVED** [review]
Hi Luis,
All tests have passed. Attached a screenshot below.
Thank you

**Review by linkhanthtel — APPROVED** [review]
All test cases passed!

PR #1044

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
