### PR TITLE
kaixiang-fix-make-intangible-hours-editable

### PR DESCRIPTION
**Pull request by KaixiangGU**
This PR is related to FE PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/635

### CODE REVIEW

**Comment by rauleffting** [comment]
I reviewed your code. Think it worked quite well on changing intangible hours, both in the profile: 

ss2

And in the dashboard:

ss1

However, it's showing an error alert when saving changes. It seems not affecting the functionalities, but I think this is not supposed to appear:

ss3

I imagine this is a [backend](https://github.com/OneCommunityGlobal/HGNRest/pull/267) issue.

Once this small error is corrected, I believe we can approve the front and back PRs.

Thank you very much!

**Review by rauleffting — CHANGES_REQUESTED** [review]
I reviewed your code. Think it worked quite well on changing intangible hours, both in the profile: 

ss2

And in the dashboard:

ss1

However, it's showing an error alert when saving changes. It seems not affecting the functionalities, but I think this is not supposed to appear:

ss3

I imagine this is a [backend](https://github.com/OneCommunityGlobal/HGNRest/pull/267) issue. It may be in the userProfileController.js.

Once this small error is corrected, I believe we can approve the front and back PRs.

Thank you very much!

**Review by rauleffting — APPROVED** [review]
After pulled the development branch, it worked perfectly!

**Review by rauleffting — CHANGES_REQUESTED** [review]
Why were so many tweaks made to the code format? It is difficult to review what has been done.

Thank you!

**Review by rauleffting — APPROVED** [review]
I understood what you did and I'm going to approve it. However, watch out for excessive formatting changes. This makes it difficult to know where the code has changed.

Thank you very much!

**Comment by RafaelCastilhoCastro** [comment]
Hi @KaixiangGU,
Please check my review in FE PR #635.

Thank you.

**Comment by PrabhjotSembhi** [comment]
@KaixiangGU Hey, I do not see the option to edit intangible hours. 
 
PR 635

**Comment by Filipe-Oliv** [comment]
Hi @KaixiangGU 


The total tangible hours was zero after I saved the intangible/tangible time.


After I edited the time from 24h to 19h I returned to the  user profile...


Then I noticed that tangible time was negative.

**Review by Filipe-Oliv — DISMISSED** [review]
Let me know whether or not this negative tangible time is part of your PR. If not, I will return your PR for approval.

**Review by PrabhjotSembhi — COMMENTED** [review]
it's not working correctly when I check the box to switch intangible to tangible Time is not get updated. Please watch video 

https://user-images.githubusercontent.com/82662768/219467957-dd823194-98f2-45b6-becd-32536d9946bd.mp4

**Review by suigunfjc — COMMENTED** [review]
Hi @KaixiangGU, I tested checking and unchecking the intangible timelog and the profile updated the intangible time correctly. Except for the error popup when saving the change, everything else looks pretty good to me.

https://user-images.githubusercontent.com/94319381/219909531-cf48cc95-a177-4b25-be46-efd4704cf935.mp4

**Comment by kamtoeddy** [comment]
Hi @KaixiangGU,
Both tangible and intangible fields are editable but I noticed that **Weekly Committed Hours** can be more than 168h (the maximum number of hours in a week). I don't understand why this is allowed

Screenshot (501)

**Review by kamtoeddy — APPROVED** [review]

**Comment by harlleybastos** [comment]
@KaixiangGU Just tested as I said on the Frontend PR and it's okay besides the error that is already fixed on development branch.

https://user-images.githubusercontent.com/37200778/221200045-948ba2e1-482f-4553-8cc1-f302f8df1518.mp4

**Comment by NyahJ** [comment]
Hi @KaixiangGU,

You changes works well from my side, following your test steps on #635 of FE.

There are two ways to send the input. However, they have their own disadvantages:
1. The increase/decrease button (shown in the first screenshot below), but every click increases/decreases only 0.01, which is positive number acceptted only but lack of efficiency;
2. Manually input, as I tried "accident" negative hours (shown in the second one as below), it worked for every rows. 

So, if this is acceptable or do we need to care about this tiny issue? @one-community 

截屏2023-02-24 上午11 44 25

截屏2023-02-24 上午11 37 19

**Comment by one-community** [comment]
Good catches. 

1. Please make the up button increase the numbers by whole numbers. 
2. Please make it so it's not possible to have negative numbers in any of those rows.

**Comment by Lunaliar** [comment]
Hey, @KaixiangGU  I am able to edit intangibleHrs and Im not able to set them to negative values if I try they save back to 0. Good job!

**Comment by dkamghem** [comment]
I am only able to modify what is in the boxes. It does not affect the time on the dashboard though. 
IMG_2381

**Review by rauleffting — APPROVED** [review]
Hi, @KaixiangGU. I've tested your PR and it worked perfectly.

https://user-images.githubusercontent.com/29555732/228068576-0d2c380f-2584-4e0a-bf81-928dbf37f68d.mp4

I verified that you also made the changes that I requested.

Thank you very much! Approved!

**Comment by one-community** [comment]
Shoot, merged the frontend that goes with this without realizing we've still got merge conflicts here. Please fix those ASAP so I can merge this backend too.

**Pull request merged**
