### PR TITLE
Jianjun - Fix the permission of changing user status

### PR DESCRIPTION
**Pull request by juneluo**
# Description
Fixes 5. (PRIORITY MEDIUM) Vitor/Jae: Fix the "Change User Status” permission
ADMIN LOGIN → Other Links → Permissions Management
When adding this permission it should give access on another person’s profile to edit the green button beside the name of the user profile you are viewing

## Related PRS (if any):
To test this backend PR you need to checkout [the frontend PR904](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/904).

## Main changes explained:
- add 'changeUserStatus' and 'submitWeeklySummaryForOthers' as the initial permissions of the Owner and Admin role.

## How to test:
1. check into current branch
2. do `npm run build` and `npm start` to run this PR locally

## Note:
The bug fix is mainly about the 'changeUserStatus', while the 'submitWeeklySummaryForOthers' is just added because it has not been included in the previous merged PR that introduces this permission (just make changes in the front end code).

### CODE REVIEW

**Review by EdwinLauM — APPROVED** [review]
Code changes look good! Left a more detailed comment in the FE PR

**Review by nathanah — APPROVED** [review]
Looks good.

**Review by nathanah — CHANGES_REQUESTED** [review]
After testing, I found the permissions are not used on the backend. I can edit my frontend permissions in dev tools and the changes will go through.
https://github.com/OneCommunityGlobal/HGNRest/assets/23086054/7ca62d8f-4201-4361-b8b8-0637ca01ed23

**Comment by nathanah** [comment]
> > After testing, I found the permissions are not used on the backend. I can edit my frontend permissions in dev tools and the changes will go through. https://github.com/OneCommunityGlobal/HGNRest/assets/23086054/7ca62d8f-4201-4361-b8b8-0637ca01ed23
> 
> The update added to the back-end barely changes the initial permissions of the user class. This `permissions` attribute stores with the roles and any changes to them will become effective to all the users of that class (for example, `roles[0].permissions`). I believe the frontend permissions are stored along with each user (for example, `this.props.auth.user?.permissions?.frontPermissions`), giving the permission to one user(the user can be any role) will not affect the permissions of other users in the same class. When we check the permission of an action using `hasPermission` function, it will check the list from both and either one includes the action it will return true, making the changes go through. Therefore, it should be right to have it works as the video shows.

I don't think ``changeUserStatus`` ever calls ``hasPermission``.

**Comment by nathanah** [comment]
I see. Ok, I'll speak to Jae.

**Comment by nathanah** [comment]
>You may find other permissions are checked in the same way without touching more files at the back end.
Looking at ``userProfileController.jsx``, it seems there are still many functions that do call ``hasPermission()`` to verify that the requesting users do in fact have permission. If there are cases where permissions are only on the front-end, any user can modify their front-end to circumvent them and they should be considered suggestions instead of real permissions.

**Comment by nathanah** [comment]
```
    if (!hasPermission(req.body.requestor.role, 'changeUserStatus')) {
      res.status(403).send('You are not authorized to change user status');
      return;
    }
```
Ok, I spoke to Jae. Add this to the beginning of ``changeUserStatus()`` in ``userProfileController.js``.

**Review by nathanah — APPROVED** [review]

**Comment by nathanah** [comment]
> It will be great if you can also check other permissions and raise a PR to fix them.

I'll do that.

**Comment by Lucas-E** [comment]
Hey @juneluo, great job! please resolve the conflicts so I can move it to final review! DM me when it's ready!

**Comment by Lucas-E** [comment]
Thank you! Moving to final review!

**Pull request merged**
