### PR TITLE
add bio requested status to report page

### PR DESCRIPTION
**Pull request by juneluo**
### Description
Add a “Bio Posted/Requested” selection to the Reports page
1. This is so anyone looking at the reports page knows if a person’s bio announcement is in the process of being created or already created.  
2. Changing this should auto-save (show saving notification like saving an intangible time log) but not refresh the page 
3. It should be editable by Owner/Admin class only

### Mainly changes explained:
add a new attribute `bioPosted` to the userProfile to store the status.

### How to test:
**Please test with the [front end PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/807).**
checkout this branch
for the server:
`npm run build`
`npm start`
for the front end:
`npm run start:local`
run the front end and test

### CODE REVIEW

**Review by abdel-lall — APPROVED** [review]
LGTM.

**Review by GKD890 — APPROVED** [review]
Tested for both frontend and backend. all looks good.

**Review by wang9hu — APPROVED** [review]
Works as described! Good job!

**Review by EdwinLauM — APPROVED** [review]
Works as intended! Left a comment with screenshots in the Frontend PR (#807)

**Review by alexander-huerta — APPROVED** [review]
Great work! Clean code

I confirmed the functionality in [my review ](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/807#pullrequestreview-1419039589)of the connected Front End PR 807

**Comment by one-community** [comment]
Thank you all, moved to final review

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
