### PR TITLE
Jerry - Track Who Changes Permissions On Permissions Management Page

### PR DESCRIPTION
**Pull request by jerryren527**
# Description
description

Edit (Sep 21, 2023): Added a table on the Permissions Management page that fetches the permissionsChangeLogs from the dev database. Only Owner accounts can view see the table. Admin accounts are unable to see the table.

## Related PRS (if any):
* FE PR [#1277](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1277)

## Main changes explained:

- Added `permissionChangeLog` schema
- Created a logging function and a middleware function that adds a log to the `permissionChangeLogs` collection in the dev MongoDB database.
- Applied middleware function to PATCH `/roles/:roleId` route.

**Edit (Sep 21, 2023)**: 
* Created controller and router for operations on the `permissionChangeLog` collection.

## How to test:

1. check into current branch. 
2. do `npm install` and `...` to run this PR locally
3. Go to FE PR and follow “How to test” instructions there to start the frontend.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/55968519/8fa9c22e-0fc3-46a4-a38c-955b9044201b

## Note:

It would be ideal for the `permissionChangeLogs` collection to be read-only and for the logs to have an expiration date (i.e., be automatically deleted after some set amount of time). From my understanding, these configurations can be made to the database by Jae or any trusted developer. If there it is possible/preferable to set these configurations in a Node.js environment, please let me know!

### CODE REVIEW

**Review by EdwinLauM — APPROVED** [review]
Hey @jerryren527! Left a more detailed review in the FR. Good job!

**Comment by DavidC0126** [comment]
I tested the PR with FE [PR#1277](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1277#pullrequestreview-1616369656), and I left a detailed comment on FE PR.

**Review by winghojackyli — APPROVED** [review]
Hi @jerryren527 , I've tested the PR and it worked great with the frontend. Comment with video left here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1277#pullrequestreview-1618728846

**Review by GaryB93 — CHANGES_REQUESTED** [review]
I found in testing that only one permissionChangeLog was logged for me when changing permissions for the Jerry Test Role multiple times. Not sure how fast the dev database should be updating but I figured it would be instant. Is a change log supposed to be stored anytime permissions are changed for a role? Would like further testing to make sure changeLogs are logged every time permissions are changed for a role.

Screenshot 2023-09-10 at 2 45 51 PM

**Comment by jerryren527** [comment]
> I found in testing that only one permissionChangeLog was logged for me when changing permissions for the Jerry Test Role multiple times. Not sure how fast the dev database should be updating but I figured it would be instant. Is a change log supposed to be stored anytime permissions are changed for a role? Would like further testing to make sure changeLogs are logged every time permissions are changed for a role.
> 
> Screenshot 2023-09-10 at 2 45 51 PM

Hi @GaryB93,

Thanks for reviewing my branch. I was unable to reproduce having only one permissionChangeLog logged when Jerry Test Role is changed multiple times. Please take a look at my screen recording where I made multiple changes to Jerry Test Role, and each individual role permissions change resulted in one log in the permissionChangeLogs collection:

https://github.com/OneCommunityGlobal/HGNRest/assets/55968519/8d7c6faa-313a-4bc6-a7a4-33b134e8f1d6

By the way, I am pressing cmd + R on mac to refresh the mongodb collection.

I would appreciate a screen recording of you making multiple role permissions changes that result in one permissionChangeLog. Thanks!

**Review by GaryB93 — APPROVED** [review]
Hey @jerryren527, I was able to verify the functionality of this PR with FE PR#1277 and a permission change log is being logged when someone updates the permissions on a user. Not sure why it wasn't working for me before. Great work!

**Review by Shiwani99 — APPROVED** [review]
Hi,
Good job. I have added my comments for front end PR#1277.

**Comment by wantingxu7** [comment]
Hi Jerry, I've tested this with FE and comment there

**Review by robertoooc — APPROVED** [review]
Pr works well as intended with FE 1277. Left comments and video on frontend pr.

**Review by malikjahanzaib — APPROVED** [review]
Hi @jerryren527, I have tested the features added in this PR.  Everything seems to work nicely. Left detailed review on the FE #1277. Nice work!

**Review by StrawberryCalpico — APPROVED** [review]
Hi I tested your PR, details at [FE#1277](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1277#pullrequestreview-1677816789)

**Comment by Lin1404** [comment]
I tested the PR with FE, and I left a comment on FE PR.

**Review by Lin1404 — APPROVED** [review]

**Pull request merged**
