### PR TITLE
Alex - Create a Pull Request Template

### PR DESCRIPTION
**Pull request by alexander-huerta**
Following the GitHub Docs, I am creating a pull request template in order to save time and create consistency in the teams PR formatting. 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### CODE REVIEW

**Review by nathanah — APPROVED** [review]
Looks good

**Review by drewlong314 — APPROVED** [review]
The template looks good.

**Review by GKD890 — APPROVED** [review]
looks good to me

**Review by yoyoweiii — APPROVED** [review]
This template looks good to me! It covers all the information PR need to know.

**Review by wechuli — APPROVED** [review]
Looks good to me!

**Pull request merged**
