### PR TITLE
Nathan permission presets

### PR DESCRIPTION
**Pull request by nathanah**
# Description
This PR addresses `Create a “Restore To Default” functionality that restores the user permissions to the default configurations`.

## Related PRS (if any):
This backend PR is related to frontend PR #1374.
To test this backend PR you may need to checkout the frontend PR unless testing with Postman.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1374

## Main changes explained:
- created `rolePresetsController`, `rolePreset` model, and `rolePresetRouter`
- added creation of `default` presets for the hard-coded permissions in `createInitialPermissions.js`. These will be updated every time the server starts.

## How to test:
Follow instructions on frontend PR. Can also test new APIs with Postman if desired.

### CODE REVIEW

**Review by wantingxu7 — APPROVED** [review]
Hi @nathanah 
I tested it and it works as intended, left comment in FE 1374. Good work!

**Review by navneeeth — APPROVED** [review]
Hi! Tested your changes and they LGTM! Commented a full review on the frontend PR.

**Comment by Shreyj14** [comment]
Hi! Tested your changes and they LGTM! Commented a full review on the frontend PR.

**Review by Shreyj14 — APPROVED** [review]

**Comment by AriaYu927** [comment]
@nathanah , I've tested your PR and it looks good! Also left a comment under frontend PR.

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. Left my comments at frontend PR#1374.

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr with 1374 and it works great. I left my comment at FE.

**Review by malikjahanzaib — APPROVED** [review]
Hi @nathanah, I have tested the PR and my detailed review and test recording is in the frontend PR #1374 thread. Great job!

**Comment by Lin1404** [comment]
@nathanah , I've tested your PR and it looks good! Also left a comment under frontend PR.

**Review by Lin1404 — APPROVED** [review]

**Review by StrawberryCalpico — APPROVED** [review]
Hi! I tested you PR, it worked really well! Great Job, details in [#1374](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1374#pullrequestreview-1665326150)

**Comment by RheaWu1212** [comment]
Hi, I test this pr with 1374 and it works great. I left my comment at FE.

**Pull request merged**
