### PR TITLE
Huijie - fix ability edit start and end date

### PR DESCRIPTION
**Pull request by metaphor987**
# Description
task description

## Related PRS (if any):
This backend PR is related to the #2655 frontend PR (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2655).

## Main changes explained:
1. When the accounts start date or end date is being saved, assume that the entered date on userprofile page is in 'America/Los_Angeles' time zone. This will prevent some time zone errors.

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm start` to run this PR locally
3. clear site data/cache
4. log as an owner or admin user
5. Please check #2655 frontend PR for more details. Thank you!

### CODE REVIEW

**Review by AJAYINAVOLU — APPROVED** [review]
Reviewed the PR on the frontend [repo](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2655#pullrequestreview-2293043116).

**Review by RishithaMamidala — APPROVED** [review]
Reviewed it in the frontend PR.
Working as expected.

**Review by vishnupriyaatheti — APPROVED** [review]
@metaphor987 Changes are working as expected and provided the comments on frontend PR.

**Review by anirudhsk2107 — APPROVED** [review]
The changes are working as expected. 
Provided a review in the frontend PR 1442

**Review by Lexie5212 — APPROVED** [review]
Code changes worked as expected! 

https://github.com/user-attachments/assets/7baf8920-1090-4ce8-9167-133273a0a979

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
