### PR TITLE
Sucheta - Make It Known When New AI Prompt is Available

### PR DESCRIPTION
**Pull request by sucheta90**
# Description
(PRIORITY HIGH) Jae: Make it clear when a new AI Prompt is available (WIP Sucheta)
- Related [PR1510](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1510)
- The AI Prompt is now editable. I’d like it to be obvious to a person when they see the button below for the first time after the AI Prompt has been updated.
Screenshot 2024-01-20 at 8 41 37 PM

- Ideally, I’d like it to look like what’s shown below: 
   - Cleaned up [200x160px image link ](https://www.dropbox.com/scl/fi/0g9cvqlzy9gj00sie28mk/New-HGN-Icon-11kb-200x160px.png?rlkey=vkngel8ezl0cbhbjutmlotvin&dl=0)to use. Give me the exact dimensions needed and I’ll create a new one. 
- After a person has copied the link for the first time, the button should return to what you see above.
Screenshot 2024-01-20 at 8 39 50 PM

## Related PRS (if any):

To test this backend PR you need to checkout the [#1899](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1899) frontend PR.
…

## Main changes explained:
- Adds new property `modifiedDateTime` to `weeklySummaryAIPrompt` - model
- Adds new property `copiedAiPrompt` to `userProfile` - model
- Adds new end points to get and put the `CopiedPromptDate`.
- Updates the `modifiedDateTime` when the owner edits the Ai prompts.
- Updates the `copiedAiPrompt` when a user copies the Ai prompt.
…

## How to test:
1. Check into current branch
2. Do `npm install` , `nmp run build` and `npm start`  to run this PR locally
3. Clear site data/cache from browser's `Application` tab.
 
Test as `OWNER`: 
1. Log as `Owner` user
2. Go to WeeklySummary submission modal, then click the button `View and Copy Current AI Prompt`. As an owner, the user should have the permission to edit the AI prmpt. 
3. Once the AI prmpt has been updated, the button changes to show a `new` icon - making it visually known that the AI prompt has been updated. 
4. The visual indication will only persist until the user has copied the updated Ai prompt. Once copied , the button changes and the `new` icon disappers.

Test as any other user:

1. Log as any user
2. Go to WeeklySummary submission modal. 
3. The button `View and Copy Current Ai Prompt` should be normal if there is no change in the AI prompt since last time the prompt was copied
4. If the AI prmpt was updated, the button changes to show a `new` icon - making it visually known that the AI prompt has been updated. 
5. The visual indication will only persist until the user has copied the updated Ai prompt. Once copied , the button changes and the `new` icon disappers.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/101291283/12ab0141-28a5-41ba-afc5-133aa4f9b71a

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by pshereen — APPROVED** [review]
Tested the PR and the implemented features are working as per the requirement.

Please check the comments in the related frontend PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1899

**Review by Pandani07 — COMMENTED** [review]
The team member tasks  is not loading and is shown as a black box for any account i use 
Screenshot 2024-01-31 at 6 42 15 PM

**Review by SaiDeepak-NEU — APPROVED** [review]
Checked into the frontend PR 1899 and tested the changes. Logged in as owner first and edited the AI prompt. Was able to see the NEW icon after editing prompt and the icon dissapeared after copying.

Then logged in as Volunteer and could see the NEW icon there as well and the icon dissapeared after copying and no edit option was there for volunteer.

Screenshot (36)
Screenshot (35)
Screenshot (34)

**Review by Pandani07 — APPROVED** [review]
Tested this PR and the functionality works as intended. I have left comments on the frontend PR #1899


https://github.com/OneCommunityGlobal/HGNRest/assets/44672833/9da0b3d7-ed97-4148-a4dc-679072fc78dc

**Review by yvonnep165 — APPROVED** [review]
Hi @sucheta90 ,

I have tested this PR with PR 1899 from frontend and the functionality works as intended. I have left a comment on PR 1899.

**Review by KevHnh — APPROVED** [review]
Tested with related Frontend PR. The icon is displayed properly when the prompt is changed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1899

**Comment by galgalinidhi** [comment]
Hi @sucheta90, I left a comment  here -https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1899.

**Review by Renanluizssx — COMMENTED** [review]
see my review @sucheta90 please: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1899

**Review by mohabbasd — APPROVED** [review]
Hello, this is the backend PR for the frontend PR #1899 and it is working perfectly.

**Comment by beblicarl** [comment]
I tested the frontend and left a comment. All functionality works as intended

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
