### PR TITLE
Luis fix user profile projects delay

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description

Screenshot 2023-11-05 at 7 42 52 PM

## Related PRS (if any):
To test this backend PR you need to checkout development branch 
…

## Main changes explained:
On the backend I added a check to remove cache.
The issue was the backend was sending back old cache instead of clearing it when a project was added.
Hence it was sending old data.
The change occurs in ProjectController.js inside of the assignProjectToUsers() when mapping over each element cache is checked if so it removes it and adds the user.

## How to test:

1. check into current branch
2. The frontend should be development, check into and run`npm install`
3. **Note** if you are getting the WBS error, you may need to pull the latest development branch
4. Run on the backend `npm run install`,  then build and run the server `npm run build && npm run start`
5. log as admin user or owner account
6. go to view-profile→ projects→ take note how many projects are there.
7. Next go to other links → projects → select a project → add your current user that you are logged in as.
8. Add the user then navigate to the view-profile→ projects→ and check if the project was added to the list of projects.
9. Next click timelog check to see if the project is in the list of tasks.
10. click "add tangible time entry"
11. click on projects/task and see if the newly added project is inside of the drop down menu

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/96cb30a8-34a6-43d9-89a1-39998f196a21

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/59580642-563d-44a8-9a70-9091121d4c65

Updated video

https://github.com/OneCommunityGlobal/HGNRest/assets/22454953/b1e9172a-d0bb-442a-831d-29c9ba7784ea

## Note:
There was a front end branch but for some reason, it removed the projects. 
Upon testing the development branch worked just fine. So, I may have adjusted the frontend which caused the issue. 
However, checking ino the development branch then pull this backend, fixes everything. 
There are a few errors that pop up on the frontend please disregard them as they are irrelevant to this PR.
Screenshot 2024-04-11 at 7 48 51 PM

### CODE REVIEW

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hi @luisarevalo21, checkout my detailed [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1496#pullrequestreview-1716881087) on [FE PR #1496](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1496).

**Comment by Shuhua-L** [comment]
Hi @luisarevalo21, I left a detailed [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1496#pullrequestreview-1721422771) on the FE PR.

**Comment by luisarevalo21** [comment]
Hello @Shuhua-L  and @malikjahanzaib 
Please re-review this PR and view the changes. 
Notable changes are, there is no longer a Frontend PR only this backend. 
The instructions are the same. 
I've also closed the front end branch

Thanks

**Comment by Shuhua-L** [comment]
> Hello @Shuhua-L and @malikjahanzaib Please re-review this PR and view the changes. Notable changes are, there is no longer a Frontend PR only this backend. The instructions are the same. I've also closed the front end branch
> 
> Thanks

Thanks for letting me know! Happy to review. However, there are a lot of formatting changes, making it a bit challenging for me to identify the actual modifications. Could you help by reducing some of those changes?

**Comment by luisarevalo21** [comment]
> > Hello @Shuhua-L and @malikjahanzaib Please re-review this PR and view the changes. Notable changes are, there is no longer a Frontend PR only this backend. The instructions are the same. I've also closed the front end branch
> > Thanks
> 
> Thanks for letting me know! Happy to review. However, there are a lot of formatting changes, making it a bit challenging for me to identify the actual modifications. Could you help by reducing some of those changes?

Hello @Shuhua-L 
Sorry for the delay. 
The actual fix is inside `controllers` `projectController.js`  inside the function `assignProjectToUsers` the code used to fixed the delay is line 182, where if there is cache for the user, it is removed, as this was causing the problem 
See the screenshot for further details 
Screenshot 2023-11-13 at 8 30 16 PM

**Review by Alforoan — CHANGES_REQUESTED** [review]
I got errors and was not able to start the server.

image

image

**Review by brandta-1 — APPROVED** [review]
# Review
Verified on current frontend branch.
# Video

https://github.com/OneCommunityGlobal/HGNRest/assets/116298512/461a1c9f-a7b8-46ed-93fb-9748b5f339ca

01_add_MongoDB

02_add_MongoDB_project

**Review by psharma1984 — APPROVED** [review]
@luisarevalo21 tested with the mentioned steps. The project shows up in the project list. Verified on current dev branch
[Screencast from 02-20-2024 09:02:19 AM.webm](https://github.com/OneCommunityGlobal/HGNRest/assets/123996264/0c9ae2ec-cc5a-42ee-b02e-36d79d580b97)

**Review by XiaohanMeng — CHANGES_REQUESTED** [review]
Hi, I attempted to test this PR using an admin account but encountered an issue when trying to assign a project to my account. After accessing the members section, I was unable to search for users, and a "404 not found" error was displayed. Please see the reference video.

https://github.com/OneCommunityGlobal/HGNRest/assets/113215317/fb8c4fc4-05e1-4dad-8f7d-116263cebf54

**Review by PratimaSingh02 — CHANGES_REQUESTED** [review]
Hi Luis, can we change the 2nd step where the commands are mentioned. After checking out into the current branch, it should be npm install first, then build and then run. As this might confuse the new developers.

**Review by PratimaSingh02 — COMMENTED** [review]
https://github.com/OneCommunityGlobal/HGNRest/assets/48998232/654abaa0-5936-439c-86d3-195ff9d6c6e2

Hi, the project works as expected.
However, when I added my name from the list of users in a particular project, I could add it twice (once directly from the list and the next time from the search result of my name)
This happened without reloading the page. 
(first I searched my name, as it took time to show the search result, I clicked "+" directly from the list, and my name got added. Then the search result appeared and I could click on "+" again. And my name got added twice.

I feel this is a React state issue that can be looked into.

**Review by skaush21 — CHANGES_REQUESTED** [review]
Error when fetching members userId.
* cleared cache
* logged in using owner account
* went to view-profile -> projects -> checked how many projects were there (3)
* went to other links -> projects -> selected a project -> attempted to add user, unable to fetch user
I took a look at the code and most of the changes seemed to be changes in formatting for readability. I noticed that there were quite a few problems related to the eslint formatting in src/helpers/userHelper.js, src/controllers/projectController.js and many more. However, these problems are unrelated to the issue with fetching the data. 

error when fetching users

eslint format issue

**Review by Coops023 — CHANGES_REQUESTED** [review]
Hi Luis, i have reviewed this PR however i get a 404 error when searching for users to add to a project.

Screenshot 2024-03-08 at 21 07 47

**Review by hetvi11110 — APPROVED** [review]
I have reviewed this PR as mentioned here, and it is working as expected. Here is the reference video.


https://github.com/OneCommunityGlobal/HGNRest/assets/13557067/defe8248-5ebf-4c67-8d26-08a49980bf43

**Review by jennZhang93 — APPROVED** [review]
Tested with owner account. Described features are working. Good work

The only thing is that during adding my current user to a project, I used the search bar at the top to search for my username. But it wouldn't return any search results (shown in video). I need to display all users and use ctrl+F to find my username. Not sure if this is within the scope of the PR but would like to point that out.

https://github.com/OneCommunityGlobal/HGNRest/assets/66922622/16921aa0-6ec7-4fa1-916c-15708ad29723

**Review by one-community — APPROVED** [review]

**Pull request merged**
