### PR TITLE
Xiao add toFixed(2) to round hour numbers to two digits

### PR DESCRIPTION
**Pull request by AuroraLovesWhales**
# Description
(PRIORITY LOW) Jae: Round hours numbers to two digits
a. Below are examples of an email for going over hours on a project and for logging too few hours in a week. I’d like these both rounded to the hundredths place so they look cleaner and more professional. 
b. Same for everywhere else hours are shown
image

## Main changes explained:
- Added .toFixed(2) to parameter hoursLogged for function notifyTaskOvertimeEmailBody in TimeEntryController.js
- Added .toFixed(2) to parameter timeSpent for function assignBlueSquareForTimeNotMet in userHelper.js

## How to test:
The following steps demonstrate how to test function notifyTaskOvertimeEmailBody in TimeEntryController.js:
1. Check into current branch
2. To send email using Gmail API using OAuth2 and nodemailer, kindly follow the first 10 mins of this tutorial (https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s) and setup a test email id and fill below variable values from the above setup in the .env file of the backend:
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = TRUE
3. Go to file HGNRest/src/cronjobs/userProfileJobs.js, comment out the existing code, and fill the code like this:

const { CronJob } = require('cron');
const timeEntrycontroller = require('../controllers/timeEntryController')();

const userProfileJobs = () => {
  const test1 = new CronJob(
    '55 * * * *', // at minute 55. You can change the minute whenever you want to test
    async () => {
      await timeEntrycontroller.checkTaskOvertime(); // the function you want to test
    },
    null,
    false,
    'America/Los_Angeles',
  );
  test1.start();
};

module.exports = userProfileJobs;

Relevant documents: 
https://docs.google.com/document/d/1j92U7Vr14gQLehr1e_gkMdqWcOA37WGxNLv9yTa96CY/edit
https://docs.google.com/document/d/1By_Ls6RGbesMgZvRzU2zIPIJtLBKMgQjabTUH2ZM8kE/edit?pli=1#heading=h.ubnt1hjxaooh
5. Do `npm install`, `npm run build`, and `npm start` to run this PR locally
6. Log as admin user, go to Other Links -> Projects -> AAA USE THIS PROJECT -> WBS -> JAE'S WBS - USE THIS, create a new task, assign a test user to the task, and input estimated hours
7. Go to the assigned user's dashboard by clicking the dot to the left of the user's name from the leaderboard, click the yellow button "Add Time Entry for user", and log tangible time entry GREATER THAN estimated hours for the task assigned to this user (the time entry should include minutes and will become infinite decimals when converting to hours)
8. Check the email you used to register for Gmail API in Step 2, verify the Hours Logged is rounded to two decimals
Pasted Graphic 6

## Note:
I can't find a way to test function assignBlueSquareForTimeNotMet in userHelper.js, but the logic is the same, so the hours should be rounded there as well. If you find a way to test this function as well, please let me know.

### CODE REVIEW

**Review by KurtisIvey — APPROVED** [review]
Getting this reviewed was definitely an experience between fighting long loading times and trying to sneak my volunteer user into tasks since the wbs was timingOut/beingAPain.  However, it all works just as intended. 
Good job. the code looks good as well

pr407

**Review by igorrochadasilva — APPROVED** [review]
Hi @AuroraLovesWhales !
I hope you are well 😃

The Pr works well. The numbers are round to two digits and the code is following the standardization of the project. 

Great job! 🚀

**Review by scoopstroop92 — APPROVED** [review]
Just tested the PR locally. Functionality works as expected. Good work 
image

**Comment by veronicacheng2** [comment]
Hi @AuroraLovesWhales, I have tried following the instructions but some problems occurred, please advise what I can do with this error:

image

P.S. the backend shows this error after I log and submit the time entry for the user

Thank you!

**Review by winghojackyli — COMMENTED** [review]
I've tested this PR and it cannot send email. I think it's not about this PR and there's some conflicts between versions of backend. 

Here's the error and email not found. 

email

**Review by winghojackyli — APPROVED** [review]
The PR works as intended. 
I can receive email for overtime. 

Capture1


Capture

**Comment by Shubhu0** [comment]
Reviewed all the previous changes to this pull request.

**Review by Shiwani99 — DISMISSED** [review]
Hi,
I tried to test your PR, and the problem is that other links is missing in administrator account. I tried to access other links in owner account, but I'm getting redirected to dashboard when I click on projects. I also tried to directly go to the projects tab through URL in administrator account, but I was again redirected to dashboard. 


https://github.com/OneCommunityGlobal/HGNRest/assets/78906820/28bd8d76-ea11-437a-bde6-cb98dac37dfc

**Review by AaronPersaud — APPROVED** [review]
LGTM. 

image

**Pull request merged**
