### PR TITLE
Jingyi unassign team members from tasks

### PR DESCRIPTION
**Pull request by Jingyii800**
# Description
Gives the user permission to UNASSIGN tasks from only their TEAM members through the Dashboard -> task -> red X. 

## Related PRS (if any):
To test this backend PR you need to check out the [#2305 Jingyi_Unassign_Team_Members_From_Tasks](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2305) frontend PR.

## Main changes explained:
- Create a new permission label
- Add checking this permission before executing the function

## How to test:
1. check into current branch
2. do `npm install`, npm run build`  and `npm start` to run this PR locally

### CODE REVIEW

**Review by peter6866 — APPROVED** [review]
Great work on the backend implementation for unassigning team members from tasks. I left a detailed review for the frontend PR.

**Review by Sandhya1236 — DISMISSED** [review]
While testing the implementation of the new permission label 'unassignUserFromTasks', several issues were encountered. This frontend PR is related to the #969Jingyi_Unassign_Team_Members_From_Tasks backend PR. The main changes involved creating a new permission label 'unassignUserFromTasks' and using dispatch to check this permission for conditional rendering in React.

After checking out the current branch and running npm install, I cleared the site data and cache. I logged in as an owner user and attempted to grant a volunteer account the permission to unassign team members from tasks through the Dashboard -> task -> red X. However, upon submitting the changes in the permission management section, an error occurred with the message: "Permission update failed. Error: Request failed with status code 400," indicating a bad request.

Additionally, I tested assigning tasks to several users from different teams. The volunteer account was supposed to unassign tasks from only their team members and not others. However, this functionality did not work as expected. Despite the permissions being set, the volunteer account could not interact with the red X to unassign users from tasks, regardless of the team association.

These issues need to be addressed to ensure that the new permission functionality works correctly and allows volunteers to unassign tasks only from their team members.


https://github.com/OneCommunityGlobal/HGNRest/assets/79351059/248e2c26-1a36-45b5-b511-fe89626ebbd8

**Comment by Jingyii800** [comment]
> While testing the implementation of the new permission label 'unassignUserFromTasks', several issues were encountered. This frontend PR is related to the #969Jingyi_Unassign_Team_Members_From_Tasks backend PR. The main changes involved creating a new permission label 'unassignUserFromTasks' and using dispatch to check this permission for conditional rendering in React.
> 
> After checking out the current branch and running npm install, I cleared the site data and cache. I logged in as an owner user and attempted to grant a volunteer account the permission to unassign team members from tasks through the Dashboard -> task -> red X. However, upon submitting the changes in the permission management section, an error occurred with the message: "Permission update failed. Error: Request failed with status code 400," indicating a bad request.
> 
> Additionally, I tested assigning tasks to several users from different teams. The volunteer account was supposed to unassign tasks from only their team members and not others. However, this functionality did not work as expected. Despite the permissions being set, the volunteer account could not interact with the red X to unassign users from tasks, regardless of the team association.
> 
> These issues need to be addressed to ensure that the new permission functionality works correctly and allows volunteers to unassign tasks only from their team members.
> 
>  HGN.APP.-.Google.Chrome.2024-05-31.20-24-56.mp4

Thank you for your reply. The problem you encountered is not related to this PR. Please check again if the account you are using is the "Owner" role, if it's the owner role, it should give the permissions successfully and all other features should work well.

**Comment by one-community** [comment]
> > While testing the implementation of the new permission label 'unassignUserFromTasks', several issues were encountered. This frontend PR is related to the #969Jingyi_Unassign_Team_Members_From_Tasks backend PR. The main changes involved creating a new permission label 'unassignUserFromTasks' and using dispatch to check this permission for conditional rendering in React.
> > After checking out the current branch and running npm install, I cleared the site data and cache. I logged in as an owner user and attempted to grant a volunteer account the permission to unassign team members from tasks through the Dashboard -> task -> red X. However, upon submitting the changes in the permission management section, an error occurred with the message: "Permission update failed. Error: Request failed with status code 400," indicating a bad request.
> > Additionally, I tested assigning tasks to several users from different teams. The volunteer account was supposed to unassign tasks from only their team members and not others. However, this functionality did not work as expected. Despite the permissions being set, the volunteer account could not interact with the red X to unassign users from tasks, regardless of the team association.
> > These issues need to be addressed to ensure that the new permission functionality works correctly and allows volunteers to unassign tasks only from their team members.
> > HGN.APP.-.Google.Chrome.2024-05-31.20-24-56.mp4
> 
> Thank you for your reply. The problem you encountered is not related to this PR. Please check again if the account you are using is the "Owner" role, if it's the owner role, it should give the permissions successfully and all other features should work well.

This is a permission that should grant any role or individual the ability. The first process sounds like it tested that and it didn't work. Am I wrong?

For the 2nd part, please include that in this PR or log it as a new bug on the bugs doc and comment on it for my approval.

**Review by AJAYINAVOLU — APPROVED** [review]
Reviewed this PR on the frontend repo.

**Pull request merged**
