### PR TITLE
Navneeth create see teams management tab custom permission

### PR DESCRIPTION
**Pull request by navneeeth**
# Description
feature description

## Related PRs:
This PR is linked to the FE PR [#1359](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1359).

## Main changes explained:
- Updated the permission checks for not allowing listing users (used while adding members) and adding new teams and adding new members if the user also does not have the `seeTeamsManagementTab` permissions.
- Added comments to define the permission checks.
- Fixed the regex check in `src/models/team.js` to allow team creation without a team code from the Teams page.
- Updated the hasPermission function call based on the latest update in its definition.

## How to test:
1. check into current branch
2. do `npm install` and `npm run build` and `npm run start` successively to run this PR locally

### CODE REVIEW

**Review by Shiwani99 — DISMISSED** [review]
Hi,
Great Work. Left comments at frontend PR#1359.

**Comment by lacnoskillz** [comment]
Hi I'm trying to test your changes and having trouble creating an account with a Owner role.
Below I don't see the option to make a owner account to test. I'm currently logged in as the devadmin@hgn.net when attempting to create


image

**Review by malikjahanzaib — APPROVED** [review]
Hi @navneeeth, I have tested the features implemented in this PR and everything seems to work fine. Detailed review in the FE PR #1359.  Nice work!

**Review by JYXiao-2021 — DISMISSED** [review]
Hi, great job. I left my comment on FE.

**Comment by RheaWu1212** [comment]
> Hi I'm trying to test your changes and having trouble creating an account with a Owner role. Below I don't see the option to make a owner account to test. I'm currently logged in as the [devadmin@hgn.net](mailto:devadmin@hgn.net) when attempting to create
> 
> image

Hi I have the same issue here:
Screen Shot 2023-10-07 at 08 35 20

**Review by StrawberryCalpico — DISMISSED** [review]
Hi! I just reviewed the PR, it works as expected. Great job! I can assign the permission, create/edit team, and delete successfully.  Details in [#1359](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1359#pullrequestreview-1665518913)

**Review by wantingxu7 — DISMISSED** [review]
Hi, the PR LGTM, left detailed comment in FE 1359. Good job!

**Comment by RheaWu1212** [comment]
> > Hi I'm trying to test your changes and having trouble creating an account with a Owner role. Below I don't see the option to make a owner account to test. I'm currently logged in as the [devadmin@hgn.net](mailto:devadmin@hgn.net) when attempting to create
> > image
> 
> Hi I have the same issue here: Screen Shot 2023-10-07 at 08 35 20

**Comment by navneeeth** [comment]
@lacnoskillz @RheaWu1212 Hi, you cannot create an Owner account. You need to contact Jae to upgrade one of your test accounts to an Owner account in order to test this PR. Thank you!

**Comment by palakgosalia** [comment]
Hi! I just reviewed the PR, it works as expected. I have left a comment in #[1359](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1359#issuecomment-1763279456)

**Comment by RheaWu1212** [comment]
Hi! I reviewed the PR again after I had owner account and I have left a comment in FE.

**Comment by Lin1404** [comment]
Hi! I just reviewed the PR, it works as expected. I have left a comment in FE PR

**Comment by ChirayuRai** [comment]
Hey! I have left my comments on FE #1359

**Review by shubhankarval — DISMISSED** [review]
Hey @navneeeth, I’m getting an error while trying to run this PR. 
Screenshot 2023-11-04 155423

**Comment by navneeeth** [comment]
> Hey @navneeeth, I’m getting an error while trying to run this PR. Screenshot 2023-11-04 155423

Hello, @shubhankarval! Thanks for your review. Since the code has not changed since the last set of reviewers successfully tested it, I believe that this is a caching issue. 

I just tried running the backend again with this PR and it works as expected:
run build success

### For the FE:
Switch to the `navneeth-create-see-teams-management-tab-custom-permission` branch if on VS Code.
In the terminal:
```
git pull navneeth-create-see-teams-management-tab-custom-permission
npm install
npm run start:local
```

### For the BE:
Switch to the `navneeth-create-see-teams-management-tab-custom-permission` branch if on VS Code.
In the terminal:
```
git pull navneeth-create-see-teams-management-tab-custom-permission
npm install
npm run build
npm run start
```

Please try again with the above steps and let me know. Thank you!

**Review by tsunami776 — APPROVED** [review]
Comment and test video left in FE PR. Great work!

**Review by Shiwani99 — APPROVED** [review]
Hi,
Left my comments at frontend PR#1359. Great work.

**Review by wantingxu7 — APPROVED** [review]
comment in FE, good work!

**Review by shubhankarval — APPROVED** [review]
Hey @navneeeth, great job! Left a comment on FE PR [#1359](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1359)

**Review by Alforoan — APPROVED** [review]
I left a comment on the fe pr.

**Review by Pandani07 — APPROVED** [review]
Tested this PR and everything works as expected. Left a video of the testing on the frontend PR.

**Review by XiaohanMeng — APPROVED** [review]
Hi! I've completed my review of the PR and everything functions as anticipated. I've provided feedback directly on the FE.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1359#pullrequestreview-1886425818

**Pull request closed without merging**
