### PR TITLE
Shereen - Equipment List View

### PR DESCRIPTION
**Pull request by pshereen**
# Description
This PR is about the Equipments List View from Phase 2 with Sorting based on project name and item name, Filtering based on selected values of project and equipment, and Modal implementation for viewing update and purchase history.
Implements # (WBS) 9.1.2

## Related PRS (if any):
This frontend PR is related to the 2359 frontend PR. (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2359).
To test this backend PR you need to check out the (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2359).

## How to test:
1. check into current branch
2. Do npm run build and npm run start to run this PR locally
3. Follow the test steps in the related frontend PR

### CODE REVIEW

**Comment by Vijeth-V** [comment]
Hello Shereen,

I am working on the front-end and back-end PR branches that you mentioned. After logging in as an admin user, I was unable to fetch any equipment data. I also tried accessing the data with different volunteer accounts, but the issue persists. Could you please investigate this issue? I have attached a video for reference.


https://github.com/OneCommunityGlobal/HGNRest/assets/72465725/6ba800ae-d108-4f73-8c49-b10be19ad6f2

**Review by Kavil-Jain-514 — COMMENTED** [review]
No data is available when routed to the equipment tab.
I added a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/4ffb2257-cace-4840-9cee-52f45c18f8b7

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the equipment list is not loading.

https://github.com/OneCommunityGlobal/HGNRest/assets/39597927/64166470-9671-4a52-9726-be6a0a516d5d

**Comment by Logeshwari-Renu** [comment]
I have tested the PR and the equipment API is successfully returning data, but in the frontend table data is not rendered. [Frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2359#pullrequestreview-2126639079)

**Comment by pshereen** [comment]
Thank you all for your feedback.
Fixed the issue.
Kindly verify again.

**Review by vishavk1992 — COMMENTED** [review]
I have tested this PR, and no data is showing on the page table. I also left a comment on the frontend PR.

**Review by HowieMiao — APPROVED** [review]
Seems like problems have been fixed, table, interactables and drop-down menus all work for me

image

**Comment by pavanswaroopl** [comment]
Added suggestions and observations in the frontend PR, as the suggestion seems to be in the frontend part

**Review by pavanswaroopl — CHANGES_REQUESTED** [review]
Suggested changes in the frontend PR.

Thank you for your feedback. Fixed the issue.
-Note: Selecting 'All Projects' will automatically set Equipment to 'All Equipments'. That is the default feature given.

**Review by DiyaWadhwani — APPROVED** [review]
Hi Shereen,

I have tested your changes, however there are some UI changes required with respect to filter+sorting of data displayed on the /bmdashboard/equipment.
I have dropped a comment on your frontend PR. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2359#pullrequestreview-2149570132

Kindly review this.
Thank you

**Comment by pshereen** [comment]
> Tested the PR and the equipment list is not loading.
> 
>  Screen.Recording.2024-06-15.at.11.49.19.PM.mov

Thank you for your feedback.
Fixed the issue.
Please pull both frontend and backend again.
Make sure to clear cache before testing.

**Comment by pshereen** [comment]
> Hello Shereen,
> 
> I am working on the front-end and back-end PR branches that you mentioned. After logging in as an admin user, I was unable to fetch any equipment data. I also tried accessing the data with different volunteer accounts, but the issue persists. Could you please investigate this issue? I have attached a video for reference.
> 
>  Screen.Recording.2024-06-14.at.10.46.54.PM.mov

Thank you for your feedback.
Fixed the issue.
Pull both front end and backend again.
make sure to clear cache before testing.

**Review by vishavk1992 — APPROVED** [review]
i have successfully tested this PR with frontend PR2359 and left comment on front end PR with video.

**Review by Kavil-Jain-514 — APPROVED** [review]
The PR works perfectly fine. I have replicated the video and everything on the video works.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/e2b4bf96-3126-4933-b2f5-652bfb2b00d1

**Comment by pshereen** [comment]
> Tested the PR and the equipment list is not loading.
> 
>  Screen.Recording.2024-06-15.at.11.49.19.PM.mov

Addressed

**Comment by pshereen** [comment]
> Suggested changes in the frontend PR.
> 
> Thank you for your feedback. Fixed the issue. -Note: Selecting 'All Projects' will automatically set Equipment to 'All Equipments'. That is the default feature given.

Addressed

**Comment by pshereen** [comment]
> Tested the PR and the equipment list is not loading.
> 
>  Screen.Recording.2024-06-15.at.11.49.19.PM.mov

Addressed

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
