### PR TITLE
Jordy fix es6export syntax

### PR DESCRIPTION
**Pull request by j-corp-25**
# Description

Several files were using ES6 syntax export method. This was causing issues when running unit tests.

## Related PRS (if any):

N/A
…

## Main changes explained:

Found all the files using ES6 export syntax and converted them to commonJs module export method. 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. do `npm run build`
4. do `npm run test -- --verbose`
5. Check that no export syntax error pops up and all working unit test should be able to run

## Screenshots or videos of changes:

Before:

Screenshot 2024-05-12 at 12 08 41 AM

After:

Screenshot 2024-05-12 at 12 11 20 AM

## Note:
 Failing unit tests does not mean its not working. The unit tests are running and some fail which is expected. The unit tests were not being executed at all before because of the syntax error.

### CODE REVIEW

**Review by Shiwani99 — APPROVED** [review]
Hi,
The changes work as expected and now I am able to run the unit tests. I am attaching the screenshot below.

Screenshot 2024-05-12 at 7 22 10 PM

**Review by pshereen — APPROVED** [review]
Updates work as intended.
Able to run unit tests.

image

image

**Review by Ramaruva — APPROVED** [review]
Hey, I have verified you'r code changes and also I have run the test cases and it was working as expected 
image

**Comment by kaushikMreddy293** [comment]
Hi, 

your fix of the syntax is working, at least some of the test cases are working
image

**Review by linkhanthtel — APPROVED** [review]
I reviewed your PR and it is working as expected! Nice work!

**Comment by KaushikMreddy** [comment]
Hi, 

your fix of the syntax is working, at least some of the test cases are working
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
