### PR TITLE
Xiaohan fix profile assign badge backend

### PR DESCRIPTION
**Pull request by XiaohanMeng**
# Description
bug

## Related PRS (if any):
This backend PR is related to the [#2089](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089) frontend PR.

## Main changes explained:
- Update the assigning badge permission
- Fix the bug of assigning badge on other user profile

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm run start` to run this PR locally.
3. Please adhere to the instructions outlined in the frontend PR.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/113215317/ad7a4c70-cfb8-4c14-b577-dba6c1b0ac95

## Note:

- If you cannot see other users in the leaderboard, you can use the Owner account to add them to the team.
- If the displayed badges have reached their limit, click "Selected Feature" to check for new badges.
- One possible reason for the badge list not displaying is due to cache. If this occurs, please clear the cache and try again.

### CODE REVIEW

**Review by SanketKaware — APPROVED** [review]
Changes look good. Here is my frontend PR review: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089#pullrequestreview-1963788920.

**Review by iven-yao — APPROVED** [review]
reviewed this pull request with corresponding frontend, please check more detail in the [frontend-review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089#pullrequestreview-1967788380)

**Review by SRamen1999 — APPROVED** [review]
reviewed this pull request with corresponding frontend, https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089

**Review by kylepham — APPROVED** [review]
Good work. I left a review in the frontend [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089#pullrequestreview-1969600189).

**Comment by anandsesha** [comment]
Reviewed the pull request with the corresponding frontend. Please check review here [PR 2089](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089#issuecomment-2027909582)

**Review by Sarthak32 — APPROVED** [review]
Hi, It works as expected nice work ! I have also gave review on frontend PR : https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089#pullrequestreview-1969841682

**Review by hetvi11110 — APPROVED** [review]
I have tested frontend and backend PR and left a comment on frontend PR. Please review there.

**Review by Parth-tech — APPROVED** [review]
Looks good.
[Link to my FrontEnd PR Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089#pullrequestreview-1975257726)

**Comment by Tiantian-C** [comment]
Hi, I have tested it and it works well!

**Review by hbodgal — APPROVED** [review]
I have tested frontend with this backend PR and it works fine.

**Comment by MQChen211** [comment]
Hi, I tested this backend with the frontend and it works as expected. 
[https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089#issuecomment-2037685084](url)

**Review by MQChen211 — APPROVED** [review]

**Review by aaryaneil — APPROVED** [review]
Reviewed this PR with it's corresponding [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2089#pullrequestreview-1984586595). Good work.

**Pull request closed without merging**
