### PR TITLE
Shiwani Make permission for "Total Valid Weekly Summaries" number editable

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Screenshot 2023-10-19 at 1 37 12 PM

## Related PRS (if any):
To test this backend PR you need to checkout the #[1459](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1459) frontend PR.
…

## Main changes explained:
- Added 'totalValidWeeklySummaries' to Owner and Administrator in createInitialPermissions.js

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Follow instructions in frontend PR

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/78906820/85989b0f-8b19-409d-b747-5e700944328f

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by olenadanykh** [comment]
hi @Shiwani99 . Left the comment at Frontend related PR. Great work!

**Review by malikjahanzaib — APPROVED** [review]
Hi @Shiwani99, tested this PR and it seems to work as intended. Left detailed review on [FE PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1459).

**Comment by ChirayuRai** [comment]
Hey! I added my comments on FE #1459. Nice Job!

**Comment by palakgosalia** [comment]
Hey, I have added a detailed review in PR 1459. Good work. Thank you

**Review by Shuhua-L — APPROVED** [review]
I’ve tested both of your PRs and they worked as expected. More details can be found in the Front End PR. Nice work!

**Review by shubhankarval — APPROVED** [review]
Hey @Shiwani99, I left a comment on FE PR [#1459](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1459)

**Comment by kavya151** [comment]
Hii Shiwani, I have left detailed review at FE Pr#1459

**Review by Pandani07 — CHANGES_REQUESTED** [review]
Left comments on the frontend PR as well, faced an error

Screenshot 2024-02-07 at 12 42 52 PM

https://github.com/OneCommunityGlobal/HGNRest/assets/44672833/97992f00-07e0-421b-bc4e-d9f87eb1d0eb

**Pull request closed without merging**
