### PR TITLE
Shiwani add permission for edit project category or status

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Make permission management fix for edit project category or status.

## Related PRS (if any):
To test this backend PR you need to checkout the [#1606](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1606) frontend PR.

## Main changes explained:
- Added condition for editProject permission to edit and update category and status for that project. The first condition for editProject checks if that permission is not present in frontPermissions and if it present then the if condition will not execute, but if the permission does not exist, it checks if the user has putProject permissions and if both of these permissions are not present then 403 error will be raised when trying to edit category and status.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Follow steps in frontend PR

## Screenshots or videos of changes:

Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/72ce48ed-e3c4-4366-a34d-64fc0d85059b

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/65c5e668-b1d9-46e7-be2a-b5dcc1fa4ff9

### CODE REVIEW

**Review by Shuhua-L — APPROVED** [review]
Comment left in the FE [PR 1606](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1606#pullrequestreview-1785325549)

**Review by ilyaflaks — APPROVED** [review]
I tested this PR and everything works perfectly. 
Detailed comment on the front end PR1606.

**Review by Alforoan — APPROVED** [review]
Please check my comment on #1606

**Comment by mianmiantea2019** [comment]
I left my comment on #1606

**Review by Pandani07 — APPROVED** [review]
Everything works as intended! Left a review on the frontend PR

**Review by XiaohanMeng — APPROVED** [review]
Hi, I left my comment on FE: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1606#pullrequestreview-1910095915

**Comment by KaushikMreddy** [comment]
I've left a review in the Frontend PR linked to this: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1606#issuecomment-2113294794

**Review by peter6866 — APPROVED** [review]
Changes work as expected. I also left a comment in the frontend PR.

**Comment by akshit0211** [comment]
I left a review on the front-end PR. [Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1606#pullrequestreview-2118934216)

**Review by akshit0211 — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
