### PR TITLE
Sucheta - Create Summary Report Recipient Button

### PR DESCRIPTION
**Pull request by sucheta90**
# Description
(PRIORITY HIGH) Jae: Create a Weekly Summaries Reports recipient button for Owners(WIP SUCHETA) 
a. Mostly done with [PR1400](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1400) but needs comments addressed and merge conflicts resolved ([tutorial for this](https://docs.google.com/document/d/1I5NJE-quI0JGL4PHgGOJZCFadqP9nLhnSxuH-MC9tWo/edit))
b. I get an email each week with the Weekly Summaries Reports details. I need a way to add people to the list of recipients for this report. 
 - Place Button somewhere on the top of the Other Links → Reports → Weekly Summaries Reports page
- Have it show and editable list of who is currently receiving the report 
- Make it password protected with the same password as the [jae@onecommunityglobal.org](mailto:jae@onecommunityglobal.org) account
- Please also remove Sangam as a recipient of these emails
- Needs final update to my password before being merged

## Related PRS (if any):
Previous frontend - [PR1400](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1400), 
backend [PR566](https://github.com/OneCommunityGlobal/HGNRest/pull/566)

To test this backend PR you need to checkout the [#2006](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2006) frontend PR.
…

## Main changes explained:
- Adds three functions `getReportRecipients`, `deleteReportsRecepients` and `saveReportsRecepients` to the resportsController.js.
- Adds function `authorizeUser` to userProfileController.js.
- Create file C for introducing new components …
…

## How to test:
1. Check into current branch
2. Do `npm install` and `...` to run this PR locally
3. Log in as `owner` user
4. go to Reports→ Weekly Summaries Reports →  Weekly Summaries Reports button
5. To be able to see the list of Recipients or being able to add recipients, enter your email-id (same as the one you used to log in to test this PR) on the `src/controllers/userProfileController.js` -> `authorizeUser`- function. 
Screenshot 2024-03-01 at 10 16 35 AM
6. Restart server after making the change if not running on dev mode. Enter your password and if the user is Authorized, a popup shows up, with a list of Weekly Summary recipients
7. Test if you're able to add/delete the Weekly Summary recipients.
8. The weekly summaries will be sent to the recipients through email. In order to test this, add yourself to the recipients and to send/receive email using Gmail API, using OAuth2 and nodemailer, kindly follow the below video and setup up a test mail id.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes
9. Go the backend src/helpers/userHelper.js  'emailWeeklySummariesForAllUsers' function and tweak the 'mailList' key to any of your test email id and run the cron job (src/cronjobs/userProfileJobs.js) to receive the email (for every hour or every minute inorder to test if you're receiving the weekly summary).

Fill below variable values from the above setup in the .env file of the backend.
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = TRUE

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by DiegoSalas27** [comment]
Hi @sucheta90, I would like to test your PR, but I don't have the password for jae@onecommunityglobal.or account. Could you please provide it?  Btw, I am following the "how to test" in the following PR, but doesn't work: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1400.

**Comment by sucheta90** [comment]
> Hi @sucheta90, I would like to test your PR, but I don't have the password for [jae@onecommunityglobal.or](mailto:jae@onecommunityglobal.or) account. Could you please provide it? Btw, I am following the "how to test" in the following PR, but doesn't work: [OneCommunityGlobal/HighestGoodNetworkApp#1400](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1400).

Hello @DiegoSalas27 , I have added the additional step to test this PR. You do not need password for the oneCommunity email. You need to set your user email in the backend server, and use ur user password to be able to see the list. Let me know if you have additional questions. I am glad you asked.

**Comment by DiegoSalas27** [comment]
@sucheta90, thank you. I will test it shortly.

**Comment by beblicarl** [comment]
I have left a comment on the frontend of this

**Review by beblicarl — APPROVED** [review]

**Review by brandta-1 — APPROVED** [review]
# Review
The back-end functionality for the recipient add/remove modal works, as well as the mailing Cron job (I only set my testing email as the sole email recipient). For reference, see [front-end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2006#pullrequestreview-1912742446)

# Picture

01_cron_job

**Comment by DiegoSalas27** [comment]
Hi Sucheta. I was able to test your PR and it works as described. The code is clear and efficient. However, I noticed your commit has many formatting code updates which it should not contain. This is not concerning your PR functionality, but having files changes for code formatting styles is not good, and has happened in other PRs I've seen.

Attached to this comment is a video explaining how we can leverage lint-staged and prettier to enforce code formatting styles regvardless of the text editor anyone uses, as well as how to create a git hook to run linting on staged files before they are committed. Please consider this as an upgrade to the source code. It will make future PRs more concise and the updates will only be concerned with the funtionality.

https://github.com/OneCommunityGlobal/HGNRest/assets/26840798/a603af27-e009-47c8-9bf9-936e6c5fe596

**Comment by sucheta90** [comment]
Hello @DiegoSalas27 , thank you so much for reviewing my code. The walkthrough is very informative. I will try implementing the lint checks going forward.

**Pull request merged**
