### PR TITLE
Xiao F Create way for owner to edit & update ChatGPT prompt text

### PR DESCRIPTION
**Pull request by tsunami776**
# Description
CleanShot 2023-11-10 at 11 19 59

## Related PRS (if any):
This back-end PR is related to the [#1510](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1510) front-end PR.

## Main changes explained:
- Create file `src/models/dashBoardData.js` for prompt text schema
- Update multiple files in controller and router for get and update prompt

## How to test:
1. Check into current branch
2. Make sure do `npm run build` and `npm start` to start the BE
3. Made sure logged in as Owner user
4. Copy Auth token from Right click -> Inspect -> Application -> Local storage -> http://localhost:3000 -> token
5. Go to Postman -> Select 'GET' http://localhost:4500/api/dashboard/aiPrompt -> Headers -> put Key 'Authorization', Value 'the token you copied in step 4'
6. Send GET request and check "aIPromptText": "xxxx" is returned
7. Change GET to PUT
8. Go to 'Body' -> Select 'raw' -> Type in `{
    "aIPromptText": "Updated prompt"
}` -> Send PUT request -> Check if 'Successfully saved AI prompt.' is returned and use GET to check if prompt is changed

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/43768723/8b0c6383-adb2-4b19-a378-5d8c99d37d2b

## Note:
N/A

### CODE REVIEW

**Comment by this-journey** [comment]
I'm getting an "Error 500 Internal Server Error" on my GET request
Screenshot 2023-11-30 at 12 47 38 PM (2)

**Comment by tsunami776** [comment]
Hi @this-journey, from the error it gave, it looks like you are passing an argument to GET request. Sorry, I cannot reproduce the error. I tested the GET endpoint and it works for me.
CleanShot 2023-11-30 at 14 59 45
CleanShot 2023-11-30 at 15 00 24
CleanShot 2023-11-30 at 15 00 38

**Review by Alforoan — DISMISSED** [review]
As per my video, it doesn't seem like the message is being saved.

https://github.com/OneCommunityGlobal/HGNRest/assets/118868270/423d6707-5fb5-4d6a-9147-8833486ca11e

**Comment by tsunami776** [comment]
Hi @Alforoan, as in your screenshot, you are using GET for updating the prompt, you should use PUT instead.

**Review by Alforoan — APPROVED** [review]
It's working as intended. My previous comment was due to my own error. I also left a comment on pr#1510. Nice!

https://github.com/OneCommunityGlobal/HGNRest/assets/118868270/820d0b73-3951-4559-aa03-6f2f94aa37e7

**Comment by DragonSlayer2401** [comment]
I used my owner account to test both the GET request and PUT request. It appears that the GET request is working as intended however the PUT request appears to be only partially working it returns the success message but it doesn't update the text. Please see the video below for more info:

https://github.com/OneCommunityGlobal/HGNRest/assets/102876103/bc5c6e34-1cf5-4c87-87ef-770369c94e4f

**Comment by ptrpengdev** [comment]
Tested with FE PR [1510](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1510). The codes work as expected.

**Review by ZichanYang324 — APPROVED** [review]
Hi @tsunami776, I have used the Postman to test the GET and PUT for Aiprompt, and all the function works well.

(1) For the **GET** request, after pasting the token from the application, it can request the response as intended and the result is correct.
(2) For the **PUT** request, after sending the put request, it showed the "successfully saved AI prompt".

Two images for reference.

Screenshot 2023-12-07 at 14 34 17

Screenshot 2023-12-07 at 14 33 15

**Review by pika-chu11 — APPROVED** [review]
Tested the PR and the comment left on the FrontEnd [#1510](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1510)

**Review by Alforoan — APPROVED** [review]
See my comment on the FE pr.

**Review by ljrirene — APPROVED** [review]
Hi XiaoFei, this works as expected! Good job!
postman
postman-2
postman-3

**Comment by mianmiantea2019** [comment]
Tested the PR and the comment left on the FrontEnd 1510

**Review by cvtqx — APPROVED** [review]
Tested this PR and its FE PR and it works as described. I am able to update and save the prompt when logged in as owner.
See my comments for FE PR.

**Comment by Haoxiang310** [comment]
Also got an "Error 500 Internal Server Error" error on my GET request.
backend3-PR#603

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
