### PR TITLE
Fix bug on WBS not being parsed

### PR DESCRIPTION
**Pull request by talDoFlemis**
# Description

Whenever someone tried to Import Tasks from a WBS file, the task are not being imported and nothing happens on the table.

image

The only feedback is an error that returns from the server that can't be saw if the user don't open Network tab or a console.log

image

The bug was originated on the taskController file on HGNRest, because there is a property `hoursLogged` that isn't being passed from the frontend to the backend.

## Mainly changes explained:
Remove the `hoursLogged` property on the `taskController` file on some functions (The property is still in the project)

## How to test:
1. Switch to this branch
2. Go to Other Links -> Projects -> (Create or Select any project) -> Add new WBS -> Import Tasks
3. The table should be properly populated with the tasks provided by the WBS
image

## Video Showing how to fix the bug

[WBS_Fix_video](https://www.dropbox.com/s/x93zptb1syh564i/WBS_fix.mp4?dl=0)
### Files Used to test:
- [File1](https://www.dropbox.com/scl/fi/463yyubpt83c4fygnpa2x/File1.xlsx?dl=0&rlkey=mjoce9jloq91rsil5lkgjlas7)
- [File2](https://www.dropbox.com/scl/fi/erd0cttdsb57jcircondr/File2.xlsx?dl=0&rlkey=5n5fc5tw5rewmkrrspqz7xx8x)
- [File3](https://www.dropbox.com/scl/fi/qsrsjfv12qx1w43fghmao/File3.xlsx?dl=0&rlkey=eb2djhiy227hpfi7rs4o3awcf)
- [File4](https://www.dropbox.com/scl/fi/38j7dnh33fb23lx5yelc5/File4.xlsx?dl=0&rlkey=mcfynq4stfpv58zsp0kcst7ru)

## Note:
The property still on the backend server on a lot of files. I don't know if there is someone using it, but it's definitively not coming from the frontend

### CODE REVIEW

**Comment by one-community** [comment]
Thank you Said. Please include a video of this process. Please also link to the file you used. 

Also, did you test this with more than one of the files I suggested? If so, which ones? 

For anyone checking this, this is Urgent PR #6 too

**Comment by talDoFlemis** [comment]
> Thank you Said. Please include a video of this process. Please also link to the file you used.
> 
> Also, did you test this with more than one of the files I suggested? If so, which ones?
> 
> For anyone checking this, this is Urgent PR #6 too



> Thank you Said. Please include a video of this process. Please also link to the file you used.
> 
> Also, did you test this with more than one of the files I suggested? If so, which ones?
> 
> For anyone checking this, this is Urgent PR #6 too

OK, I'll be sending a video on the 8AM UTC-3 and I've used all 4 files that was provided for testing and all of them was working

**Comment by one-community** [comment]
Excellent! Please put the video in your shared folder and then link to it here.

**Comment by talDoFlemis** [comment]
> Excellent! Please put the video in your shared folder and then link to it here.

I've updated the PR description with the video and the files used to do the testing

**Comment by one-community** [comment]
Excellent, thank you!!

**Comment by EvianTan** [comment]
Hey @talDoFlemis ,

I'm testing this PR. I can verify the import WBS functionality has been fixed, but when I try to log time to the newly imported tasks, the functionality of "logging time to task" broke.

I tested with below environment:
site: Dev
account: Yiyun Admin
project: Yiyun Testing Project:
WBS: Yiyun Testing the import WBS bug
Task: 11.1 Update all business plan Enclosure 6b details and refresh related "main" business plan and Enclosure 6a charts

Test steps:
1. login as Yiyun Admin on Dev
2. go to project (Yiyun Testing Project:), go to WBS (Yiyun Testing the import WBS bug)
3. import file:  [file 3](https://www.dropbox.com/scl/fi/qsrsjfv12qx1w43fghmao/File3.xlsx?dl=0&rlkey=eb2djhiy227hpfi7rs4o3awcf) as you provided above
4. assigned 11.1 task to my account, see image below
image
5. logged 3 minutes time on the above task, which just imported and assigned to my account
image
6. it shows 0 hours logged instead of 0.05 hours (which is 3 minutes) on dashboard, also 0.00 hoursLogged on single task page, also 0 hoursLogged from database.
image
image
image

That means, this PR fixed the bug "wbs cannot be imported", but introduce a new bug "cannot log time to imported task".

**Comment by talDoFlemis** [comment]
Hi @EvianTan, I think the best outcome here is to go the frontend and pass that forgotten property to the backend and revert all the changes that I've made here. Do you know how that calculus is made to determine the hours logged? If all tasks are initially with hoursLogged as 0?

**Comment by EvianTan** [comment]
> Hi @EvianTan, I think the best outcome here is to go the frontend and pass that forgotten property to the backend and revert all the changes that I've made here. Do you know how that calculus is made to determine the hours logged? If all tasks are initially with hoursLogged as 0?

Hi @talDoFlemis ,
The calculus for hours logged is rounding up to 2 decimal places. Like the example you gave on PR 627, you logged 4 min to a task, it's 0.066666667 hours, rounding up to 2 decimal places, so dashboard showed 0.07 hours logged into that task.

**Comment by EvianTan** [comment]
Close this PR due to PR 627 fixed this bug in a simpler way.

**Comment by EvianTan** [comment]
Close this PR due to PR 627 fixed this bug in a simpler way.

**Pull request closed without merging**
