### PR TITLE
Imran added getProjectMembers permission

### PR DESCRIPTION
**Pull request by ImzIssa**
# Description
Gives the user permission to access the profile of any user directly from the projects members page. "Other Links" -> "Projects" -> "Members"

## Related PRS (if any):
To test this backend PR you need to checkout the [#2263](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2263) frontend PR.
…

## Main changes explained:
- updated getprojectMembership function to return _id if requestor has permission

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
6. Follow steps in Frontend PR[#2263](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2263) to test

### CODE REVIEW

**Comment by MinSun0814** [comment]
Left comment at Frontend

**Review by peter6866 — APPROVED** [review]
Changes work as expected. Also left a comment in the frontend PR.

**Review by cecilia-uu — APPROVED** [review]
Approved! Left a comment in the frontend.

**Review by nathcarnevalli — APPROVED** [review]
Left the review on the [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2263#pullrequestreview-2078068207).

**Review by Sandhya1236 — APPROVED** [review]
I successfully followed all the required steps to test the new permission functionality. After checking out the current branch and running npm install, I cleared the site data/cache and logged in as an admin user. I navigated to Permissions Management, added the "See User in Project" permission for a specific user, and submitted the changes. Upon logging in as that user, I verified they could click on members' names and navigate to their profiles. Conversely, users without this permission were unable to do so. All tests were successful, confirming that the permission management feature works as intended.


image
image

**Review by Parth-tech — APPROVED** [review]
Hey Imran,
Everything is working correctly. I have left a review on the front-end repo. [Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2263#pullrequestreview-2078773332)

**Review by Infinite-Turkey — APPROVED** [review]
Left a comment in front end

**Review by Kavil-Jain-514 — APPROVED** [review]
The functionality works.
The review is submitted on the [PR #2263](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2263)

**Review by jinxyou — APPROVED** [review]
I left a review at frontend https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2263#pullrequestreview-2092179894

**Comment by akshit0211** [comment]
The functionality works as expected. Good job!

Permission

With permission
can go to profile

Without permission
can't go to profile

**Review by akshit0211 — APPROVED** [review]

**Comment by KurtisIvey** [comment]
Hi Imran, I just wanted to see if you could clear up the merge conflict on this please, so we can rereview and get it merged asap.

**Review by suaniii — APPROVED** [review]
The permission functionality works as expected. 
with permission:


https://github.com/OneCommunityGlobal/HGNRest/assets/113208952/3c4ae66f-0577-4aee-a949-13c49e941e6d



without permission:

https://github.com/OneCommunityGlobal/HGNRest/assets/113208952/f79ceb48-e0a0-4dca-870a-31b776703c08

**Review by shradac — APPROVED** [review]
Good job! Left the comment on frontend PR.

**Review by DiyaWadhwani — APPROVED** [review]
Approved your changes and left a comment on the frontend PR.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
