### PR TITLE
Haohui - Gives the user permission to manage individual user permissions.

### PR DESCRIPTION
**Pull request by Lin1404**
# Description
image

## Related PRS (if any):
To test this backend PR you need to checkout the #1218 frontend PR.
…

## Main changes explained:
Allow user who have "manageUser" permission to get users' profile, also update users' permission.
…

## How to test:
1. check into current branch
2. do `npm run build` and `npm run start` to run this PR locally
3. log as owner user call user A
4. go to dashboard→ Other Links→ Permissions Management→ Manage User Permissions
5. input another user name, call user B
6. find the "Manage User Permissions", click the add button
7. scroll down and click submit button
8. log out and login as user B
9. go to dashboard→ Other Links→ Permissions Management→ Manage User Permissions
10. check the user B able to manage user permissions.

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Haoj1 — APPROVED** [review]
@Lin1404 Your backend PR looks good when working with FE 1218. Great job!

https://github.com/OneCommunityGlobal/HGNRest/assets/99279909/ae99cc12-0154-4266-818c-1e7408b082f0

**Review by GaryB93 — APPROVED** [review]
Reviewed with frontend PR#1218. Editing the Manage User Permissions functionality for a user account works and no errors logged.

**Review by robertoooc — APPROVED** [review]
Hi @Lin1404, I reviewed with frontend PR#1218. Your changes work as expected and didn't receive any issues.

**Comment by AriaYu927** [comment]
Hi @Lin1404 I've tested #1218. It works great, thank you！

**Comment by wantingxu7** [comment]
Hi, I've tested this PR with FE #1218 and comment there

**Review by Shiwani99 — CHANGES_REQUESTED** [review]
Hi,
Added my comments for frontend PR#1218

**Comment by DavidC0126** [comment]
LGTM. Good job! Left the comment on FE PR.

**Review by EdwinLauM — APPROVED** [review]
Hey @Lin1404, left a more detailed comment in your FE PR!

**Comment by Lin1404** [comment]
> ded my comments for fronten

Hi @Shiwani99 , I have fixed the bug and retested. Please feel free to check the retest recording in frontend.

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. Left comments at frontend PR#1218.

**Comment by one-community** [comment]
Thank you all, moving to final review

**Pull request merged**
