### PR TITLE
Ivy-reasonSche-unit-test

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
This frontend PR is related to the #XXX backend PR.
To test this backend PR you need to checkout the #XXX frontend PR.
…

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run build` to run this PR locally
3. do `npm run test reason `
Screenshot 2024-08-29 at 4 35 01 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by AJAYINAVOLU — APPROVED** [review]
Tests are passing without any errors. 

image

Thank You

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (181)

**Review by SMitta11 — APPROVED** [review]
Tested PR and all test cases passed.
Screenshot:
Screen Shot 2024-08-31 at 12 36 26 AM

**Review by manikittu810 — COMMENTED** [review]
Hello @20chen-7 
I have executed the command as mentioned but, i have seen for test cases  have not been passed on my end.
Screenshot 2024-08-31 at 1 34 52 AM

Thank you.

**Review by linkhanthtel — APPROVED** [review]
All test cases passed as expected! Nice work!

PR #1089

**Review by CillianRen — CHANGES_REQUESTED** [review]
Ran tests for Ivy-reasonSche-unit-test. Out of 40 tests, 16 failed, mainly due to missing authorization headers and async timeouts.

Issues:

Authorization Errors: Headers are missing/undefined in multiple tests.
Timeouts: Async operations not completing within set time limits.
Database Errors: Mongoose operations timing out.
image

**Comment by 20chen-7** [comment]
> Ran tests for Ivy-reasonSche-unit-test. Out of 40 tests, 16 failed, mainly due to missing authorization headers and async timeouts.
> 
> Issues:
> 
> Authorization Errors: Headers are missing/undefined in multiple tests. Timeouts: Async operations not completing within set time limits. Database Errors: Mongoose operations timing out. image

Not sure why your unit test failed. Plz deleted dist folder before test.

**Review by ddshah878 — APPROVED** [review]
All test cases passed as expected! Great job!

image

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and all test cases passed successfully.

Screenshot 2024-09-04 175325

**Review by Saniya98 — APPROVED** [review]
Tests are running successfully 
image

**Review by sri0606 — APPROVED** [review]
Hey @20chen-7 , I was successfully able to run all test cases.



image

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases were passed.
Screenshot 2024-09-12 at 5 36 30 PM

**Pull request merged**
