### PR TITLE
Cleaning commented code and removing debug statements

### PR DESCRIPTION
**Pull request by anant2047**
### Description

Screen Shot 2023-04-11 at 6 47 30 PM

Reference - [Doc](https://docs.google.com/document/d/10CdEY31Me90XP_oVt3T3WSt9MhAvm4wSJ0B4ScqUorY/edit)

### Mainly changes explained:
The PR is not specific to any feature or bug. It just removes commented code and logs statements for better code quality. 

### How to test:
So it is necessary to test the product end to end and see if there are any failures because of these changes, which logically shouldn't be anything.

In HGNrest do this - 
git checkout cleanup-comments-debug-output
npm run build
npm start

Then in HightestGoodNetworkApp -
git checkout development
npm run start:local

Test the website end to end and see if there are any issues.

### CODE REVIEW

**Review by ToobaJamal — APPROVED** [review]
I have tested the app end to end and there are no issues on my end. I have tested it for every role. Here's just a small walkthrough of it

https://user-images.githubusercontent.com/52610124/231388603-9c1114c4-334e-43f1-8bec-7269b0d4bcd0.mp4

**Review by ypan710 — APPROVED** [review]
Hi @anant2047, I've tested your PR and all features I've tested worked without any issues.

Screen Shot 2023-04-12 at 11 49 30 AM

Screen Shot 2023-04-12 at 11 51 13 AM

**Review by abdel-lall — APPROVED** [review]
Works as expected. I don't see any changes in the source code that could have an effect on the app.

**Comment by LucileTech** [comment]
Hi @anant2047 everything went well.


I tried to go to the Timelog and It is loading for a weirdly long time but I have the same issue on the development branch today.  

Screenshot 2023-04-12 at 16 23 28

**Review by LucileTech — APPROVED** [review]

**Comment by one-community** [comment]
Great job everyone. Everyone here please approve the backend too and I'll move this to final review. Anant, please follow up with them by DM if you'd like to move this along faster.

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
