### PR TITLE
Tim add bmdashboard login route

### PR DESCRIPTION
**Pull request by tdkent**
# Description
Backend updates to support the new Building Management Dashboard (ie Phase 2) entry point and login screen. 

## Related PRS (if any):
[Frontend PR 1325](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1325)

## Main changes explained:
- New API route, router, and controller function for users to verify their current login credentials to access the BM Dashboard.
   - Note: Currently any user role can access the BM Dashboard.
- Adds a new access object to JWT tokens with a Boolean value controlling access to the BM Dashboard.
- The controller function accepts the user’s credentials and matches them against the submitted token. Mismatches result in an error with status code 422. If the credentials are verified, the response is a new token with `access.canAccessBMPortal=true`
   - Note: token expiration is not refreshed

## How to test:
- `git checkout Tim_add_bmdashboard_login_route`
- `npm install`
- `npm run build`
- `npm start`

### CODE REVIEW

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I have left comments at frontend PR#1325.

**Review by DavidC0126 — APPROVED** [review]
LGTM. Left comment on FE PR.

**Review by wantingxu7 — APPROVED** [review]
Great job! Comment in FE 1325

**Comment by astrjc0326** [comment]
Good job! Comment in FE#1325

**Review by navneeeth — APPROVED** [review]
Hello! Tested the changes and they LGTM! Commented the review on the[ frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1325#pullrequestreview-1638627312). Good implementation!

**Review by JYXiao-2021 — APPROVED** [review]
I test the whole pr and shown on FE.

**Review by JeffLi117 — APPROVED** [review]
Great job, looks good. Comments left on FE (PR #1325).

**Review by tsunami776 — APPROVED** [review]
Great work! bmdashboard works as described, and I left a comment in the FE PR #1325.

**Review by TuanDinh140194 — COMMENTED** [review]
Very great job. I have left comment on font end #1325

**Comment by Vishala09** [comment]
Working as intended! Awesome work!

[Untitled_ Sep 26,2023 3_33 PM.webm](https://github.com/OneCommunityGlobal/HGNRest/assets/65274029/8b528ba3-e888-4963-a853-41b1d3bdc7f3)

**Comment by Vishala09** [comment]
Works Perfect! Awesome Work! 
Commented in the Front-end PR

**Review by Vishala09 — COMMENTED** [review]
Works Perfect! Awesome Work!

**Pull request merged**
