### PR TITLE
Ashish Fix Total team report team code fields

### PR DESCRIPTION
**Pull request by AshishNags**
…active

# Description
Screenshot 2024-11-01 160923

## Related PRS (if any):
To test this backend PR you need to checkout the development frontend PR.
…

## Main changes explained:
- Update getAllTeams function in teamController.js to include the most-used team code
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→ Reports→Teams
6. verify it shows list of active and most used team code in the team code field

## Screenshots or videos of changes:
Screenshot 2024-11-01 155502

### CODE REVIEW

**Review by samarth9201 — APPROVED** [review]
Reviewed that the PR works.

Screenshot 2024-11-01 174630

**Review by RashmiKY98 — APPROVED** [review]
The PR request is working fine. The PR was reviewed in different browsers and is working fine. Checked by toggling between Projects, People and Teams and the team code was displayed correctly. 
Screenshot 2024-11-02 150653
Screenshot 2024-11-02 150707

**Comment by humera314** [comment]
I tested the pull request, and it’s working as expected, with full functionality in both dark and light modes.
image

**Review by hqzhu0913 — APPROVED** [review]
Team code works as explained.
Screenshot 2024-11-05 at 11 31 32 PM

**Review by audreydieuanh — APPROVED** [review]
It shows list of active and most used team code in the team code field.

test9

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
