### PR TITLE
Luis warning component backend

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description
This is the backend for PR 1873
The backend created the warnings route, controller, and assigned a warnings array to the user's profile 
The frontend targets this endpoint to receive the user's current warnings. 

## Related PRS (if any):
To test this backend PR you need to checkout the #1873 frontend PR.
…

## Main changes explained:
-Created warningsController, warningRouter, and added an array of warnings to the user's profile
…

## How to test:
1. check into current branch
2. do `npm run build && npm run start` 
3. Follow instructions on PR 1873
4. You must check into this Backend to test the front end.

### CODE REVIEW

**Review by Sophie-lei — COMMENTED** [review]
Hey,  I reviewed this backend and left a comment in PR#1873.

**Comment by xmyoot** [comment]
Hello Luis, I posted a review on PR#1783, thanks

**Review by 666saofeng — APPROVED** [review]
See reviews on front-end PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1873#pullrequestreview-1847307490

**Review by KevHnh — APPROVED** [review]
Tested with frontend PR and works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1873

**Comment by galgalinidhi** [comment]
See Comments on https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1873

**Review by peterson337 — APPROVED** [review]
Hi Luis, I have tested your application in PR Front End: OneCommunityGlobal/HighestGoodNetworkApp#1873

**Review by X1aoZhang99 — APPROVED** [review]
Hi Luis,

I test you PR with FE #1873, and I logged in as admin. All functionalities worked as intended, nice work! Please refer to the video. 


https://github.com/OneCommunityGlobal/HGNRest/assets/113070229/2183b07b-1197-452e-9b68-73505a27cdcf

**Review by pshereen — APPROVED** [review]
Tested the PR and all the features are working as per the requirement.
Please find my comments in the related frontend PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1873

**Review by Pandani07 — APPROVED** [review]
Works as intended, have left the approval comment on the frontend PR

**Review by yvonnep165 — APPROVED** [review]
Hi @luisarevalo21 ,

I have tested this backend with PR 1873 from frontend and left a comment in PR 1873.

**Review by sucheta90 — APPROVED** [review]
Hello @luisarevalo21 , I was able to successfully test this PR and it works as intended. Great Work! Please refer to mu video review on the frontend [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1873#pullrequestreview-1861182537)

**Review by mohabbasd — APPROVED** [review]
Hello, this PR works as intended. I posted a video on the frontend PR #1873.

**Review by XiaohanMeng — COMMENTED** [review]
Hey, I reviewed this backend and left a comment in PR#1873. Please see the video at the frontend PR.

**Review by cvtqx — APPROVED** [review]
Tested and left comment in the FE PR. Everything works as described. Great job!

**Pull request merged**
