### PR TITLE
Tim add materials list routing

### PR DESCRIPTION
**Pull request by tdkent**
# Description
Backend updates to support the BM Dashboard materials list page.

## Main changes explained:
- Add new database schema **models/inventoryItemMaterial.js**
- Update existing schema **models/inventoryItemType.js**
- Add new api route “/bmdashboard/materials”
- Add new subdirectory **routes/bmdashboard** and file **bmMaterialsRouter.js** with `GET` request
- Add new subdirectory **controllers/bmdashboard** and file **bmMaterialsController.js**
- Controller fetches all data objects in new **inventoryMaterial** collection in MongoDB
- Populates with data objects from **inventoryItemType**, **userProfiles**, and **projects** collections

## How to test:
1. `git checkout Tim_add_materials_list_routing`
2. `npm install`
3. `npm run build`
4. `npm start`

## Notes:
- The edit icons in the table currently are not hooked up to anything and return null

### CODE REVIEW

**Review by ChirayuRai — DISMISSED** [review]
Looks good! All functionality on frontend is working, and all information is showing up correctly on home page. 

Only issues are editing seem to not be working, so I cannot test that functionality. 

https://github.com/OneCommunityGlobal/HGNRest/assets/15188751/01a9db10-ad13-4e76-b764-7918897629a5

**Comment by tdkent** [comment]
> Looks good! All functionality on frontend is working, and all information is showing up correctly on home page.
> 
> Only issues are editing seem to not be working, so I cannot test that functionality.
> 
>  Screen.Recording.2023-10-11.at.2.49.16.PM.mov

Thanks for your review. As explained in the frontend PR description (which is where your change request should have been made since it is a frontend issue), the edit buttons currently return null by design.

**Comment by olenadanykh** [comment]
Looks good! All functionality in Front End works as expected. Great work.

**Review by tsunami776 — APPROVED** [review]
Comment and test video left on FE PR. Great job!

**Review by StrawberryCalpico — APPROVED** [review]
Hi I tested your PR, worked as expected, details in [#1401](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1401#pullrequestreview-1675584082)

**Review by JeffLi117 — APPROVED** [review]
Comment left on FE PR #1401.

**Review by malikjahanzaib — APPROVED** [review]
Hi @tdkent, I have tested your PR and everything seems to work perfectly. Left detailed review and test recordings on FE. Great job!!!

**Comment by RheaWu1212** [comment]
Comment left on FE PR #1401.

**Comment by beblicarl** [comment]
Commented on the frontend PR

**Review by beblicarl — APPROVED** [review]

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Left main review on pr1401.

Would like to see chronological sort implemented in the mongodb query, so the results are return chronologically on the frontend. 

pr1401 does this sort via the usage date
pr1401 need to confirm if purchases sorted via date
pr1401 does updates sort via date

@KurtisIvey Thanks for your review. I agree there should be sorting and additional filtering options. However, the PR was already so big I decided to stay focused on a MVP approach. I have already added this task to the Phase 2 WBS Sheet. For now I think its more important to get this branch merged since it adds many new file structure elements that are essential to other devs working on Phase 2.

**Review by KurtisIvey — APPROVED** [review]
Clarification was given, so this things all good to go 👍🏻

**Pull request merged**
