### PR TITLE
Unit and integration tests for put method / routes

### PR DESCRIPTION
**Pull request by Abi-Liu**
# Description
Unit and integration tests for the put method / routes

## Related PRS (if any):
N/A

## Main changes explained:
- unit tests for the put method in the controller
- integration tests for the put route

## How to test:
1. check into current branch
2. do `npm install`
3. run `npm run test badge`
4. verify all tests pass

## Screenshots or videos of changes:
Screenshot 2024-04-15 at 12 24 17 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by alla0810** [comment]
Test passed successfully.  Good work!

image

**Review by linkhanthtel — APPROVED** [review]
All tests passed! Nice work!

**Review by j-corp-25 — COMMENTED** [review]
I'm just having bad luck running these tests.

I switched to `node 14.17.6` just in case. But I still get a lot of errors and a only about half the tests are passing.

I made sure to delete `node modules` and `package-lock.json` everytime just for extra insurance but still. This is sorta worrying me because Im planning to dive deeper into unit testing. I hope I dont run into an issue where Im creating the test properly and its still failing.

Here is the picture showing only 25 passing tests

PR#899

This is very unfortunate

**Comment by mianmiantea2019** [comment]
Test passed successfully. Good work!

image

**Review by aaryaneil — APPROVED** [review]
Tested your PR and all test cases passed.
Screenshot 2024-04-20 at 12 30 03 PM

**Review by Ramaruva — APPROVED** [review]
all test cases passed
image

**Review by MinSun0814 — APPROVED** [review]
image
All tests successfully passed.

**Pull request merged**
