### PR TITLE
Edwin - Backend for the functionality of the 'x' checkmark

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-06-17 at 8 01 35 PM

## Related PRS (if any):
This backend PR is related to FE PR [#920](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/920)

## Main changes explained:
Added "removeUserFromTask"  initial permission for Administrator and Owner accounts 

## How to test:
1. check into current branch
2. do `npm run build` && `npm run start`

### CODE REVIEW

**Review by bienzguoa — COMMENTED** [review]
Good job! Left review on frontend PR.

**Comment by Lucas-E** [comment]
Hey @EdwinLauM, great job! Please solve the conflicts and ask for review and approval so I can move it to the final review!

**Review by cvtqx — APPROVED** [review]
Works as described. I left a review in the related FE PR#920.

**Review by mahamakhan — APPROVED** [review]
Checked from the admin and volunteer account and everything works as mentioned.

**Review by AuroraLovesWhales — APPROVED** [review]

**Pull request merged**
