### PR TITLE
Jinchao add weekly summary indicator on leaderboard for admin users

### PR DESCRIPTION
**Pull request by suigunfjc**
# Description
image

## Related PRS (if any):
This backend PR is related to frontend [#880](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/880)

## Main changes explained:
Update function `getLeaderboard` and `getUserLaborData` to provide the weekly summary submission state of latest week for each user data in leaderboard.

## How to test:
Please see refer FE PR [#880](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/880)

### CODE REVIEW

**Review by EdwinLauM — APPROVED** [review]
Code looks good! Left a suggestion in the frontend PR.

**Comment by KurtisIvey** [comment]
reviewed and functions as expected

**Review by KurtisIvey — APPROVED** [review]
functions as expected. Left review for this in the front end on PR #880

**Review by eduhorta — APPROVED** [review]
It works as intended! Nice job! 👍
Left a suggestion in the frontend PR.

**Review by stevenpaalz — APPROVED** [review]
This feature works as intended. See note on Frontend PR. 

Screenshot 2023-06-06 at 2 21 03 PM

**Review by bienzguoa — APPROVED** [review]
Functions work as expected. Left review on frontend PR #880.

**Review by cvtqx — APPROVED** [review]
Implemented changes work as described.

1. When logged in as volunteer, red dots are centered:
Volunteer - red dots centered

2. After submitting weekly summary on a volunteer account and then logging back in as Admin, I can see a  green checkmark next to the corresponding record. 
Admin-GreenCheckMarkDisplayed

**Comment by mahamakhan** [comment]
Both features are working fine just as mentioned in the description.

Screenshot 2023-06-09 132933

**Review by mahamakhan — APPROVED** [review]
Both features are working fine just as mentioned in the description.

Screenshot 2023-06-09 132933

**Comment by rachnapandya** [comment]
Works as intended.
image

**Pull request merged**
