### PR TITLE
Shuhua - add google doc icon

### PR DESCRIPTION
**Pull request by Shuhua-L**
# Description
description

## Related PRS (if any):

To test this backend PR you need to checkout the [PR1980](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1980) frontend PR.

## Main changes explained:

- Added `adminLinks` field for each user in `getTasksForTeams()` in `src/helpers/taskHelper.js`

## How to test:

1. check into current branch
2. do `npm run build && npm start` to run this PR locally
3. checkout the frontend PR[#1980](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1980)

### CODE REVIEW

**Review by skaush21 — APPROVED** [review]
left comment on frontend [PR #1980](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1980)

**Review by XiaohanMeng — APPROVED** [review]
Hi, I left my comment on FE project: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1980#pullrequestreview-1905168783

**Review by MALAV1308 — APPROVED** [review]
Hello , I have reviewed this backend PR and it's working great. Check Frontend PR comment. Thank You.

**Comment by DiegoSalas27** [comment]
Hi Shushua. I have just left a comment in the associated [FE PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1980)

**Review by navyasrim — APPROVED** [review]
Tested and working fine as mentioned...picture in frontend PR #1980

**Review by brandta-1 — APPROVED** [review]
# Review
Please see [front-end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1980#pullrequestreview-1912746791).

**Pull request merged**
