### PR TITLE
Imran edit summary submit requirement others

### PR DESCRIPTION
**Pull request by ImzIssa**
# Description
Gives the user permission to change the requirement to the user to submit a summary.

## Related PRS (if any):
To test this backend PR you need to checkout the [PR#2242](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2242)  frontend PR.

## Main changes explained:
- added updateSummaryRequirements permission
- added permission check for updateSummaryRequirements in profileController
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Follow the frontend [PR#2242](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2242) to test

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Sandhya1236 — APPROVED** [review]
Everything works as intended. I was able to change weekly summary options using the owner account. However, I could not make these changes with the volunteer account. After granting specific permissions—such as seeing all users, editing user profiles, changing user status, and editing summary submission requirements—from the owner account to the volunteer account, the volunteer account was updated and could change the weekly summary options.

Have a look at the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/3ea8dd87-128b-4efe-b566-53ec2d5de27c

**Review by Parth-tech — APPROVED** [review]
Hey Imran,
I have reviewed the backend codebase and it is concise and correct to me. Left a review on the frontend repo. [Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2242#pullrequestreview-2084083622)

**Review by Infinite-Turkey — APPROVED** [review]
After giving the rights of Seeing All Users + Editing User Profile + Editing Summary Submit Requirement (others) to my personal account, I could change others' duty of submitting a weekly summary. This function works as expected. But from my point of view, it might be a better choice to check if the user has the prerequisite permissions when adding the right of Editing Summary Submit Requirement (others). If not, give all the rights to the user.
屏幕截图 2024-05-30 230303

**Review by peter6866 — APPROVED** [review]
Changes work as expected. I left a comment for the frontend PR.

**Review by Kavil-Jain-514 — APPROVED** [review]
The functionality works as expected, and the review is provided in the frontend PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2242

**Comment by akshit0211** [comment]
I left a review on the front-end PR. [Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2242#pullrequestreview-2105534455)

**Review by akshit0211 — APPROVED** [review]

**Review by jinxyou — APPROVED** [review]
I left a review at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2242#pullrequestreview-2106056312

**Review by shradac — APPROVED** [review]
Tested for the functionality and works as expected, and the review is provided in the frontend PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2242

**Review by DiyaWadhwani — APPROVED** [review]
Hey Imran,
Tested out as per your instructions. 

I logged in from the admin account and updated the permissions for the volunteer role. Added the Edit User Profile permission.
Screenshot 2024-06-22 at 2 01 13 AM

Logged into the user and checked. The volunteer timings are editable.
Screenshot 2024-06-22 at 2 00 42 AM

Logged back into the admin account and deleted the Edit User Profile permission
Screenshot 2024-06-22 at 2 02 09 AM

Once permissions are revoked, the volunteer cannot edit the timings anymore.
Screenshot 2024-06-22 at 2 02 58 AM

Great work. Thanks

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
