### PR TITLE
yihan fix weekly summary submission date

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
This backend PR is related to the[ #840](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/840) frontend PR.

## Main changes explained:
Added uploadDate in weeklySummaries object. 

## How to test:
check into current branch on both frontend and backend
do `npm install` and  `npm run build`  to run this PR locally
then follow the instruction of PR of frontend to test

### CODE REVIEW

**Review by yoyoweiii — COMMENTED** [review]
Hi @AriaYu927 I submitted a weekly summary and it did show 05/19 as it intended.
HGN APP and 23 more pages - Personal - Microsoft​ Edge 5_19_2023 4_17_32 PM
However, I noticed that every user also shows 05/19 no matter in "this week", "last week" and "week bofore last" tab
HGN APP and 23 more pages - Personal - Microsoft​ Edge 5_19_2023 4_19_06 PM

**Review by nathanah — APPROVED** [review]
Seems to work as intended.

**Review by EdwinLauM — COMMENTED** [review]
Hi @AriaYu927, I ran into the same problem that @yoyoweiii stated. I submitted a weekly summary report today (05/19) and the due date became (05/19) for every member whether they submitted a weekly summary report or not. This also applies for the "This Week", "Last Week", "Week Before Last" and "Three Weeks Ago" tab

PR #840

**Review by NidaZaki — COMMENTED** [review]
The weekly submission date is the current date under the "Last Week", "Week Before Last", "Three Weeks Ago" tabs.

yihan-fix-weekly-summary-submission-date

yihan-fix-weekly-summary-submission-date-1

yihan-fix-weekly-summary-submission-date-2

**Comment by drewlong314** [comment]
[https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/840#issuecomment-1556034924](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/840#issuecomment-1556034924) comment on the frontend

**Comment by papiasharmin** [comment]
Hello @AriaYu927, I am seeing the same problem, everyone talking about. after testing the component it shows that, summaries data are fetching for all tabs. while it should be fetching data for weekindex 0 for this week, and weekindex 1 for last week.. so on in front end. and in summary.weeklySummaries object dueDate for all members at this week due date. I have showed this in the video. I think  the summaries prop should be fixed first. then you can use this
 " (
      {summary.weeklySummaries[weekIndex]?.summary ? moment(summary.weeklySummaries[weekIndex]?.uploadDate)
        .tz('America/Los_Angeles')
        .format('YYYY-MMM-DD'):  moment(summary.weeklySummaries[weekIndex]?.dueDate)
        .tz('America/Los_Angeles')
        .format('YYYY-MMM-DD')}
   )" on line 110 of FormatedReport.jsx

https://github.com/OneCommunityGlobal/HGNRest/assets/86232710/23cbcf38-4547-489c-9e12-2365b77db6db


to show due date for those member who have not set summary, and update date for those who have set summaries.

**Review by papiasharmin — CHANGES_REQUESTED** [review]
Hi @AriaYu927 , I think the line 89 '' default: moment().tz('America/Los_Angeles').endOf('week')'' on userProfile.js will  always show the due date of current week's due date, regardless of last week, week before that and so on, it should be updated to show due date according to the weeks. or you can edit it depending on different weekindex in summaries props used in formattedReport.jsx. to show due date for those member who have not set summary, and update date for those who have set summaries.

**Review by lchua2314 — CHANGES_REQUESTED** [review]
Hi, @AriaYu927 I made a review for the front end so please take a look at that. The code looks fine here. I will approve this PR when the front end PR is done. 

Reiterate from my other review: Front end is showing all summary dates as my summary submission date.

My test:
1 My test
This Week:
2 This Week
Three Weeks Ago:
3 Three Weeks Ago

**Comment by AriaYu927** [comment]
Hi everyone, thank you for your reviewing. I've updated the frontend code. Please follow the steps to review the PRs again.

**Review by NidaZaki — APPROVED** [review]
Change here looks good to me.

**Review by lchua2314 — APPROVED** [review]

**Review by eduhorta — APPROVED** [review]
Hi, @AriaYu927!
The feature works as intended. Nice job! 👍
Screenshot 2023-06-05 09-41-48 - PR #840

**Review by bienzguoa — COMMENTED** [review]
Left review on Frontend #840.

**Review by bienzguoa — APPROVED** [review]
Works as intended!

**Review by papiasharmin — APPROVED** [review]
everything is working as intended

**Pull request merged**
