### PR TITLE
Xiao F update teams page sorting part b and c

### PR DESCRIPTION
**Pull request by tsunami776**
# Description
CleanShot 2023-12-29 at 16 36 28

## Related PRS (if any):
This frontend PR is related to the [#1756](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1756) and [#1757](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1757) frontend PR.
To test this backend PR you need to checkout the above frontend PR.

## Main changes explained:
- Update file `src/controllers/teamController.js` to set new modifiedDatetime when a member is added or removed from a team

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm start` to run this PR locally
3. Please see  [#1756](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1756) and [#1757](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1757) frontend PR's test instructions

### CODE REVIEW

**Review by abdel-lall — APPROVED** [review]
LGTM.

**Review by Alforoan — APPROVED** [review]
Please check my comment on fe pr #1756,

**Review by Alforoan — APPROVED** [review]
Please check my comment on fe pr #1757,

**Review by bienzguoa — APPROVED** [review]
Commented on frontend PR.

**Pull request merged**
