### PR TITLE
Abdel log requested time off for blue squares

### PR DESCRIPTION
**Pull request by abdel-lall**
## Related PRS:
This backend PR is related to the [#1471](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1471) frontend PR.

## How to test:
1. check into current branch
2. do `npm run build`

### CODE REVIEW

**Review by this-journey — DISMISSED** [review]
See my review on the FE.

**Review by pika-chu11 — COMMENTED** [review]
Reviewed both PRs, I have left a review on the FronEnd [#1417](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1471).

**Review by pshereen — APPROVED** [review]
Reviewed both frontend and backend PRs.
Please check my comments on related Front PR. [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1471#pullrequestreview-1831620635](url)

**Review by Sophie-lei — CHANGES_REQUESTED** [review]
Tasted this PR with FE. Please view the #1471 FE for details. I think the email function has some problems to be solved in BE.

**Review by Renanluizssx — COMMENTED** [review]
see my review please: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1471

**Pull request merged**
