### PR TITLE
Edwin - Add 3rd Toggle to Bio Announcement (Fixed)

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description
- **Fixed typo in line 188 from userProfileController.js that caused user to not be able to create new users.**
- Added a third state for the “Bio Posted/Requested” selection to the Weekly Summary Report Page. It now includes "Posted, "Default", "Requested"
- A toggle switch that can change the status of bio announcement has been modified to toggle between three states instead of 2. 

### Mainly changes explained:
- **Changed typo of `up.permissions = req.body.bioPosted || 'default';`  to  `up.bioPosted = req.body.bioPosted || 'default';`**

### How to test:
**Please test with the front end [PR 866](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/866)**
checkout this branch
for the server:
npm run build
npm start
for the front end:
npm run start:local
run the front end and test

### CODE REVIEW

**Review by nathanah — APPROVED** [review]
Everything looks good.

**Review by mahamakhan — APPROVED** [review]
The toggle works 3 ways in the front end and can be seen when checked in the front end.

**Review by bienzguoa — APPROVED** [review]
Looks good!

**Review by wechuli — APPROVED** [review]
Backend changes look good!

**Review by stevenpaalz — APPROVED** [review]
Backend changes appear to be working correctly.

**Pull request merged**
