### PR TITLE
Edwin - Create way to show how many times a deadline has been updated

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-06-29 at 6 03 50 AM

## Related PRS (if any):
This backend PR is related to FE PR [#956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/956)

## Main changes explained:
Added "deadlineCount" property to track the amount of times a deadline has been updated

## How to test:
1. check into current branch
2. do `npm run build` && `npm run start`

### CODE REVIEW

**Review by cvtqx — APPROVED** [review]
Implemented counter works as described. Great job! Left a review on a related FE PR.

**Review by mahamakhan — APPROVED** [review]
Number changes when the hours are changed.

**Comment by Lucas-E** [comment]
Great job everybody! Moving this one to final review!

**Comment by igorrochadasilva** [comment]
Hi @EdwinLauM again : D
Implemented counter works as described. Great job! I left a review on a related FE PR.

**Review by igorrochadasilva — APPROVED** [review]

**Comment by beblicarl** [comment]
This PR works as intended

**Review by beblicarl — APPROVED** [review]

**Review by NidaZaki — APPROVED** [review]

**Pull request merged**
