### PR TITLE
Roberto - For Main Branch- sends email to Jae whenever Admin or Owner accounts are created or password reset

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
Screenshot 2023-10-10 at 1 34 00 PM
Like PR 569 this PR sends an email whenever an Owner account is created or their password is reset. However this PR is meant for the main branch so it also includes an email sent for the creation of Admin accounts and their passwords reset as well.

## Related PRS (if any):
This backed PR is a continuation of [569](https://github.com/OneCommunityGlobal/HGNRest/pull/569)

## Main changes explained:
- Imports and uses emailSender function in userProfileController.js. Email is sent when a new owner account or admin account is created or password is reset. 
- Adds more security checks to the reset password function because it didn't originally check permissions.

## How to test:
1. Follow PR [569](https://github.com/OneCommunityGlobal/HGNRest/pull/569) instructions and set up first
2. Additionally verify that creating a new Admin account results in an email.
3. Verify that resetting an Admin's account results in an email as well.

## Note:
PR 569 is a prerequisite to this PR so check it out first. This is a continuation of that PR.

### CODE REVIEW

**Review by malikjahanzaib — APPROVED** [review]
Hi @robertoooc, I have already tested PR #569 and it is working fine about the owner account. I tested this PR and it works exactly like that one but this time for Admin and Owner accounts both. So when I created and reset password for Admin and Owner accounts, an email was sent out notifying about the respective change. Nice work!!!

Screenshots:

Screenshot 2023-10-21 034708

Screenshot 2023-10-21 034850

Screenshot 2023-10-21 034902

Screenshot 2023-10-21 034821

Screenshot 2023-10-21 034911

Screenshot 2023-10-21 034920

**Review by shubhankarval — APPROVED** [review]
Hey @robertoooc, I tested this PR and it works as intended, good job!
\
Creating new Admin account:
Screenshot 2023-10-21 201949
Screenshot 2023-10-21 202005
\
Resetting password for an Admin account:
Screenshot 2023-10-21 202044

**Review by Shuhua-L — APPROVED** [review]
Hi @robertoooc, I've tested these actions: 
- reset an Owner's password as Owner
- created an Admin account as Owner
- reset the new Admin's password as Owner
- created an Admin account as Admin
- reset the new Admin's password as Admin

All received corresponding email notifications. Well done!

https://github.com/OneCommunityGlobal/HGNRest/assets/83729360/e9f7fd5d-6b38-4769-b4c1-0e35c1de68cf

**Review by ilyaflaks — COMMENTED** [review]
I left a more detailed comment on PR#569, but I'm having the same issue with this one. Can not create user with the backend in this branch because "location" is not being parsed correctly as a string. This is not due to the code changes in this PR but rather due to the changes to the "development" branch of the front end since this PR was submitted.

**Review by psharma1984 — COMMENTED** [review]
Hi @robertoooc tested with admin accounts in continuation to PR#569 and it sends email for new admin account and password change for the same. Here's the screenshot
Screenshot from 2024-02-19 18-38-06
Screenshot from 2024-02-19 18-37-44
Screenshot from 2024-02-19 18-39-31

**Review by psharma1984 — APPROVED** [review]

**Review by huangweihou — APPROVED** [review]
Hey @robertoooc, I have tested PR#569 and PR#570 works correctly as well. Please take the below screenshot as references:
Screen Shot 2024-02-24 at 7 49 39 PM
Screen Shot 2024-02-24 at 7 49 28 PM

**Review by skaush21 — APPROVED** [review]
Hi, I commented on [PR 569](https://github.com/OneCommunityGlobal/HGNRest/pull/569) 
* signed in as owner
* created an admin account, received email verification
* reset admin account password, received email verification
This added feature works great!
creating account
resetting password

**Pull request closed without merging**
