### PR TITLE
Fix weekly badge assignment tasks do not update the badge earned date collection

### PR DESCRIPTION
**Pull request by ptrpengdev**
# Description
**Fix the badge  earned date not being updated in the weekly badge assignment task**
image

**Fix the issue where the last modified date mismatches with the last earned date in the frontend.**
image

## Related PRS (if any):
This backend PR is related to the #[1671](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1761) frontend PR.
To test this backend PR you need to check out the #1671 frontend PR.
…

## Main changes explained:
- Update file userHelper.js to include new code to process existing earned date records when the badge count is updated
- Update file userHelper.js to fix all linting issues

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an admin/owner user
5. to test the last modified date mismatches with the last earned date fix (no backend modification needded):
      - go to View Profile link Or Others -> Badge Management
      - add a new badge to a user and verify the newly added badge's last modified date is the same as the latest earned date
      - update an existing badge and verify the badge's last modified date is the same as the latest earned date
6. to test the weekly badge assignment fix:
      - go to the userProfileJobs.js file in the backend
      - **modify the line**  '1 0 * * *' to '* * * * *' so the cron job runs every minute
      - **comment out all scheduled tasks but userhelper.awardNewBadges()** -> so you don't run irrelevant jobs
image
      - go to the userHelper.js file in the backend
      - **modify the awardNewBadges()** function to run tasks on a specific user (an account to which you have access would be the best) -> so you don't run the badge award function to all users
       - We are doing unit testing on the modified function here: Comment out 1494-1515. 
      image
      - code snippet

      ```
      /*
       * the changeBadgeCount takes 3 arguments userId, badgeId, and newBadgeCount. 
       * The provided code snippet retrieves the user by user id and updates the existing badge records. 
       * To run the sample testing code, all you need is to change the input 'userId ' to the actual user id you prefer.
      */
      
             // retrieves user
             const userId = '65500b658e0b2922b80d5f9f'; // replace this to your user id
             const user = await userProfile
             .findOne({ _id: userId })
             .populate('badgeCollection.badge');
             // unit testing for changeBadgeCount
             for (let badgeItem of user.badgeCollection){
               await changeBadgeCount(userId, badgeItem.badge._id, badgeItem.count + 1); // or any number you like
             }
      
             if (cache.hasCache(`user-${userId}`)) {
                  cache.removeCache(`user-${userId}`);
             }
     ```

     - verify that **all badges count increase by 1 or any number you specified in the previous code** and **the last modified date should match the latest earned date**. Refresh the frontend page after seeing 'Awarding' in the backend console.
      image

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/69882989/e7f2f0c0-1fc0-419c-975b-e7955e1ebda1

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by ChengyanOo — CHANGES_REQUESTED** [review]
@ptrpengdev

Your documentation and explanation of the testing walkthrough are excellent. However, I encountered a few issues while testing your code.

1. **Volunteer Role Issue:** I followed your video, checking out this branch for the backend and updating all files accordingly. Testing with the volunteer role, I consistently observed "awarding" messages in the backend console. Despite refreshing the webpage, the badge count did not increase. Interestingly, after restarting the backend, the badge count showed an increase to 4. Here's a screenshot for reference:
Screenshot 2024-01-03 at 11 21 38 AM


2. **Admin Role Issue:** Testing with the admin role, I noticed that updates were reflected on page refresh, but only after the first instance of 'rewarding'. Given that the scheduled task is supposed to update each time, this seems inconsistent, especially since your demo video also showed only one instance of 'rewarding'. Is this behavior expected, or is it a potential universal issue?

3. **Dashboard UI Discrepancy**: I observed a minor discrepancy in the badge dashboard UI. It indicated that I had three badges, whereas I actually had four. Here's a screenshot for clarity:

Screenshot 2024-01-03 at 11 21 07 AM



Looking forward to your insights on these issues.

**Comment by ptrpengdev** [comment]
> @ptrpengdev
> 
> Your documentation and explanation of the testing walkthrough are excellent. However, I encountered a few issues while testing your code.
> 
> 1. **Volunteer Role Issue:** I followed your video, checking out this branch for the backend and updating all files accordingly. Testing with the volunteer role, I consistently observed "awarding" messages in the backend console. Despite refreshing the webpage, the badge count did not increase. Interestingly, after restarting the backend, the badge count showed an increase to 4. Here's a screenshot for reference:
> 
> Screenshot 2024-01-03 at 11 21 38 AM
> 2. **Admin Role Issue:** Testing with the admin role, I noticed that updates were reflected on page refresh, but only after the first instance of 'rewarding'. Given that the scheduled task is supposed to update each time, this seems inconsistent, especially since your demo video also showed only one instance of 'rewarding'. Is this behavior expected, or is it a potential universal issue?
> 3. **Dashboard UI Discrepancy**: I observed a minor discrepancy in the badge dashboard UI. It indicated that I had three badges, whereas I actually had four. Here's a screenshot for clarity:
> 
> Screenshot 2024-01-03 at 11 21 07 AM
> Looking forward to your insights on these issues.

Thanks for testing. To address your questions:

1. **Testing with the volunteer role, I consistently observed "awarding" messages in the backend console**. 
> As I mentioned in **How to test section step 6**, modify the line '1 0 * * ' to ' * * * *' so **the cron job runs every minute**. Hence, this is an expected behavior. 
2.   **Despite refreshing the webpage, the badge count did not increase, after restarting the backend, the badge count showed an increase to 4.** 
> Could you verify that the badge count didn't increase after refreshing the page and seeing the awarding message? The badge count increased since this is a backend-scheduled job, and it should award badges as we defined in the test code snippet. 
3. **I noticed that updates were reflected on page refresh, but only after the first instance of 'rewarding'.** 
> You should see "awarding" every minute since this is defined in the task scheduler according to **How to test section step 6** - modify the line '1 0 * * ' to ' * * * *' so **the cron job runs every minute**. Did you wait for another minute to allow the scheduled task to run, or did the app crash after the first awarding message? Please provide me with more details. Thanks!
4. **Dashboard UI Discrepancy: I observed a minor discrepancy in the badge dashboard UI. It indicated that I had three badges, whereas I actually had four. Here's a screenshot for clarity**
> This issue is not related to this PR. You could report it as a bug in the HGN bug document.

**Comment by ChengyanOo** [comment]
@ptrpengdev 

Thanks for your quick reply, I did modify the line '1 0 * * ' to ' * * * *' as you suggested, and the console was outputting 'rewarding' each minute, however the changes were not reflect, like I mentioned after the first 'rewarding' for the admin account for me.

**Comment by ptrpengdev** [comment]
> @ptrpengdev
> 
> Thanks for your quick reply, I did modify the line '1 0 * * ' to ' * * * *' as you suggested, and the console was outputting 'rewarding' each minute, however the changes were not reflect, like I mentioned after the first 'rewarding' for the admin account for me.

Hi @ChengyanOo ,

I just re-tested the code. The backend code worked as expected. However, I noticed that the user cache wasn't evicted after the scheduler ran. Hence, we would have correct data in the DB but still the same badge count in the frontend. I believe this was a bug that we weren't aware of. Thanks for pointing it out.

**Review by ChengyanOo — APPROVED** [review]
@ptrpengdev 

I just tested again and everything works as intended!

Screenshot 2024-01-03 at 13 29 35

**Pull request merged**
