### PR TITLE
Mohan - Add Team Code to Create New User

### PR DESCRIPTION
**Pull request by mohangadde1**
# Description
Screenshot 2024-10-05 153641
Added 

## Related PRS (if any):

To test this backend PR you need to checkout the [#2758](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2758) frontend PR.
…

## Main changes explained:
added team code to UserProfileController.js
…

## How to test:
check into current branch
do npm run build && npm run start
follow steps of the frontend PR [#2758](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2758)

### CODE REVIEW

**Review by ziyanw52 — APPROVED** [review]
I have tested this PR and it works. I have also left a comment on the frontend PR #2758.

**Review by Ankuriboh — APPROVED** [review]
Tested and it worked along with the corresponding frontend PR, I also left [my two cents](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2758#pullrequestreview-2357466823) there.

**Review by shivansh-nathani — APPROVED** [review]
The white screen issue has been fixed. PFB the testing video demonstrating the same.

https://github.com/user-attachments/assets/2d8a1e63-c584-4660-9b6a-3223a1c4539f

**Review by anirudhsk2107 — APPROVED** [review]
Left a comment on [PR 2758](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2758#pullrequestreview-2364324757)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
