### PR TITLE
Jingyi create/edit/delete badges permission

### PR DESCRIPTION
**Pull request by Jingyii800**
# Description
This PR is related to badge [permission management fixes](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit#gid=0). It enables users with create/edit/delete badges permission to see the changes of badges immediately.

## Related PRS (if any):
This backend PR is related to the development frontend PR.

## Main changes explained:
Whenever the user has the badge management permissions ("createBadges," "updateBadges," or "deleteBadges") and makes changes to badges, the badge management table will fetch the newest data and display the badge immediately. 

## How to test:
1. check into the current branch
2. do `npm install`,  `npm run build`, and `npm start to run the frontend PR locally
4. Clear site data/cache
5. log as admin/owner user
6. go to Other Links -> Permissions Management -> Manage User Permissions -> Badge Permission -> Choose a user without badge management permissions such as 'create badges' 'edit badges' or 'delete badges' -> add the permission for this user -> Scroll down then submit
7. log into the account just granted permission and go to Other Links -> Badge Management to test the permission you just added. For example, create one badge, edit one, or delete one badge.
8. You will see the change immediately on the page.

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/d879dabd-4d4e-48d4-a60c-7982e0ceb097

### CODE REVIEW

**Review by Sandhya1236 — DISMISSED** [review]
This PR addresses badge permission management fixes, enabling users with create/edit/delete badges permissions to see changes immediately. The main changes involve updating the badge management table to fetch and display the newest data whenever changes are made by users with the relevant permissions.

To test, I checked into the current branch, ran npm install, npm run build, and npm start to run the frontend PR locally. I cleared the site data/cache, logged in as an admin/owner user, navigated to Other Links → Permissions Management → Manage User Permissions → Badge Permission, and granted badge management permissions to a user. Upon logging into the account with the newly granted permissions, I tested creating, editing, and deleting badges to ensure the changes were reflected immediately.

However, I encountered several warnings related to unsupported engines and deprecation notices for MongoDB's collection.ensureIndex, suggesting a need for dependency updates. Despite these warnings, the application did not proceed as expected, indicating further investigation and resolution are required before full functionality can be verified.

image

**Review by Kavil-Jain-514 — CHANGES_REQUESTED** [review]
I have tested the PR. Started by giving permissions to the user for the Badge Management.
However, I have found a bug unrelated to the PR.
The bug: Admin -> Other Links -> Permission Management -> Manage User Permission 
If an admin wants to add all the badge management permissions for the user, the  Add button for the permission will not work. I had to manually click all the child permissions for badge management (See/create/edit/delete/assign). |
image


Coming to the PR review. I was facing issues after assigning permission. When I logged in as a test user and navigated to view the profile to test the permission, I was encountered this error and a blank white screen
image

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and the functionality is working fine.

--Able to provide badge permission for users with no access to 'create badges'  'edit badges' and 'delete badges'.
--Can Create, Edit and Delete Badges successfully for users with access. 
--When the user is removed with the access, and attempting to create or edit or delete badges, getting the "You are not Authorized" message.

Suggestion: 
1. Whenever a new badge is created, the created item is not available at the top row. Please ensure the order of the latest added badges.
2. When the user is not having create access, the error message can be displayed on clicking the "Create New Badge" button rather than "Create" button available after submitting the details.

https://github.com/OneCommunityGlobal/HGNRest/assets/166590596/32556763-0656-49ca-8c89-af09218261a8


PR974_DeleteAccess_Err_Msg
PR974_UpdateAccess_Err_Msg

**Comment by akshit0211** [comment]
Hi Jingyi, I have tested the PR functionality, and it works as expected. I have one suggestion: whenever a user edits a badge, there should be a pop-up message saying something like "You have updated the badge," similar to the pop-ups for badge creation and deletion.

Badge Permissions
Added Permissions
Created badge
Deleted Badge

**Review by akshit0211 — APPROVED** [review]

**Review by Wenboooooo — CHANGES_REQUESTED** [review]
I followed the instructions provided in the pull request to test the badge permission management fixes. Here are the steps I took and the issue I encountered:
Checked out the Current Branch:
I switched to the branch associated with the pull request.
Installed Dependencies and Ran the Frontend:
I ran npm install, followed by npm run build, and finally npm start to launch the frontend locally.
Cleared Site Data/Cache:
I cleared the site data and cache in my browser to ensure no old data interfered with the test.
Logged in as Admin/Owner User:
I logged into the application using an admin/owner user account.
Navigated to Badge Permission Management:
I went to Other Links -> Permissions Management -> Manage User Permissions -> Badge Permission.
Granted Badge Management Permissions to Another User:
I selected a user who did not previously have badge management permissions (such as 'create badges', 'edit badges', or 'delete badges'). I added the badge management permissions for this user and submitted the changes.
Logged in with the Granted User Account:
I logged out of the admin account and logged in with the user account that was just granted the badge management permissions.
Issue Encountered:
When logged into the user interface with the newly granted permissions, I did not see the badge management button or section appear. This suggests that the badge management permissions might not be applied correctly, or the interface is not updating as expected to reflect the new permissions.

https://github.com/OneCommunityGlobal/HGNRest/assets/114895283/6c2902bc-2bea-4128-8a21-fc4ad18fffb3

**Comment by Jingyii800** [comment]
> I followed the instructions provided in the pull request to test the badge permission management fixes. Here are the steps I took and the issue I encountered: Checked out the Current Branch: I switched to the branch associated with the pull request. Installed Dependencies and Ran the Frontend: I ran npm install, followed by npm run build, and finally npm start to launch the frontend locally. Cleared Site Data/Cache: I cleared the site data and cache in my browser to ensure no old data interfered with the test. Logged in as Admin/Owner User: I logged into the application using an admin/owner user account. Navigated to Badge Permission Management: I went to Other Links -> Permissions Management -> Manage User Permissions -> Badge Permission. Granted Badge Management Permissions to Another User: I selected a user who did not previously have badge management permissions (such as 'create badges', 'edit badges', or 'delete badges'). I added the badge management permissions for this user and submitted the changes. Logged in with the Granted User Account: I logged out of the admin account and logged in with the user account that was just granted the badge management permissions. Issue Encountered: When logged into the user interface with the newly granted permissions, I did not see the badge management button or section appear. This suggests that the badge management permissions might not be applied correctly, or the interface is not updating as expected to reflect the new permissions.
> 
>  974.mp4

Thank you for your message. I have updated the code with the newest development branch code and tested it on my local machine. It worked well. Could you please test it again?

**Review by jinxyou — APPROVED** [review]
I tested the function of badge management by following steps:
- Add a user to gain badge permission.
- Log into the user.
- Trying to add, edit, delete badges.

The result seems great. All functions can be performed without errors. Great work!

Screenshot 2024-06-08 161213
Screenshot 2024-06-08 161254
Screenshot 2024-06-08 161311
Screenshot 2024-06-08 161322

**Review by Ramaruva — APPROVED** [review]
Hey, I have tested your changes and are working fine as expected, when I assign badge permission to any particular user I am able to navigate to badge management and also assign,edit, delete those badge also.
image
image
image
image

**Review by TXMO-dev — APPROVED** [review]
Jingyi create/edit/delete badges permission has been assigned successfully to the controller. Approved!

**Review by Kavil-Jain-514 — APPROVED** [review]
The user with the Badge Management permission can create a new badge, edit an existing badge and also delete badge.

The PR works great.
image
image
image

**Review by deepthikannan — APPROVED** [review]
image
image
Hey I've tested the badge management function and it works great with the expected results.

**Review by suaniii — APPROVED** [review]
I have tested the changes and confirmed they work as expected. Logged in as an admin, selected a user without badge management permissions, added the necessary permissions, and submitted. Then, logging into the account just granted these permissions. I successfully assigned, created, edited, and deleted badges, with all actions working perfectly and the badge management table updating and displaying changes immediately. 


https://github.com/OneCommunityGlobal/HGNRest/assets/113208952/1a82f61d-225f-4344-a03a-87f23c0a6ff4

**Review by shradac — APPROVED** [review]
Hey, I have tested your changes and are working fine as expected
Created a volunteer account
Logged in into the admin account -> added badge permissions for the volunteer account
logged out - . logged in again into the volunteer account
Changes visible
Created a badge
Deleted a badge
Modified a badge

Good job!
Screenshot 2024-06-17 at 8 59 08 PM
Screenshot 2024-06-17 at 9 48 19 PM
Screenshot 2024-06-17 at 9 48 30 PM
Screenshot 2024-06-17 at 9 48 37 PM

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by cvtqx — APPROVED** [review]
Everything works as described. Great job!
Using an admin account I enabled another user to create/edit/delete badges. When logged in as that other account I could perform all these actions. I then logged in again as admin and  removed 'edit' permission for this user. The change was immediately in effect and the user could no longer edit a badge. 

Video:

https://github.com/OneCommunityGlobal/HGNRest/assets/107726913/a673b5f1-b5fb-41c8-b465-7a549074a71e

Edit permission removed:

Screenshot 2024-06-22 at 1 31 53 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
