### PR TITLE
Jinchao add invisible icon on leaderboard

### PR DESCRIPTION
**Pull request by suigunfjc**
BE update for [#859](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/859). Please see the detailed instructions on FE PR.

### CODE REVIEW

**Review by EdwinLauM — APPROVED** [review]
Work as intended! Left a more detailed comment in the frontend.

**Review by lchua2314 — APPROVED** [review]
Backend code looks good and everything works as intended. More details on the frontend PR. I approved the frontend PR as well. Good work!

**Review by wechuli — APPROVED** [review]
Backend changes look good to me

**Review by 20chen-7 — APPROVED** [review]
I approved the FE, and the BE code looks clean and good.

**Review by NidaZaki — APPROVED** [review]
Changes look good to me. Approved FE as well!

**Pull request merged**
