### PR TITLE
Equipment_List_View

### PR DESCRIPTION
**Pull request by Aishwaryak01**
This PR is about the Equipments List View from Phase 2 with Sorting based on project name and item name, Filtering based on selected values of project and equipment, and Modal implementation for viewing update and purchase history.
Implements # (WBS) 9.1.2

Related PRS (if any):
To test this backend PR you need to check out the #1937  frontend PR.

Main changes explained:
Created a fetch API for equipments

How to test:
1. check into the current branch
2. do npm run build and npm run start to run this PR locally
3. Test api : http://localhost:4500/api/bm/equipments

### CODE REVIEW

**Review by swathyjayaseelan — APPROVED** [review]
Changes look good. Attached screen recording in the front-end PR.

**Review by XiaohanMeng — APPROVED** [review]
Hi, I've left my comment on the Frontend project. The backend terminal did not show any errors. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#pullrequestreview-1897229570

**Comment by skaush21** [comment]
left comment on frontend [PR #1937](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#pullrequestreview-1899224609)

**Review by brandta-1 — APPROVED** [review]
# Review
```src/controllers/bmdashboard/bmEquipmentController.js``` looks correct. My Node terminal did not print any errors during testing.

# Video
See [front end review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#pullrequestreview-1899577466).

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed the frontend PR related to this and the backend server runs without any errors.

**Comment by rajnada** [comment]
Hi,

It's working good !
here is my Frontend Review [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#issuecomment-1986095964](url)

**Comment by SanketKaware** [comment]
The changes look good. Here is my frontend review of your PR - [HighestGoodNetworkApp/pull/1937](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#issuecomment-1986623872)

**Review by YHX6 — APPROVED** [review]
I tested and this feature works correctly.

**Review by bhuvan-dv — APPROVED** [review]
Changes look good here, have approved the [Frontend changes too.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#pullrequestreview-1926294764)

**Review by iven-yao — APPROVED** [review]
checked this with [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#pullrequestreview-1941345378), works as expected.

**Review by 20chen-7 — APPROVED** [review]
Good job, left review at the frontend

**Review by ImzIssa — APPROVED** [review]
Hello, your changes look good, nice work.

My Frontend PR Review: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#pullrequestreview-1953951874

**Review by kylepham — APPROVED** [review]
Changes work for me. I left a review on the frontend [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#pullrequestreview-1959164998).

**Comment by Gayathr-2012** [comment]
Hi,
I have left comment in Front end It woks as expected. I checked Backend URL  http://localhost:4500/api/bm/equipments
It works. Good job.

image

**Review by Parth-tech — APPROVED** [review]
Great Job. Please do check the suggestion.

[Approved review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#pullrequestreview-1984849112)

**Comment by MQChen211** [comment]
Hi, I tested the frontend and it works well.
[https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1937#issuecomment-2045865464](url)

**Review by cvtqx — APPROVED** [review]
This works as described. Left comments in the FE PR.

**Comment by kaushikMreddy293** [comment]
Hi, 

image

The API call works as expected. Left comments in the Frontend PR as well

**Comment by KaushikMreddy** [comment]
Hi, 

image

The API call works as expected. Left comments in the Frontend PR as well

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
