### PR TITLE
Shihao - Add 'members' to the Team schema

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Screenshot 2023-08-18 at 13 52 18
To implement the sort by added date. It requires adding a new field to record it.

## Related PRS:
This PR is related to the [#1136](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1136) frontend PR.

## Main changes explained:
- Add `members` to the Team schema
- Create a script to add team documents to the database

## How to test:
1. check into current branch
2. ❗️ for the product environment only, run `node src/utilities/addMembersToTeams.js` to update the database schema (already update the dev database)
4. do `npm install` and `npm run build` to run this PR locally
5. start the server by `npm start`
6. ❗️ follow the instruction in the frontend PR [#1136](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1136)

## Screenshots or videos of changes:
**Instruction to run the script**

https://github.com/OneCommunityGlobal/HGNRest/assets/62367016/89c9396e-be0b-41a8-ba3b-518899c11b08

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Hi @sxiong5 , I've tested this PR along with the frontend PR. Approval with comments is left here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1136#pullrequestreview-1585079716

**Review by LunaticLeo — APPROVED** [review]
Hi, I have viewed the frontend changes, it works well, and the backend code has no problem by me. Excellent work! @sxiong5

**Review by navneeeth — APPROVED** [review]
LGTM! Tested the changes and the PR works as expected. I have also approved and commented on the [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1136). Good implementation!

**Review by veronicacheng2 — APPROVED** [review]
Hi @sxiong5, tested the PR together with #1136. Everything works as intended. Comments left on [#1136](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1136).

**Comment by KurtisIvey** [comment]
Functions as intended. Tested this pr together with [1136](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1136)

Well done! no errors on the backend, even when I was adding and removing users from teams.

**Review by TheDescendant39 — APPROVED** [review]
Hi @sxiong5, approved the Frontend PR as well.

**Comment by AuroraLovesWhales** [comment]
Hi @sxiong5. I have approved this pair of PR and left my comment at the frontend. Great job!

**Review by AuroraLovesWhales — APPROVED** [review]

**Review by yunshan111 — APPROVED** [review]
LGTM, Tested both frontend and backend.

**Review by yaow62023 — APPROVED** [review]
I have test your PR at frontend PR #1136. All the features works as intended.

**Review by arcan9 — APPROVED** [review]
Test on both ends. This worked alongside the FE PR. Nice job!

**Review by tsunami776 — APPROVED** [review]
I conducted tests on both the FE and BE. Specifically, I added new members with different addDateTime to a team and examined the sorting functionalities and how DB behaved. The new member correctly appeared in the sorted member list in FE and BE. This functionality integrated well with the FE PR #1136. 


https://github.com/OneCommunityGlobal/HGNRest/assets/43768723/5468ec6c-e7ed-4c48-9c05-07b6f5a3af6c

**Review by Haoj1 — APPROVED** [review]
Hi @sxiong5, both date column and sort work great! Comments in #1136

**Pull request merged**
