### PR TITLE
Jinchao apply missed hours to Core Team member

### PR DESCRIPTION
**Pull request by suigunfjc**
# Description
Back-end update for: a & b
image
Frontend [PR757](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/757)

## Mainly changes explained:
Add `applyMissedHourForCoreTeam` function in userHelper.js to calculate missed hours for Core Team weekly.
Update `assignBlueSquareForTimeNotMet` function in userHelper.js to apply missed hours in the weekly blueSquare check.
Update `getTasksForTeamsByUser` function in taskController.js to send updated weeklycommittedHours for the tasks component.
Update `getLeaderboard` function in dashboard.js to send updated weeklycommittedHours for the leaderboard component.

## How to test:
This PR needs API testing using Postman, please first set up the Postman environment. 
1. If this is your first time using Postman, just start HGNRest and post to http://localhost:4500/api/login with the email and password in the body. You will get a token as a result if your setup is successful.
image

2. Make the following adjustments to HGNRest then rebuild and restart the HGNRest:
**userProfileController.js: Add test function in userProfileController**
image
**userProfileRouter.js: Add a new route to call the test function**
image
**userHelper.js: Add `role: 'Core Team'` to line 247 to let assignBlueSquareForTimeNotMet just apply for Core Team member.**
image

3. Use Postman and send a GET request to http://localhost:4500/api/userProfiletest. Make sure you input the correct address and method set to GET. **Set the authorization value to the token you get at step 1 in the header**. The request will return finished (this will take a few seconds.)
image

4. Open a 'Core Team' userProfile page and check the value of Additional Make-up Hours This Week. It should be (previous make-up hours + weeklycommittedHours - last week's total tangible time). Also, check the blue square to see if the blue square assignment is correct.
image

5. Use an admin user account to assign 'Core Team' user tangible time of last week. You can click the green/red dot of that user from the leaderboard and go to that user's dashboard, then assign a time log. Then repeat step 4 to see if the make-up hours and blue square assignment process is correct.
image

## Note
In step 4 and 5, the make-up hours and blue square may not update since the cache of that user won't get updated. Try inactive/active the user to clean the cache. The applyMissedHourForCoreTeam function doesn't need to update the cache since it runs weekly and doesn't require immediate affection.

### CODE REVIEW

**Review by abdel-lall — COMMENTED** [review]
the blue square assignment process worked fine for me, however when I add tangible time for last week, it doesn’t subtract it from  previous make-up hours + weeklycommittedHours.
According to the PR description:
“the value of Additional Make-up Hours This Week. should be (previous make-up hours + weeklycommittedHours - last week's total tangible time)”
In the picture attached shouldn't  the Additional Make-up Hours This Week be 10 hours instead of 15 hours since I added 5 hours tangible hours to the last week.

image1
image2

**Comment by suigunfjc** [comment]
Hi @abdel-lall thank you for testing the function!! It's not easy I know. I tried to debug on my console about the calculation of the missed hours. Here is the result:
image
Currently, your AL tester account has 15 missed hours, 15 weekly committed hours, and 5 tangible hours for last week. The result is 15 + 15 -5 = 25 as expected.
Could you record a video about your operations causing an incorrect result? Thanks so much!

**Review by abdel-lall — COMMENTED** [review]
Hi @suigunfjc, My AL tester account now has 30 missed hours, 15 weekly committed hours, and 5 tangible hours for the week before last week. The result should be 15 + 30 - 5 = 40.

https://user-images.githubusercontent.com/49083865/230838183-200cf158-4717-4464-bc66-862e066aea49.mp4

**Comment by suigunfjc** [comment]
@abdel-lall I noticed that in your video when you run the function, the 5h time log is logged as the week before last week, so your effort for last week is 0, then the result should be 45.

**Review by abdel-lall — COMMENTED** [review]
yes, you're right. thank you for the clarification.

**Comment by LucileTech** [comment]
Hi [suigunfjc](https://github.com/suigunfjc) I tested your back and step 5 is not working even when I active/inactive the user. 
Is it the right place to inactive the user as you said? 
Screenshot 2023-04-12 at 17 31 37

The rest is working


Screenshot 2023-04-12 at 17 13 48
Screenshot 2023-04-12 at 17 21 15
Screenshot 2023-04-12 at 17 23 00
Screenshot 2023-04-12 at 17 24 31
Screenshot 2023-04-12 at 17 27 31
Screenshot 2023-04-12 at 17 28 15

**Comment by suigunfjc** [comment]
Hi @LucileTech, from the picture you provide for tangible hour time log, the date for that time log is April 12. However, the calculation for the missed hour only takes time log in last week (currently April 2 to April 8). So you might need to change the time period for that time log by logging in as an admin user and opening the core team user's dashboard from the leaderboard then editing the time for that time log

**Comment by agujjar2206** [comment]
Great job on the PR! It must have been challenging to implement. I tested the PR and it works as expected. Also, thank you for the note!

Screenshots:

**Review by PrabhjotSembhi — COMMENTED** [review]
Added my comments on Frontend PR

**Review by one-community — APPROVED** [review]
Merging along with frontend because Prabh approved final request there.

**Pull request merged**
