### PR TITLE
make the hoursLogged field work for task

### PR DESCRIPTION
**Pull request by EvianTan**
This PR is the backend changes for task allowing `hoursLogged` field to work.

How to test:
1. get this branch install/build/start
2. use request `getTaskById()` on Postman to test and verify

Images showing debug results for task "15 HGN Test Close Task 111":
image1: time entries for this task
debug output1

image 2: sum up time for above time entries of this task
debug output2

image 3: response on Postman
image

### CODE REVIEW

**Comment by esk47** [comment]
Looks like it works but when I test it, hoursLogged shows the sum of intagible and tangible time logged. Is that expected?

**Comment by one-community** [comment]
Hours logged should be total tangible time only

**Comment by EvianTan** [comment]
> Looks like it works but when I test it, hoursLogged shows the sum of intagible and tangible time logged. Is that expected?

I updated the timeEntries counting to only add tangible ones.

Tested like below:
Added a new intangible time entry for "HGN Test Close Task 111", the `hoursLogged` field of task response didn't change.
image
image

**Review by esk47 — APPROVED** [review]
Works great

**Comment by one-community** [comment]
Merged to Dev. Adding tangible time didn't change the tangible time number for me though. The Total Tangible Hours field should also be editable. The other fields when edited should allow me to save the edits also. Right now if I edit them, the "save" button is still inactive.

**Pull request merged**
