### PR TITLE
Sucheta -  Search Projects By Person

### PR DESCRIPTION
**Pull request by sucheta90**
# Description
(PRIORITY HIGH) Jae: Search Projects By Person
- Other Links > Projects
- Need a way to search project by person so I know which ones they belong to and can easily add tasks for them
[Video of what’s needed](https://www.loom.com/share/3c95e9c100f44bcd8cab922bcff8e8e1)

## Related PRS (if any):
To test this backend PR you need to checkout the #[2312](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2312) frontend PR.
…

## Main changes explained:
- Adds a new controller function `getProjectsByPerson` to `controller > userProfileController.js`
- This function fetches the user profile by the first and the last name of a user that is received though user input.
- Once the user's profile has been retrieved, the `projects` array is then sent as a response for use in frontend.

…

## How to test:
1. check into current branch
2. do `npm install` , `npm run build`, and `npm run dev` to run this PR locally
3. Clear site data/cache
4. log as admin/ owner user (any account that has access to the project's page)
5. go to dashboard→ Other Links→ Projects

### CODE REVIEW

**Review by Ramaruva — CHANGES_REQUESTED** [review]
Hi reviewed this changes in frontend and requested some changes

**Comment by KaushikMreddy** [comment]
Hi @sucheta90 , 

I've reviewed this PR. Backend is working as expected. I have suggested and requested some changes for an error faced in the frontend here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2240#pullrequestreview-2047247833

Good work!

**Review by Ramaruva — APPROVED** [review]
Changes are working as expected 
and commented in frontend also

**Review by nathcarnevalli — APPROVED** [review]
I searched for different accounts with the roles Admin, Owner, Mentor, Manager, Assistant, and Volunteer with and without projects, and all of them worked as demonstrated in your video at [#2241](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2241) frontend PR

Volunteer:
Screenshot 2024-05-10 151254

**Review by jayyy-s — CHANGES_REQUESTED** [review]
I tested these changes and they seem to work as intended. I am able to correctly search for a user in a project and get an error for users that do not exist. 

I would suggest allowing users to search by only first name or only last name (mentioned in the frontend PR) and have included a suggestion to make this possible.
https://github.com/OneCommunityGlobal/HGNRest/assets/71467346/fde87769-3148-4e2b-ac44-a31fd3166b1d
https://github.com/OneCommunityGlobal/HGNRest/assets/71467346/df156fa7-aa16-43a6-86d1-01a0d5698930

**Review by hbodgal — APPROVED** [review]
image

Your code works well. I was able to search user based on Firstname and Lastname. But, the suggestions given by reviewers seems practical and should be implemented.

**Comment by ZhangPeizhou** [comment]
https://github.com/OneCommunityGlobal/HGNRest/assets/95693786/299bfb8c-b4c2-4248-be2f-6b1836e23eaa

It works as expected. Nice wrk!

**Review by gowthamdongari — APPROVED** [review]
Works as expected 
Screenshot 2024-05-16 140717

**Review by Parth-tech — APPROVED** [review]
Good job. Left a review on the frontend repo: [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2241#pullrequestreview-2064373688)

**Review by peter6866 — APPROVED** [review]
I have reviewed the frontend PR and it works great with the backend.

**Review by Sandhya1236 — COMMENTED** [review]
The changes work as expected. This video demonstrates that I can successfully search for a specific user by first and last name on the projects page. However, if no projects are associated with the user, even if the user exists, it would be nice to display a popup saying "No projects associated" along with the empty projects page that is being displayed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/8663dcb0-6ff0-418e-a458-1ed10b80d0cf

**Review by jennZhang93 — COMMENTED** [review]
Tested with owner account. Get latest changes from mentioned frontend and backend branch. But tried multiple usernames and no projects were returned, while I'm expecting projects to be returned. Not sure if the latest commits changed anything here.

Screenshot 2024-05-25 at 9 25 54 PM
Screenshot 2024-05-25 at 9 25 57 PM

**Comment by dikshitakejriwal** [comment]
Everything Works as intended in the backend. I have left a review also in the frontend repo - https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2241#pullrequestreview-2079852849
Good Work!

**Review by Sandhya1236 — APPROVED** [review]
I have successfully tested the implementation of the new functionality to search projects by person. This update, related to backend PR #919, adds a new component SearchProjectByPerson.jsx to Projects.jsx. The component provides a form for user input and displays suggested users in a dropdown list. Once a user is selected, the search function is executed. Additionally, a new reducer function userProjectsByUserNameReducer.js was created to manage the state of userProjects and userError. Users can now be searched by first name, last name, or through alphabetic search. After checking into the current branch, running npm install, and starting the application locally, I cleared the site data and cache. Logging in as an admin or owner user, I navigated to dashboard → Other Links → Projects. The form for searching users appeared as expected, allowing me to select a user from the dropdown and view their related projects. The functionality worked correctly, displaying an error message if no projects were found for the selected user.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/4aa99d68-2f1e-4e53-89b2-aa0465f31010

**Review by mohabbasd — CHANGES_REQUESTED** [review]
Hello, I tested your PR and left a review on the frontend PR.

**Review by Kavil-Jain-514 — APPROVED** [review]
The functionality works. I have added the review in the front-end PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2312

**Pull request closed without merging**
