### PR TITLE
XiaoW - optimize the request for user tasks to one post request (backend)

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
When loading dashboard, app will send a get request for each user for its task and for admin there will be hundreds of requests. This PR integrates all the request into one post request.

## Related PRS (if any):
This backend PR is related to the [#905](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/905#issue-1751170104) frontend PR.
To test this backend PR you need to checkout the [#905](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/905#issue-1751170104) frontend PR.
…

## Main changes explained:
- change request method of `/TimeEntry/users` to post
- modify getTimeEntriesForUsersList for handling tasks for userIds
…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build`, and `npm start` to run this PR locally
3. check [#905](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/905#issue-1751170104) for more details

### CODE REVIEW

**Review by bienzguoa — APPROVED** [review]
Works as intended! Reviewed on frontend.

**Review by Chuehleo — APPROVED** [review]
Works as intended! Reviewed on frontend.

**Review by oreoluwadnd — DISMISSED** [review]
Screenshot from 2023-06-12 19-08-00
The request was optimized but was not successful

**Review by KurtisIvey — APPROVED** [review]
Functions as intended. Left review in front end PR

**Comment by wang9hu** [comment]
> Screenshot from 2023-06-12 19-08-00 The request was optimized but was not successful

Just to be sure, did you run `npm run build` before `npm start`?

**Review by eduhorta — APPROVED** [review]
Working as intended!
Left a review on the FE PR!
Great job! 👍

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @wang9hu. I have tested you PR and the optimization is working as intended. Great work! Left the comment in Frontend PR.

**Review by cvtqx — APPROVED** [review]
Changes work as intended. Well done! Left review in the related FE PR.

**Review by EdwinLauM — APPROVED** [review]
Works as intended! Left a more detailed review in the FE

**Review by AuroraLovesWhales — APPROVED** [review]
Reviewed this PR again and everything is working as intended. Great job!
image

**Comment by mahamakhan** [comment]
Works as intended. Left a review on the frontend too.

**Review by mahamakhan — APPROVED** [review]
Works as intended. Left a review on the frontend too.

**Pull request merged**
