### PR TITLE
show badges in weekly report

### PR DESCRIPTION
**Pull request by juneluo**
# Description
Jae: Make most difficult to earn badges show up by a person’s name on Reports Page
There are certain badges that are very hard to earn. When a person earns these, I’d like them to post to the right of the person’s other details on the Reports → Weekly Summaries Reports page. This is so that Management can see these badges were earned by that person and acknowledge them for it
- Make visible to anyone who has access to the page
- Make it remain on whatever weekly tab it is awarded on, just like a weekly summary stays on that tab and can be referenced up to two weeks past.
- Make it so multiple badges can be shown on this page if they happen to be earned in the same week
- Integrate this into the Other Links → Badge Management → Badge Development page. Add a column for “Reports Page Notification”. Checking a box here makes that badge one that shows up on the Weekly Summaries Reports page tab for that week when earned

## Related PRS (if any):
This backend PR is related to the [#1116 frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1116).

## Main changes explained:
- create an attribute 'showReport' to the badge schema
- include badge data in the summary

## How to test:
1. check into current branch
2. do `npm run build` and `npm start` to run this PR locally
3. run the frontend PR

### CODE REVIEW

**Review by veronicacheng2 — APPROVED** [review]
Hi @juneluo, I have tested the PR and everything works as intended. Comments left on #1116

**Review by TheDescendant39 — COMMENTED** [review]
Hi @juneluo, This PR looks good. Also reviewed [#1116](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1116#pullrequestreview-1575568203)

**Review by winghojackyli — APPROVED** [review]
This PR works great with the frontend part. Comment left on the review on #1116 front end PR.  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1116#pullrequestreview-1575586285

**Review by robertoooc — APPROVED** [review]
Hi @juneluo, I tested the branch and everything works as expected. Review left on #1116 frontend.

**Review by jerryren527 — APPROVED** [review]
Hello @juneluo!

Great job! Everything works as intended. I also reviewed FE PR #1116

**Review by yurisokolovicz — APPROVED** [review]
Dear @juneluo 

The backend logic seems fine to me. The comments regarding the front-end are in the respective PR1116 pull request's section.

**Comment by Lin1404** [comment]
The Backend code looks good. And I leave comment in the frontend PR.

**Review by Lin1404 — APPROVED** [review]

**Review by cvtqx — APPROVED** [review]
Works as described. Left comment in FE [PR#1116](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1116#pullrequestreview-1580939674)

**Review by yunshan111 — APPROVED** [review]
LGTM, I leave a comment with a testing record in frontend PR.

**Comment by one-community** [comment]
Thank you all, merging!

**Review by wantingxu7 — COMMENTED** [review]
LGTM! Detailed comment in Frontend PR

**Pull request merged**
