### PR TITLE
Edwin - Made changes to add permission seeAllReports

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-06-08 at 4 17 49 PM

## Related PRS (if any):
This backend PR is related to FE PR [899](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/899)

## Main changes explained:
Added "seeAllReports"  initial permission for Administrator and Owner accounts 

## How to test:
Please see refer FE PR [#899](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/899)

### CODE REVIEW

**Review by bienzguoa — APPROVED** [review]
Left reviews in frontend PR #899.

**Review by KurtisIvey — APPROVED** [review]
Functions as intended.  Great job!

volunteerWorkingAsIntenged

**Review by 20chen-7 — APPROVED** [review]
approved in 899. Good job!

**Comment by Lucas-E** [comment]
Thank you everyone, moving this to final review!

**Pull request merged**
