### PR TITLE
Edwin - Fixed category reverting after creating a new project 

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-08-16 at 11 29 36 PM

## Main changes explained:

- Made slight changes to the backend controller for posting a new project
- The property was incorrect those always resulted in undefined

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Login as Admin/Owner
4. Dashboard -> Click "Other Links" -> Click "Projects"
5. Create a new project and select any category
6. Refresh and make sure the category is correct for the newly added project 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/42288987/b38f0653-dc4a-45b9-84e7-10c9ef6d9d2c

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Hi @EdwinLauM , I've tested the PR and everything works as intended. 
Project with corresponding category is created successfully. 


https://github.com/OneCommunityGlobal/HGNRest/assets/108389005/0f67a85f-81d8-41f1-9547-0cee2aec64f1

**Review by navneeeth — APPROVED** [review]
LGTM! Tested the PR by logging in as an Admin user, navigating to Projects under Other Links, and creating a new project. Selected 'Housing' as the Category for a project 'NavneethTest2' and the new project's category remains the same when I refresh the page. Good implementation!


https://github.com/OneCommunityGlobal/HGNRest/assets/44264834/81338407-adbf-4573-be63-9cc742e9d578

**Review by jerryren527 — APPROVED** [review]
Hello @EdwinLauM !

Thanks for fixing this bug! Everything works as intended! The category of a newly created project remains unchanged after refreshing the page.


https://github.com/OneCommunityGlobal/HGNRest/assets/55968519/13421cc3-5b82-419a-a9ac-4a8c9df54887


Great job!

**Review by veronicacheng2 — APPROVED** [review]
Hi @EdwinLauM, I have tested the PR according to the video and everything works perfectly. After navigating to other pages and returning back to the project page. The category remains the same.

https://github.com/OneCommunityGlobal/HGNRest/assets/95119686/b0034e00-fd26-4cd9-b5c9-c2b41005075e

**Review by yaow62023 — APPROVED** [review]
The new feature work as intended. Good job!

https://github.com/OneCommunityGlobal/HGNRest/assets/137429365/03f4e13c-10f3-4360-8644-2b357e96ddb9

**Comment by mounica-dingari-by** [comment]
Hi @EdwinLauM , unfortunately I'm unable to see the category even after refreshing the page multiple times. I'm enclosing the screenshot below
Screenshot from 2023-08-19 19-17-01

**Review by yunshan111 — APPROVED** [review]
Tested this PR, LGTM.

**Review by DavidC0126 — COMMENTED** [review]
Hi @EdwinLauM I tested your PR and after refreshment of the page, the category was changed into unspecified and cannot be changed.

https://github.com/OneCommunityGlobal/HGNRest/assets/74082492/b3f77578-c169-4b5c-b3db-6ac16ab03b12

**Review by GaryB93 — CHANGES_REQUESTED** [review]
I noticed this issue is also being resolved in PR#490 and PR#1226.
However, in testing this PR with the up-to-date frontend development branch I was unable to access the Projects page. I can access the Projects page if I use the backend development branch. Probably has to do with this PR branch not having the most up-to-date development branch changes.

https://github.com/OneCommunityGlobal/HGNRest/assets/108501006/432cc63b-7920-4bdc-a36c-310d56f4ee41

**Comment by Shubhu0** [comment]
Tested this PR. Looks good

**Review by Shiwani99 — CHANGES_REQUESTED** [review]
Hi,
I tried testing your PR and I was not able to access the project page as it redirected to dashboard when I tried to access the project page. I'm attaching a screen recording of what is happening. I also tried directly going to the projects tab through URL but I was still redirected to dashboard even if I did that.


https://github.com/OneCommunityGlobal/HGNRest/assets/78906820/78061b44-463e-4708-8743-d73a4ea049b1

**Comment by astrjc0326** [comment]
I tested the PR. It works perfectly with the create project and shows the right category after I refresh the page. Great job!

https://github.com/OneCommunityGlobal/HGNRest/assets/98345990/ea055544-c2ca-42fa-8aad-b4087b8ee49c

**Review by vikrambadhan — CHANGES_REQUESTED** [review]
Hi, I tried testing your PR, but I was unable to access the project page since it kept redirecting me to the dashboard. I am attaching a screen recording showing the same.

https://github.com/OneCommunityGlobal/HGNRest/assets/85417946/da0c1c1d-1a15-4ba6-b421-8ec1d7e41ee0

**Pull request closed without merging**
