### PR TITLE
Logeshwari fix for user management "fetching error: invitation history"

### PR DESCRIPTION
**Pull request by Logeshwari-Renu**
# Description
Error

## Related PRS (if any):
This backend PR is related to the development frontend PR.

## Main changes explained:
- Made changes in the profileInitialSetupController.js in getSetupInvitation request to include the volunteer or any other user with "user Management" access to call the service.  

## How to test:
1. check into current branch
2. do `npm install`, `npm run build`, `npm run start` to run this PR locally
3. Clear site data/cache
4. Log as Volunteer user with "Create New User" or "See All Users" access.
	4a. If the volunteer is not having acess to User Management, then login as Admin/ Owner go to "Other Links" -> "Permission Management" -> "Manage User Permissions"
	4b. Search the user and enable permissions for "Create New User" or "See All Users"
5. Go to dashboard → Other Links → User Management
6. verify the error "Fetching error: Invitation History" is not displayed in the toaster message.
7. Verify for other user role with "User Management" access.

## Screenshots or videos of changes:

Before Changes
https://github.com/user-attachments/assets/18336660-d988-43df-8b9b-3a1d4ee1c19f

After Changes
https://github.com/user-attachments/assets/a36cb96f-d83c-409a-9d2c-1efbc571dd6d

### CODE REVIEW

**Comment by angelalalacheng** [comment]
Hi Logeshwari-Renu, I use your backend branch `Logeshwari_fix_for_user_management_fetching_error_invitation_history` and also use the latest frontend development branch. I changed the permission for volunteer but  "Fetching error: Invitation History" still displays in the toaster message.

Screenshot 2024-07-12 at 8 09 03 PM
Screenshot 2024-07-12 at 8 10 24 PM

**Review by nyelmela — APPROVED** [review]
I've thoroughly tested the current branch by running `npm install`, `npm run build`, and `npm run start` locally. After clearing the site data/cache, I logged in as a Volunteer user with "Create New User" or "See All Users" access. For volunteers without this access, I logged in as Admin/Owner, navigated to "Other Links" -> "Permission Management" -> "Manage User Permissions," and enabled the necessary permissions. I then verified the absence of the "Fetching error: Invitation History" toaster message in the User Management section. Additionally, I confirmed this fix for other user roles with "User Management" access. No errors were encountered during the testing process, and the functionality works as expected. 

image

image

**Review by sahithidhulipala9 — APPROVED** [review]
I have enabled the permissions to volunteer account, toast message didn't appeared. Great work!
Screenshot (115)
Screenshot (116)

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (131)
Screenshot (132)
Screenshot (133)
Screenshot (134)

**Review by manikittu810 — APPROVED** [review]
Hello @Logeshwari-Renu 
Followed the mentioned steps and No error poppedUp. Good work!

https://github.com/user-attachments/assets/0ce7a6a1-fc1e-4729-aec7-9d8984120567

Thank you.

**Review by adityasure9 — APPROVED** [review]
I tested the PR thoroughly by following the steps provided. The "Fetching error: Invitation History" message no longer appears when using the User Management section after the necessary permissions are granted to volunteer users.

**Comment by SMitta11** [comment]
I have tested the PR and everything works as expected. I have created a new user and added access "Create New User"/"See All Users"  for this new user and  after login using this new user credentials error "fetching error: invitation history" is not appearing in user management.


Screen Shot 2024-08-15 at 1 48 37 AM
PR 1026

https://github.com/user-attachments/assets/4e4b097b-49a8-42b9-8379-73fa2e0bb4b5

**Review by SMitta11 — APPROVED** [review]
I have tested the PR and everything works as expected. I have created a new user and added access "Create New User"/"See All Users" for this new user and after login using this new user credentials error "fetching error: invitation history" is not appearing in user management.

Screen Shot 2024-08-15 at 1 48 37 AM

https://github.com/user-attachments/assets/74e0f05a-b52c-45f8-83cf-144a05af863b

PR 1026

**Review by AnkitLall — APPROVED** [review]
I have tested the feature, following the instructions in the PR, and it works as expected. Please refer the screenshots attached below.

Screen Shot 2024-08-18 at 12 58 04 AM
Screen Shot 2024-08-18 at 12 58 16 AM

**Review by oliviahyw — APPROVED** [review]
I have tested this PR and everything works as expected. I created a new user and granted them the "Create New User" and "See All Users" permissions. After logging in with this new user's credentials, the "fetching error: invitation history" error no longer appears in the user management section.
PR1026-1
PR1026-2

**Review by yashwanth170 — APPROVED** [review]
Everything is working as expected. Attaching Screenshots for reference
user_no_msg
user_permissions

**Review by vedantg24 — APPROVED** [review]
Tested the PR, and the changes are working as expected. I gave an existing volunteer account the permissions required through an admin account, and after logging in back as the volunteer, didn’t get the error popup.

Screenshot 2024-08-31 at 12 00 54 PM
Screenshot 2024-08-31 at 12 04 56 PM

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected. I have tested using both volunteer and admin accounts.

Volunteer Account: 
PR 1026

Admin Account:
PR 1026-1

Thank You

**Review by vishnupriyaatheti — APPROVED** [review]
@Logeshwari-Renu I have verified your changes and working as expected. 
BE PR 1026

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
