### PR TITLE
Abi badge controller post method tests

### PR DESCRIPTION
**Pull request by Abi-Liu**
# Description
Unit and integration tests for the post badge controller and route.

## Related PRS (if any):
N/A

## Main changes explained:
- Unit test for the postBadge function in the badgeController
- Integration tests for the post Badge route

## How to test:
1. check into current branch
2. do `npm install` 
3. run `npm run test badge`
4. verify all tests pass

## Screenshots or videos of changes:
Screenshot 2024-04-01 at 3 27 06 PM

### CODE REVIEW

**Comment by DiegoSalas27** [comment]
Hey Abi,

Awesome job with the unit tests. You just missed to test the cache dependency: we need to tests that the cache method gets called with 'allBadges' key, and iif it exists, that the cache.removeCache method is called, and that is called with the 'allBadges' key.

Integration tests on the hand are easy to follow, concise and test thouroughly integration of components. I really like the way you worked to assign permissions to different user roles. Very nice job overall!

Please address the cache depenency in your unit tests, and I will approve this PR.

**Review by DiegoSalas27 — CHANGES_REQUESTED** [review]
Hey Abi,

Awesome job with the unit tests. You just missed to test the cache dependency: we need to tests that the cache method gets called with 'allBadges' key, and iif it exists, that the cache.removeCache method is called, and that is called with the 'allBadges' key.

Integration tests on the hand are easy to follow, concise and test thouroughly integration of components. I really like the way you worked to assign permissions to different user roles. Very nice job overall!

Please address the cache depenency in your unit tests, and I will approve this PR.

**Review by linkhanthtel — APPROVED** [review]
Hi Abi! 

Looks good! I reviewed your PR and all tests passed!

**Review by bhuvaneswarignanasekar — APPROVED** [review]
Hi Abi,

I reviewed the PR. All test passed. 
Screenshot 2024-04-02 at 4 05 39 PM

**Review by DiegoSalas27 — APPROVED** [review]
Hey Abi,

This is perfect. cache closure gets mocked correctly and it's methods are also mocked to account for the arguments they have been called with.

**Pull request merged**
