### PR TITLE
Peterson_fix_the_bug_after_writing_find_user_in_the_input_and_receivi…

### PR DESCRIPTION
**Pull request by peterson337**
# Description
In the project member addition page,  there is an input for searching users to be added to the project. However, upon typing in the input, a 500 error is returned in the browser's console or network. This pull request has been opened to fix the bug.

## Related PRS (if any):
none
…

## Main changes explained:
The archive userProfileController.js has been modified to fix the bug.

…

## How to test:
1. check into current branch
2. do `npm install`, `npm run build` and `npm run start` to run this PR locally
3. Clear site data/cache
4. Log in as an administrator or owner
5. go to other links→ projects → click the button inside the column "members".
6.  You need to open the browser console or network to test.
7. After writing 'find user' in the input, a table displaying users should appear, and no error 500 should be returned in the browser console or network.

## Screenshots or videos of changes:
Before my fix:
Before my fix

After my fix:
After my fix

## Note:
If the user name is misspelled, a 400 error will be returned in the browser console or network. Additionally, if something is written in the input and then deleted, a 404 error will be returned in the browser console or network. This behavior is normal and unrelated to the bug.
v

### CODE REVIEW

**Review by Ramaruva — APPROVED** [review]
HI I verified your changes in and it is working as expected 
image

**Review by Parth-tech — COMMENTED** [review]
Hi Peterson,
The PR does work as intended but I wanted highlight that when I pull the latest development branch and tested the `Filter Name Search Bar`, I did not see 500 error. I did encounter 400 & 404 which were expected as well as out of the scope of this PR. 

When I switched to your branch everything worked correctly. But I was puzzled as I couldn't emulate the 500 error on dev branch. 

`Dev Branch`

https://github.com/OneCommunityGlobal/HGNRest/assets/56110372/6dc0ddb6-8c97-40d4-991a-0eb83c3fe561


`#08ed22b branch (i.e your branch)`

https://github.com/OneCommunityGlobal/HGNRest/assets/56110372/b20a3dd1-57ae-46a9-8206-ac11eddbf301

**Review by linkhanthtel — APPROVED** [review]
I reviewed your PR and it is working as expected! I see no error 500 in the browser console. Nice work!

**Review by Wenboooooo — APPROVED** [review]
image
There no errors on the page and it works as expected.

**Review by jayyy-s — APPROVED** [review]
Looks good to me. I reviewed your fix and it does make sense, but I will echo @Parth-tech 's point. I was also not able to replicate the 500 error on the dev branch, but there was no new error after your changes.
works

**Comment by cecilia-uu** [comment]
It works well when typing the correct username, and it returns 400 when typing the user who does not exist. But I reviewed the section 'files changed', there are only some changes including inverting double quotation marks into single ones and deleting some line breaks. In order to be consistent in quotes, I suppose that the 'wbsController.js', 'rolesController.js', 'rolePresetsController.js', etc. should also apply these changes in the future.
截屏2024-05-20 上午10 35 39

**Review by cecilia-uu — APPROVED** [review]
I have already left my comments in the conversation area.

**Review by Infinite-Turkey — APPROVED** [review]
屏幕截图 2024-05-22 170920
The PR does work well, and no error occurs. I tried to input signs like ! and (, 404 error appeared. But as you said, this behavior is normal and unrelated to the bug, so that is totally fine.

**Review by Sandhya1236 — APPROVED** [review]
Everything works as expected. Job Well done.


https://github.com/OneCommunityGlobal/HGNRest/assets/79351059/93647a38-2351-4470-bfac-a451328a98b2

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Comment by KurtisIvey** [comment]
Hey Peterson, I just wanted to see if you could clear up the merge conflict when you have a chance please. We'd love to get this merged in asap as it looks like you've done good clean work here just from looking at the code files.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
