### PR TITLE
Anirudh loginmethod unittest

### PR DESCRIPTION
**Pull request by Pandani07**
# Description
Created unit tests for the login controller

## How to test:
1. check into the current branch
2. do `npm install` 
3. do `npm run test logincontroller`
All  8 tests should pass. If you run `npx jest logincontroller`, you may get a console error saying try block failed. That is a test case.

Screenshot 2024-04-26 at 10 31 26 PM

### CODE REVIEW

**Review by j-corp-25 — APPROVED** [review]
Hey @Pandani07 ,

All tests are working as expected on my end 

TestingLoginControllerUnitTest

**Review by Ramaruva — APPROVED** [review]
Hi I have verified changes in my local env and all test cases are passed

image

**Review by MinSun0814 — APPROVED** [review]
image
Same error as described above. All tests passed.

**Comment by belagaam** [comment]
I tested the unit test and all test cases are passing. Good work.

Anirudh loginmethod unittest

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi @Pandani07, 
1. I ran `npm run test`, there were 25 test cases and 16 passed.
image

2. I ran `npx jest logincontroller`, I got the try block failed, the expected output and 8 test cases passed
image

If this is your desired output, could you please update that in the description of the PR?
Also add a few words about #1.

**Comment by Pandani07** [comment]
> Hi @Pandani07,
> 
> 1. I ran `npm run test`, there were 25 test cases and 16 passed.
>    image
> 2. I ran `npx jest logincontroller`, I got the try block failed, the expected output and 8 test cases passed
>    image
> 
> If this is your desired output, could you please update that in the description of the PR? Also add a few words about #1.

Run only the logincontroller test cases as that is what this PR is for.

**Comment by Pandani07** [comment]
run this `npx jest logincontroller`. You are running all the test suites in the backend, some of which are unfinished. I mentioned the command to run my tests in the description.

**Review by peter6866 — APPROVED** [review]
All tests passed!
image
image

**Review by Sandhya1236 — APPROVED** [review]
Upon reviewing the PR, I checked into the current branch, installed the necessary dependencies using npm install, and executed the tests with npm run test logincontroller. All 8 tests passed successfully. Running npx jest logincontroller may show a console error saying "try block failed," which is an expected test case and also passed. This confirms that the logincontroller functionality and its associated test cases are working as intended.

image

image

**Review by deepthikannan — CHANGES_REQUESTED** [review]
image
When I tried npm run test logincontroller, the test cases failed.

image
When I tried npx jest logincontroller, it still failed.

Kindly do check the code once again

**Comment by akshit0211** [comment]
All test cases passed. Great job!

All test cases passed

**Review by akshit0211 — APPROVED** [review]

**Comment by DiegoSalas27** [comment]
Guys, please run the tests only for the controller and follow this PR instructions on how to run it. The fact that other tests are failing should not be a concern, since what gets committed is only the `file changes` code. If the `file changes` code works, then that's all we care about.

**Review by DiegoSalas27 — APPROVED** [review]
Nice job. All tests are passing and this is ready for merge.

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
