### PR TITLE
Logeshwari---Fix for Team Management Page struck on Team Edit

### PR DESCRIPTION
**Pull request by Logeshwari-Renu**
# Description
Page struck Task

## Related PRS (if any):
This backend PR is related to the Frontend [#PR2627](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2627#issue-2492611418).

## Main changes explained:
- Removed the redundant user role for verifying the permission in the PuTeam API while editing the team codes. 

## How to test:
1. check into current branch
2. do `npm install`, `npm run build`, `npm run dev` to run this PR locally
3. Follow the instructions on the Frontend [#PR2627](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2627#issue-2492611418) to test.

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
Reviewed this PR on the frontend.

**Review by RishithaMamidala — DISMISSED** [review]
Requested the changes on the frontend PR

**Review by AJAYINAVOLU — APPROVED** [review]
Reviewed the PR on the frontend repo.

Thank You

**Review by Jingyii800 — APPROVED** [review]
Left the comment for the frontend branch.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2627#pullrequestreview-2270656392

**Review by SnelPatare — APPROVED** [review]
Left comment on frontend branch. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2627#pullrequestreview-2270656603

**Comment by sri0606** [comment]
[Left a comment on the frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2627#issuecomment-2322636405). Please check it out.

**Review by SMitta11 — APPROVED** [review]
Tested frontend PR. 
[Frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2627#pullrequestreview-2273767328)

**Review by CillianRen — APPROVED** [review]
Reviewed the PR on the frontend.

**Review by sam19981 — CHANGES_REQUESTED** [review]
Left Comments on [FronentEnd PR-2627](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2627#pullrequestreview-2288365575).

**Comment by one-community** [comment]
Thank you all, merging!  Listed requested change as a new bug

**Pull request merged**
