### PR TITLE
add change bio announcement to permission management

### PR DESCRIPTION
**Pull request by juneluo**
# Description
While many roles have the permission to view the weekly summaries report page, we expect only admin/owner can change/edit the bio announcement status with a toggle switch, and other roles just see the label. But outside of Owner/Admin, there will be people who will be granted editing ability. The users or classes can be granted special editing ability via the Other Links --> Permissions Management option.

## Related PRS (if any):
To test this backend PR you need to checkout the [frontend PR879](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/879).

## Main changes explained:
- add changeBioAnnouncement to the initial permissions of the Owner/Admin

## How to test:
1. check into current branch
2. `npm run build` and `npm start`
3. test using the frontend PR

### CODE REVIEW

**Review by EdwinLauM — APPROVED** [review]
Works as intended! Good job! Left a more detailed comment in the frontend PR

**Review by EdwinLauM — APPROVED** [review]
Works as intended! Good job! Left a more detailed comment in the frontend PR

**Review by KurtisIvey — APPROVED** [review]
full review on front end of PR #879 . functions as intended. 😁

**Review by eduhorta — APPROVED** [review]
Works as intended! Nice job! 👍
Left review on frontend PR879

**Review by bienzguoa — APPROVED** [review]
Works as intended! Full review on front end of PR #879.

**Comment by one-community** [comment]
Good job, thank you everyone

**Pull request merged**
