### PR TITLE
chris_equipment_details_backend_linked

### PR DESCRIPTION
**Pull request by chrischenlixing**
# Description
image

## Related PRS (if any):
This frontend PR is related to the [#2114](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2114) backend PR.
…

## Main changes explained:
- Added bmEquipment router and the router to routes
- Added bmEquipment Controller
- Added buildingequipment in models

## How to test:
- check into current branch
- do npm install, npm run build and npm run start to run this PR locally.
- Please adhere to the instructions outlined in the frontend PR.

### CODE REVIEW

**Review by ImzIssa — APPROVED** [review]
Hello, I've tested your PR and everything looks good.

I've also left a Frontend PR Review https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2114#pullrequestreview-1983283664

**Review by aaryaneil — APPROVED** [review]
Tested your PR and the changes look good.
Left a review on the [Frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2114#pullrequestreview-1983814498)

**Review by lacnoskillz — APPROVED** [review]
see front end review

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2114#pullrequestreview-1984777718

**Review by ShengjieMao — APPROVED** [review]
The page looks good as expected. got no error when testing. Also left a [review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2114#pullrequestreview-1991175536) in FE pr

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
