### PR TITLE
format for (userHelper.js) and xhourxweeks streak bug fixes

### PR DESCRIPTION
**Pull request by aashish-thapa-magar**
This is a bugfix for auto-assignment of XhoursForXWeeks streak. The new changes in the code enables the following:

If it is a streak of the same number (i.e. 3-week 40 hour streak being replaced by a 4-week 40-hour streak), then the previous one should drop off because the badge would be a continuation of the previous badge.

If, however, the badge is a NEW streak (i.e. 50-hour streak started, but they already had a 40-hour streak), then they should still keep the 40-hour streak because that was a different accomplishment.

And nobody should ever earn two different streaks the same week... meaning earning a 50-hour streak should not also earn you a 40-hour streak, you should only always earn the highest number.

Note:- It will not increase the badge count of a similar streak.

It does not block an admin from manually assigning any number of such badges, and thus may also enable duplicate creation of badges. However, it will remove the duplicate and wrong streak badges that were manually assigned every new week on Sunday.

How to test? steps:

1. Since, this deals with auto assignment of badges, you will have to go to src/cronjobs/userProfileJobs.js and alter the date to now, for the code to run.
2. The badges are assigned based on the last saved tangible hours array of a user. Please refer to userProfile model savedTangibleHours object.

https://www.dropbox.com/home/Highest%20Good%20Network%20Team/Aashish

There's a video on how to test, and also a screenshot of an alternative to bypass cronjob.

### CODE REVIEW

**Comment by rauleffting** [comment]
Hi @aashish-thapa-magar, please, put more information. We have to maintain it organized. There are new team members going to review it. Thank you!

**Comment by one-community** [comment]
How is someone supposed to know what to do with this? Clear instructions are needed for what this does and how to test it Ashish. Please add those and be sure to include them in ALL PRs you raise. If you need to review what's needed in all PRs, please read this: https://docs.google.com/document/d/1d-ZzDnb_OOXXUN49V-wExHpAgOFMYpe2se1SaziA7Xw/edit#bookmark=id.1qihiwkbdteo

**Comment by aashish-thapa-magar** [comment]
This is a bugfix for auto-assignment of XhoursForXWeeks streak. The new changes in the code enables the following:

If it is a streak of the same number (i.e. 3-week 40 hour streak being replaced by a 4-week 40-hour streak), then the previous one should drop off because the badge would be a continuation of the previous badge.

If, however, the badge is a NEW streak (i.e. 50-hour streak started, but they already had a 40-hour streak), then they should still keep the 40-hour streak because that was a different accomplishment.

And nobody should ever earn two different streaks the same week... meaning earning a 50-hour streak should not also earn you a 40-hour streak, you should only always earn the highest number.

Note:- It will not increase the badge count of a similar streak.

It does not block an admin from manually assigning any number of such badges, and thus may also enable duplicate creation of badges. However, it will remove the duplicate and wrong streak badges that were manually assigned every new week on Sunday.

**Comment by aashish-thapa-magar** [comment]
How to test? steps:

1. Since, this deals with auto assignment of badges, you will have to go to src/cronjobs/userProfileJobs.js and alter the date to now, for the code to run.
2. The badges are assigned based on the last saved tangible hours array of a user. Please refer to userProfile model savedTangibleHours object.

**Comment by aashish-thapa-magar** [comment]
https://www.dropbox.com/home/Highest%20Good%20Network%20Team/Aashish

There's a video on how to test, and also a screenshot of an alternative to bypass cronjob.

**Comment by PrabhjotSembhi** [comment]
I have read all the instructions d watched the video and tried to review it. But not able to figure out what exactly needs to be reviewed.

**Comment by Filipe-Oliv** [comment]
Hi @aashish-thapa-magar 

Same difficulty

Following up on this

**Comment by PrabhjotSembhi** [comment]
@aashish-thapa-magar, I am waiting for your response. 
Please add clear instructions
What is the issue? What is fixed? 
Before /After screenshots if possible.
Your video is very confusing, a lot of context is missing.
Thanks 
waiting for your response

**Comment by one-community** [comment]
Hi All, 

Thank you for your reviews on this and diligence in trying to get quality input from Aashish. After multiple warnings to him about needing timely responses, better quality PRs, and visible progress, I've made the decision to remove Aashish from the team and close this PR because it does not appear to have any usable progress. 

Thank you again.

**Pull request closed without merging**
