### PR TITLE
Diego finished adding tests to postUserProfile

### PR DESCRIPTION
**Pull request by DiegoSalas27**
# Description
Adds missing unit tests to postUserProfile method in userProfileController

## Related PRS:
N/A

## Main changes explained:
- Refactors postUserProfile method and adds unit tests for positive and negative cases

## How to test:
1. check into current branch
2. do `npm install`
3. if working on MacOS or Linux run: `npm run prepare`
4. run: `npm run test /src/controllers/userProfileController.spec.js`
5. all tests should pass

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HGNRest/assets/26840798/48c44a68-7025-403f-8f8f-2f59019e1f82

## Note:
This unit tests covers positive and negative cases for postUserProfile method userProfileController

### CODE REVIEW

**Review by navyasrim — APPROVED** [review]
Hi,
Tested your code changes for positive and negative cases and working as expected. 
PR-813
PR-813-Negativescenario
Attached is the images.

**Review by luisarevalo21 — APPROVED** [review]
Hello @DiegoSalas27 
I tested your PR and all tests have passed great work!
I was unsure how to test the fail cases can you elaborate on how to test that?
Thanks
Screenshot 2024-03-25 at 7 50 59 PM


The negative (failing) cases are tested as 400, 401, 403, 500, or 501 errors. Any status code found in a test within that range is a failing case.

**Review by linkhanthtel — APPROVED** [review]
I reviewed this PR and all tests have passed!

**Review by 20chen-7 — APPROVED** [review]
Excellent work and good unit test
Screenshot 2024-03-26 at 4 37 04 PM

**Review by hetvi11110 — APPROVED** [review]
I have reviewed this PR, as mentioned, and it passed all tests. Here is the reference image.
image

**Review by Pandani07 — APPROVED** [review]
test cases passed!
Screenshot 2024-03-26 at 5 21 28 PM

**Review by SRamen1999 — APPROVED** [review]
All the test cases passed. 
Screen Shot 2024-03-27 at 12 16 19 PM

**Review by Abi-Liu — APPROVED** [review]
Looks great! Tested the integration and unit tests and all cases are passing.

Screenshot 2024-03-27 at 11 47 17 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
