### PR TITLE
Replace all variables comitted to committed.

### PR DESCRIPTION
**Pull request by LeeSingChanYau**
This misspelling occurs over 200 times on the frontend, and 40 on the backend.  Most of which are in “weeklyCommitedHours”.  All occurrences should be fixed to proper spelling and the app tested for resulting errors, section by section as each spelling correction is made.

How to test:
-Check if the correct weeklyCommittedHours value is displaying in the summaryBar.

More testing should be done, and ask teammates to help me debug any errors that may occur in this PR. Thanks.

### CODE REVIEW

**Comment by tingedudu8** [comment]
Hi @LeeSingChanYau, I used global search and found out that there is still one mispell left in BE files.
PR276

Also, what do you mean when you refer to "summaryBar"? If you mean "Weekly Committed Hours", this input box seems different from the development branch, you might forgot to update to the newest version. Thanks!!
Screen Shot 2023-02-02 at 6 58 32 PM

**Comment by tingedudu8** [comment]
Hi @LeeSingChanYau, there are no "commit" to "comit" errors in BE, but do have three "committed" to "commited" mispellings. You can see from the pic below. Thanks!
PR267

**Review by PrabhjotSembhi — COMMENTED** [review]
Hey @LeeSingChanYau 
I have checked and Found these

1. "commited"  with 1 "t" is in 14 files and used 48 times
PR 671 1

2. "comitted"  with 1 "m" is in 27 files and used 188 times
PR 671 2

 3. "weeklyCommitedHours"  with 1 "t" is in 2 files and used 4 times
PR 671 3

 4. "weeklyComittedHours"  with 1 "m" is in 24 files and used 178 times
PR 671 4

**Comment by LeeSingChanYau** [comment]
@PrabhjotSembhi sorry about, please review again.

**Comment by LeeSingChanYau** [comment]
@PrabhjotSembhi sorry about that, please review again.

**Comment by Filipe-Oliv** [comment]
Hi @LeeSingChanYau 

Commited 47 results


Comitted 240 results


weeklyCommitedHours 3 results


weeklyComittedHours 230 results

**Comment by Lunaliar** [comment]
Hello! 

I connected with @Filipe-Oliv, still not exactly sure why we're getting different results but I haven't been able to find any typos of "weeklyCommittedHours". I searched for "weeklyComittedHours", "weeklyCommitedHours" and "weeklyComitedHours"
Here are some screenshots I took for the results: 
Screenshot from 2023-02-13 11-23-21
Screenshot from 2023-02-13 11-23-12
Screenshot from 2023-02-13 11-23-04
Screenshot from 2023-02-13 11-22-54

**Comment by angelinatr15** [comment]
Hello @LeeSingChanYau,

I pulled this branch and ran the build. I used the search filter in VSCode and found that there are no misspellings. Below are the following results for the different spellings in the back-end. 

“committed” 115 results 
"comitted" 0 results
"commited" 0 results
"commited" 0 results

committed
commited
comitted
comited

**Comment by Filipe-Oliv** [comment]
Hi @LeeSingChanYau, you or some knows why this is still being showed to me?

When @Lunaliar showed me his result, I thought it might be a branch update problem, or something like that. But now @angelinatr15 found the same result.

Please, take a look in this image.

**Comment by Filipe-Oliv** [comment]
Hi @LeeSingChanYau. Here's what I found right now. It only shows up when I put "weeklyCommittedHours". For the other misspellings, the result was zero.

**Review by angelinatr15 — APPROVED** [review]

**Review by PrabhjotSembhi — APPROVED** [review]
this one is fine. 
Before merging Make sure frontend PR 671 related to this is also approved too.

**Comment by PrabhjotSembhi** [comment]
@one-community this one is approved. Please make sure the Frontend PR related to this is also Approved before merging

**Comment by one-community** [comment]
Thank you. Moved to PR Review Management Team for final review before merging.

**Review by rauleffting — APPROVED** [review]
Working perfectly! Didn't find any other misspellings. Thank you!

**Pull request merged**
