### PR TITLE
Jiadong - Replace Badges Section on Dashboard / badge count APIs

### PR DESCRIPTION
**Pull request by yunshan111**
# Description
image
image

## Related PRS (if any):
This backend PR is related to the #https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2529
…

## Main changes explained:
replace badge section on the dash board to Timlog component
add number indicator
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
4. log as admin user
5. go to dashboard -> Other Links -> Badge Management -> assign a new badge to another user.
6. log out
7. Log in as the user who was recently assigned the badge.
8. Check the number indicator on the dashboard.
9. Click on the "Badge" tab to view the assigned badge.
10. Check if the number indicator reset to 0.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/476243f0-9309-4d25-8df2-4062e0e72453

### CODE REVIEW

**Review by Pranay-ai — APPROVED** [review]
Hey @yunshan111 
I have Tested the PR it's working as expected
image

image
Thank You.

**Review by jinxyou — APPROVED** [review]
I left a review at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2529#pullrequestreview-2217379451

**Review by aaryaneil — CHANGES_REQUESTED** [review]
Tested the PR but when assigning a badge to a user I am getting a 500 error.
But the UI changes look as described.
Screenshot 2024-08-04 at 12 21 33 PM
Screenshot 2024-08-04 at 12 22 30 PM

**Review by vishavk1992 — COMMENTED** [review]
I have tested this PR with front end PR 2529 And also let comment on front end PR .

**Review by Parth-tech — APPROVED** [review]
Hey Jiadong,
The PR works as intended and the codebase looks good too. Great job!
[Front End review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2529#pullrequestreview-2222458867)

**Review by Aishwarya0898 — APPROVED** [review]
Hello Jiadong,
The PR works as mentioned and the codebase looks good too. Review reference on the frontend PR.

Thank you

**Review by DiyaWadhwani — APPROVED** [review]
Hi,
All changes work fine. Left a detailed review on your frontend PR
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2529#pullrequestreview-2226324805
Thank you

**Pull request merged**
