### PR TITLE
Roberto -adds opencage http request to backend timezone route

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
Changing the OpenCage http request to happen on backend rather than client. Keeping the get request on the client allows for security risks since anyone can view the network tab and see the api key. By transitioning the request to happen on backend the api key can stay secure and concealed while just returning needed information to client.

## Related PRS (if any):
To test this backend PR you need to checkout the #[1640](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1640) frontend PR.

## Main changes explained:
- Updated TimeZoneAPIController to handle the opencage http request and return needed information to client
- Added Axios as a dependency to perform third party http request

## How to test:
1. check into current branch
2. sign up for an api key at `https://opencagedata.com` - it's free
3. add `TIMEZONE_PREMIUM_KEY=your api key` and 
`TIMEZONE_COMMON_KEY= your api key` to your environmental variables
4. do `npm install` and `npm run build && npm start` to run this PR locally
5. follow FE instructions

## Note:
Make sure to `npm install ` - a new dependency is added
Make sure to compile code after adding to your .env

### CODE REVIEW

**Review by this-journey — APPROVED** [review]
Reviewed PR please see my notes on the FE.

**Comment by DragonSlayer2401** [comment]
I tested this PR with the related frontend PR please go there to see the full review.

**Review by Alforoan — APPROVED** [review]
I left my comment on fe pr #1640.

**Review by pshereen — DISMISSED** [review]
Tested the PR. Updated the API key.

In View Profile page, updating location to Vatican, Zagreb, Podgorica in Basic Info is causing the page to crash. See the video for details.

Uploading HGN APP and 11 more pages - Personal - Microsoft​ Edge 2024-01-25 21-51-03.mp4…

**Review by pshereen — APPROVED** [review]
Reviewed PR please see my comments on the FE.

**Review by Sophie-lei — COMMENTED** [review]
Hey, I have tested this PR and met the problem of connecting API. I have left the commend in PR #1640. Please view the details.

**Comment by galgalinidhi** [comment]
See my comment on https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1640

**Review by Pandani07 — APPROVED** [review]
Created a new API key and followed the testing steps, works as intended. 

https://github.com/OneCommunityGlobal/HGNRest/assets/44672833/69a196a8-3ed6-416e-b301-e1fb057d7d0c

**Comment by xmyoot** [comment]
Created a new API key on Open Cage and followed the testing steps, works as intended. The timezone can be updated by typing in the location. Works well!

Setup an API key and checkout the branch, waiting on the owner account so I tested with admin account and I was able to update timezone, please reference pictures:
Before:
PR#1640:639
After running TimeZoneAPIController:
PR#1640:639(after)

**Review by SaiDeepak-NEU — APPROVED** [review]
Hello roberto,

I added the api key to the environment variables in my backend code and ran the application and tested all the changes given in the frontend PR1640.
Everything worked smoothly and as requested. 
Please refer to the frontend for more comments and screenshots of testing.

**Review by mohabbasd — APPROVED** [review]
Hello, I tested this PR and it is working very nicely.

**Review by XiaohanMeng — APPROVED** [review]
This PR works well. Please see my comment and video on FE.

**Review by Coops023 — APPROVED** [review]
I reviewed this PR as-well as the front-end PR and all works well, good job!

**Review by lacnoskillz — COMMENTED** [review]
see front end PR

**Review by navneeeth — APPROVED** [review]
Reviewed the changes in the BE + FE and have provided a detailed review on the FE. Approving. Thank you!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
