### PR TITLE
Jinchao fixed project/task field of timeEntry component

### PR DESCRIPTION
**Pull request by suigunfjc**
# Description
BE update for [#906](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/906)
Please refer FE for more details.
## Main changes explained:
This pull request (PR) introduces a modification to the getTimeEntriesForSpecifiedPeriod function. The previous logic for finding data has been replaced with an aggregate logic, resulting in reduced communication frequency between HGNRest and Mongodb. This change also enhances the result by providing additional information. As a result, the frontend no longer requires additional axios requests to retrieve task and project information from the backend.

### CODE REVIEW

**Review by stevenpaalz — APPROVED** [review]
Confirming that frontend and backend aspects work as intended.
Screenshot 2023-06-12 at 4 01 39 PM

**Review by cvtqx — APPROVED** [review]
The fix in this component works as intended. Left my comments in related FE PR#906.

**Review by KurtisIvey — APPROVED** [review]
works as intended. Left review in pr906. Great job

**Review by bienzguoa — APPROVED** [review]
Frontend works as intended!

**Review by NidaZaki — APPROVED** [review]
Changes look good! I've tested and it works! Good job!

**Comment by Lucas-E** [comment]
Good work with the aggregation code, it works as intended!

**Review by Lucas-E — APPROVED** [review]

**Pull request merged**
