### PR TITLE
Jiayu fix streak badge not auto dropoff

### PR DESCRIPTION
**Pull request by peter6866**
# Description
image
This PR is fixing the auto-dropoff issue that PR #901  does not solve.

## Related PRS (if any):
This PR is not based on frontend. 
This PR is based on PR #665

## Main changes explained:
image

- Above are the changes made by PR #665
- Fixed a bug introduced by [this commit](https://github.com/OneCommunityGlobal/HGNRest/commit/fa2e3ff654613ca067e301f4a401d38ccef97934).
- in `userHelper.js`, changed the query to remove a badge from the `badgeCollection` by using the `badge` of the badge entry instead of the `_id` field.
- modified the badge assigning order so that if higher order badge is assigned, the 1 week badge will not be assigned.

### Setup

1. Check out the current branch
2. Modify `controllers/badgeController.js`:
   - Uncomment lines 16-19 and line 275 to add the `awardBadgesTest` controller
3. Modify `routes/badgeRouter.js`:
   - Uncomment line 8 to register the API
4. Modify `helpers/userHelper.js`:
   - Comment out lines 1911-1916 and line 1918, leaving only `checkXHrsForXWeeks`
   - Change line 1905 to:
     ```javascript
     const users = await userProfile.find({ email: "<YOUR_EMAIL>" }).populate('badgeCollection.badge');
     ```
     Replace `<YOUR_EMAIL>` with your testing account email

### Running the PR Locally

5. Install dependencies and start the server:
   ```bash
   npm install
   npm run build && npm run start
   ```

### Database Setup

6. Open the database using Compass or Studio 3T
7. Find your account in `userProfiles` using the query: `{email: "<YOUR_EMAIL>"}`
8. Ensure `badgeCollection` is empty (delete any existing badges)

### Testing 30-Hours Streak 3 Weeks in a Row with only one **30 Hours in 1 Week** badge(90hrs)

9. Under `savedTangibleHrs`, empty the array and add one element: `[30]`. Also change `lastWeekTangibleHrs` to 30.
10. In Postman:
    - Log in to your account and copy the token
    - Create a new GET request to `http://localhost:4500/api/badge/awardBadgesTest`
    - Add the Authorization header with your token
11. Send the request
12. Refresh the database and verify:
    - `badgeCollection` has only one badge
    - The badge name is "30 Hours in 1 Week"
      (Find the badge in the `badges` collection using the query: `{_id: ObjectId('<YOUR_COPIED_BADGE_ID>')}`)
13. Update `savedTangibleHrs` to `[30, 30]`
14. Repeat steps 10-12 and verify:
    - `badgeCollection` has only one badge
    - The badge name is "30 HOURS 2-WEEK STREAK"
15. Update `savedTangibleHrs` to `[30, 30, 30]`
16. Repeat steps 10-12 and verify:
    - `badgeCollection` has only one badge
    - The badge name is "30 HOURS 3-WEEK STREAK"

### Additional Testing

17. Perform other tests following the same pattern
    - lastWeekTangibleHrs: 90, savedTangibleHrs: [90]
    - lastWeekTangibleHrs: 60, savedTangibleHrs: [90, 60]
    - lastWeekTangibleHrs: 50, savedTangibleHrs: [90, 60, 50]
    - Please use postman to send the request each time after modifying the database entires.
    - Finally you will have three Badges: 
        - 90 HOURS IN 1 WEEK
        - 60 HOURS IN 2 WEEK
        - 50 HOURS IN 3 WEEK

## Note:
If you still have problems on testing this, please refer to [this video](https://www.youtube.com/watch?v=GYR6GSAVC_k) by Jerry for #665

### CODE REVIEW

**Review by angelalalacheng — COMMENTED** [review]
I switch the backend branch to `jiayu_streak_fix_auto_dropoff` and follow the instructions. The first part works as expected.

**Before**
Screenshot 2024-07-11 at 5 36 57 PM
Screenshot 2024-07-11 at 5 40 23 PM
Screenshot 2024-07-11 at 5 54 11 PM
Screenshot 2024-07-11 at 5 59 36 PM
**After**
Screenshot 2024-07-11 at 6 00 05 PM
Screenshot 2024-07-11 at 6 04 37 PM
Screenshot 2024-07-11 at 6 08 39 PM
**Frontend**
Screenshot 2024-07-11 at 6 09 27 PM

**Review by angelalalacheng — APPROVED** [review]
This is additional test.

Screenshot 2024-07-11 at 7 51 44 PM
Screenshot 2024-07-11 at 7 54 44 PM
Screenshot 2024-07-11 at 7 57 26 PM
The following is result about

lastWeekTangibleHrs: 90, savedTangibleHrs: [90]
lastWeekTangibleHrs: 60, savedTangibleHrs: [90, 60]
lastWeekTangibleHrs: 50, savedTangibleHrs: [50]
90 HOURS IN 1 WEEK
60 HOURS IN 2 WEEK
`50 HOURS IN 1 WEEK
`Screenshot 2024-07-11 at 7 59 08 PM
I think if you want to get `50 HOURS IN 3 WEEK`.
The testing process should be:
lastWeekTangibleHrs: 90, savedTangibleHrs: [90]
lastWeekTangibleHrs: 60, savedTangibleHrs: [90, 60]
lastWeekTangibleHrs: 50, savedTangibleHrs: [90, 60, 50]
Screenshot 2024-07-11 at 8 02 01 PM

Overall, it performs as it should be

**Comment by peter6866** [comment]
> This is additional test.
> 
> Screenshot 2024-07-11 at 7 51 44 PM Screenshot 2024-07-11 at 7 54 44 PM Screenshot 2024-07-11 at 7 57 26 PM The following is result about
> lastWeekTangibleHrs: 90, savedTangibleHrs: [90] lastWeekTangibleHrs: 60, savedTangibleHrs: [90, 60] lastWeekTangibleHrs: 50, savedTangibleHrs: [50] 90 HOURS IN 1 WEEK 60 HOURS IN 2 WEEK `50 HOURS IN 1 WEEK `Screenshot 2024-07-11 at 7 59 08 PM I think if you want to get `50 HOURS IN 3 WEEK`. The testing process should be: lastWeekTangibleHrs: 90, savedTangibleHrs: [90] lastWeekTangibleHrs: 60, savedTangibleHrs: [90, 60] lastWeekTangibleHrs: 50, savedTangibleHrs: [90, 60, 50] Screenshot 2024-07-11 at 8 02 01 PM
> 
> Overall, it performs as it should be

Thank you! You are right. It should be [90, 60, 50]. It was a typo.

**Review by skaush21 — COMMENTED** [review]
image
These videos show the badge collection and display. (not all steps are shown).

https://github.com/user-attachments/assets/c1325f4d-f5a2-42f9-95b6-3f96e72ae82c


https://github.com/user-attachments/assets/c8cfda15-59e5-4db9-934e-2b951ad6dda4

**Pull request merged**
