### PR TITLE
Roberto- Fixes Time Entry Log Modal Issues

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
When trying to delete a time entry log, the delete modal doesn't close by itself it requires you to click out and refresh the page manually instead of doing it on its own. On occasions when creating, editing, or deleting time entry logs sometimes you can observe errors thrown in your backend server.

## Related PRS (if any):
To test this backend PR you need to checkout the #[1508](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1508) frontend PR.

## Main changes explained:
- Adds logic to timeEntryController.js file to distinguish whether a time entry is associated with a task or just a project. No longer throwing errors on backend server.

## How to test:
1. check into current branch
2. do `npm install` and `npm run build && npm start`
3. log as any user
4. follow frontend instructions

### CODE REVIEW

**Comment by beblicarl** [comment]
I have tested the frontend and it works perfectly

**Review by beblicarl — APPROVED** [review]

**Review by Bali2Mohit — COMMENTED** [review]
Tested the frontend PR and added comment there.
It works perfectly. Well done

**Review by JeffLi117 — APPROVED** [review]
Comments left on FE PR #1508.

**Review by sahilpatel18 — APPROVED** [review]
I have left a comprehensive review on [#1508](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1508), including a video demonstration. Great work!

**Comment by palakgosalia** [comment]
Hey, I have reviewed your PR and have left detail comment in the frontend PR #1508

**Review by Hemsharavanan — APPROVED** [review]
Checked out both UI and API. Left PR review for UI PR #1508. Nice work!

**Review by pika-chu11 — APPROVED** [review]
I tested test the FrontEnd and it works perfectly fine. PR 1508

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR and left comment on PR 1508. Good job!

**Review by lichanghaogit — COMMENTED** [review]
Hi @robertoooc 
Nice work, comment left in the frontend.

**Pull request merged**
