### PR TITLE
Lucas user hours set to zero

### PR DESCRIPTION
**Pull request by Lucas-E**
This is the backend for the PR [#727](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/727), use them together so the functionality can work properly. This PR also needs to be reviewed.

### Main changes

Now roles are showed on the Leaderboard requested data and Mentors and zero hour users are not counted in HGN totals.

### How to test

Follow PR's [#727](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/727) instructions

### CODE REVIEW

**Review by nicollext — COMMENTED** [review]
Working as expected. Great Job!

**Review by nicollext — APPROVED** [review]

**Comment by AriaYu927** [comment]
Tested this PR, it works great. The test result has been published in [#727](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/727#issuecomment-1483057403)

**Review by kangjay88 — APPROVED** [review]
Hi @Lucas-E , tested this PR on PR727, and it is working as intended.

**Comment by Lucas-E** [comment]
@one-community

**Comment by one-community** [comment]
Thank you everyone. Moved his pair to final review.

**Review by Elisaudo — APPROVED** [review]
Hi, Lucas, I tested all cases and it is working as expected.

1)Owners, Administrators and Core Team members should be able to see all users, including zero hour users and Mentor users.

[PR#727 PR#298 Video 1.webm](https://user-images.githubusercontent.com/64317219/231634894-914599fd-99cc-4e4d-9b8c-51306883a4ad.webm)

2)	Mentor users can only be seen by themselves and Owners, Administrators and Core Teams on the Leaderboard. 

PR#727 PR#298 - Mentor users can only be seen by themselves

PR#727 PR#298 - Mentor users can only be seen by themselves 2

3)	Mentor users and users with zero hours are not displayed on the leaderboard and do not add to the HGN totals. Other role's users should not see Mentor users and zero hour users. (manager, volunteer)

PR#727 PR#298 - Other role's cannot see Mentor users and zero hour users

4)	Mentor users and users with zero hours can see the members on their respective teams.

PR#727 PR#298 - Mentor users and users with zero hours can see team members 1



PR#727 PR#298 - Mentor users and users with zero hours can see team members 2



PR#727 PR#298 - Elisaudo Team - team members

**Pull request merged**
