### PR TITLE
Delete yarn

### PR DESCRIPTION
**Pull request by LeeSingChanYau**
Remove the yarn files such as yarn.lock from the repo keeping only npm as the package manager.

### CODE REVIEW

**Comment by one-community** [comment]
Following up on this...

**Review by RJBornToWin — COMMENTED** [review]
Please provide details on what has been changed in package-lock.json. Was it manually edited ? or changes to npm install/uninstall caused this ? 

If this was unintended, this can be removed as the other change has no effect.

**Comment by one-community** [comment]
Following up on this... Frontend has been merged: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/563 What's needed to get this backend merged too? Is one being merged without the other causing any of our problems?

**Comment by RJBornToWin** [comment]
Jae: For review, I couldn't load the difference because it shows +15k lines of change. This is because few lines has been deleted from the file and I would like to know more on it to approve this.

**Comment by one-community** [comment]
@EvianTan this is that PR where Alan said yesterday "I double checked just now and the backend branch of development does not have yarn in the project anymore. Could it have been another PR that deleted yarn?"

Not sure what to do here...

**Comment by EvianTan** [comment]
Hey @one-community and @RJBornToWin and @LeeSingChanYau ,

Since we don't know what's going on there, I would suggest we just close this PR for now.

**Comment by one-community** [comment]
Closed, thank you all

**Comment by one-community** [comment]
Alan, please delete this branch if there's no reason to keep it

**Pull request closed without merging**
