### PR TITLE
Sucheta - Update Projects Page sorting

### PR DESCRIPTION
**Pull request by sucheta90**
# Description
(PRIORITY HIGH) Jae: Update Projects Page sorting (WIP Sucheta ) 
Other Links>Projects
I’d like the default filter/sorting of this page to show the Projects that have most recently had additions to their WBSs (or of a new WBS) at the top. 
For testing adding a WBS, you'll need a properly formatted/working WBS file too. Here's a file for that: https://www.dropbox.com/scl/fi/3ijzq1zgfmfzj9x5z85xy/WORKING-TEST-FILE-TEST-WBS.xlsx?rlkey=7ownwt61ff4w9833yldnu1cea&dl=0 
2ND PR: I’d also like sort buttons added by Project Name, Category, and Active so I can 1-click and sort by these instead if needed
3RD PR: Add a sort button to the Members and Inventory heading so I can 1-click and sort by whichever of these have had edits most recently.

## Related PRS (if any):
To test this backend PR you need to check out the [#1812](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1812) frontend PR.
…

## Main changes explained:
- Project page default sorting is based on `modifiedDateandTime`
- Updates the Project and WBS - `modifiedDateAndTime` when a `Task` in added or updated in wbs.
…

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/ owner user
5. go to → Dashboard→ Projects →…
6. The user should see the sorted list of Projects.
7. Each time there is an update in the WBS -> Task, the project will be put at the top of the list (most recent modification)

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HGNRest/assets/101291283/1db011fb-c470-4718-b5e3-2d19067b5c31

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by Haoxiang310** [comment]
Reviewed and commented in the related FE PR#1812: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1812

**Comment by yuhuimin1996** [comment]
Hi I've tested this backend PR also with the frontend PR #1812. All the features worked well. Please see the details at https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1812

**Comment by mianmiantea2019** [comment]
Reviewed and commented in the related FE [ pr#1812](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1812)

**Review by keyunhuangg — APPROVED** [review]
All the filters seems to be working well. Tested using owner account. Also reviewed code and the changes looks good.
Uploading Screen Recording 2024-01-12 at 1.16.17 PM.mov…

**Review by Renanluizssx — APPROVED** [review]
I tested your application  this backend PR with frontend PR and it's working perfect. For  more details at PR: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1812

**Review by Sophie-lei — APPROVED** [review]
Hey! I just tasted this PR and the project can be sorted with the recent task as expected. 

https://github.com/OneCommunityGlobal/HGNRest/assets/70113822/3a0b0708-82fc-4d73-a3e7-4119767d6bc4

**Review by 666saofeng — APPROVED** [review]
Hi, I tested both PR693 on backend and PR1812 on the frontend. All functions worked well. Congrats!

https://github.com/OneCommunityGlobal/HGNRest/assets/62363348/64937882-0d2d-4fca-9450-bde87bfb4575

**Review by KevHnh — APPROVED** [review]
Tested with FR [PR#1812](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1812#pullrequestreview-1833728393) and everything works as expected without encountering any issues.

**Comment by peterson337** [comment]
>

**Comment by peterson337** [comment]
I tested it and it doesn't work.

https://github.com/OneCommunityGlobal/HGNRest/assets/73541319/8eda9480-4b46-4604-a92a-73dbfb7b581d

**Comment by xmyoot** [comment]
I've tested the front end and back end of this feature for the creation of a new project and in the Project list it was updated to appear at the top, please reference the video: 

https://github.com/OneCommunityGlobal/HGNRest/assets/15240538/f035b60f-1b73-421b-a3a0-da85fb7a6060

**Review by peterson337 — DISMISSED** [review]
I tested and successfully created a new WBS, but I was unable to create a new task because the 'Save' button did not appear in the modal.

one comunnity

**Review by pshereen — APPROVED** [review]
Tested the PR and it is working as per the requirement. Logged in as owner user.

1. The user should see the sorted list of Projects. - Working

1. Each time there is an update in the WBS -> Task, the project will be put at the top of the list (most recent modification) - Working

The video shows the working of the implemented feature.


https://github.com/OneCommunityGlobal/HGNRest/assets/7041610/c03519c1-8b70-4192-9824-a41ea4d374f2

**Review by X1aoZhang99 — CHANGES_REQUESTED** [review]
Hi Sucheta,

I've tested your pull request with FE [#1812](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1812). All the functionalities in that PR are working as intended. However, it appears that the sorted list is being overridden by an alphabetical list. As a result, I can only see the list in either an ascending or descending sequence, regardless of any changes made to the task. Please refer to the video. 

https://github.com/OneCommunityGlobal/HGNRest/assets/113070229/fc49846b-9d38-48ea-86c8-4f12d68263a2

**Comment by xmyoot** [comment]
Hi Sucheta, 

I added a review on the related front end PR: [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1812](url)

**Comment by galgalinidhi** [comment]
Hi @sucheta90, I tested this PR and it works as expected with the most recently modified project on Top.


https://github.com/OneCommunityGlobal/HGNRest/assets/44816413/0a6da7c9-98c5-459c-847c-e34e66de17e6

**Review by Pandani07 — APPROVED** [review]
Tested this PR as an admin and it works as expected. The most recently modified project (WBS change) is on the top of the list and the rest of the list is sorted. The list is sorted even if you filter by any of the categories and you can change the order of sorting as well.


https://github.com/OneCommunityGlobal/HGNRest/assets/44672833/83b47c47-b631-403e-a120-ab4191048892

**Review by SaiDeepak-NEU — APPROVED** [review]
Hello Sucheta,
I have tested the feature and everything worked smoothly and as expected.
Logged in as an admin and navigated to projects.
modified the wbs for a project by adding a task and observed that the project came to the top as expected.
Screenshot (49)
Screenshot (48)

However, while trying to add a wbs to a project using Postman like you mentioned I faced an error which said invalid token. I don't know if needed to do something additional.
Screenshot (50)

**Pull request merged**
