### PR TITLE
 Aishwarya-Purchase-Consumable-Request-Form-(Backend)

### PR DESCRIPTION
**Pull request by Aishwaryak01**
Aishwarya_Purchase-Consumable-Request-Form-(Backend)

Description
This pull request adds the backend logic for the Purchase Request: Consumable form in the BM Dashboard (Phase 2).

Related PRS (if any):
This PR must be checked out to test #2018 frontend PR

Main changes explained:

Add POST route to either create a new document in buildingInventoryItem collection (if the consumablel is being ordered to the project for the first time), or update purchase record sub-document in an existing document (if the material has been ordered previously for the project). In either case, the purchaseRecord sub-document will have default values added to date, requestedBy, and status fields, in addition to the submitted form data.

How to test:
git checkout Aishwarya_Purchase-Consumable-Request-Form-(Backend)
npm install
npm run dev
check the related frontend PR for further instructions

Optional: connect to the dev db via Mongo Compass, open the buildingInventoryItem collection, and observe that documents and sub-documents are being updated correctly.

Notes
Please remember to either Approve or Request Changes. Do not just leave a comment.
Please leave a review for both the front and backend branches after you have finished testing!

### CODE REVIEW

**Review by abdel-lall — APPROVED** [review]
LGTM!

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested this PR with the related frontend PR and everything works as intended. Please refer the frontend PR for detailed review.

**Review by Pandani07 — APPROVED** [review]
Works as intended! left a review on the frontend PR

**Review by tdkent — APPROVED** [review]
Have tested this branch and confirmed the functionality works as intended:
- a request for a new project/item combination adds a new document and purchase request subdocument to the **buildingInventoryItems** collection.
- a request for an existing project/item combination adds a purchase request object to the subdocument of the correct existing document in **buildingInventoryItems**
- the purchase status default value is "Pending"
- the key value `__t : "consumable_item` is added to the document

newitem1

newitem2

**Review by ImzIssa — APPROVED** [review]
Hey, I've tested this PR and everything works great.

My Frontend PR Review for ref.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2018#pullrequestreview-1948716442

**Pull request merged**
