### PR TITLE
Nathan permissions merge

### PR DESCRIPTION
**Pull request by nathanah**
# Description
Fixes #6 (HIGH) Verify that permissions are implemented on the back end and not just the front end.
See front-end PR #

## Related PRS (if any):
This backend PR is related to the #931 frontend PR.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/931

## Main changes explained:
- Updated createInitialPermissions to combine front-end and back-end permissions into a single permission set.
- Update rolesController.js, taskController.js, teamController.js, and userProfileController.js to have permissions set up. 
- Updated role.js to use different db collection (to not delete data for current system while still testing. can clean up old permissions in a later PR.)
- Updated permissions.js to only check one set of permissions.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. The front-end should work the same.

## Screenshots or videos of changes:
Everything should look the same other than the code.

### CODE REVIEW

**Review by ThapeloMasasa — COMMENTED** [review]
Left a comment on the frontend

**Review by DavidC0126 — COMMENTED** [review]
Left a comment on the frontend [PR#931](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/931#pullrequestreview-1562318130).

**Review by Abiddy — APPROVED** [review]
left comment in the FE PR.

**Review by winghojackyli — APPROVED** [review]
Hi @nathanah , I've tested this PR along with frontend #931 PR. Approval with comments left here https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/931#pullrequestreview-1577800162

**Review by veronicacheng2 — APPROVED** [review]
Hi @nathanah, I have tested this PR together with #931. Comments left there.

**Pull request merged**
