### PR TITLE
Imran toggle invisibility permission self and others

### PR DESCRIPTION
**Pull request by ImzIssa**
# Description
Desc

## Main changes explained:
1. Added toggleInvisibility permission in  src/utilities/createInitialPermissions.js
2. Created a new route in src/routes/userProfileRouter.js
3. Added toggleVisibility function in src/controllers/userProfileController.js

## Related PRS (if any):
To test this backend PR you need to checkout the [PR#2183](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183)  frontend PR.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Refer to [PR#2183](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183) to test

### CODE REVIEW

**Review by alla0810 — CHANGES_REQUESTED** [review]
Please see the comment on the frontend.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183#pullrequestreview-2017977420

**Review by nathcarnevalli — COMMENTED** [review]
I reviewed the PR on [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183#pullrequestreview-2057909165).

**Review by nathcarnevalli — APPROVED** [review]

**Review by jayyy-s — APPROVED** [review]
Changes look good and address the issue in scope. Please reference my review in [PR 2183](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183#pullrequestreview-2064592397) to see that it works. Approving.

**Review by Infinite-Turkey — COMMENTED** [review]
Left a comment at front-end side[Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183#pullrequestreview-2091868624)

**Review by Kavil-Jain-514 — APPROVED** [review]
The funtionality works as expected.
Reviewed the PR and gave comments in the front-end PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183

**Comment by akshit0211** [comment]
It is working as expected. I left a comment on the frontend PR. [Review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183)

**Review by akshit0211 — APPROVED** [review]

**Review by DiyaWadhwani — CHANGES_REQUESTED** [review]
Hi Imran,
I was unable to test this functionality. I've left a detailed comment with a video of the error I'm facing on the frontend PR related to this
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183#pullrequestreview-2140648717
Kindly review this. 
Thank you

**Review by vishavk1992 — CHANGES_REQUESTED** [review]
Hi Imran,

I am unable to test this PR. I have left a comment on the frontend PR.

**Review by Parth-tech — COMMENTED** [review]
Hey Imran,
I wasn't able to test the PR due to errors. Left a review on the [frontend](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183#issuecomment-2292549708)

**Review by adityasure9 — APPROVED** [review]
I've provided detailed feedback on the frontend PR related.

**Review by Shreyav2000 — CHANGES_REQUESTED** [review]
Hi,

I’ve encountered some issues while testing this feature on the frontend. The frontend PR related to this backend PR has some functionality issues (e.g., the page going blank when navigating to a user profile). Please refer to the frontend PR (https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183#pullrequestreview-2287450041) to help review the issues before proceeding with the backend changes.

Thanks!

Screenshot 2024-09-07 at 3 28 24 AM

**Comment by sam19981** [comment]
The backend code changes look good, but I was wondering if we could filter out the invisible useras in the backend itself before sending it through one of the controllers? What do you think @ImzIssa ?

Left front end PR comments [here.](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2183#pullrequestreview-2287693034)

**Review by swaroop-2007 — CHANGES_REQUESTED** [review]
I reviewed this PR and it is not working as expected. Added my comments in PR #2183. 

Thanks.

**Pull request closed without merging**
