### PR TITLE
Leon and Oleksandr add interactive map

### PR DESCRIPTION
**Pull request by xaanders**
# Description
See PR   #[1503](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1503)

## Related PRS :
To test this backend PR you need to checkout the #[1503](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1503) frontend PR.
…

## Main changes explained:
- added map location controller, router and mongoose model
- changed user profile model to handle location object

## How to test:
1.get the API key from https://opencagedata.com/
2. add to env same API key from step 1:
TIMEZONE_PREMIUM_KEY=1234
TIMEZONE_COMMON_KEY=1234
 check into current branch
3. do `npm install` and `npm run build && npm start` to run this PR localy

### CODE REVIEW

**Review by lichanghaogit — COMMENTED** [review]
Comment left in the FE, great work!

**Comment by palakgosalia** [comment]
Hey, I have left comments in FE PR. Thank you

**Comment by kavya151** [comment]
Hi @xaanders , Review at PR 1503

**Review by Shuhua-L — APPROVED** [review]
Test video and comment left in the [FE PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1503#pullrequestreview-1738546485). Nice work!

**Review by robertoooc — APPROVED** [review]
Backend works well, FE just needs one slight adjustment and all will be well.

**Comment by beblicarl** [comment]
tested the frontend and all is well

**Review by navneeeth — APPROVED** [review]
Hello, @xaanders and @leonzh2k! Commented the full review on the frontend PR. Great job with this implementation!

**Pull request merged**
