### PR TITLE
yihan Create way to manually add in lost hours for past years of volunteers

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
To test this backend PR you need to checkout the[ #1535](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1535) frontend PR.

## Main changes explained:
- Update timeentry.js for including new properties.
- Update timeentryRouter.js and timeEntryController.js for updating exist functions and adding new functions that related to time entries.
- Update dashboardhelper.js, taskHelper.js and userHelper.js for filtering unrelated timeEntries.

## How to test:
1. check into current branch on both FE and BE.
2. do `npm run build` and `npm start` to run this PR locally
3. follow test steps in [#1535](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1535).

### CODE REVIEW

**Comment by palakgosalia** [comment]
Hey, I Left a comment in FE PR. Thank you

**Comment by ptrpengdev** [comment]
Hi @AriaYu927, I tested the FE [PR1535 ](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1535) with this BE PR611 and had no issues with the PRs. Thank you!

**Review by pika-chu11 — APPROVED** [review]
Hi @AriaYu927 , I have tested your PRs and left a comment in the FrontEnd [#1535](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1535). Great Job!

**Review by Alforoan — APPROVED** [review]
I left my comment on the FE pr.

**Comment by beblicarl** [comment]
I left a comment on the frontend, this branch has conflicts though

**Comment by AriaYu927** [comment]
> I left a comment on the frontend, this branch has conflicts though

Thanks for the reminder! I've solved the conflicts.

**Review by navneeeth — COMMENTED** [review]
Just reviewed the implementation on the FE and everything looks good!

**Pull request merged**
