### PR TITLE
Wanting new make 5 letter codes editable only by admin&owner

### PR DESCRIPTION
**Pull request by wantingxu7**
# Description
截屏2023-11-03 上午11 16 18

## Related PRS (if any):
FE #1485

## Main changes explained:
update userProfileController.js
…

## How to test:
1. check into current branch and FE #1485
2. do `npm run build` and `npm start` to run this PR locally

## Screenshots or videos of changes:
see FE #1485

## Note:
see FE #1485

### CODE REVIEW

**Comment by AriaYu927** [comment]
Hi @wantingxu7 , I've tested this PR and left a comment under [#1485 ](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485#issuecomment-1793313920)with more details. Thank you!

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hi @wantingxu7, left detailed review on [FE PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485#pullrequestreview-1713694482).

**Review by shubhankarval — APPROVED** [review]
Left a comment on FE PR [#1485](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485). Everything works as intended, great job!

**Review by sahilpatel18 — APPROVED** [review]
I tested this PR and provided a full review at [#1485](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485) Good work!

**Review by jerryren527 — APPROVED** [review]
Hi @wantingxu7 ,

I left a more detailed review for your [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485#pullrequestreview-1713901857). Great job!

**Comment by palakgosalia** [comment]
Hey, I have reviewed your PR and left a detailed comment in PR 1485. Thank you

**Review by Shuhua-L — APPROVED** [review]
I’ve tested both of your PRs and they worked as expected. More details can be found in the FE PR. Nice work!

**Comment by kavya151** [comment]
Hi @wantingxu7 Left detailed review at PR #1400

**Review by lichanghaogit — COMMENTED** [review]
comments left in the FE, Thank you for the nice work!

**Comment by ptrpengdev** [comment]
The code works as expected. Great work!

Tested both Admin and Owner role:
1. Update team code in weekly summaries component (Success)
2. Update team code in user profile component (Success)

Env Setup:
frontend commit [60815f3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/60815f30cbedbeb98780469af307085ec48b0c39) and backend commit [c819cc8](https://github.com/OneCommunityGlobal/HGNRest/commit/c819cc8c81d0e6543b0fec006def60161121b5f8).


Enhancement:
1. The Weekly Report API currently returns all records, which over 900 records and takes 18 seconds to finish the request. It would be beneficial to implement pagination in both the frontend and backend for this data. Without pagination, the application may load more data than necessary and will lead to performance issue as the number of weekly summaries increases. 
    - http://localhost:4500/api/reports/weeklysummaries
enhancementWeeklyReport

**Review by ptrpengdev — APPROVED** [review]
Approved. Comment Reference:
https://github.com/OneCommunityGlobal/HGNRest/pull/594#issuecomment-1817354797

**Comment by Bali2Mohit** [comment]
Hi @wantingxu7 ,
I have reviewed and added comment on the frontend PR

**Comment by DragonSlayer2401** [comment]
I tested this PR with the related front end PR please see the full review there  [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485](url)

**Review by sucheta90 — COMMENTED** [review]
Hi @wantingxu7 , I left a detailed review on the Frontend [PR1485](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485#pullrequestreview-1773701223)

**Pull request closed without merging**
